SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_INVOICE_PROTOCOL') IS NULL EXEC('CREATE PROCEDURE REPEX_INVOICE_PROTOCOL AS RETURN')
GO
ALTER PROCEDURE REPEX_INVOICE_PROTOCOL
	(@XMLPARAM NTEXT) AS
	
/* parameters */
DECLARE @HDOC INT
DECLARE @ID_INVOICE BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_INVOICE = ID_INVOICE
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_INVOICE BIGINT 'ID_INVOICE')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

-- ьЮОЙЮ Х ЯОХЯНЙ РНБЮПНБ Б ОПХУНДМНИ МЮЙКНДМНИ
SELECT
ITEM.ID_INVOICE_ITEM_GLOBAL,
  -- мнлеп опхундмни мюйкндмни
INV.MNEMOCODE AS INVOICE_NUMBER,
  -- дюрю опхундмни мюйкюдмни
CONVERT(VARCHAR, INV.DOCUMENT_DATE, 104)AS INVICE_DATE,
  -- бундъыхи днйслемр
COALESCE(INV.INCOMING_NUMBER, '')+
COALESCE(' нр '+CONVERT(VARCHAR, INV.INCOMING_DATE, 104), '') 
AS INCOMING_NUMBER,
  -- онярюбыхй 
CNR_SUP.NAME AS SUPPLIER_NAME,
  -- онйсоюрекэ
(
SELECT TOP 1 C.NAME
FROM DBO.INVOICE I
INNER JOIN DBO.STORE S ON S.ID_STORE = I.ID_STORE 
INNER JOIN DBO.CONTRACTOR C ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
WHERE I.ID_INVOICE = @ID_INVOICE) AS CUSTOMER_NAME,
G.[NAME] + ' [' + PROD.NAME + ', ' + CNR.NAME + ']' AS GOODS,
SER.SERIES_NUMBER + ' / '+ CONVERT(VARCHAR,SER.BEST_BEFORE,104) AS SERIES_NUMBER,
ITEM.QUANTITY	AS QUANTITY,
 --опнхгбндхрекэ
PROD.[NAME] AS PRODUCER_NAME,
 --жемю цня. пееярпю
G.REGISTER_PRICE,
 --жемю опнхгбндхрекъ
ITEM.PRODUCER_PRICE AS PRODUCER_PRICE_PER_UNIT,
 --рнпцнбюъ мюдаюбйю онярюбыхйю %
ITEM.SUPPLIER_ADPRICE AS CONTRACTOR_ADPRICE,
 --рнпцнбюъ мюдаюбйю онярюбыхйю ясллю
ITEM.QUANTITY * (ITEM.PRODUCER_PRICE/100)*ITEM.SUPPLIER_ADPRICE AS CONTRACTOR_ADD_PRICE,
 --жемю онярюбыхйю аег мдя
ITEM.SUPPLIER_PRICE AS CONTRACTOR_PRICE_PER_UNIT,
 -- мдя %
ITEM.SUPPLIER_VAT AS TAX_RATE,
 -- мдя ясллю
ITEM.SUPPLIER_VAT_SUM AS CONTRACTOR_VAT_SUM,
 --рнпцнбюъ мюдаюбйю пнгмхвмнцн гбемю %
ITEM.RETAIL_ADPRICE,
 --рнпцнбюъ мюдаюбйю пнгмхвмнцн гбемю ясллю
    -- рхою ме ясллю
RETAIL_ADD_PRICE_NO_SUM = ITEM.RETAIL_ADPRICE_PER_UNIT,
    -- рхою ясллю
RETAIL_ADD_PRICE = ITEM.QUANTITY * ITEM.RETAIL_ADPRICE_PER_UNIT,

 --пнгмхв. жемю гю ед.
ITEM.RETAIL_PRICE,
 -- мдя %
ITEM.RETAIL_VAT AS RETAIL_VAT,
 -- мдя ясллю гю ед.
ITEM.RETAIL_VAT_SUM,
 --пнгм. жемю гю ед. я мдя
ITEM.RETAIL_PRICE_VAT,
 -- ясллю
ITEM.RETAIL_SUM_VAT
FROM DBO.INVOICE INV
  INNER JOIN DBO.CONTRACTOR CNR_SUP ON CNR_SUP.ID_CONTRACTOR = INV.ID_CONTRACTOR_SUPPLIER
  INNER JOIN DBO.INVOICE_ITEM ITEM ON ITEM.ID_INVOICE = INV.ID_INVOICE
  INNER JOIN DBO.GOODS G ON G.ID_GOODS = ITEM.ID_GOODS
  INNER JOIN DBO.PRODUCER PROD ON G.ID_PRODUCER = PROD.ID_PRODUCER
  INNER JOIN DBO.COUNTRY CNR ON PROD.ID_COUNTRY = CNR.ID_COUNTRY
  INNER JOIN DBO.SCALING_RATIO SR ON SR.ID_SCALING_RATIO = ITEM.ID_SCALING_RATIO
  INNER JOIN DBO.UNIT U ON SR.ID_UNIT = U.ID_UNIT
  LEFT JOIN DBO.SERIES SER ON ITEM.ID_SERIES = SER.ID_SERIES 
WHERE (INV.ID_INVOICE = @ID_INVOICE)
ORDER BY GOODS

SELECT
    CONTRACTOR_ADD_PRICE = SUM(ITEM.QUANTITY * (ITEM.PRODUCER_PRICE/100) * ITEM.SUPPLIER_ADPRICE),
    CONTRACTOR_VAT_SUM = SUM(ITEM.SUPPLIER_VAT_SUM),
    RETAIL_ADD_PRICE = SUM(ITEM.QUANTITY * ((ITEM.RETAIL_PRICE * ITEM.RETAIL_ADPRICE) / (100+ITEM.RETAIL_ADPRICE))),
    RETAIL_VAT_SUM = SUM(ITEM.RETAIL_VAT_SUM),
    RETAIL_SUM_VAT = SUM(ITEM.RETAIL_SUM_VAT)
FROM INVOICE I
  INNER JOIN INVOICE_ITEM ITEM ON ITEM.ID_INVOICE = I.ID_INVOICE
WHERE I.ID_INVOICE = @ID_INVOICE


SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO
FROM CONTRACTOR
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)

RETURN 0
GO

