SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INVOICE_OUT_PRICE_NEGOTIATION_PROTOCOL_ZNVLS_SALIKS') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INVOICE_OUT_PRICE_NEGOTIATION_PROTOCOL_ZNVLS_SALIKS AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INVOICE_OUT_PRICE_NEGOTIATION_PROTOCOL_ZNVLS_SALIKS
    @XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT @ID_GLOBAL = ID_GLOBAL FROM OPENXML(@HDOC, '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	FR_NAME = CASE WHEN ISNULL(C_FR.FULL_NAME, '') = '' THEN C_FR.NAME ELSE C_FR.FULL_NAME END,
	TO_NAME = CASE WHEN ISNULL(C_TO.FULL_NAME, '') = '' THEN C_TO.NAME ELSE C_TO.FULL_NAME END,
	DOC_NUM = I.DOC_NUM,
	DOC_DATE = CONVERT(VARCHAR, I.DOC_DATE, 104)
FROM INVOICE_OUT I
	INNER JOIN STORE S ON I.ID_STORE = S.ID_STORE
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = I.ID_CONTRACTOR_TO
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S.ID_CONTRACTOR
	WHERE i.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL
	
SELECT DISTINCT
	GOODS_NAME = G.NAME, 
	SERIES_NAME = S.SERIES_NUMBER,
	PRODUCER_NAME = P.NAME,
	REGISTER_PRICE = L.REGISTER_PRICE,
	--6
	--7
	PRICE_PROD = L.PRICE_PROD,
	SUP_ADPRICE = CASE WHEN L.ADPRICE_SUP < 0 THEN ((L.PRICE_SAL - L.PVAT_SAL) / (L.PRICE_SUP - L.PVAT_SUP) - 1) * 100 
		ELSE L.ADPRICE_SUP + ((L.PRICE_SAL - L.PVAT_SAL) / (L.PRICE_SUP - L.PVAT_SUP) - 1) * 100 END,
	SUM_ADPRICE_SUP = CASE WHEN L.ADPRICE_SUP < 0 THEN L.PRICE_SAL - L.PVAT_SAL - L.PRICE_SUP + L.PVAT_SUP 
		ELSE L.PRICE_PROD * L.ADPRICE_SUP / 100 + L.PRICE_SAL - L.PVAT_SAL - L.PRICE_SUP + L.PVAT_SUP END,
	PRICE_SUP = L.PRICE_SUP - L.PVAT_SUP, 
	L.VAT_SUP, 
	PRICE_SUP_NDS = L.PRICE_SUP, 
	II.ADPRICE_SAL, 
	SUM_ADPRICE_SAL = L.PRICE_SAL - L.PVAT_SAL - L.PRICE_SUP + L.PVAT_SUP, 
	PRICE_SAL = L.PRICE_SAL - L.PVAT_SAL, 
	PRICE_SAL_NDS = L.PRICE_SAL
FROM INVOICE_OUT_ITEM II
	INNER JOIN INVOICE_OUT I ON II.ID_INVOICE_OUT_GLOBAL = I.ID_INVOICE_OUT_GLOBAL
	LEFT JOIN LOT L ON L.ID_LOT_GLOBAL = II.ID_LOT_GLOBAL
	LEFT JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
	LEFT JOIN SERIES S ON S.ID_SERIES = L.ID_SERIES	
WHERE II.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL AND 
	I.STATE IN ('PROC', 'SAVE') AND G.IMPORTANT = 1
ORDER BY G.NAME

RETURN 0
GO

--exec DBO.REPEX_INVOICE_OUT_PRICE_NEGOTIATION_PROTOCOL_ZNVLS_SALIKS N'<XML><ID_GLOBAL>EFB5BAF6-07E8-414E-BDC8-FFE990F870A6</ID_GLOBAL></XML>'

