SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
---------------------------------------------------------------------------
IF (OBJECT_ID('DBO.REP_TAX_GROUPS_SHORT_REP_EX') IS NULL ) EXEC ('CREATE PROCEDURE DBO.REP_TAX_GROUPS_SHORT_REP_EX AS SELECT NULL')
GO
ALTER PROCEDURE DBO.REP_TAX_GROUPS_SHORT_REP_EX
         @XMLPARAM NTEXT
AS
SET NOCOUNT ON
DECLARE @NO_DETAIL BIT
DECLARE @DATE_FR DATETIME, @DATE_TO DATETIME
DECLARE @SORT_DOC BIT, @SHOW_ADD BIT, @SHOW_SUB BIT, @REFRESH_DOC_MOV BIT

DECLARE @HDOC INT, @SQL NVARCHAR(4000), @SQL_FIELDS NVARCHAR(4000)

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
    SELECT TOP 1 
        @DATE_FR = DATE_FR, @DATE_TO = DATE_TO,
        @NO_DETAIL = NO_DETAIL, @SORT_DOC = SORT_DOC,
        @SHOW_ADD = SHOW_ADD, @SHOW_SUB = SHOW_SUB,
        @REFRESH_DOC_MOV = REFRESH_DOC_MOV
    FROM OPENXML(@HDOC, '/XML') WITH(
        DATE_FR DATETIME 'DATE_FR', 
        DATE_TO DATETIME 'DATE_TO', 
        NO_DETAIL BIT 'NO_DETAIL',
        SORT_DOC BIT 'SORT_DOC', 
        SHOW_ADD BIT 'SHOW_ADD', 
        SHOW_SUB BIT 'SHOW_SUB',
        REFRESH_DOC_MOV BIT 'REFRESH_DOC_MOV')

    /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬  ŒÕ“–¿√≈Õ“Œ¬ */
    SELECT DISTINCT C.ID_CONTRACTOR, C.NAME INTO #CONTRACTOR
    FROM 
        (SELECT * FROM OPENXML(@HDOC, '//ID_CONTRACTOR') 
        WITH(ID_CONTRACTOR BIGINT '.')) TAB
    INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = TAB.ID_CONTRACTOR
    
    /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬ — À¿ƒŒ¬ */
    SELECT DISTINCT S.ID_STORE, S.ID_CONTRACTOR, S.NAME INTO #STORE
    FROM
    	(SELECT * FROM OPENXML(@HDOC, '//ID_STORE') 
        WITH(ID_STORE BIGINT '.')) TAB
    INNER JOIN STORE S ON S.ID_STORE = TAB.ID_STORE
EXEC SP_XML_REMOVEDOCUMENT @HDOC

IF @REFRESH_DOC_MOV = 1 BEGIN
    -- ÔÂÂÒ˜ËÚ‡Ú¸ DOC_MOVEMENT ÔÓ ‚ÒÂÏ ‰ÓÍÛÏÂÌÚ‡Ï
    EXEC UTL_REFRESH_DOC_MOVEMENT 'REPAIR', 0
END

-- ÓÚÌÓÏËÓ‚‡Ú¸ ‰‡Ú˚
EXEC USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT

-- ≈—À» Õ≈ ” ¿«¿Õ — À¿ƒ, “Œ »“Œ√» ¬€¡»–¿ﬁ“—ﬂ œŒ ¬—≈Ã — À¿ƒ¿Ã
IF NOT EXISTS(SELECT TOP 1 1 FROM #STORE) BEGIN
    INSERT INTO #STORE (ID_STORE, ID_CONTRACTOR, NAME)
    SELECT S.ID_STORE, S.ID_CONTRACTOR, S.NAME
    FROM STORE S(NOLOCK) INNER JOIN #CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
END
DELETE FROM #STORE WHERE ID_CONTRACTOR NOT IN (SELECT ID_CONTRACTOR FROM #CONTRACTOR)

-- Œ—“¿“Œ  Õ¿ Õ¿◊¿ÀŒ
SELECT
    SUM_SUP = SUM(DM.SUM_SUP * DM.SIGN_OP),
    SUM_ACC = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP),
	NAL = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP - DM.SUM_SUP * DM.SIGN_OP),
    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,

    SUM_SVAT_SUP = SUM(DM.SVAT_SUP * DM.SIGN_OP),
    SUM_SVAT_ACC = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP),

    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),

    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN SVAT_ACC * DM.SIGN_OP ELSE 0 END),
    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SVAT_ACC * DM.SIGN_OP ELSE 0 END)	
FROM DOC_MOVEMENT DM
WHERE DATE_OP < @DATE_FR
AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)

IF(@SHOW_ADD = 1) BEGIN
	-- Œ¡Ÿ»… œ–»’Œƒ œŒ ƒŒ ”Ã≈Õ“¿Ã
    SELECT
        ID_DOCUMENT = DM.ID_DOCUMENT,
        DOC_NAME = ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')',''),--(SELECT TOP 1 [DESCRIPTION_EXT] FROM FN_DOC_MOVEMENT_DESCRIPTION() DMD
        DATE_OP = DM.DATE_OP, 
        DOC_NUM = AD.DOC_NUM,
		INCOMING_NUMBER = CASE WHEN DM.ID_TABLE = 2 THEN ISNULL('π Õœ:'+ I.INCOMING_NUMBER,'') ELSE '' END,

	    SUM_SUP = SUM(DM.SUM_SUP),
	    SUM_ACC = SUM(DM.SUM_ACC),--SUM(CASE WHEN CODE_OP<>'DIS' THEN DM.SUM_ACC ELSE 0 END),
		NAL = SUM(DM.SUM_ACC - DM.SUM_SUP),
	    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,
	
	    SUM_SVAT_SUP = SUM(DM.SVAT_SUP),
	    SUM_SVAT_ACC = SUM(DM.SVAT_ACC),--SUM(CASE WHEN CODE_OP<>'DIS' THEN DM.SVAT_ACC ELSE 0 END),
	
	    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN SUM_ACC ELSE 0 END),
--SUM(CASE WHEN DM.VAT_RATE = 0 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
	    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE =10 THEN SUM_ACC ELSE 0 END),
--SUM(CASE WHEN DM.VAT_RATE = 10 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
	    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SUM_ACC ELSE 0 END),
--SUM(CASE WHEN DM.VAT_RATE = 18 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
	
	    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN SVAT_ACC ELSE 0 END),
--SUM(CASE WHEN DM.VAT_RATE = 10 THEN SVAT_ACC * DM.SIGN_OP ELSE 0 END),
	    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SVAT_ACC ELSE 0 END)
--SUM(CASE WHEN DM.VAT_RATE = 18 THEN SVAT_ACC * DM.SIGN_OP ELSE 0 END)	

    FROM DOC_MOVEMENT DM
    INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = DM.ID_TABLE
    INNER JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = DM.ID_DOCUMENT
	LEFT JOIN INVOICE I ON DM.ID_DOCUMENT = I.ID_INVOICE_GLOBAL
    LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
    LEFT JOIN STORE S ON S.ID_STORE = DM.ID_STORE_FROM
    WHERE (CODE_OP='ADD' OR (CODE_OP='DIS' AND DM.ID_TABLE=19 AND SIGN_OP=-1))--DM.CODE_OP='ADD' AND DM.ID_TABLE<>19
	AND DATE_OP BETWEEN @DATE_FR AND @DATE_TO
	AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)	 
    GROUP BY DM.ID_DOCUMENT, 
			 DM.ID_TABLE, 
			 TD.DESCRIPTION, 
			 DM.DATE_OP, 
			 AD.DOC_NUM,
  			 CASE WHEN DM.ID_TABLE = 2 THEN ISNULL('π Õœ:'+ I.INCOMING_NUMBER,'') ELSE '' END,
			 ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','')
-- 			 CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(DM.ID_CONTRACTOR_FROM, 0) END,
--              CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END
    ORDER BY CASE WHEN NULLIF(@SORT_DOC,0) IS NULL THEN DM.DATE_OP ELSE DM.ID_TABLE END, DM.DATE_OP
END
ELSE BEGIN
    SELECT
        ID_DOCUMENT = CAST(NULL AS UNIQUEIDENTIFIER),
        DOC_NAME = CAST(NULL AS NVARCHAR(128)),
		DATE_OP = CAST(NULL AS DATETIME),
		DOC_NUM = CAST(NULL AS NVARCHAR(128)),
		INCOMING_NUMBER = CAST(NULL AS NVARCHAR(128)),
        SUM_SUP = CAST(NULL AS MONEY),
        SUM_ACC = CAST(NULL AS MONEY),
		KOF = CAST(NULL AS BIT),
		SUM_SVAT_SUP = CAST(NULL AS MONEY),
		SUM_SVAT_ACC = CAST(NULL AS MONEY),
		SUM_SUP0 = CAST(NULL AS MONEY),
		SUM_SUP10 = CAST(NULL AS MONEY),
		SUM_SUP18 = CAST(NULL AS MONEY),
		SUM_ACC0 = CAST(NULL AS MONEY),
		SUM_ACC10 = CAST(NULL AS MONEY),
		SUM_ACC18 = CAST(NULL AS MONEY),
	    SVAT_SUP10 = CAST(NULL AS MONEY),
	    SVAT_SUP18 = CAST(NULL AS MONEY),
	    SVAT_ACC10 = CAST(NULL AS MONEY),
	    SVAT_ACC18 = CAST(NULL AS MONEY)
END

IF(@SHOW_SUB = 1) BEGIN
	-- Œ¡Ÿ»… –¿—’Œƒ œŒ ƒŒ ”Ã≈Õ“¿Ã
	SELECT 
        ID_DOCUMENT = DM.ID_DOCUMENT,
        DOC_NAME = ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')',''),--(SELECT TOP 1 [DESCRIPTION_EXT] FROM FN_DOC_MOVEMENT_DESCRIPTION() DMD
        DATE_OP = DM.DATE_OP, 
        DOC_NUM = AD.DOC_NUM,
		
		SUM_DIS = SUM(CASE WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE=19 THEN DM.SUM_ACC * DM.SIGN_OP
						   WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE<>19 THEN DM.SUM_ACC
						   ELSE 0 END),
	    SUM_SUP = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
						   ELSE DM.SUM_SUP * DM.SIGN_OP * -1
						   END),--SUM(DM.SUM_SUP),
	    SUM_ACC = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
						   ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   END),
		NAL = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_ACC * DM.SIGN_OP * -1 END - 
				  CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_SUP * DM.SIGN_OP * -1 END),
	    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,
	
	    SUM_SVAT_SUP = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
						   ELSE DM.SVAT_SUP * DM.SIGN_OP * -1
						   END),--SUM(DM.SVAT_SUP),
	    SUM_SVAT_ACC = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
						   ELSE DM.SVAT_ACC * DM.SIGN_OP * -1
						   END),--SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP),
	
	    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN DM.SUM_SUP ELSE 0 END),
	    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SUM_SUP ELSE 0 END),
	    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SUM_SUP ELSE 0 END),
	    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	
	    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SVAT_SUP ELSE 0 END),
	    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SVAT_SUP ELSE 0 END),
	    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SVAT_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SVAT_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END)	
	INTO #T
    FROM DOC_MOVEMENT DM
    INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = DM.ID_TABLE
    INNER JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = DM.ID_DOCUMENT
    LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_TO
    LEFT JOIN STORE S ON S.ID_STORE = DM.ID_STORE_TO
    WHERE (CODE_OP IN ('SUB', 'DIS') OR DM.ID_TABLE=19)
		AND DATE_OP BETWEEN @DATE_FR AND @DATE_TO
		AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)	 
    GROUP BY DM.ID_DOCUMENT, 
		     DM.ID_TABLE, 
             TD.DESCRIPTION, 
             DM.DATE_OP, 
             AD.DOC_NUM,
             ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','')
-- 			 CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(DM.ID_CONTRACTOR_TO, 0) END,
-- 			 CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END			
    ORDER BY CASE WHEN NULLIF(@SORT_DOC,0) IS NULL THEN DM.DATE_OP ELSE DM.ID_TABLE END, DM.DATE_OP

	SELECT * FROM #T

	SELECT SUM_DIS = SUM(SUM_DIS) FROM #T
END
ELSE BEGIN
    SELECT
        ID_DOCUMENT = CAST(NULL AS UNIQUEIDENTIFIER),
        DOC_NAME = CAST(NULL AS NVARCHAR(128)),
		DATE_OP = CAST(NULL AS DATETIME),
		DOC_NUM = CAST(NULL AS NVARCHAR(128)),
		SUM_DIS = CAST(NULL AS MONEY),
        SUM_SUP = CAST(NULL AS MONEY),
        SUM_ACC = CAST(NULL AS MONEY),
		KOF = CAST(NULL AS BIT),
		SUM_SVAT_SUP = CAST(NULL AS MONEY),
		SUM_SVAT_ACC = CAST(NULL AS MONEY),
		SUM_SUP0 = CAST(NULL AS MONEY),
		SUM_SUP10 = CAST(NULL AS MONEY),
		SUM_SUP18 = CAST(NULL AS MONEY),
		SUM_ACC0 = CAST(NULL AS MONEY),
		SUM_ACC10 = CAST(NULL AS MONEY),
		SUM_ACC18 = CAST(NULL AS MONEY),
	    SVAT_SUP10 = CAST(NULL AS MONEY),
	    SVAT_SUP18 = CAST(NULL AS MONEY),
	    SVAT_ACC10 = CAST(NULL AS MONEY),
	    SVAT_ACC18 = CAST(NULL AS MONEY)
END

DECLARE @STORES VARCHAR(1024)
DECLARE @CONTRACTORS VARCHAR(1024)

EXEC DBO.USP_TABLE_NAMES '#STORE', @STORES OUT
EXEC DBO.USP_TABLE_NAMES '#CONTRACTOR', @CONTRACTORS OUT
SELECT CONTRACTOR = @CONTRACTORS, STORE = @STORES

-- Œ—“¿“Œ  Õ¿  ŒÕ≈÷
    SELECT
        SUM_SUP = SUM(DM.SUM_SUP * DM.SIGN_OP),
        SUM_ACC = SUM(CASE WHEN ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP),
		NAL = SUM(CASE WHEN ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP - DM.SUM_SUP * DM.SIGN_OP),
	    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,
	
	    SUM_SVAT_SUP = SUM(DM.SVAT_SUP * DM.SIGN_OP),
	    SUM_SVAT_ACC = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP),
	
	    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
	    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
	    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SUM_ACC * DM.SIGN_OP ELSE 0 END),
	
	    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN SVAT_ACC * DM.SIGN_OP ELSE 0 END),
	    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SVAT_ACC * DM.SIGN_OP ELSE 0 END)	
    FROM DOC_MOVEMENT DM
    WHERE DATE_OP <= @DATE_TO
    AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)

RETURN 0
GO

--exec REP_GOODS_REPORTS_TO_EX @xmlParam = N'<XML><DATE_FR>2008-07-21T00:00:00.000</DATE_FR><DATE_TO>2008-11-19T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_CONTRACTOR>5271</ID_CONTRACTOR></XML>'
--exec REP_GOODS_REPORTS_TO_EX @xmlParam = N'<XML><DATE_FR>2008-01-01T00:00:00.000</DATE_FR><DATE_TO>2009-02-10T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_CONTRACTOR>5271</ID_CONTRACTOR></XML>'
--exec REP_TAX_GROUPS_SHORT_REP_EX @xmlParam = N'<XML><DATE_FR>2009-01-01T00:00:00.000</DATE_FR><DATE_TO>2009-05-15T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_CONTRACTOR>5271</ID_CONTRACTOR></XML>'