SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_IM_TORG_13') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_IM_TORG_13 AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_IM_TORG_13
	(@XMLPARAM NTEXT) AS 
		
DECLARE	@HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
		
SELECT TOP 1 @ID_GLOBAL = ID_GLOBAL
FROM OPENXML(@HDOC , '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC 
DECLARE @INVENTORY_CALC_PRICE VARCHAR(100)
select @INVENTORY_CALC_PRICE = VALUE from SYS_OPTION
where code ='INVENTORY_CALC_PRICE'
--select @INVENTORY_CALC_PRICE

SELECT
	DOC_NUM = IM.MNEMOCODE,
	DOC_DATE = IM.DATE,
	NAME_FR = C_FR.NAME,
	NAME_TO = C_TO.NAME,
	OKPO_FR = C_FR.OKPO	
FROM INTERFIRM_MOVING IM
	INNER JOIN STORE S_FR ON S_FR.ID_STORE = IM.ID_STORE_FROM_MAIN
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S_FR.ID_CONTRACTOR
	INNER JOIN STORE S_TO ON S_TO.ID_STORE = IM.ID_STORE_TO_MAIN
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = S_TO.ID_CONTRACTOR
WHERE ID_INTERFIRM_MOVING_GLOBAL = @ID_GLOBAL

DECLARE @USE_VAT BIT
SELECT @USE_VAT = C_FR.USE_VAT
FROM INTERFIRM_MOVING IM
	INNER JOIN STORE S_FR ON S_FR.ID_STORE = IM.ID_STORE_FROM_MAIN
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S_FR.ID_CONTRACTOR
WHERE ID_INTERFIRM_MOVING_GLOBAL = @ID_GLOBAL

SELECT
	GOODS_NAME = G.NAME,
	GOODS_CODE = G.CODE,
	UNIT_NAME = CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	OKEI_CODE = U.OKEI_CODE,
	QUANTITY = II.QUANTITY,
	PRICE_SUP =CASE WHEN @INVENTORY_CALC_PRICE = 'SAL' THEN II.PVAT_RETAIL ELSE L.PRICE_SUP END,-- ,--CASE WHEN @USE_VAT <> 1 THEN L.PRICE_SUP ELSE L.PRICE_SUP - L.PVAT_SUP END,
	SUM_SUP = CASE WHEN @INVENTORY_CALC_PRICE = 'SAL' THEN II.PVAT_RETAIL ELSE L.PRICE_SUP END * II.QUANTITY,-- CASE WHEN @USE_VAT <> 1 THEN II.SUM_SUPPLIER ELSE II.SUM_SUPPLIER / (100 + L.VAT_SUP) * 100 END,
	PRICE_PROD = L.PRICE_PROD,
	SUM_PROD = II.QUANTITY * L.PRICE_PROD
	--select * 
FROM INTERFIRM_MOVING_ITEM II
	INNER JOIN LOT L ON L.ID_LOT = II.ID_LOT_FROM
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON L.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	INNER JOIN UNIT AS U ON U.ID_UNIT = SR.ID_UNIT
WHERE II.ID_INTERFIRM_MOVING_GLOBAL = @ID_GLOBAL
ORDER BY G.NAME
	
RETURN 0
GO

--exec REPEX_IM_TORG_13 N'<XML><ID_GLOBAL>E0040B60-39D0-46DD-8404-0F818DCDC3FC</ID_GLOBAL></XML>'
/*
select * 
FROM INTERFIRM_MOVING
WHERE ID_INTERFIRM_MOVING_GLOBAL ='E0040B60-39D0-46DD-8404-0F818DCDC3FC'
*/