SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_F29N_INTERFIRM_MOVING') IS NULL EXEC('CREATE PROCEDURE REPEX_F29N_INTERFIRM_MOVING AS RETURN')
GO
ALTER PROCEDURE REPEX_F29N_INTERFIRM_MOVING
	(@XMLPARAM NTEXT) AS 

DECLARE @HDOC INT, @ID_MOVEMENT BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_MOVEMENT = ID_INTERFIRM_MOVING
	FROM OPENXML(@HDOC, '/XML') WITH(ID_INTERFIRM_MOVING BIGINT 'ID_INTERFIRM_MOVING')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	case
	  when Full_NAME is null then NAME 
	  when Full_NAME = '' then NAME 
	  else Full_NAME
	 end AS COMPANY
FROM CONTRACTOR WHERE ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()

SELECT
	MNEMOCODE = MNEMOCODE, --+ ' ' + COMMENT,
	DATE,
	STORENAMEFROM = (SELECT TOP 1 case 
	                                  when C.FULL_NAME is null then C.NAME
	                                  when C.FULL_NAME = '' then C.NAME
	                                  else  C.FULL_NAME
	                                end  + ' - ' + S.NAME FROM STORE AS S  
		LEFT JOIN CONTRACTOR AS C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
		WHERE S.ID_STORE = M.ID_STORE_FROM_MAIN),
	STORENAMETO = (SELECT TOP 1 case 
	                                  when C.FULL_NAME is null then C.NAME
	                                  when C.FULL_NAME = '' then C.NAME
	                                  else  C.FULL_NAME
	                                end + ' - ' + S.NAME FROM STORE AS S 
		LEFT JOIN CONTRACTOR AS C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR 
		WHERE S.ID_STORE = M.ID_STORE_TO_MAIN),
		MOL_STORE_TO = (select top 1 e.LAST_NAME+' '+LEFT(e.FIRST_NAME,1)+'. '+LEFT(e.MIDDLE_NAME,1)+'. ' 
		from EMPLOYEE e, STORE s 
		where s.ID_STORE=M.ID_STORE_TO_MAIN and s.INVENTORY_CUSTODIAN=e.ID_EMPLOYEE)
	/*ƒÓÍÛÏÂÌÚ ÓÒÌÓ‚‡ÌËÂ*/--DOC = (SELECT TOP 1 'œ–»’ŒƒÕ¿ﬂ Õ¿ À¿ƒÕ¿ﬂ ' + INV.MNEMOCODE + ' Œ“ '+ CONVERT(VARCHAR(10),INV.DOCUMENT_DATE,104) FROM INVOICE AS INV WHERE M.ID_DOCUMENT_BASE = INV.ID_INVOICE)
FROM INTERFIRM_MOVING AS M 
WHERE ID_INTERFIRM_MOVING = @ID_MOVEMENT

SELECT
	GOODSNAME = G.NAME + ' ( ' + (SELECT TOP 1 P.NAME FROM PRODUCER AS P WHERE G.ID_PRODUCER = P.ID_PRODUCER) + ' ) ',
	SERIESNUMBER = SER.SERIES_NUMBER,
	QUANTITY = M.QUANTITY,
	UNITNAME = DBO.FN_SCALE_NAME(L.ID_SCALING_RATIO),
	BEST_BEFORE = DBO.REP_DATE(SER.BEST_BEFORE),
	PRICE_SALE = L.PRICE_SAL,
	PRICE_SUMM_SALE = QUANTITY * L.PRICE_SAL,
	PRICE_SUPPLIER = L.PRICE_SUP,
	PRICE_SUMMA = QUANTITY * L.PRICE_SUP,
	PRICE_SUPPLIER_VAT = L.PVAT_SUP,
	PRICE_SUMMA_VAT = QUANTITY * L.PVAT_SUP,
	INTERNAL_BARCODE = L.INTERNAL_BARCODE
FROM INTERFIRM_MOVING_ITEM AS M
	INNER JOIN LOT L ON L.ID_LOT = M.ID_LOT_FROM
	LEFT JOIN GOODS AS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN SERIES SER ON SER.ID_SERIES = L.ID_SERIES
	LEFT JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	LEFT JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT 
WHERE (ID_INTERFIRM_MOVING_GLOBAL = (select ID_INTERFIRM_MOVING_GLOBAL from INTERFIRM_MOVING where ID_INTERFIRM_MOVING = @ID_MOVEMENT))
ORDER BY GOODSNAME

SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO,
	MOL = e.LAST_NAME+' '+LEFT(e.FIRST_NAME,1)+'. '+LEFT(e.MIDDLE_NAME,1)+'. '
FROM CONTRACTOR c, EMPLOYEE e
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)
and c.ID_MOL=e.ID_EMPLOYEE

RETURN 0
GO

--exec REPEX_F29N_INTERFIRM_MOVING '<XML><ID_MOVEMENT>212</ID_MOVEMENT></XML>'