SET NOCOUNT ON
--USE EPLUS_DEV10
IF OBJECT_ID('REP_INVOICE_BOOK_EX') IS NULL EXEC('CREATE PROCEDURE REP_INVOICE_BOOK_EX AS RETURN')
GO
ALTER PROCEDURE REP_INVOICE_BOOK_EX @XMLPARAM NTEXT AS
		
DECLARE	@HDOC INT
DECLARE	@DATE_FROM DATETIME
DECLARE @DATE_TO DATETIME
DECLARE @ID_STORE BIGINT
DECLARE @DETAIL BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT , @XMLPARAM OUTPUT
		
	SELECT	TOP 1 
        @DATE_FROM = DATE_FROM, 
        @DATE_TO = DATE_TO, 
        @ID_STORE = ID_STORE, 
        @DETAIL = DETAIL
	FROM OPENXML(@HDOC , '/XML') 
    WITH(DATE_FROM DATETIME 'DATE_FROM', DATE_TO DATETIME 'DATE_TO', ID_STORE BIGINT 'ID_STORE', DETAIL BIT 'DETAIL')
		
EXEC SP_XML_REMOVEDOCUMENT @HDOC
EXEC USP_RANGE_DAYS @DATE_FROM OUTPUT, @DATE_TO OUTPUT
		
IF	@DETAIL = 1
BEGIN		
	SELECT	
        ID_CONTRACTOR_SUPPLIER = o.ID_CONTRACTOR_SUPPLIER, 
        CONTRACTOR_NAME = o.CONTRACTOR_NAME,
		MNEMOCODE = o.MNEMOCODE,
        DATE = o.DATE,
        INCOMING_NUMBER = o.INCOMING_NUMBER,
        INCOMING_DATE = o.INCOMING_DATE ,
		CONTRACTOR_SUM_VAT = SUM(CONTRACTOR_SUM_VAT) , RETAIL_SUM = SUM(RETAIL_SUM),
		SUPPLIER_VAT_RATE_18 = SUM(SUPPLIER_VAT_RATE_18) , SUPPLIER_VAT_RATE_10 = SUM(SUPPLIER_VAT_RATE_10),
		RETAIL_VAT_RATE_18 = SUM(RETAIL_VAT_RATE_18) , RETAIL_VAT_RATE_10 = SUM(RETAIL_VAT_RATE_10),
		SUM_NP = 0,
        SUM_PROD = 0
	FROM	(
	SELECT	ID_INVOICE_ITEM = II.ID_INVOICE_ITEM,
		ID_CONTRACTOR_SUPPLIER = MAX(I.ID_CONTRACTOR_SUPPLIER),
		CONTRACTOR_NAME = MAX(C.NAME),
		MNEMOCODE = MAX(I.MNEMOCODE),
		DATE = MAX(I.DOCUMENT_DATE),
		INCOMING_NUMBER = MAX(I.INCOMING_NUMBER),
		INCOMING_DATE = MAX(I.INCOMING_DATE),
		CONTRACTOR_SUM_VAT = MAX(II.SUPPLIER_SUM_VAT),
		RETAIL_SUM = MAX(II.RETAIL_SUM_VAT),
		SUPPLIER_VAT_RATE_18 = CASE WHEN MAX(II.SUPPLIER_VAT) = 18.0 THEN MAX(II.SUPPLIER_VAT_SUM) ELSE 0 END,
		SUPPLIER_VAT_RATE_10 = CASE WHEN MAX(II.SUPPLIER_VAT) = 10.0 THEN MAX(II.SUPPLIER_VAT_SUM) ELSE 0 END,
		RETAIL_VAT_RATE_18 = CASE WHEN MAX(II.RETAIL_VAT) = 18.0 THEN MAX(II.RETAIL_VAT_SUM) ELSE 0 END,
		RETAIL_VAT_RATE_10 = CASE WHEN MAX(II.RETAIL_VAT) = 10.0 THEN MAX(II.RETAIL_VAT_SUM) ELSE 0 END,
		SUM_NP = 0,
		SUM_PROD = 0
	FROM CONTRACTOR C(NOLOCK), LOT L(NOLOCK), INVOICE I(NOLOCK), INVOICE_ITEM II(NOLOCK)
	WHERE L.ID_TABLE = 2 AND I.ID_STORE = @ID_STORE AND I.DOCUMENT_STATE = 'PROC' AND
		C.ID_CONTRACTOR = I.ID_CONTRACTOR_SUPPLIER AND L.ID_DOCUMENT = I.ID_INVOICE_GLOBAL AND I.ID_INVOICE = II.ID_INVOICE AND
		I.DOCUMENT_DATE BETWEEN @DATE_FROM AND @DATE_TO
	GROUP BY II.ID_INVOICE_ITEM
		) o	
	GROUP	BY o.ID_CONTRACTOR_SUPPLIER , o.CONTRACTOR_NAME , o.MNEMOCODE , o.DATE , o.INCOMING_NUMBER , o.INCOMING_DATE
END		
ELSE		
BEGIN		
	SELECT	ID_CONTRACTOR_SUPPLIER = o.ID_CONTRACTOR_SUPPLIER , CONTRACTOR_NAME = o.CONTRACTOR_NAME ,
		CONTRACTOR_SUM_VAT = SUM(o.CONTRACTOR_SUM_VAT) , RETAIL_SUM = SUM(o.RETAIL_SUM) ,
		SUPPLIER_VAT_RATE_18 = SUM(o.SUPPLIER_VAT_RATE_18) , SUPPLIER_VAT_RATE_10 = SUM(o.SUPPLIER_VAT_RATE_10) ,
		RETAIL_VAT_RATE_18 = SUM(o.RETAIL_VAT_RATE_18) , RETAIL_VAT_RATE_10 = SUM(o.RETAIL_VAT_RATE_10) ,
		SUM_NP = 0 , SUM_PROD = 0
	FROM	(	
	SELECT	ID_INVOICE_ITEM = II.ID_INVOICE_ITEM ,
		ID_CONTRACTOR_SUPPLIER = MAX(I.ID_CONTRACTOR_SUPPLIER) ,
		CONTRACTOR_NAME = MAX(C.NAME) ,
		CONTRACTOR_SUM_VAT = MAX(II.SUPPLIER_SUM_VAT) ,
		RETAIL_SUM = MAX(II.RETAIL_SUM_VAT) ,
		SUPPLIER_VAT_RATE_18 = CASE WHEN MAX(II.SUPPLIER_VAT) = 18.0 THEN MAX(II.SUPPLIER_VAT_SUM) ELSE 0 END ,
		SUPPLIER_VAT_RATE_10 = CASE WHEN MAX(II.SUPPLIER_VAT) = 10.0 THEN MAX(II.SUPPLIER_VAT_SUM) ELSE 0 END ,
		RETAIL_VAT_RATE_18 = CASE WHEN MAX(II.RETAIL_VAT) = 18.0 THEN MAX(II.RETAIL_VAT_SUM) ELSE 0 END ,
		RETAIL_VAT_RATE_10 = CASE WHEN MAX(II.RETAIL_VAT) = 10.0 THEN MAX(II.RETAIL_VAT_SUM) ELSE 0 END ,
		SUM_NP = 0 ,
		SUM_PROD = 0
	FROM	CONTRACTOR C(NOLOCK) , LOT L(NOLOCK) , INVOICE I(NOLOCK) , INVOICE_ITEM II(NOLOCK)
	WHERE	L.ID_TABLE = 2 AND I.ID_STORE = @ID_STORE AND I.DOCUMENT_STATE = 'PROC' AND
		C.ID_CONTRACTOR = I.ID_CONTRACTOR_SUPPLIER AND L.ID_DOCUMENT = I.ID_INVOICE_GLOBAL AND I.ID_INVOICE = II.ID_INVOICE AND
		I.DOCUMENT_DATE BETWEEN @DATE_FROM AND @DATE_TO
	GROUP	BY II.ID_INVOICE_ITEM
		) o	
	GROUP	BY o.ID_CONTRACTOR_SUPPLIER , o.CONTRACTOR_NAME
END		

SELECT	COMPANY = ISNULL(NAME , '')
FROM	CONTRACTOR
WHERE	ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()

SELECT 
    CONTRACTOR_STORE = ISNULL(C.NAME , ''),
   S.NAME
FROM CONTRACTOR C
LEFT JOIN STORE S ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
		
FINISH:	RETURN ( 0 )
GO
-- EXEC	DBO.REP_INVOICE_BOOK_EX '<XML><DATE_FROM>2006-01-01</DATE_FROM><DATE_TO>2006-11-30</DATE_TO><ID_STORE>84</ID_STORE><DETAIL>1</DETAIL></XML>'
-- GO
--exec REP_INVOICE_BOOK_EX @xmlParam = N'<XML><DATE_FROM>2008-09-01</DATE_FROM><DATE_TO>2008-10-02</DATE_TO><ID_STORE>148</ID_STORE><DETAIL>1</DETAIL></XML>'