SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_R36RGLVNS_Law_reps') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_R36RGLVNS_Law_reps AS RETURN')
GO
ALTER  PROCEDURE DBO.REPEX_R36RGLVNS_Law_reps
	@XMLPARAM NTEXT AS

DECLARE @HDOC INT
--DECLARE @TEXT NVARCHAR(4000)
DECLARE @DATE_OST DATETIME
--DECLARE @ALL_GOODS BIT
DECLARE @ALL_STORE BIT,@IS_20 BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @DATE_OST = DATE_OST , @IS_20=IS_20
		FROM OPENXML(@HDOC, '/XML') 
	WITH(DATE_OST DATETIME 'DATE_OST' , IS_20 BIT 'IS_20')

	SELECT * INTO #STORE
	FROM OPENXML(@HDOC, '//ID_STORE') 
	WITH(ID_STORE BIGINT '.') WHERE ID_STORE <> 0
	IF @@ROWCOUNT = 0 SET @ALL_STORE = 1

EXEC SP_XML_REMOVEDOCUMENT @HDOC

--EXEC DBO.USP_RANGE_NORM NULL, @DATE_OST OUT
/*
SELECT 
    ISNULL(CNT.NAME, '') AS COMPANY,
    CNT.PHONE
FROM DBO.CONTRACTOR CNT
WHERE CNT.ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()*/

if (@IS_20=0) 
begin
SELECT '' AS MNN,CT.NAME AS APTEKA, G.CODE AS GOODS_CODE, G.NAME AS GOODS_NAME, 
	PR.NAME AS PRODUCER_NAME, SUM(L.QUANTITY_REM) AS QUANTITY_REM, 
	'' AS CONTRACTOR,
    --CASE WHEN G.IMPORTANT = 1 THEN 'Да' ELSE 'Нет' END AS GNVLS, 
    G.REGISTER_PRICE AS REESTR_PRICE, 
    RESULT_WITHOUT_DATE.SUPPLIER_PRICE_VAT AS SUPPLIER_PRICE_VAT_WD, 
    RESULT_WITHOUT_DATE.RETAIL_PRICE AS RETAIL_PRICE_WD, 
    RESULT_WITHOUT_DATE.RETAIL_ADPRICE AS RETAIL_ADPRICE_WD, 
    RESULT_WITH_DATE.SUPPLIER_PRICE_VAT AS SUPPLIER_PRICE_VAT_D, 
    RESULT_WITH_DATE.RETAIL_PRICE AS RETAIL_PRICE_D, 
    RESULT_WITH_DATE.RETAIL_ADPRICE AS RETAIL_ADPRICE_D,
    avg((RESULT_WITH_DATE.RETAIL_ADPRICE+RESULT_WITHOUT_DATE.RETAIL_ADPRICE)/2) AS RETAIL_ADPRICE
FROM LOT AS L INNER JOIN GOODS AS G ON G.ID_GOODS = L.ID_GOODS 
INNER JOIN STORE AS S ON S.ID_STORE = L.ID_STORE 
INNER JOIN CONTRACTOR AS CT ON CT.ID_CONTRACTOR = S.ID_CONTRACTOR 
INNER JOIN PRODUCER AS PR ON PR.ID_PRODUCER = G.ID_PRODUCER 
LEFT OUTER JOIN (SELECT INVOICE_ITEM_1.ID_GOODS, 
					AVG(INVOICE_ITEM_1.SUPPLIER_PRICE_VAT) AS SUPPLIER_PRICE_VAT, 
					AVG(INVOICE_ITEM_1.RETAIL_PRICE) AS RETAIL_PRICE, 
					AVG(INVOICE_ITEM_1.RETAIL_ADPRICE) AS RETAIL_ADPRICE
                 FROM INVOICE_ITEM AS INVOICE_ITEM_1 
                 INNER JOIN INVOICE AS INVOICE_1 
							ON INVOICE_ITEM_1.ID_INVOICE = INVOICE_1.ID_INVOICE 
							AND INVOICE_ITEM_1.ID_INVOICE_GLOBAL = INVOICE_1.ID_INVOICE_GLOBAL
                 WHERE (INVOICE_1.DOCUMENT_STATE = 'PROC') 
                 AND (@ALL_STORE = 1 OR INVOICE_1.ID_STORE IN (SELECT ID_STORE FROM #STORE))
                 AND (INVOICE_1.DOCUMENT_DATE < CONVERT(DATETIME, '2012-01-01 00:00:00', 102))
                 GROUP BY INVOICE_ITEM_1.ID_GOODS
                 ) AS RESULT_WITH_DATE ON L.ID_GOODS = RESULT_WITH_DATE.ID_GOODS 
LEFT OUTER JOIN (SELECT INVOICE_ITEM.ID_GOODS, 
					AVG(INVOICE_ITEM.SUPPLIER_PRICE_VAT) AS SUPPLIER_PRICE_VAT, 
					AVG(INVOICE_ITEM.RETAIL_PRICE) AS RETAIL_PRICE, 
					AVG(INVOICE_ITEM.RETAIL_ADPRICE) AS RETAIL_ADPRICE
                 FROM INVOICE_ITEM 
				 INNER JOIN INVOICE ON INVOICE_ITEM.ID_INVOICE = INVOICE.ID_INVOICE 
							AND INVOICE_ITEM.ID_INVOICE_GLOBAL = INVOICE.ID_INVOICE_GLOBAL
                 WHERE (INVOICE.DOCUMENT_STATE = 'PROC')
                 AND (@ALL_STORE = 1 OR INVOICE.ID_STORE IN (SELECT ID_STORE FROM #STORE))
                 AND (INVOICE.DOCUMENT_DATE <= @DATE_OST)
                 GROUP BY INVOICE_ITEM.ID_GOODS
                 ) AS RESULT_WITHOUT_DATE ON L.ID_GOODS = RESULT_WITHOUT_DATE.ID_GOODS 
WHERE (L.QUANTITY_REM > 0) AND (G.IMPORTANT = 1) AND (L.PRICE_PROD <> 0)
AND  (@ALL_STORE = 1 OR L.ID_STORE IN (SELECT ID_STORE FROM #STORE))
--AND LM.DATE_OP <= @DATE_OST
GROUP BY CT.NAME,/* L.ID_LOT_GLOBAL,*/ G.CODE, G.NAME, PR.NAME, 
	--CASE WHEN G.IMPORTANT = 1 THEN 'Да' ELSE 'Нет' END, G.ID_GOODS, 
    RESULT_WITHOUT_DATE.SUPPLIER_PRICE_VAT, RESULT_WITHOUT_DATE.RETAIL_PRICE, 
    RESULT_WITHOUT_DATE.RETAIL_ADPRICE, RESULT_WITH_DATE.SUPPLIER_PRICE_VAT, 
    RESULT_WITH_DATE.RETAIL_PRICE, RESULT_WITH_DATE.RETAIL_ADPRICE, G.REGISTER_PRICE
ORDER BY GOODS_NAME,APTEKA
end
else
begin
/*SELECT     ES_GOODS_NAIMS.TRN_NAME_RUS AS [Международное непат. название],
CT.NAME AS Аптека, 
G.NAME AS [Торговое наименование],
PR.NAME AS [Производитель],
SUM(L.QUANTITY_REM) AS [Кол-во уп.],
(CONTRACTOR_1.FULL_NAME + CONTRACTOR_1.ADDRESS) AS [Поставщик],
RESULT_WITHOUT_DATE.SUPPLIER_PRICE_VAT AS [Цена 1 уп.в соот. с протоколом пост.],
RESULT_WITH_DATE.RETAIL_PRICE AS [Отпуск.роз.цена на 010112],
RESULT_WITHOUT_DATE.RETAIL_PRICE AS [Отпуск.роз.цена на тек. дата],
RESULT_WITHOUT_DATE.RETAIL_ADPRICE AS [Размер общей опт. надбавки]*/

SELECT     ES_GOODS_NAIMS.TRN_NAME_RUS AS MNN,
CT.NAME AS APTEKA, G.CODE AS GOODS_CODE,G.NAME AS GOODS_NAME,
PR.NAME AS PRODUCER_NAME,SUM(L.QUANTITY_REM) AS QUANTITY_REM,
(CONTRACTOR_1.FULL_NAME + CONTRACTOR_1.ADDRESS) AS CONTRACTOR,
0 AS REESTR_PRICE,
RESULT_WITHOUT_DATE.SUPPLIER_PRICE_VAT AS SUPPLIER_PRICE_VAT_WD,
RESULT_WITHOUT_DATE.RETAIL_PRICE AS RETAIL_PRICE_WD,
0 AS RETAIL_ADPRICE_WD,
0 AS SUPPLIER_PRICE_VAT_D, 
RESULT_WITH_DATE.RETAIL_PRICE AS RETAIL_PRICE_D,
0 AS RETAIL_ADPRICE_D,
RESULT_WITHOUT_DATE.RETAIL_ADPRICE AS RETAIL_ADPRICE
FROM LOT AS L 
INNER JOIN GOODS AS G ON G.ID_GOODS = L.ID_GOODS 
INNER JOIN STORE AS S ON S.ID_STORE = L.ID_STORE 
INNER JOIN CONTRACTOR AS CT ON CT.ID_CONTRACTOR = S.ID_CONTRACTOR  
INNER JOIN CONTRACTOR AS CONTRACTOR_1 ON  L.ID_SUPPLIER = CONTRACTOR_1.ID_CONTRACTOR  
INNER JOIN PRODUCER AS PR ON PR.ID_PRODUCER = G.ID_PRODUCER 
LEFT OUTER JOIN (SELECT INVOICE_1.ID_CONTRACTOR_SUPPLIER,
				(CONTRACTOR_1.FULL_NAME + CONTRACTOR_1.ADDRESS) AS SUPPLIER_NAME, 
				INVOICE_ITEM_1.ID_GOODS, 
				AVG(INVOICE_ITEM_1.SUPPLIER_PRICE_VAT) AS SUPPLIER_PRICE_VAT, 
				AVG(INVOICE_ITEM_1.RETAIL_PRICE) AS RETAIL_PRICE, 
				AVG(INVOICE_ITEM_1.RETAIL_ADPRICE) AS RETAIL_ADPRICE
                FROM INVOICE_ITEM AS INVOICE_ITEM_1 
                INNER JOIN INVOICE AS INVOICE_1 
						ON INVOICE_ITEM_1.ID_INVOICE_GLOBAL = INVOICE_1.ID_INVOICE_GLOBAL 
				INNER JOIN CONTRACTOR AS CONTRACTOR_1 
						ON INVOICE_1.ID_CONTRACTOR_SUPPLIER = CONTRACTOR_1.ID_CONTRACTOR
                WHERE (INVOICE_1.DOCUMENT_STATE = 'PROC') 
                AND (INVOICE_1.DOCUMENT_DATE < CONVERT(DATETIME, '2012-01-01 00:00:00', 102)) 
                AND (@ALL_STORE = 1 OR INVOICE_1.ID_STORE IN (SELECT ID_STORE FROM #STORE))
                GROUP BY INVOICE_1.ID_CONTRACTOR_SUPPLIER, 
                (CONTRACTOR_1.FULL_NAME + CONTRACTOR_1.ADDRESS), INVOICE_ITEM_1.ID_GOODS
                ) AS RESULT_WITH_DATE 
					ON L.ID_GOODS = RESULT_WITH_DATE.ID_GOODS 
					AND L.ID_SUPPLIER = RESULT_WITH_DATE.ID_CONTRACTOR_SUPPLIER 
LEFT OUTER JOIN (SELECT INVOICE.ID_CONTRACTOR_SUPPLIER, 
				(CONTRACTOR.FULL_NAME + CONTRACTOR.ADDRESS) AS SUPPLIER_NAME, 
				INVOICE_ITEM.ID_GOODS, 
--				AVG(INVOICE_ITEM.SUPPLIER_PRICE_VAT) AS SUPPLIER_PRICE_VAT,
				AVG(INVOICE_ITEM.PRODUCER_PRICE) AS SUPPLIER_PRICE_VAT, /*фактическая отпускная цена производителя*/
				AVG(INVOICE_ITEM.RETAIL_PRICE) AS RETAIL_PRICE, 
--				AVG(INVOICE_ITEM.RETAIL_ADPRICE) AS RETAIL_ADPRICE
				AVG(INVOICE_ITEM.SUPPLIER_ADPRICE) AS RETAIL_ADPRICE
                FROM INVOICE_ITEM 
                INNER JOIN INVOICE ON INVOICE_ITEM.ID_INVOICE_GLOBAL = INVOICE.ID_INVOICE_GLOBAL 
                INNER JOIN CONTRACTOR AS CONTRACTOR ON INVOICE.ID_CONTRACTOR_SUPPLIER = CONTRACTOR.ID_CONTRACTOR
                WHERE (INVOICE.DOCUMENT_STATE = 'PROC')  
                AND (@ALL_STORE = 1 OR INVOICE.ID_STORE IN (SELECT ID_STORE FROM #STORE))
                AND (INVOICE.DOCUMENT_DATE <= @DATE_OST)
                GROUP BY INVOICE.ID_CONTRACTOR_SUPPLIER, 
                (CONTRACTOR.FULL_NAME + CONTRACTOR.ADDRESS),INVOICE_ITEM.ID_GOODS
                ) AS RESULT_WITHOUT_DATE ON L.ID_GOODS = RESULT_WITHOUT_DATE.ID_GOODS 
										AND L.ID_SUPPLIER = RESULT_WITHOUT_DATE.ID_CONTRACTOR_SUPPLIER
                            
INNER JOIN (SELECT GOODS.ID_GOODS_GLOBAL, ES_EF2.TRN_NAME_RUS
			FROM ES_EF2 INNER JOIN ES_ES_2_GOODS ON ES_EF2.GUID_ES = ES_ES_2_GOODS.C_ES 
			RIGHT OUTER JOIN GOODS ON ES_ES_2_GOODS.ID_GOODS_GLOBAL = GOODS.ID_GOODS_GLOBAL
			) AS ES_GOODS_NAIMS ON G.ID_GOODS_GLOBAL = ES_GOODS_NAIMS. ID_GOODS_GLOBAL                        
WHERE (L.QUANTITY_REM > 0) AND (G.IMPORTANT = 1) AND (L.PRICE_PROD <> 0)                       
AND ((G.NAME LIKE '%Ацетилсалициловая кислота%') OR 
	(G.NAME LIKE '%Ацетилсалицилов%') OR 
    (G.NAME LIKE '%Уголь активированный%') OR
    (G.NAME LIKE '%Ацетилцистеин%') OR
    (G.NAME LIKE '%гидрокортизон%') OR
    (G.NAME LIKE '%скорбинов%') OR
    (G.NAME LIKE '%сенаде%') OR
    (G.NAME LIKE '%флуимуцил%') OR
    (G.NAME LIKE '%лоратадин%') OR
    (G.NAME LIKE '%кларотадин%') OR
    (G.NAME LIKE '%Диклофенак%') OR
    (G.NAME LIKE '%Дротаверин%') OR
    (G.NAME LIKE '%Ибупрофен%') OR
    (G.NAME LIKE '%Кагоцел%') OR
    (G.NAME LIKE '%Клотримазол%') OR
    (G.NAME LIKE '%лоперамид%') OR
    (G.NAME LIKE '%Лоратадин%') OR
    (G.NAME LIKE '%Аскорбиновая кислота%') OR
    (G.NAME LIKE 'Аскорбинов%') OR
    (G.NAME LIKE '%Нитроглицерин%') OR
    (G.NAME LIKE '%Панкреатин%') OR
    (G.NAME LIKE '%Парацетамол%') OR
    (G.NAME LIKE '%Ранитидин%') OR
    (G.NAME LIKE '%Сеннозид%') OR
    (G.NAME LIKE '%Тетрациклин%') OR
    (G.NAME LIKE '%Фамотидин%') OR
    (G.NAME LIKE '%Бисакодил%') )
AND (@ALL_STORE = 1 OR L.ID_STORE IN (SELECT ID_STORE FROM #STORE))
GROUP BY ES_GOODS_NAIMS.TRN_NAME_RUS,CT.NAME, G.CODE, G.NAME, PR.NAME,
(CONTRACTOR_1.FULL_NAME + CONTRACTOR_1.ADDRESS), G.ID_GOODS, RESULT_WITHOUT_DATE.SUPPLIER_PRICE_VAT,
RESULT_WITHOUT_DATE.RETAIL_PRICE, RESULT_WITHOUT_DATE.RETAIL_ADPRICE, RESULT_WITH_DATE.SUPPLIER_PRICE_VAT,
RESULT_WITH_DATE.RETAIL_PRICE, RESULT_WITH_DATE.RETAIL_ADPRICE, G.REGISTER_PRICE

end
RETURN 0
GO