SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_AP_10') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_AP_10 AS RETURN')
GO

ALTER PROCEDURE DBO.REPEX_AP_10
    @XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @DATE_FR DATETIME
DECLARE @DATE_TO DATETIME

DECLARE @ALL_GOODS BIT
DECLARE @ALL_STORE BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUT, @XMLPARAM
SELECT
	@DATE_FR = DATE_FR,
	@DATE_TO = DATE_TO
FROM OPENXML(@HDOC, '/XML') WITH(
	DATE_FR DATETIME 'DATE_FR',
	DATE_TO DATETIME 'DATE_TO'
)

SELECT * INTO #GOODS FROM OPENXML(@HDOC, '//ID_GOODS') 
WITH(ID_GOODS BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_GOODS = 1

SELECT * INTO #STORE FROM OPENXML(@HDOC, '//ID_STORE') 
WITH(ID_STORE BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_STORE = 1;

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT
EXEC USP_RANGE_DAYS @DATE_FR OUT, @DATE_TO OUT

--SELECT @DATE_FR, @DATE_TO
--SELECT @ALL_GOODS
--SELECT * FROM #GOODS
--SELECT * FROM #STORE

SET LANGUAGE RUSSIAN

CREATE TABLE #DOCS
(
	ID_GOODS BIGINT,
	GOODS_NAME VARCHAR(400),
	DOC_NAME VARCHAR(100),	
	QUANTITY MONEY,
	DOC_DATE DATETIME,
	[MONTH] VARCHAR(20),
	MONTH_NUM INT,
	YEAR_NUM INT,
	NUMERATOR INT,
	DENOMINATOR INT,
	ID_UNIT BIGINT
)

INSERT INTO #DOCS
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_NAME = D.MNEMOCODE + ' 我 ' + CONVERT(VARCHAR, D.DOCUMENT_DATE, 112),
	QUANTITY = DI.QUANTITY,
	DOC_DATE = D.DOCUMENT_DATE,
	[MONTH] = DATENAME(MONTH, D.DOCUMENT_DATE),
	MONTH_NUM = DATEPART(month, D.DOCUMENT_DATE),
	YEAR_NUM = DATEPART(year, D.DOCUMENT_DATE),
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM INVOICE D
	INNER JOIN INVOICE_ITEM DI ON DI.ID_INVOICE_GLOBAL = D.ID_INVOICE_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = DI.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = DI.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
WHERE DOCUMENT_DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

INSERT INTO #DOCS
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_NAME = D.MNEMOCODE + ' 我 ' + CONVERT(VARCHAR, D.DOCUMENT_DATE, 112),
	QUANTITY = DI.QUANTITY,
	DOC_DATE = D.DOCUMENT_DATE,
	[MONTH] = DATENAME(MONTH, D.DOCUMENT_DATE),
	MONTH_NUM = DATEPART(month, D.DOCUMENT_DATE),
	YEAR_NUM = DATEPART(year, D.DOCUMENT_DATE),
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM IMPORT_REMAINS D
	INNER JOIN IMPORT_REMAINS_ITEM DI ON DI.ID_IMPORT_REMAINS_GLOBAL = D.ID_IMPORT_REMAINS_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = DI.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = DI.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
WHERE DOCUMENT_DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

INSERT INTO #DOCS
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_NAME = D.MNEMOCODE + ' 我 ' + CONVERT(VARCHAR, D.DATE, 112),
	QUANTITY = DI.QUANTITY,
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM MOVEMENT D
	INNER JOIN MOVEMENT_ITEM DI ON DI.ID_MOVEMENT_GLOBAL = D.ID_MOVEMENT_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = DI.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = DI.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT	
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE_TO IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

INSERT INTO #DOCS
SELECT
	ID_GOODS = L.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_NAME = D.MNEMOCODE + ' 我 ' + CONVERT(VARCHAR, D.DATE, 112),
	QUANTITY = DI.QUANTITY,
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM INTERFIRM_MOVING_ACCEPTANCE_ACT D
	INNER JOIN INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM DI ON DI.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL = D.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL	
	LEFT JOIN LOT L ON L.ID_LOT = DI.ID_LOT_TO
	LEFT JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	LEFT JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT	
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE_TO_MAIN IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (L.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1
	
INSERT INTO #DOCS
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_NAME = D.MNEMOCODE + ' 我 ' + CONVERT(VARCHAR, D.DATE, 112),
	QUANTITY = DI.QUANTITY,	
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	NUMERATOR = sr.numerator,
	DENOMINATOR = sr.denominator,
	ID_UNIT = SR.ID_UNIT
FROM ACT_DISASSEMBLING D
	INNER JOIN ACT_DISASSEMBLING_ITEM DI ON DI.ID_ACT_DISASSEMBLING_GLOBAL = D.ID_ACT_DISASSEMBLING_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = DI.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = DI.ID_SCALING_RATIO_to
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

--SELECT * FROM #DOCS ORDER BY ID_GOODS

DECLARE @NUM INT

DECLARE @ID_GOODS BIGINT
DECLARE @GOODS_NAME VARCHAR(400)
DECLARE @DOC_NAME VARCHAR(100)
DECLARE @MONTH VARCHAR(20)
DECLARE @MONTH_NUM INT
DECLARE @YEAR_NUM INT
DECLARE @QUANTITY MONEY
DECLARE @DOC_DATE DATETIME
DECLARE @NUMERATOR INT
DECLARE @DENOMINATOR INT
DECLARE @ID_UNIT BIGINT

CREATE TABLE #DOCS_X
(
	ID INT IDENTITY(1,1),
	ID_GOODS BIGINT,
	GOODS_NAME VARCHAR(400),
	[MONTH] VARCHAR(20),
	MONTH_NUM INT,
	YEAR_NUM INT,
	D1 VARCHAR(100),
	Q1 MONEY,
	D2 VARCHAR(100),
	Q2 MONEY,
	NUMERATOR INT,
	DENOMINATOR INT,
	ID_UNIT BIGINT,
	CNT INT
)

DECLARE CURS CURSOR FOR SELECT * FROM #DOCS ORDER BY ID_GOODS, DOC_DATE, NUMERATOR, DENOMINATOR

OPEN CURS 
FETCH NEXT FROM CURS INTO @ID_GOODS,
	@GOODS_NAME,
	@DOC_NAME,	
	@QUANTITY,
	@DOC_DATE,
	@MONTH,
	@MONTH_NUM,
	@YEAR_NUM,
	@NUMERATOR,
	@DENOMINATOR,
	@ID_UNIT
	
WHILE @@FETCH_STATUS = 0
BEGIN

SET @NUM = (SELECT ISNULL(SUM(CNT), 0) FROM #DOCS_X WHERE ID_GOODS = @ID_GOODS AND NUMERATOR = @NUMERATOR AND DENOMINATOR = @DENOMINATOR AND [MONTH_NUM] = @MONTH_NUM AND YEAR_NUM = @YEAR_NUM AND ID_UNIT = @ID_UNIT) + 1

IF (@NUM % 2 = 1)
BEGIN
	INSERT INTO #DOCS_X SELECT @ID_GOODS,
		@GOODS_NAME,
		@MONTH,
		@MONTH_NUM,
		@YEAR_NUM,
		@DOC_NAME,
		@QUANTITY,
		NULL,
		NULL,			
		@NUMERATOR,
		@DENOMINATOR,
		@ID_UNIT,
		1
END
ELSE BEGIN
	UPDATE #DOCS_X SET D2 = @DOC_NAME, Q2 = @QUANTITY, CNT = CNT + 1 WHERE ID = (SELECT MAX(ID) FROM #DOCS_X WHERE ID_GOODS = @ID_GOODS AND NUMERATOR = @NUMERATOR AND DENOMINATOR = @DENOMINATOR AND [MONTH_NUM] = @MONTH_NUM AND YEAR_NUM = @YEAR_NUM AND ID_UNIT = @ID_UNIT)
END

FETCH NEXT FROM CURS INTO @ID_GOODS,
	@GOODS_NAME,
	@DOC_NAME,
	@QUANTITY,
	@DOC_DATE,
	@MONTH,
	@MONTH_NUM,
	@YEAR_NUM,
	@NUMERATOR,
	@DENOMINATOR,
	@ID_UNIT
	
END

DEALLOCATE CURS

--SELECT * FROM #DOCS_X

CREATE TABLE #DOCS2
(
	ID_GOODS BIGINT,
	GOODS_NAME VARCHAR(400),
	DOC_DATE DATETIME,
	[MONTH] VARCHAR(20),
	MONTH_NUM INT,
	YEAR_NUM INT,
	SUMM MONEY,	
	NUMERATOR INT,
	DENOMINATOR INT,
	ID_UNIT BIGINT
)

INSERT INTO #DOCS2
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,	
	DOC_DATE = D.DATE_CHEQUE,
	[MONTH] = DATENAME(MONTH, D.DATE_CHEQUE),
	MONTH_NUM = DATEPART(month, D.DATE_CHEQUE),
	YEAR_NUM = DATEPART(year, D.DATE_CHEQUE),
	SUMM = DI.QUANTITY,
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM CHEQUE D
	INNER JOIN CHEQUE_ITEM DI ON D.ID_CHEQUE_GLOBAL = DI.ID_CHEQUE_GLOBAL
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = DI.ID_LOT_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT	
WHERE D.DATE_CHEQUE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (L.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

INSERT INTO #DOCS2
SELECT
	ID_GOODS = L.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,		
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	SUMM = DI.QUANTITY,
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM INVOICE_OUT D
	INNER JOIN INVOICE_OUT_ITEM DI ON D.ID_INVOICE_OUT_GLOBAL = DI.ID_INVOICE_OUT_GLOBAL
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = DI.ID_LOT_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
WHERE D.DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (L.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1
	
INSERT INTO #DOCS2
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	SUMM = DI.QUANTITY_FROM,
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT	
FROM ACT_DISASSEMBLING D
	INNER JOIN ACT_DISASSEMBLING_ITEM DI ON DI.ID_ACT_DISASSEMBLING_GLOBAL = D.ID_ACT_DISASSEMBLING_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = DI.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = DI.ID_SCALING_RATIO_from
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT	
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

INSERT INTO #DOCS2
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	SUMM = DI.QUANTITY,
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM ACT_DEDUCTION D
	INNER JOIN ACT_DEDUCTION_ITEM DI ON DI.ID_ACT_DEDUCTION_GLOBAL = D.ID_ACT_DEDUCTION_GLOBAL
	LEFT JOIN LOT L ON L.ID_LOT_GLOBAL = DI.ID_LOT_GLOBAL
	LEFT JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO --
	LEFT JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT	
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

INSERT INTO #DOCS2
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	SUMM = DI.QUANTITY,
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM ACT_RETURN_TO_CONTRACTOR D
	INNER JOIN ACT_RETURN_TO_CONTRACTOR_ITEM DI ON DI.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = D.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = DI.ID_GOODS	
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = DI.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

--SELECT * FROM #DOCS2

CREATE TABLE #DOCS3
(
	ID_GOODS BIGINT,
	GOODS_NAME VARCHAR(400),
	DOC_DATE DATETIME,
	[MONTH] VARCHAR(20),
	MONTH_NUM INT,
	YEAR_NUM INT,
	SUMM MONEY,	
	NUMERATOR INT,
	DENOMINATOR INT,
	ID_UNIT BIGINT
)

INSERT INTO #DOCS3
SELECT
	ID_GOODS = DI.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,	
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	SUMM = DI.QUANTITY,
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM MOVEMENT D
	INNER JOIN MOVEMENT_ITEM DI ON DI.ID_MOVEMENT_GLOBAL = D.ID_MOVEMENT_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = DI.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = DI.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT	
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE_FROM IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (DI.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

INSERT INTO #DOCS3
SELECT
	ID_GOODS = L.ID_GOODS,
	GOODS_NAME = G.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,		
	DOC_DATE = D.DATE,
	[MONTH] = DATENAME(MONTH, D.DATE),
	MONTH_NUM = DATEPART(month, D.DATE),
	YEAR_NUM = DATEPART(year, D.DATE),
	SUMM = DI.QUANTITY,
	NUMERATOR = SR.NUMERATOR,
	DENOMINATOR = SR.DENOMINATOR,
	ID_UNIT = SR.ID_UNIT
FROM INTERFIRM_MOVING D
	INNER JOIN INTERFIRM_MOVING_ITEM DI ON DI.ID_INTERFIRM_MOVING_GLOBAL = D.ID_INTERFIRM_MOVING_GLOBAL
	LEFT JOIN LOT L ON L.ID_LOT = DI.ID_LOT_FROM
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT	
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND D.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORE = 1 OR (D.ID_STORE_FROM_MAIN IN (SELECT ID_STORE FROM #STORE)))
	AND (@ALL_GOODS = 1 OR (L.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS)))
	AND G.IN_DRUG = 1

--SELECT * FROM #DOCS3

SELECT
	ID_GOODS = COALESCE(DX.ID_GOODS, D2.ID_GOODS, D3.ID_GOODS),
	GOODS_NAME = COALESCE(DX.GOODS_NAME, D2.GOODS_NAME, D3.GOODS_NAME),
	NUMERATOR = COALESCE(DX.NUMERATOR, D2.NUMERATOR, D3.NUMERATOR),
	DENOMINATOR = COALESCE(DX.DENOMINATOR, D2.DENOMINATOR, D3.NUMERATOR),
	[MONTH] = COALESCE(DX.[MONTH], D2.[MONTH], D3.[MONTH]),
	MONTH_NUM = COALESCE(DX.MONTH_NUM, D2.MONTH_NUM, D3.MONTH_NUM),
	YEAR_NUM = COALESCE(DX.YEAR_NUM, D2.YEAR_NUM, D3.YEAR_NUM),
	ID_UNIT = COALESCE(DX.ID_UNIT, D2.ID_UNIT, D3.ID_UNIT),
	DX1 = DX.D1,
	Q1 = DX.Q1,
	DX2 = DX.D2,
	Q2 = DX.Q2,
	IN_SUMM = (SELECT SUM(ISNULL(Q1, 0) + ISNULL(Q2, 0)) FROM #docs_x where ID_GOODS = COALESCE(DX.ID_GOODS, D2.ID_GOODS, D3.ID_GOODS) AND MONTH_NUM = COALESCE(DX.MONTH_NUM, D2.MONTH_NUM, D3.MONTH_NUM) AND YEAR_NUM = COALESCE(DX.YEAR_NUM, D2.YEAR_NUM, D3.YEAR_NUM) AND NUMERATOR = COALESCE(DX.NUMERATOR, D2.NUMERATOR, D3.NUMERATOR) AND DENOMINATOR = COALESCE(DX.DENOMINATOR, D2.DENOMINATOR, D3.NUMERATOR) AND ID_UNIT = COALESCE(DX.ID_UNIT, D2.ID_UNIT, D3.ID_UNIT))
into #temp_full
FROM #DOCS_X DX
	FULL OUTER JOIN
(
SELECT 
	ID_GOODS,
	GOODS_NAME,
	--DOC_DATE,
	[MONTH],
	MONTH_NUM,
	YEAR_NUM,
	--SUMM,
	NUMERATOR,
	DENOMINATOR,
	ID_UNIT
FROM #DOCS2
GROUP BY ID_GOODS, GOODS_NAME, NUMERATOR, DENOMINATOR, [MONTH], MONTH_NUM, YEAR_NUM, ID_UNIT
) D2 ON DX.ID_GOODS = D2.ID_GOODS AND DX.MONTH_NUM = D2.MONTH_NUM AND DX.YEAR_NUM = D2.YEAR_NUM AND DX.NUMERATOR = D2.NUMERATOR AND DX.DENOMINATOR = D2.DENOMINATOR AND DX.ID_UNIT = D2.ID_UNIT
	FULL OUTER JOIN 
(

SELECT 
	ID_GOODS,
	GOODS_NAME,
	DOC_DATE,
	[MONTH],
	MONTH_NUM,
	YEAR_NUM,
	SUMM,
	NUMERATOR,
	DENOMINATOR,
	ID_UNIT
FROM #DOCS3

) D3 ON ISNULL(DX.ID_GOODS, D2.ID_GOODS) = D3.ID_GOODS AND ISNULL(DX.[MONTH_NUM], D2.[MONTH_NUM]) = D3.[MONTH_NUM] AND ISNULL(DX.YEAR_NUM, D2.YEAR_NUM) = D3.YEAR_NUM AND ISNULL(DX.NUMERATOR, D2.NUMERATOR) = D3.NUMERATOR AND ISNULL(DX.DENOMINATOR, D2.DENOMINATOR) = D3.DENOMINATOR AND ISNULL(DX.ID_UNIT, D2.ID_UNIT) = D3.ID_UNIT
 
--select * from #temp_full

SET LANGUAGE ENGLISH
 
select t.*,
	QUANTITY_REM_BEGIN = (SELECT SUM(LM.QUANTITY_ADD - LM.QUANTITY_SUB) FROM LOT_MOVEMENT LM INNER JOIN LOT L ON L.ID_LOT_GLOBAL = LM.ID_LOT_GLOBAL INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO WHERE L.ID_GOODS = t.ID_GOODS AND SR.NUMERATOR = t.NUMERATOR AND SR.DENOMINATOR = t.DENOMINATOR AND SR.ID_UNIT = t.ID_UNIT AND LM.DATE_OP < CAST(CAST(t.YEAR_NUM AS VARCHAR(4)) + '/' + CAST(t.MONTH_NUM AS VARCHAR(2)) + '/01' AS DATETIME)),
	OUT_D = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND MONTH_NUM = t.MONTH_NUM AND YEAR_NUM = t.YEAR_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT),
	OUT_M = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND MONTH_NUM = t.MONTH_NUM AND YEAR_NUM = t.YEAR_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT),
	D1 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 1),
	D2 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 2),
	D3 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 3),
	D4 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 4),
	D5 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 5),
	D6 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 6),
	D7 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 7),
	D8 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 8),
	D9 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 9),
	D10 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 10),
	D11 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 11),
	D12 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 12),
	D13 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 13),
	D14 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 14),
	D15 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 15),
	D16 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 16),
	D17 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 17),
	D18 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 18),
	D19 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 19),
	D20 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 20),
	D21 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 21),
	D22 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 22),
	D23 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 23),
	D24 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 24),
	D25 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 25),
	D26 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 26),
	D27 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 27),
	D28 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 28),
	D29 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 29),
	D30 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 30),
	D31 = (SELECT SUM(SUMM) FROM #DOCS2 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 31),
	
	M1 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 1),
	M2 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 2),
	M3 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 3),
	M4 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 4),
	M5 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 5),
	M6 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 6),
	M7 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 7),
	M8 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 8),
	M9 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 9),
	M10 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 10),
	M11 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 11),
	M12 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 12),
	M13 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 13),
	M14 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 14),
	M15 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 15),
	M16 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 16),
	M17 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 17),
	M18 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 18),
	M19 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 19),
	M20 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 20),
	M21 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 21),
	M22 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 22),
	M23 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 23),
	M24 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 24),
	M25 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 25),
	M26 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 26),
	M27 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 27),
	M28 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 28),
	M29 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 29),
	M30 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 30),
	M31 = (SELECT SUM(SUMM) FROM #DOCS3 WHERE ID_GOODS = t.ID_GOODS AND [MONTH_NUM] = t.MONTH_NUM AND NUMERATOR = t.NUMERATOR AND DENOMINATOR = t.DENOMINATOR AND ID_UNIT = t.ID_UNIT AND DATEPART(DAY, DOC_DATE) = 31)
from #temp_full t
order by goods_name, month_num

SELECT SELF_NAME = NAME FROM CONTRACTOR WHERE ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()

RETURN
GO

/*
EXEC REPEX_AP_10 N'
<XML>
	<DATE_FR>2010-05-26T00:00:00.000</DATE_FR>
	<DATE_TO>2010-05-26T00:00:00.000</DATE_TO>
</XML>'*/