SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_INVENTORY_SESSION_OPIS_EX') IS NULL EXEC('CREATE PROCEDURE REPEX_INVENTORY_SESSION_OPIS_EX AS RETURN')
GO
ALTER PROCEDURE REPEX_INVENTORY_SESSION_OPIS_EX
    @XMLPARAM NTEXT
AS

DECLARE	@HDOC INT
DECLARE @ID_INVENTORY_GLOBAL UNIQUEIDENTIFIER
DECLARE @ID_STORE BIGINT
DECLARE @DOC_DATE DATETIME
DECLARE @FULL BIT
DECLARE @C_NAME VARCHAR(120), @S_NAME VARCHAR(120)

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT , @XMLPARAM OUTPUT
	SELECT TOP 1 
        @ID_INVENTORY_GLOBAL = ID_INVENTORY_GLOBAL 
    FROM OPENXML(@HDOC , '/XML') WITH(
        ID_INVENTORY_GLOBAL UNIQUEIDENTIFIER 'ID_INVENTORY_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

DECLARE @SVED TABLE(ID_INVENTORY_GLOBAL UNIQUEIDENTIFIER NULL, ID_STORE BIGINT NULL, [FULL] BIT NULL, DOC_DATE DATETIME, CONTRACTOR_NAME VARCHAR(256) NULL, STORE_NAME VARCHAR(256) NULL)
INSERT @SVED(ID_INVENTORY_GLOBAL, ID_STORE, [FULL], DOC_DATE, CONTRACTOR_NAME, STORE_NAME)
SELECT
    ID_INVENTORY_GLOBAL = I.ID_INVENTORY_GLOBAL,
    ID_STORE = I.ID_STORE, 
    [FULL] = I.[FULL], 
    DOC_DATE = DOC_DATE,
    CONTRACTOR_NAME = C.NAME,
    STORE_NAME = S.NAME
FROM INVENTORY_SVED I(NOLOCK)
    INNER JOIN STORE S ON I.ID_STORE = S.ID_STORE
    INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
WHERE I.ID_INVENTORY_SESSION_GLOBAL = @ID_INVENTORY_GLOBAL

SELECT 
    C_NAME = TAB.CONTRACTOR_NAME,
    S_NAME = TAB.STORE_NAME,
    DOC_DATE = SVED.DOC_DATE,
    DOC_NUM = SVED.DOC_NUM
FROM INVENTORY_SVED SVED(NOLOCK)
    INNER JOIN @SVED TAB ON TAB.ID_INVENTORY_GLOBAL = SVED.ID_INVENTORY_GLOBAL

SELECT 
   G_NAME = G.NAME,
   G_CODE = G.CODE,
   OKEI_CODE = U.OKEI_CODE,
   UNIT_NAME = U.NAME + '(' + CAST(SR.NUMERATOR AS VARCHAR) + '/' + CAST(SR.DENOMINATOR AS VARCHAR) + ')',
   PRICE_SAL = II.PRICE_SAL,
   QUANTITY_FACT = II.QUANTITY,
   SUM_FACT = II.PRICE_SAL * II.QUANTITY
FROM INVENTORY_SVED SVED(NOLOCK)
    INNER JOIN @SVED TAB ON TAB.ID_INVENTORY_GLOBAL = SVED.ID_INVENTORY_GLOBAL
    INNER JOIN INVENTORY_VED VED(NOLOCK) ON VED.ID_INVENTORY_SVED_GLOBAL = SVED.ID_INVENTORY_GLOBAL
    INNER JOIN INVENTORY_VED_ITEM II(NOLOCK) ON II.ID_INVENTORY_VED_GLOBAL = VED.ID_INVENTORY_VED_GLOBAL
    INNER JOIN GOODS G(NOLOCK) ON G.ID_GOODS = II.ID_GOODS
    INNER JOIN SCALING_RATIO SR(NOLOCK) ON SR.ID_SCALING_RATIO = II.ID_SCALING_RATIO
    INNER JOIN UNIT U(NOLOCK) ON SR.ID_UNIT = U.ID_UNIT
ORDER BY G.NAME

RETURN
GO

--exec REPEX_INVENTORY_SESSION_OPIS_EX @XMLPARAM = N'<XML><ID_INVENTORY_GLOBAL>f1dddad5-443d-43c9-a9f8-d345f5d66669</ID_INVENTORY_GLOBAL></XML>'