SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('[REPEX_INVOICE_REESTRPRICE]') IS NULL EXEC('CREATE PROCEDURE [REPEX_INVOICE_REESTRPRICE] AS RETURN')
GO
ALTER PROCEDURE REPEX_INVOICE_REESTRPRICE
	(@XMLPARAM NTEXT) AS
	
DECLARE @HDOC INT
DECLARE @ID_INVOICE BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_INVOICE = ID_INVOICE
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_INVOICE BIGINT 'ID_INVOICE')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

-- ьюойю х яохянй рнбюпнб б опхундмни мюйкндмни
SELECT
    ITEM.ID_INVOICE_ITEM_GLOBAL,
    -- мнлеп опхундмни мюйкндмни
    INV.MNEMOCODE,
    -- дюрю опхундмни мюйкюдмни
    INV0ICE_DATE = CONVERT(VARCHAR, INV.DOCUMENT_DATE, 104),
    -- бундъыхи днйслемр
    INCOMING_NUMBER = COALESCE(INV.INCOMING_NUMBER, '')+
        COALESCE(' НР '+CONVERT(VARCHAR, INV.INCOMING_DATE, 104), ''),
    -- онярюбыхй 
    SUPPLIER_NAME = CNR_SUP.[NAME],
    -- онйсоюрекэ
    CUSTOMER_NAME = (SELECT TOP 1 C.[NAME] FROM DBO.INVOICE I
        INNER JOIN DBO.STORE S ON S.ID_STORE = I.ID_STORE 
        INNER JOIN DBO.CONTRACTOR C ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
        WHERE I.ID_INVOICE = @ID_INVOICE),
    GOODS = G.[NAME] + ' [' + PROD.NAME + ', ' + CNR.NAME + ']',
    SERIES_NUMBER = ISNULL(SER.SERIES_NUMBER,'') + ISNULL(' / '+ CONVERT(VARCHAR,SER.BEST_BEFORE,104),''),
    QUANTITY = CAST(ROUND(ITEM.QUANTITY, 0) AS VARCHAR),
    --опнхгбндхрекэ
    PRODUCER_NAME = PROD.[NAME],
    --жемю рнбюпю цня. пееярпю
    REGISTER_PRICE = G.REGISTER_PRICE,
    --жемю опнхгбндхрекъ гю ед. рнбюпю
    PRODUCER_PRICE = ITEM.PRODUCER_PRICE,
    --ясллю опнхгбндхрекъ он ярпнйе
    PRODUCER_PRICE_SUM = ITEM.QUANTITY * ITEM.PRODUCER_PRICE,
    --опнжемр мюдаюбйх онярюбыхйю
    SUPPLIER_ADPRICE = ITEM.SUPPLIER_ADPRICE,
    SUP_ADD = (ITEM.SUPPLIER_PRICE - ITEM.PRODUCER_PRICE) * ITEM.QUANTITY,
    --ясллю рнпцнбни мюдаюбйх он ярпнйе мю бяе йнкхвеярбн рнбюпю
    RETAIL_VAT_SUM = ITEM.RETAIL_VAT_SUM,
    --жемю онярюбыхйю аег мдя
    SUPPLIER_PRICE = ITEM.SUPPLIER_PRICE,
    --ясллю онярюбыхйю аег мдя он ярпнйе мю бяе йнкхвеярбн рнбюпю
    SUPPLIER_SUM = ITEM.SUPPLIER_SUM,
    --опнжемр мдя онярюбыхйю
    SUPPLIER_VAT = ITEM.SUPPLIER_VAT,
    --ясллю мдя онярюбыхйю он ярпнйе мю бяе йнкхвеярбю рнбюпю
    SUPPLIER_VAT_SUM = ITEM.SUPPLIER_VAT_SUM,
    --жемю онярюбыхйю я свернл мдя
    SUPPLIER_PRICE_VAT = ITEM.SUPPLIER_PRICE_VAT,
    --ясллю онярюбыхйю я мдя он ярпнйе мю бяе йнкхвеярбн рнбюпю
    SUPPLIER_SUM_VAT = ITEM.SUPPLIER_SUM_VAT,
    --опнжемр рнпцнбни мюдаюбйх юорейх
    RETAIL_ADPRICE = ITEM.RETAIL_ADPRICE,
    --жемю опндюфх пнгмхвмюъ я мдя гю ед.
    RETAIL_PRICE_VAT = ITEM.RETAIL_PRICE_VAT,
    --ясллю опндюфх пнгмхвмюъ я мдя он ярпнйе мю бяе йнкхвеярбн рнбюпю
    RETAIL_SUM_VAT = ITEM.RETAIL_SUM_VAT,
    RETAIL_ADPRICE_ABS = ITEM.RETAIL_ADPRICE_PER_UNIT,
    RETAIL_ADPRICE_ABS_SUM = ITEM.RETAIL_ADPRICE_PER_UNIT * ITEM.QUANTITY
FROM DBO.INVOICE INV
  INNER JOIN DBO.CONTRACTOR CNR_SUP ON CNR_SUP.ID_CONTRACTOR = INV.ID_CONTRACTOR_SUPPLIER
  INNER JOIN DBO.INVOICE_ITEM ITEM ON ITEM.ID_INVOICE = INV.ID_INVOICE
  INNER JOIN DBO.GOODS G ON G.ID_GOODS = ITEM.ID_GOODS
  INNER JOIN DBO.PRODUCER PROD ON G.ID_PRODUCER = PROD.ID_PRODUCER
  INNER JOIN DBO.COUNTRY CNR ON PROD.ID_COUNTRY = CNR.ID_COUNTRY
  LEFT JOIN DBO.SERIES SER ON ITEM.ID_SERIES = SER.ID_SERIES 
WHERE (INV.ID_INVOICE = @ID_INVOICE)
ORDER BY GOODS

SELECT
    PRODUCER_PRICE_SUM = SUM(II.QUANTITY * II.PRODUCER_PRICE),
    SUP_ADD = SUM((II.SUPPLIER_PRICE - II.PRODUCER_PRICE) * II.QUANTITY),
    SUPPLIER_SUM = I.SUM_SUPPLIER - I.SVAT_SUPPLIER,
    SUPPLIER_VAT_SUM = I.SVAT_SUPPLIER,
    SUPPLIER_SUM_VAT = I.SUM_SUPPLIER,
    RETAIL_VAT_SUM = SUM((II.RETAIL_PRICE - II.SUPPLIER_PRICE_VAT) * II.QUANTITY), 
    RETAIL_SUM_VAT = I.SUM_RETAIL,
    RETAIL_ADPRICE_ABS_SUM = SUM(((II.RETAIL_PRICE * II.RETAIL_ADPRICE) / (100+II.RETAIL_ADPRICE))*II.QUANTITY)
FROM INVOICE I
    INNER JOIN INVOICE_ITEM II ON I.ID_INVOICE_GLOBAL = II.ID_INVOICE_GLOBAL 
WHERE (II.ID_INVOICE = @ID_INVOICE)
GROUP BY I.SUM_SUPPLIER, I.SVAT_SUPPLIER, I.SUM_RETAIL

RETURN 0
GO