SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INV3') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INV3 AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INV3 @XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT

SELECT TOP 1 @ID_GLOBAL = ID_GLOBAL
FROM OPENXML(@HDOC, '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	CONTRACTOR = COALESCE(C.FULL_NAME, C.NAME),
	STORE = S.NAME,
	DOC_NUM = I.DOC_NUM,
	DOC_DATE = CONVERT(VARCHAR(10), I.DOC_DATE, 104)
FROM INVENTORY_SVED I
	INNER JOIN STORE S ON S.ID_STORE = I.ID_STORE
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
WHERE I.ID_INVENTORY_GLOBAL = @ID_GLOBAL
	
SELECT
	GOODS_NAME = G.NAME,
	GOODS_CODE = G.CODE,
	OKEI_CODE = U.OKEI_CODE,
	UNIT_NAME = U.NAME,
	RETAIL_PRICE = IVI.PRICE_SAL,
	QUANTITY = IVI.QUANTITY,
	RETAIL_SUM = IVI.SUM_SAL,
	MIVI.QUANTITY_REM,
	RETAIL_SUM_REM = MIVI.QUANTITY_REM * IVI.PRICE_SAL
FROM INVENTORY_SVED I INNER JOIN INVENTORY_VED IV
	ON IV.ID_INVENTORY_SVED_GLOBAL = I.ID_INVENTORY_GLOBAL INNER JOIN INVENTORY_VED_ITEM IVI
	ON IVI.ID_INVENTORY_VED_GLOBAL = IV.ID_INVENTORY_VED_GLOBAL INNER JOIN GOODS G
	ON G.ID_GOODS = IVI.ID_GOODS INNER JOIN SCALING_RATIO SR
	ON SR.ID_SCALING_RATIO = IVI.ID_SCALING_RATIO INNER JOIN UNIT U
	ON U.ID_UNIT = SR.ID_UNIT INNER JOIN MV_INVENTORY_VED_ITEM MIVI
	ON MIVI.ID_INVENTORY_VED_ITEM_GLOBAL = IVI.ID_INVENTORY_VED_ITEM_GLOBAL
WHERE I.ID_INVENTORY_GLOBAL = @ID_GLOBAL
ORDER BY G.NAME

RETURN 0
GO

--exec REPEX_INV3 '<XML><ID_GLOBAL>EBE73D52-AD90-44D8-8AAE-8E5F7F760BA0</ID_GLOBAL></XML>'