IF (OBJECT_ID('DBO.REP_CARDS_INTERFIRM_EX') IS NULL) EXEC('CREATE PROCEDURE DBO.REP_CARDS_INTERFIRM_EX AS RETURN')
GO
ALTER PROCEDURE DBO.REP_CARDS_INTERFIRM_EX
	(@XMLPARAM NTEXT) AS

DECLARE @HDOC INT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT 
        ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL
    INTO #TAB
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL UNIQUEIDENTIFIER 'ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC
DECLARE @CERTIFICATE TABLE(
    CERTIFICATE VARCHAR(8000),
    ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL UNIQUEIDENTIFIER
)
INSERT INTO @CERTIFICATE(    
    CERTIFICATE,
    ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL)
SELECT  
    CERTIFICATE = CASE WHEN C.CERT_NUMBER IS NOT NULL THEN C.CERT_NUMBER +', ' ELSE '' END +
                  CASE WHEN C.CERT_DATE IS NOT NULL THEN CONVERT(VARCHAR(10),C.CERT_DATE,104) +', ' ELSE '' END+ 
                  CASE WHEN C.ISSUED_BY IS NOT NULL THEN C.ISSUED_BY +', ' ELSE '' END+
                  CASE WHEN S.SERIES_NUMBER IS NOT NULL THEN S.SERIES_NUMBER+', ' ELSE '' END+
                  CASE WHEN C.CERT_END_DATE IS NOT NULL THEN CONVERT(VARCHAR(10),C.CERT_END_DATE,104) ELSE '' END,
    ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL
FROM DBO.INTERFIRM_MOVING_ACCEPTANCE_ACT INV
INNER JOIN DBO.INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM II ON II.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL = INV.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL
INNER JOIN LOT L ON L.ID_LOT = II.ID_LOT_FROM
LEFT JOIN SERIES S ON S.ID_SERIES = L.ID_SERIES
LEFT JOIN CERTIFICATE C ON C.ID_SERIES = S.ID_SERIES
WHERE EXISTS (SELECT NULL FROM #TAB T WHERE T.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL = INV.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL)
-- 

DECLARE @IDS TABLE(ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL UNIQUEIDENTIFIER)
DECLARE @ROWCOUNT INT
INSERT INTO @IDS
SELECT DISTINCT ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL FROM @CERTIFICATE
SET @ROWCOUNT = @@ROWCOUNT
-- 
    DECLARE @ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL UNIQUEIDENTIFIER
    DECLARE @G VARCHAR(8000)
-- 
    DECLARE @CERT TABLE(    
        CERTIFICATE VARCHAR(8000),
        ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL UNIQUEIDENTIFIER)
-- 
WHILE(@ROWCOUNT>0)BEGIN
    SET @G=NULL
    SELECT TOP 1 @ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL = ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL
    FROM @IDS

    SELECT 
        @G = ISNULL(@G+'; '+C.CERTIFICATE, C.CERTIFICATE)
    FROM @CERTIFICATE C
    WHERE ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL = @ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL
          
    INSERT INTO @CERT(
        CERTIFICATE,
        ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL)
    SELECT DISTINCT @G,@ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL


    DELETE FROM @IDS WHERE ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL = @ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL
    SET @ROWCOUNT = @ROWCOUNT-1
END

SELECT
  CONTRACTOR = C.NAME,--CNTR.[NAME],
  GOODS = G.NAME,--G.[NAME],
  PRODUCER = PROD.[NAME], --PROD.[NAME]
  QUANTITY = MAI.QUANTITY,--II.QUANTITY,
  CONTRACTOR_PRICE_PER_UNIT_VAT = ROUND(L.PRICE_SUP,2),--ROUND(II.SUPPLIER_PRICE_VAT, 2),
  CONTRACTOR_PRICE_PER_UNIT = ROUND((L.PRICE_SUP - L.PVAT_SUP),2),--ROUND(II.SUPPLIER_PRICE, 2),
  RETAIL_PRICE_VAT = ROUND(L.PRICE_SAL,2),--ROUND(II.RETAIL_PRICE_VAT, 2),
  SUPPLIER = SUPL.[NAME],--SUPL.[NAME],
  [DATE] = MA.DATE,--INV.DOCUMENT_DATE,
  NUMBER = MA.MNEMOCODE,--INV.MNEMOCODE,
  INCOMING_NUMBER = L.INCOMING_NUM + ' нр '+ CONVERT(VARCHAR, L.INCOMING_DATE, 104),
  SERIES = SE.SERIES_NUMBER, --SE.SERIES_NUMBER,
  BEST_BEFORE = SE.SERIES_NUMBER,--SE.BEST_BEFORE,
  TAX = L.VAT_SUP,--II.SUPPLIER_VAT,
  IMPORTANT = (CASE G.IMPORTANT WHEN 0 THEN 'мер' WHEN 1 THEN 'дю' END),
  REQUIRIED = (CASE G.REQUIRIED WHEN 0 THEN 'мер' WHEN 1 THEN 'дю' END),
  IN_DRUG = (CASE G.IN_DRUG WHEN 0 THEN 'мер' WHEN 1 THEN 'дю' END),
  MNEMOCODE = G.MNEMOCODE,
  CODE = bc.CODE,--II.BAR_CODE,
  CERT = CERT.CERTIFICATE,
  REG_CERTIFICATE = RC.[NAME] + ', '+RC.ORGAN+', '+CONVERT(VARCHAR(10),RC.[DATE],104),
  PRODUCER_PRICE = ISNULL(l.price_prod,''),
  RETAIL_ADPRICE = ISNULL(l.adprice_sal,'')
FROM INTERFIRM_MOVING_ACCEPTANCE_ACT MA
INNER JOIN INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM MAI ON MAI.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL = MA.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL
INNER JOIN LOT L ON L.ID_LOT = MAI.ID_LOT_FROM
INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
INNER JOIN DBO.CONTRACTOR SUPL ON SUPL.ID_CONTRACTOR = L.ID_SUPPLIER
INNER JOIN STORE S ON S.ID_STORE = MA.ID_STORE_TO_MAIN
INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
LEFT JOIN DBO.PRODUCER PROD ON PROD.ID_PRODUCER = G.ID_PRODUCER
LEFT JOIN DBO.COUNTRY CNR ON CNR.ID_COUNTRY = PROD.ID_COUNTRY
LEFT JOIN DBO.SERIES SE ON SE.ID_SERIES = L.ID_SERIES
LEFT JOIN BAR_CODE BC ON BC.ID_GOODS = G.ID_GOODS
LEFT JOIN REG_CERT RC ON RC.ID_REG_CERT_GLOBAL = L.ID_REG_CERT_GLOBAL
LEFT JOIN @CERT CERT ON CERT.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL = MAI.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_ITEM_GLOBAL
WHERE EXISTS (SELECT NULL FROM #TAB T WHERE T.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL = MA.ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL)
ORDER BY MA.DATE
-- 
--  select * from invoice_item where id_goods = 188840
--  
-- select * from lot where id_goods = 188840

-- select * from goods where id_goods = 188840
-- select * from bar_code order by id_goods
-- FROM DBO.INVOICE INV
--   INNER JOIN DBO.INVOICE_ITEM II ON II.ID_INVOICE_GLOBAL = INV.ID_INVOICE_GLOBAL
--   INNER JOIN DBO.STORE ST ON ST.ID_STORE = INV.ID_STORE
--   INNER JOIN DBO.CONTRACTOR CNTR ON CNTR.ID_CONTRACTOR = ST.ID_CONTRACTOR
--   INNER JOIN DBO.GOODS G ON G.ID_GOODS = II.ID_GOODS
--   INNER JOIN DBO.CONTRACTOR SUPL ON SUPL.ID_CONTRACTOR = INV.ID_CONTRACTOR_SUPPLIER
--   LEFT JOIN DBO.PRODUCER PROD ON PROD.ID_PRODUCER = G.ID_PRODUCER
--   LEFT JOIN DBO.COUNTRY CNR ON CNR.ID_COUNTRY = PROD.ID_COUNTRY
--   LEFT JOIN DBO.SERIES SE ON II.ID_SERIES = SE.ID_SERIES
--   LEFT JOIN REG_CERT RC ON RC.ID_REG_CERT_GLOBAL = II.ID_REG_CERT_GLOBAL
--   LEFT JOIN @CERT CERT ON CERT.ID_INVOICE_ITEM_GLOBAL = II.ID_INVOICE_ITEM_GLOBAL
-- WHERE EXISTS (SELECT NULL FROM #INVOICE WHERE #INVOICE.ID_INVOICE = INV.ID_INVOICE_GLOBAL)
-- ORDER BY INV.[DATE]

RETURN
GO

-- exec REP_CARDS_INTERFIRM_EX 
-- @XMLPARAM=N'<XML><ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL>50ebb3ad-8840-468c-b1d1-e22bc924a658</ID_INTERFIRM_MOVING_ACCEPTANCE_ACT_GLOBAL></XML>'
