SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF (OBJECT_ID('DBO.REPEX_R36RInvoiceOutAP16') IS NULL) EXEC ('CREATE PROCEDURE DBO.REPEX_R36RInvoiceOutAP16 AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_R36RInvoiceOutAP16
    @XMLPARAM NTEXT
AS

DECLARE	@HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT @ID_GLOBAL = ID_GLOBAL FROM OPENXML(@HDOC, '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT 
	DOC_NUM = I.MNEMOCODE,
	DOC_DATE = I.DATE,
	CONTRACTOR_TO = ISNULL(CT.FULL_NAME, CT.NAME),
	AUTH_VALID = I.AUTH_VALID_PERIOD,
	STORE_NAME=s.name,
	SELF_NAME=(SELECT ISNULL(FULL_NAME, NAME) FROM CONTRACTOR
				WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR 
										FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1))
FROM INVOICE_OUT I
	INNER JOIN CONTRACTOR CT ON I.ID_CONTRACTOR_TO = CT.ID_CONTRACTOR
	inner join store s on i.id_store=s.id_store
	LEFT JOIN CONTRACTS CR ON CR.ID_CONTRACTS_GLOBAL = I.ID_CONTRACTS_GLOBAL
WHERE I.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

SELECT
	GOODS_NAME = G.NAME,
	SCALE_NAME=u.SHORT_NAME,
	QUANTITY = II.QUANTITY * SR.NUMERATOR / CAST(SR.DENOMINATOR AS MONEY),
--	PRICE_SAL = II.PRICE_SAL * SR.DENOMINATOR / CAST(SR.NUMERATOR AS MONEY),
	PRICE_SAL = L.PRICE_SUP * SR.DENOMINATOR / CAST(SR.NUMERATOR AS MONEY),
	SUM_SAL = II.QUANTITY * L.PRICE_SUP --II.PRICE_SAL
FROM INVOICE_OUT_ITEM II
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = II.ID_LOT_GLOBAL
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	--inner join UNIT u on u.ID_UNIT= g.ID_UNIT_DEFAULT
	inner join UNIT u on u.ID_UNIT= SR.ID_UNIT
WHERE II.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL
ORDER BY GOODS_NAME

RETURN
GO

--exec DBO.REPEX_INVOICE_OUT_AP16 '<XML><ID_GLOBAL>FDE96528-8A6D-4D50-B3F1-CA1DEC7F7BD3</ID_GLOBAL></XML>'