SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_TURNOVER_PERCENT') IS NULL EXEC ('CREATE PROCEDURE DBO.REPEX_TURNOVER_PERCENT AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_TURNOVER_PERCENT
    @XMLPARAM NTEXT
AS

DECLARE @DATE_FR DATETIME
DECLARE @DATE_TO DATETIME
DECLARE @ID_CONTRACTOR BIGINT
DECLARE @ORDER INT
DECLARE @IS_SAL INT
DECLARE @HDOC INT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT
	@DATE_FR = DATE_FR,
	@DATE_TO = DATE_TO,
	@ID_CONTRACTOR = ID_CONTRACTOR,
	@ORDER = [ORDER],
	@IS_SAL = IS_SAL
FROM OPENXML(@HDOC, '/XML') WITH(
	DATE_FR DATETIME 'DATE_FR',
	DATE_TO DATETIME 'DATE_TO',
	ID_CONTRACTOR BIGINT 'ID_CONTRACTOR',
	[ORDER] INT 'ORDER',
	IS_SAL INT 'IS_SAL'
)

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC DBO.USP_RANGE_NORM	@DATE_FR OUTPUT, @DATE_TO OUTPUT
EXEC DBO.USP_RANGE_DAYS	@DATE_FR OUTPUT, @DATE_TO OUTPUT

--SELECT @DATE_FR, @DATE_TO, @id_contractor
--SELECT @ORDER
--SELECT @IS_SAL

DECLARE @TEMP_T1 TABLE
(
	GOODS_NAME VARCHAR(255),
	QUANTITY MONEY,
	VAT INT,
	SUMM MONEY
)

IF (@IS_SAL = 0)
BEGIN

INSERT INTO @TEMP_T1 (
	GOODS_NAME,
	QUANTITY,
	VAT,
	SUMM
) 
SELECT
	GOODS_NAME = G.NAME,
	QUANTITY = SUM((LM.QUANTITY_SUB - LM.QUANTITY_ADD)* SR.NUMERATOR / SR.DENOMINATOR),
	VAT = L.VAT_SUP,
	SUMM = SUM(CASE WHEN LM.QUANTITY_SUB > 0 THEN 1 ELSE CASE WHEN LM.CODE_OP = 'MOVE' THEN 0 ELSE -1 END END * LM.SUM_SUP)
--INTO #TEMP_T1
FROM DBO.LOT_MOVEMENT LM
	INNER JOIN DBO.LOT L ON LM.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	INNER JOIN DBO.GOODS G ON L.ID_GOODS = G.ID_GOODS
	INNER JOIN dbo.STORE S ON S.ID_STORE = L.ID_STORE
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
WHERE LM.DATE_OP BETWEEN @DATE_FR AND @DATE_TO
	AND LM.CODE_OP IN ('ACT_R2B', 'INVOICE_OUT', 'CHEQUE', 'MOVE')
	AND S.ID_CONTRACTOR = @ID_CONTRACTOR
GROUP BY G.ID_GOODS, G.[NAME], L.VAT_SUP
END
ELSE
BEGIN
SELECT
	ID_GOODS = G.ID_GOODS,
	GOODS_NAME = G.NAME,
	QUANTITY = (LM.QUANTITY_SUB - LM.QUANTITY_ADD) * SR.NUMERATOR / SR.DENOMINATOR,
	VAT = L.VAT_SAL,
	SUMM = CASE WHEN LM.QUANTITY_SUB > 0 THEN 1 ELSE CASE WHEN LM.CODE_OP = 'MOVE' THEN 0 ELSE -1 END END * CASE WHEN LM.CODE_OP <> 'ACT_R2B' THEN LM.SUM_ACC ELSE LM.SUM_ACC - 
		(CASE WHEN (SELECT ID_TABLE_DATA_DOCUMENT_BASE FROM ACT_RETURN_TO_BUYER WHERE ID_ACT_RETURN_TO_BUYER_GLOBAL = LM.ID_DOCUMENT) = 21 THEN (SELECT II.SUM_DISCOUNT FROM INVOICE_OUT I INNER JOIN INVOICE_OUT_ITEM II ON I.ID_INVOICE_OUT_GLOBAL = II.ID_INVOICE_OUT_GLOBAL WHERE I.ID_INVOICE_OUT = (SELECT ID_DOCUMENT_BASE FROM ACT_RETURN_TO_BUYER WHERE ID_ACT_RETURN_TO_BUYER_GLOBAL = LM.ID_DOCUMENT) AND II.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL)
		WHEN (SELECT ID_TABLE_DATA_DOCUMENT_BASE FROM ACT_RETURN_TO_BUYER WHERE ID_ACT_RETURN_TO_BUYER_GLOBAL = LM.ID_DOCUMENT) = 7 THEN (SELECT CHI.SUMM_DISCOUNT FROM CHEQUE CH INNER JOIN CHEQUE_ITEM CHI ON CHI.ID_CHEQUE_GLOBAL = CH.ID_CHEQUE_GLOBAL WHERE CH.ID_CHEQUE = (SELECT ID_DOCUMENT_BASE FROM ACT_RETURN_TO_BUYER WHERE ID_ACT_RETURN_TO_BUYER_GLOBAL = LM.ID_DOCUMENT) AND CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL) END) END
INTO #TEMP_T1
FROM DBO.LOT_MOVEMENT LM
	INNER JOIN DBO.LOT L ON LM.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	INNER JOIN DBO.GOODS G ON L.ID_GOODS = G.ID_GOODS
	INNER JOIN dbo.STORE S ON S.ID_STORE = L.ID_STORE
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
WHERE LM.DATE_OP BETWEEN @DATE_FR AND @DATE_TO
	AND LM.CODE_OP IN ('ACT_R2B', 'INVOICE_OUT', 'CHEQUE', 'MOVE')
	AND S.ID_CONTRACTOR = @ID_CONTRACTOR

INSERT INTO @TEMP_T1 (
	GOODS_NAME,
	QUANTITY,
	VAT,
	SUMM
) 
SELECT
	GOODS_NAME,
	QUANTITY = SUM(QUANTITY),
	VAT,
	SUMM = SUM(SUMM)
FROM #TEMP_T1	
GROUP BY ID_GOODS, GOODS_NAME, VAT

END

--SELECT * FROM #TEMP_T1

SELECT
	SUMM = SUM(SUMM),
	SUMM_0 = SUM(CASE WHEN VAT = 0 THEN SUMM ELSE 0 END),
	SUMM_10 = SUM(CASE WHEN VAT = 10 THEN SUMM ELSE 0 END),
	SUMM_18 = SUM(CASE WHEN VAT = 18 THEN SUMM ELSE 0 END)
INTO #TEMP_T2
FROM @TEMP_T1

DECLARE @SUMM MONEY
SET @SUMM = (SELECT SUMM FROM #TEMP_T2)

--SELECT @SUMM 

IF (@ORDER = 0)
BEGIN
SELECT
	GOODS_NAME,
	QUANTITY,
	VAT = CASE WHEN VAT = 0 THEN 'Áåç ÍÄÑ' ELSE CAST(VAT AS VARCHAR(10)) END,
	SUMM,
	[PERCENT] = CASE WHEN @SUMM = 0 THEN NULL ELSE SUMM / @SUMM * 100 END
FROM @TEMP_T1
ORDER BY GOODS_NAME
END
ELSE
BEGIN
SELECT
	GOODS_NAME,
	QUANTITY,
	VAT = CASE WHEN VAT = 0 THEN 'Áåç ÍÄÑ' ELSE CAST(VAT AS VARCHAR(10)) END,
	SUMM,
	[PERCENT] = CASE WHEN @SUMM = 0 THEN NULL ELSE SUMM / @SUMM * 100 END
FROM @TEMP_T1
ORDER BY CASE WHEN @ORDER = 1 THEN VAT ELSE CASE WHEN @SUMM = 0 THEN NULL ELSE SUMM / @SUMM * 100 END END
END

SELECT
	SUMM_0 = SUMM_0,
	PSUMM_0 = CASE WHEN SUMM = 0 THEN NULL ELSE SUMM_0 / SUMM * 100 END,
	SUMM_10 = SUMM_10,
	PSUMM_10 = CASE WHEN SUMM = 0 THEN NULL ELSE SUMM_10 / SUMM * 100 END,
	SUMM_18 = SUMM_18,
	PSUMM_18 = CASE WHEN SUMM = 0 THEN NULL ELSE SUMM_18 / SUMM * 100 END
FROM #TEMP_T2

RETURN
GO

/*
EXEC DBO.REPEX_TURNOVER_PERCENT N'
<XML>
	<DATE_FR>2009-10-15T16:13:14.453</DATE_FR>
	<DATE_TO>2009-10-15T16:13:14.453</DATE_TO>
	<ID_CONTRACTOR>5271</ID_CONTRACTOR>
	<ORDER>0</ORDER>
	<IS_SAL>1</IS_SAL>
</XML>'*/


SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO 

IF OBJECT_ID('DBO.REMOVE_REPORT_BY_TYPE_NAME') IS NULL EXEC('CREATE PROCEDURE DBO.REMOVE_REPORT_BY_TYPE_NAME AS RETURN')
GO
ALTER PROCEDURE DBO.REMOVE_REPORT_BY_TYPE_NAME 
	@REPORT_TYPE_NAME VARCHAR(200) AS
	
DECLARE @id_meta_report BIGINT

	select 
		@id_meta_report = id_meta_report
	from meta_report
	where type_name = @REPORT_TYPE_NAME
	--select @id_meta_report
		
	DECLARE @SQL NVARCHAR(200)
	SET @SQL = N'delete from META_REPORT_2_REPORT_GROUPS
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('META_REPORT_2_REPORT_GROUPS') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_csv_export
		where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_csv_export') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_visible
		where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_visible') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_managed
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_managed') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report


	SET @SQL = N'delete from meta_report_settings_archive
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_archive') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report


	delete from meta_report
	where id_meta_report = @id_meta_report

RETURN 0
GO

EXEC DBO.REMOVE_REPORT_BY_TYPE_NAME 'TurnoverPercent.FormParams'