SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INVOICE_BOOK') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INVOICE_BOOK AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INVOICE_BOOK
	@XMLPARAM NTEXT AS
		
DECLARE	@HDOC INT

DECLARE	@DATE_FR DATETIME
DECLARE @DATE_TO DATETIME
DECLARE @DETAIL BIT
DECLARE @ALL_STORES BIT
DECLARE @SHOW_REMAIN BIT
DECLARE @ROUND_DIGIT INT
   
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT , @XMLPARAM OUTPUT
		
SELECT
	@DATE_FR = DATE_FR,
	@DATE_TO = DATE_TO,
	@DETAIL = DETAIL,
	@SHOW_REMAIN = SHOW_REMAIN,
	@ROUND_DIGIT = ROUND_DIGIT
FROM OPENXML(@HDOC , '/XML') 
	WITH(DATE_FR DATETIME 'DATE_FR',
	DATE_TO DATETIME 'DATE_TO',
	DETAIL BIT 'DETAIL',
	SHOW_REMAIN BIT 'SHOW_REMAIN',
	ROUND_DIGIT INT 'ROUND_DIGIT')
    
SELECT ID_STORE = STORE INTO #STORES
FROM OPENXML(@HDOC, '/XML/STORE') WITH(STORE BIGINT '.')
IF (@@ROWCOUNT = 0)
	SET @ALL_STORES = 1

EXEC SP_XML_REMOVEDOCUMENT @HDOC

declare @date_fr_one datetime
declare @date_fr_two datetime
declare @date_fr_three datetime
declare @date_fr_half datetime
declare @date_fr_year datetime

declare @date_now datetime
select @date_now = getdate()

set @date_fr_one = dateadd(month, -1, @date_now)
set @date_fr_two = dateadd(month, -2, @date_now)
set @date_fr_three = dateadd(month, -3, @date_now)
set @date_fr_half = dateadd(month, -6, @date_now)
set @date_fr_year = dateadd(year, -1, @date_now)

EXEC USP_RANGE_NORM @DATE_FR OUTPUT, @DATE_TO OUTPUT
EXEC USP_RANGE_DAYS @DATE_FR OUTPUT, @DATE_TO OUTPUT

EXEC USP_RANGE_DAYS @DATE_FR_ONE OUTPUT, @DATE_TO OUTPUT
EXEC USP_RANGE_DAYS @DATE_FR_TWO OUTPUT, @DATE_TO OUTPUT
EXEC USP_RANGE_DAYS @DATE_FR_THREE OUTPUT, @DATE_TO OUTPUT
EXEC USP_RANGE_DAYS @DATE_FR_HALF OUTPUT, @DATE_TO OUTPUT
EXEC USP_RANGE_DAYS @DATE_FR_YEAR OUTPUT, @DATE_TO OUTPUT

DECLARE @TOTAL_CONTRACTOR_SUM_VAT MONEY

SELECT
	CONTRACTOR_NAME = C.NAME,
	CONTRACTOR_SUM_VAT = SUM(DM.SUM_SUP),
	RETAIL_SUM = SUM(DM.SUM_ACC)
INTO #TEMP_T
FROM DOC_MOVEMENT DM
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
WHERE ((@SHOW_REMAIN <> 1 AND DM.ID_TABLE = 2) OR (@SHOW_REMAIN = 1 AND DM.ID_TABLE IN (2,30)))
	AND DM.DATE_OP BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_STORES = 1 OR DM.ID_STORE IN (SELECT ID_STORE FROM #STORES))
GROUP BY DM.ID_CONTRACTOR_FROM, C.NAME

SELECT @TOTAL_CONTRACTOR_SUM_VAT = SUM(CONTRACTOR_SUM_VAT) FROM #TEMP_T

--SELECT
--	CONTRACTOR_NAME = T.CONTRACTOR_NAME,
--	CONTRACTOR_SUM_VAT = T.CONTRACTOR_SUM_VAT,
--	RETAIL_SUM = T.RETAIL_SUM,
--	PERCENTAGE = T.CONTRACTOR_SUM_VAT * 100 / @TOTAL_CONTRACTOR_SUM_VAT
--FROM #TEMP_T T
--ORDER BY T.CONTRACTOR_SUM_VAT * 100 / @TOTAL_CONTRACTOR_SUM_VAT DESC


--declare @temp_t table
--(
--	CONTRACTOR_NAME VARCHAR(100),
--	MNEMOCODE VARCHAR(40),
--	[DATE] DATETIME,
--	INCOMING_NUMBER VARCHAR(50),
--	INCOMING_DATE DATETIME,
--	CONTRACTOR_SUM_VAT MONEY,
--	RETAIL_SUM MONEY,
--	SUPPLIER_VAT_RATE_10 MONEY,
--	SUPPLIER_VAT_RATE_18 MONEY,
--	RETAIL_VAT_RATE_10 MONEY,
--	RETAIL_VAT_RATE_18 MONEY
--)

--IF (@SHOW_REMAIN = 1)
--BEGIN
--insert into @temp_t
--SELECT
--	CONTRACTOR_NAME = MAX(C.NAME),
--	MNEMOCODE = I.MNEMOCODE,
--	[DATE] = DM.DATE_OP,
--	INCOMING_NUMBER = I.INCOMING_NUMBER,
--	INCOMING_DATE = I.INCOMING_DATE,
--	CONTRACTOR_SUM_VAT = SUM(DM.SUM_SUP),
--	RETAIL_SUM = SUM(DM.SUM_ACC),
--	SUPPLIER_VAT_RATE_10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SVAT_SUP ELSE 0 END),
--	SUPPLIER_VAT_RATE_18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SVAT_SUP ELSE 0 END),
--	RETAIL_VAT_RATE_10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SVAT_ACC ELSE 0 END),
--	RETAIL_VAT_RATE_18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SVAT_ACC ELSE 0 END)
--FROM DOC_MOVEMENT DM
--	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
--	INNER JOIN INVOICE I ON I.ID_INVOICE_GLOBAL = DM.ID_DOCUMENT
--WHERE DM.ID_TABLE = 2
--	--AND DM.DATE_OP BETWEEN @DATE_FR AND @DATE_TO
--	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
--GROUP BY DM.ID_DOCUMENT, I.MNEMOCODE, DM.DATE_OP, I.INCOMING_NUMBER, I.INCOMING_DATE

--UNION ALL

--SELECT
--	CONTRACTOR_NAME = MAX(C.NAME),
--	MNEMOCODE = I.MNEMOCODE,
--	[DATE] = i.document_date,
--	INCOMING_NUMBER = NULL,
--	INCOMING_DATE = NULL,
--	CONTRACTOR_SUM_VAT = SUM(ii.supplier_sum_vat),
--	RETAIL_SUM = SUM(ii.retail_sum_vat),
--	SUPPLIER_VAT_RATE_10 = SUM(CASE WHEN ii.supplier_vat = 10 THEN ii.supplier_vat_sum ELSE 0 END),
--	SUPPLIER_VAT_RATE_18 = SUM(CASE WHEN ii.supplier_vat = 18 THEN ii.supplier_vat_sum ELSE 0 END),
--	RETAIL_VAT_RATE_10 = SUM(CASE WHEN ii.retail_vat = 10 THEN ii.retail_vat_sum ELSE 0 END),
--	RETAIL_VAT_RATE_18 = SUM(CASE WHEN ii.retail_vat = 18 THEN ii.retail_vat_sum ELSE 0 END)	
--FROM IMPORT_REMAINS I
--	INNER JOIN IMPORT_REMAINS_ITEM II ON II.ID_IMPORT_REMAINS_GLOBAL = I.id_import_remains_global
--	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = ii.id_supplier	
--	inner join doc_movement dm on dm.id_document = i.id_import_remains_global
--WHERE --i.document_date BETWEEN @DATE_FR AND @DATE_TO
--	/*and*/ i.document_state = 'PROC'
--	AND (@ALL_STORES = 1 OR i.ID_STORE IN (SELECT ID_STORE FROM #STORES))
--GROUP BY ii.id_supplier, I.MNEMOCODE, i.document_date
--ORDER BY CONTRACTOR_NAME

--END
--ELSE
--BEGIN

--insert into @temp_t
--SELECT
--	CONTRACTOR_NAME = MAX(C.NAME),
--	MNEMOCODE = I.MNEMOCODE,
--	[DATE] = DM.DATE_OP,
--	INCOMING_NUMBER = I.INCOMING_NUMBER,
--	INCOMING_DATE = I.INCOMING_DATE,
--	CONTRACTOR_SUM_VAT = SUM(DM.SUM_SUP),
--	RETAIL_SUM = SUM(DM.SUM_ACC),
--	SUPPLIER_VAT_RATE_10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SVAT_SUP ELSE 0 END),
--	SUPPLIER_VAT_RATE_18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SVAT_SUP ELSE 0 END),
--	RETAIL_VAT_RATE_10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SVAT_ACC ELSE 0 END),
--	RETAIL_VAT_RATE_18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SVAT_ACC ELSE 0 END)
--FROM DOC_MOVEMENT DM
--	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
--	INNER JOIN INVOICE I ON I.ID_INVOICE_GLOBAL = DM.ID_DOCUMENT
--WHERE DM.ID_TABLE = 2
--	--AND DM.DATE_OP BETWEEN @DATE_FR AND @DATE_TO
--	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
--GROUP BY DM.ID_DOCUMENT, I.MNEMOCODE, DM.DATE_OP, I.INCOMING_NUMBER, I.INCOMING_DATE
--ORDER BY MAX(C.NAME)

--END

--END 
--select * from @temp_t where date between @date_fr and @date_to

/*SELECT COMPANY = CASE WHEN ISNULL(FULL_NAME, '') = '' THEN [NAME] ELSE FULL_NAME END
FROM CONTRACTOR
WHERE ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()

select SUMM = sum(contractor_sum_vat) from @temp_t where date > @date_fr_one
select SUMM = sum(contractor_sum_vat) from @temp_t where date > @date_fr_two
select SUMM = sum(contractor_sum_vat) from @temp_t where date > @date_fr_three
select SUMM = sum(contractor_sum_vat) from @temp_t where date > @date_fr_half
select SUMM = sum(contractor_sum_vat) from @temp_t where date > @date_fr_year*/

CREATE TABLE #T1
(ID_CONTRACTOR BIGINT, CONTRACTOR_NAME VARCHAR(100), MNEMOCODE VARCHAR(40),
[DATE] DATETIME, INCOMING_NUMBER VARCHAR(50), INCOMING_DATE DATETIME,
SUMM MONEY, VAT_RATE MONEY, TYPE_RATE VARCHAR(3),
SVAT MONEY)

IF (@SHOW_REMAIN = 1)
BEGIN

INSERT INTO #T1(ID_CONTRACTOR, CONTRACTOR_NAME, MNEMOCODE,
	[DATE], INCOMING_NUMBER, INCOMING_DATE, SUMM,
	VAT_RATE, TYPE_RATE, SVAT)
SELECT
	ID_CONTRACTOR = MAX(C.ID_CONTRACTOR),
	CONTRACTOR_NAME = MAX(C.NAME),
	MNEMOCODE = I.MNEMOCODE,
	[DATE] = DM.DATE_OP,
	INCOMING_NUMBER = I.INCOMING_NUMBER,
	INCOMING_DATE = I.INCOMING_DATE,
	SUM(DM.SUM_SUP),
	--RETAIL_SUM = SUM(DM.SUM_ACC),
	DM.VAT_RATE,
	'SUP',
	SUM(DM.SVAT_SUP)--,
	--SVAT_ACC = SUM(DM.SVAT_ACC)
--INTO #T1
FROM DOC_MOVEMENT DM
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
	INNER JOIN INVOICE I ON I.ID_INVOICE_GLOBAL = DM.ID_DOCUMENT
WHERE DM.ID_TABLE = 2
	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
GROUP BY DM.ID_DOCUMENT, I.MNEMOCODE, DM.DATE_OP, I.INCOMING_NUMBER, I.INCOMING_DATE, DM.VAT_RATE

UNION ALL
SELECT
	ID_CONTRACTOR = MAX(C.ID_CONTRACTOR),
	CONTRACTOR_NAME = MAX(C.NAME),
	MNEMOCODE = I.MNEMOCODE,
	[DATE] = DM.DATE_OP,
	INCOMING_NUMBER = I.INCOMING_NUMBER,
	INCOMING_DATE = I.INCOMING_DATE,
	--CONTRACTOR_SUM_VAT = SUM(DM.SUM_SUP),
	SUM(DM.SUM_ACC),
	DM.VAT_RATE,
	'SAL',
	--SVAT_SUP = SUM(DM.SVAT_SUP),
	SUM(DM.SVAT_ACC)
--INTO #T1
FROM DOC_MOVEMENT DM
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
	INNER JOIN INVOICE I ON I.ID_INVOICE_GLOBAL = DM.ID_DOCUMENT
WHERE DM.ID_TABLE = 2
	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
GROUP BY DM.ID_DOCUMENT, I.MNEMOCODE, DM.DATE_OP, I.INCOMING_NUMBER, I.INCOMING_DATE, DM.VAT_RATE

UNION ALL
SELECT
	ID_CONTRACTOR = C.ID_CONTRACTOR,
	CONTRACTOR_NAME = MAX(C.NAME),
	MNEMOCODE = I.MNEMOCODE,
	[DATE] = I.DOCUMENT_DATE,
	INCOMING_NUMBER = NULL,
	INCOMING_DATE = NULL,
	SUM(II.SUPPLIER_SUM_VAT),
	--RETAIL_SUM = SUM(II.RETAIL_SUM_VAT),
	II.SUPPLIER_VAT,
	'SUP',
	SUM(II.SUPPLIER_VAT_SUM)--,
	--SVAT_ACC = SUM(II.RETAIL_VAT_SUM)
--INTO #T1
--select *
FROM IMPORT_REMAINS I
	INNER JOIN IMPORT_REMAINS_ITEM II ON II.ID_IMPORT_REMAINS_GLOBAL = I.id_import_remains_global
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = ii.id_supplier	
	--inner join doc_movement dm on dm.id_document = i.id_import_remains_global
WHERE I.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
GROUP BY C.ID_CONTRACTOR, I.MNEMOCODE, I.DOCUMENT_DATE, II.SUPPLIER_VAT

UNION ALL
SELECT
	ID_CONTRACTOR = C.ID_CONTRACTOR,
	CONTRACTOR_NAME = MAX(C.NAME),
	MNEMOCODE = I.MNEMOCODE,
	[DATE] = I.DOCUMENT_DATE,
	INCOMING_NUMBER = NULL,
	INCOMING_DATE = NULL,
	--CONTRACTOR_SUM_VAT = SUM(II.SUPPLIER_SUM_VAT),
	SUM(II.RETAIL_SUM_VAT),
	II.RETAIL_VAT,
	'SAL',
	--SVAT_SUP = SUM(II.SUPPLIER_VAT_SUM),
	SUM(II.RETAIL_VAT_SUM)
--INTO #T1
FROM IMPORT_REMAINS I
	INNER JOIN IMPORT_REMAINS_ITEM II ON II.ID_IMPORT_REMAINS_GLOBAL = I.id_import_remains_global
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = ii.id_supplier	
	--inner join doc_movement dm on dm.id_document = i.id_import_remains_global
WHERE I.DOCUMENT_STATE = 'PROC'
	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
GROUP BY C.ID_CONTRACTOR, I.MNEMOCODE, I.DOCUMENT_DATE, II.RETAIL_VAT
ORDER BY CONTRACTOR_NAME


END
ELSE
BEGIN
INSERT INTO #T1(ID_CONTRACTOR, CONTRACTOR_NAME, MNEMOCODE,
	[DATE], INCOMING_NUMBER, INCOMING_DATE, SUMM,
	VAT_RATE, TYPE_RATE, SVAT)
SELECT
	ID_CONTRACTOR = MAX(C.ID_CONTRACTOR),
	CONTRACTOR_NAME = MAX(C.NAME),
	MNEMOCODE = I.MNEMOCODE,
	[DATE] = DM.DATE_OP,
	INCOMING_NUMBER = I.INCOMING_NUMBER,
	INCOMING_DATE = I.INCOMING_DATE,
	SUM(DM.SUM_SUP),
	--RETAIL_SUM = SUM(DM.SUM_ACC),
	DM.VAT_RATE,
	'SUP',
	SUM(DM.SVAT_SUP)--,
	--SVAT_ACC = SUM(DM.SVAT_ACC)
--INTO #T1
FROM DOC_MOVEMENT DM
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
	INNER JOIN INVOICE I ON I.ID_INVOICE_GLOBAL = DM.ID_DOCUMENT
WHERE DM.ID_TABLE = 2
	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
GROUP BY DM.ID_DOCUMENT, I.MNEMOCODE, DM.DATE_OP, I.INCOMING_NUMBER, I.INCOMING_DATE, DM.VAT_RATE
UNION ALL
SELECT
	ID_CONTRACTOR = MAX(C.ID_CONTRACTOR),
	CONTRACTOR_NAME = MAX(C.NAME),
	MNEMOCODE = I.MNEMOCODE,
	[DATE] = DM.DATE_OP,
	INCOMING_NUMBER = I.INCOMING_NUMBER,
	INCOMING_DATE = I.INCOMING_DATE,
	--CONTRACTOR_SUM_VAT = SUM(DM.SUM_SUP),
	SUM(DM.SUM_ACC),
	DM.VAT_RATE,
	'SAL',
	--SVAT_SUP = SUM(DM.SVAT_SUP),
	SUM(DM.SVAT_ACC)
--INTO #T1
FROM DOC_MOVEMENT DM
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
	INNER JOIN INVOICE I ON I.ID_INVOICE_GLOBAL = DM.ID_DOCUMENT
WHERE DM.ID_TABLE = 2
	AND (@ALL_STORES = 1 OR I.ID_STORE IN (SELECT ID_STORE FROM #STORES))
GROUP BY DM.ID_DOCUMENT, I.MNEMOCODE, DM.DATE_OP, I.INCOMING_NUMBER, I.INCOMING_DATE, DM.VAT_RATE
ORDER BY CONTRACTOR_NAME
END
declare @SHOW_NDS0_SUP BIT
declare @SHOW_NDS0_SAL BIT
SET @SHOW_NDS0_SUP = 0
SET @SHOW_NDS0_SAL = 0 
select top 1 @SHOW_NDS0_SUP=COUNT(*) from #T1 where ([DATE] between @DATE_FR and @DATE_TO)and(TYPE_RATE='SUP')and(VAT_RATE=0)
select top 1 @SHOW_NDS0_SAL=COUNT(*) from #T1 where ([DATE] between @DATE_FR and @DATE_TO)and(TYPE_RATE='SAL')and(VAT_RATE=0) 

create table #vt
(ID_CONTRACTOR bigint, CONTRACTOR_NAME varchar(100), MNEMOCODE varchar(40), 
DATE datetime, VAT_RATE money, TYPE_RATE VARCHAR(3),
INCOMING_NUMBER varchar(50), INCOMING_DATE datetime, SUMM money)

declare @vat money
--DECLARE @TYPE VARCHAR(3)

declare cs cursor for 
select distinct 
	VAT_RATE--, TYPE_RATE
from #T1

OPEN cs 
FETCH NEXT FROM cs INTO @vat--, @TYPE

while @@FETCH_STATUS = 0
begin
	insert into #vt
		(ID_CONTRACTOR, CONTRACTOR_NAME, MNEMOCODE, DATE, VAT_RATE, TYPE_RATE,
			INCOMING_NUMBER, INCOMING_DATE, SUMM)
	select distinct
		ID_CONTRACTOR, CONTRACTOR_NAME, MNEMOCODE, DATE, @vat, TYPE_RATE, --@TYPE,
			INCOMING_NUMBER, INCOMING_DATE,	SUMM
	from 
	(SELECT 
			T1.ID_CONTRACTOR,
			T1.CONTRACTOR_NAME,
			T1.MNEMOCODE,
			T1.DATE,
			T1.INCOMING_NUMBER,
			T1.INCOMING_DATE,
			T1.TYPE_RATE,--
			SUMM = SUM(T1.SUMM)
		FROM #T1 T1
		GROUP BY T1.ID_CONTRACTOR,
			T1.CONTRACTOR_NAME,
			T1.MNEMOCODE,
			T1.DATE,
			T1.INCOMING_NUMBER,
			T1.INCOMING_DATE,
			T1.TYPE_RATE) t
	where NOT exists (select null from #vt vt
	where t.ID_CONTRACTOR = vt.ID_CONTRACTOR
		and t.MNEMOCODE = vt.MNEMOCODE and t.DATE = vt.DATE 
		and vt.VAT_RATE = @vat AND VT.TYPE_RATE = T.TYPE_RATE/*@TYPE*/)
	
	FETCH NEXT FROM cs INTO @vat--, @TYPE
end

DEALLOCATE cs

--проверка
--select * from #vt

SELECT
		vt.ID_CONTRACTOR,
		vt.MNEMOCODE,
		vt.CONTRACTOR_NAME,
		vt.DATE,
		vt.INCOMING_NUMBER,
		vt.INCOMING_DATE,
		vt.TYPE_RATE,
		vt.SUMM,
		VT.VAT_RATE,
		SVAT = ISNULL(T.SVAT, 0)
INTO #RESULT
FROM #vt vt
LEFT JOIN 
(
SELECT 
		T11.ID_CONTRACTOR,
		T11.MNEMOCODE,
		T11.DATE,
		T11.VAT_RATE,
		T11.TYPE_RATE,
		SVAT = SUM(T11.SVAT)
	FROM #T1 T11
	GROUP BY T11.ID_CONTRACTOR,
		T11.MNEMOCODE,
		T11.DATE,
		T11.VAT_RATE,
		T11.TYPE_RATE
) T ON vt.ID_CONTRACTOR = T.ID_CONTRACTOR and vt.MNEMOCODE = T.MNEMOCODE
		and vt.DATE = T.DATE and vt.VAT_RATE = t.VAT_RATE AND vt.TYPE_RATE = t.TYPE_RATE
--WHERE VT.VAT_RATE > 0 AND VT.DATE BETWEEN @DATE_FR AND @DATE_TO

/*SELECT * FROM #RESULT
WHERE VAT_RATE > 0 AND DATE BETWEEN @DATE_FR AND @DATE_TO*/

CREATE TABLE #MAIN (ID_CONTRACTOR BIGINT, CONTRACTOR_NAME VARCHAR(100), MNEMOCODE VARCHAR(40),
[DATE] DATETIME, INCOMING_NUMBER VARCHAR(50), INCOMING_DATE DATETIME,
SUMM_SUP MONEY, SUMM_SAL MONEY, SUMM_SUP_SUB_NDS MONEY, SUMM_SAL_SUB_NDS MONEY)
--,SUMM_NDS_18_SUP MONEY, SUMM_NDS_18_SAL MONEY, SUMM_NDS_10_SUP MONEY, SUMM_NDS_10_SAL MONEY)

		
INSERT INTO #MAIN
(ID_CONTRACTOR, MNEMOCODE, CONTRACTOR_NAME,
[DATE], INCOMING_NUMBER, INCOMING_DATE,
SUMM_SUP, SUMM_SAL)
SELECT DISTINCT
		R.ID_CONTRACTOR,
		R.MNEMOCODE,
		R.CONTRACTOR_NAME,
		R.DATE,
		R.INCOMING_NUMBER,
		R.INCOMING_DATE,
		SUMM_SUP = ROUND(SUM(RSUP.SUMM),@ROUND_DIGIT),
		SUMM_SAL = ROUND(CASE WHEN R.TYPE_RATE = 'SAL' THEN SUM(R.SUMM) ELSE 0 END,@ROUND_DIGIT)
FROM #RESULT R
INNER JOIN
(
SELECT DISTINCT ID_CONTRACTOR, MNEMOCODE, DATE, SUMM
FROM #RESULT 
WHERE TYPE_RATE = 'SUP' AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1 /*WHERE VAT_RATE > 0*/)
) RSUP ON R.ID_CONTRACTOR = RSUP.ID_CONTRACTOR AND R.DATE = RSUP.DATE AND R.MNEMOCODE = RSUP.MNEMOCODE
WHERE /*R.VAT_RATE > 0 AND*/ R.DATE BETWEEN @DATE_FR AND @DATE_TO
	AND R.VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1 /*WHERE VAT_RATE > 0*/)
GROUP BY R.ID_CONTRACTOR,
		R.MNEMOCODE,
		R.CONTRACTOR_NAME,
		R.DATE,
		R.INCOMING_NUMBER,
		R.INCOMING_DATE,
		R.TYPE_RATE
HAVING CASE WHEN R.TYPE_RATE = 'SAL' THEN SUM(R.SUMM) ELSE 0 END > 0
--select * from #result
--select * from #t1
--select * from #main
-- получаем нужные столбцы, затем сгенерим полную таблицу

SELECT DISTINCT
	FIELD_NAME = 'SUMM_NDS_' + CONVERT(VARCHAR(10), CAST(VAT_RATE AS INT)) + 
		'_' + TYPE_RATE,
	FIELD_TEXT = 'Сумма НДС ' + CONVERT(VARCHAR(10), CAST(VAT_RATE AS INT)) + '%' + 
		CASE WHEN TYPE_RATE = 'SAL' THEN ' розн.' ELSE ' опт.' END,
	TYPE_RATE,
	VAT_RATE
INTO #FIELDS
FROM #RESULT
WHERE VAT_RATE > 0 AND DATE BETWEEN @DATE_FR AND @DATE_TO
	AND SVAT <> 0
ORDER BY TYPE_RATE DESC, VAT_RATE ASC

SELECT FIELD_NAME, FIELD_TEXT FROM #FIELDS ORDER BY FIELD_NAME

SELECT
	CONTRACTOR_NAME = T.CONTRACTOR_NAME,
	CONTRACTOR_SUM_VAT = ROUND(T.CONTRACTOR_SUM_VAT,@ROUND_DIGIT),
	RETAIL_SUM = ROUND(T.RETAIL_SUM,@ROUND_DIGIT),
	PERCENTAGE = ROUND(T.CONTRACTOR_SUM_VAT * 100 / @TOTAL_CONTRACTOR_SUM_VAT, @ROUND_DIGIT)
FROM #TEMP_T T
ORDER BY T.CONTRACTOR_SUM_VAT * 100 / @TOTAL_CONTRACTOR_SUM_VAT DESC

DECLARE @FIELD_NAME VARCHAR(100)
DECLARE @TYPE_RATE VARCHAR(3)
DECLARE @VAT_RATE MONEY
DECLARE @SQL NVARCHAR(2048)
SET @SQL = ''

DECLARE CS_FLD CURSOR FOR
SELECT 
	FIELD_NAME, TYPE_RATE, VAT_RATE
FROM #FIELDS
DECLARE @FIELDS_NDS_SUP VARCHAR(500), @FIELDS_NDS_SAL VARCHAR(500) --chsa
SET @FIELDS_NDS_SUP=''
SET @FIELDS_NDS_SAL=''
OPEN CS_FLD
FETCH NEXT FROM CS_FLD INTO @FIELD_NAME, @TYPE_RATE, @VAT_RATE
WHILE @@FETCH_STATUS = 0
BEGIN
	-----------------------------   chsa
	IF (CHARINDEX('SUP', @FIELD_NAME)=0)
		SET @FIELDS_NDS_SAL=@FIELDS_NDS_SAL+ISNULL(' - '+@FIELD_NAME,'')
		else
			SET @FIELDS_NDS_SUP=@FIELDS_NDS_SUP+ISNULL(' - '+@FIELD_NAME,'')
	-----------------------------
	SET @SQL = 'ALTER TABLE #MAIN ADD ' + @FIELD_NAME + ' MONEY'
	EXEC SP_EXECUTESQL @SQL, N'@FIELD_NAME VARCHAR(100)', @FIELD_NAME = @FIELD_NAME
	
	SET @SQL = 'UPDATE #MAIN SET '
	SET @SQL = @SQL + @FIELD_NAME
	SET @SQL = @SQL + ' = ROUND(S.SVAT,@ROUND_DIGIT) FROM #MAIN M INNER JOIN (SELECT ID_CONTRACTOR,	MNEMOCODE, DATE, TYPE_RATE,	VAT_RATE, SVAT FROM #RESULT	WHERE DATE BETWEEN @DATE_FR AND @DATE_TO AND TYPE_RATE = @TYPE_RATE AND VAT_RATE = @VAT_RATE) S ON S.ID_CONTRACTOR = M.ID_CONTRACTOR AND S.DATE = M.DATE AND S.MNEMOCODE = M.MNEMOCODE'
	EXEC SP_EXECUTESQL @SQL, N'@DATE_FR DATETIME, @DATE_TO DATETIME, 
	@TYPE_RATE VARCHAR(3), @VAT_RATE MONEY, @ROUND_DIGIT INT', @DATE_FR = @DATE_FR, @DATE_TO = @DATE_TO,
	@TYPE_RATE = @TYPE_RATE, @VAT_RATE = @VAT_RATE, @ROUND_DIGIT=@ROUND_DIGIT
	
 FETCH NEXT FROM CS_FLD INTO @FIELD_NAME, @TYPE_RATE, @VAT_RATE
END
DEALLOCATE CS_FLD

--select * from #fields
DECLARE @SQL1 NVARCHAR(200)
SET @SQL1 = 'update #MAIN SET SUMM_SUP_SUB_NDS = ROUND(SUMM_SUP '+@FIELDS_NDS_SUP+',@ROUND_DIGIT), SUMM_SAL_SUB_NDS=ROUND(SUMM_SAL '+@FIELDS_NDS_SAL+',@ROUND_DIGIT)'
--SELECT @SQL1
EXEC SP_EXECUTESQL @SQL1,N'@ROUND_DIGIT INT',@ROUND_DIGIT=@ROUND_DIGIT

--update #MAIN SET SUMM_SUP_SUB_NDS=SUMM_SUP-(SUMM_NDS_10_SUP+SUMM_NDS_18_SUP) , SUMM_SAL_SUB_NDS=SUMM_SAL-(SUMM_NDS_10_SAL+SUMM_NDS_18_SAL)--chsa

SELECT *,
		SHOW_NDS0_SUP =@SHOW_NDS0_SUP
		,SHOW_NDS0_SAL =@SHOW_NDS0_SAL
FROM #MAIN
ORDER BY CONTRACTOR_NAME, MNEMOCODE

--select 1--
SELECT 
	SUMM_NAME = 'Сумма оптовая',
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SUMM ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1/* WHERE VAT_RATE > 0*/)
UNION ALL 
SELECT 
	SUMM_NAME = 'Сумма розничная',
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SAL' THEN SUMM ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1/* WHERE VAT_RATE > 0*/)
UNION ALL
SELECT
	SUMM_NAME = 'Сумма НДС 0% опт.',
	SUMM =0
	where ((SELECT count(*) FROM #MAIN)>=1)and(@SHOW_NDS0_SUP = 1)
UNION ALL
SELECT
	SUMM_NAME = 'Сумма НДС ' + CONVERT(VARCHAR, CAST(VAT_RATE AS INT)) + '% опт.',
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SVAT ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND VAT_RATE > 0 
GROUP BY VAT_RATE
having ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SVAT ELSE 0 END),@ROUND_DIGIT)<>0
UNION ALL

SELECT
	SUMM_NAME = 'Сумма НДС 0% розн.',
	SUMM =0
	where ((SELECT count(*) FROM #MAIN)>=1)and(@SHOW_NDS0_SAL = 1)
UNION ALL
SELECT
	SUMM_NAME = 'Сумма НДС ' + CONVERT(VARCHAR, CAST(VAT_RATE AS INT)) + '% розн.',
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SAL' THEN SVAT ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE BETWEEN @DATE_FR AND @DATE_TO
	AND VAT_RATE > 0 
GROUP BY VAT_RATE
having ROUND(SUM(CASE WHEN TYPE_RATE = 'SAL' THEN SVAT ELSE 0 END),@ROUND_DIGIT)<>0
SELECT COMPANY = CASE WHEN ISNULL(FULL_NAME, '') = '' THEN [NAME] ELSE FULL_NAME END
FROM CONTRACTOR
WHERE ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()

SELECT 
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SUMM ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE > @date_fr_one
	AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1 /*WHERE VAT_RATE > 0*/)
--select @date_fr_one
SELECT 
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SUMM ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE > @date_fr_two
	AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1 /*WHERE VAT_RATE > 0*/)
	
SELECT 
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SUMM ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE > @date_fr_three
	AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1/* WHERE VAT_RATE > 0*/)
	
SELECT 
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SUMM ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE > @date_fr_half
	AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1/* WHERE VAT_RATE > 0*/)
	
SELECT 
	SUMM = ROUND(SUM(CASE WHEN TYPE_RATE = 'SUP' THEN SUMM ELSE 0 END),@ROUND_DIGIT)
FROM #RESULT 
WHERE DATE > @date_fr_year
	AND VAT_RATE = (SELECT MIN(VAT_RATE) FROM #T1/* WHERE VAT_RATE > 0*/)

--SELECT FIELD_NAME, FIELD_TEXT FROM #FIELDS

RETURN 0
GO  

/*
EXEC REPEX_INVOICE_BOOK '
<XML>
	<DATE_FR>2011-08-09</DATE_FR>
	<DATE_TO>2011-08-09T16:35:00.000</DATE_TO>
	<DETAIL>1</DETAIL>
	<SHOW_REMAIN>1</SHOW_REMAIN>
	<ROUND_DIGIT>4</ROUND_DIGIT>
</XML>'
*/




SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO 

IF OBJECT_ID('DBO.REMOVE_REPORT_BY_TYPE_NAME') IS NULL EXEC('CREATE PROCEDURE DBO.REMOVE_REPORT_BY_TYPE_NAME AS RETURN')
GO
ALTER PROCEDURE DBO.REMOVE_REPORT_BY_TYPE_NAME 
	@REPORT_TYPE_NAME VARCHAR(200) AS
	
DECLARE @id_meta_report BIGINT

	select 
		@id_meta_report = id_meta_report
	from meta_report
	where type_name = @REPORT_TYPE_NAME
	--select @id_meta_report
		
	DECLARE @SQL NVARCHAR(200)
	SET @SQL = N'delete from META_REPORT_2_REPORT_GROUPS
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('META_REPORT_2_REPORT_GROUPS') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_csv_export
		where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_csv_export') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_visible
		where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_visible') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_managed
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_managed') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report


	SET @SQL = N'delete from meta_report_settings_archive
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_archive') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report


	delete from meta_report
	where id_meta_report = @id_meta_report

RETURN 0
GO

EXEC DBO.REMOVE_REPORT_BY_TYPE_NAME 'InvoiceBookEx.InvoiceBookParams'
