IF
(
	(SELECT TOP 1 value FROM SGAU_REP_UZO_PACK_OPTIONS WHERE mnemocode = 'NEW_PERCENT_PARAM_UPDATER') = '1'
)
BEGIN
	
	SELECT date_start, date_end, percent_service INTO #PS FROM SGAU_REP_UZO_PACK_PERCENT_SERVICE 
	
	DROP TABLE SGAU_REP_UZO_PACK_PERCENT_SERVICE
	
	CREATE TABLE SGAU_REP_UZO_PACK_PERCENT_SERVICE
	(
		id_percent_service bigint IDENTITY(1,1) NOT NULL,
		date_start datetime,
		date_end datetime,
		percent_service money,
		mnemocode_store_type varchar(12),
		id_discount2_medical_organization_global uniqueidentifier,
		CONSTRAINT [PK_PERCENT_SERVICE] PRIMARY KEY CLUSTERED 
		(
			[id_percent_service] ASC
		)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
	) ON [PRIMARY]
	
	SELECT DISTINCT 
		DMO.ID_DISCOUNT2_MEDICAL_ORGANIZATION_GLOBAL
	INTO #DMO
	FROM SGAU_REP_UZO_PACK UP
	LEFT JOIN TRUST_LETTER TL ON (TL.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' от '+CONVERT(VARCHAR(10), UP.date_pack, 104))
	LEFT JOIN STORE ST ON TL.ID_STORE = ST.ID_STORE
	LEFT JOIN STORE_TYPE STT ON STT.ID_STORE_TYPE_GLOBAL = ST.ID_STORE_TYPE_GLOBAL
	LEFT JOIN DISCOUNT2_MEDICAL_ORGANIZATION DMO on TL.ID_DISCOUNT2_MEDICAL_ORGANIZATION = DMO.ID_DISCOUNT2_MEDICAL_ORGANIZATION
	WHERE
		1 = 1
		AND TL.DOCUMENT_STATE='PROC'
		AND STT.MNEMOCODE = 'RLO'

	INSERT INTO SGAU_REP_UZO_PACK_PERCENT_SERVICE
	SELECT 
		PS.date_start,
		PS.date_end,
		PS.percent_service,
		'RLO',
		NULL
	FROM #PS PS
	UNION ALL
	SELECT 
		PS.date_start,
		PS.date_end,
		PS.percent_service,
		'RLO',
		DMO.ID_DISCOUNT2_MEDICAL_ORGANIZATION_GLOBAL
	FROM #PS PS
	LEFT JOIN #DMO DMO ON 1 = 1
	
	DROP TABLE #DMO
	DROP TABLE #PS
	
	UPDATE SGAU_REP_UZO_PACK_OPTIONS SET value = '0' WHERE mnemocode = 'NEW_PERCENT_PARAM_UPDATER'
END
