IF
(
	(SELECT TOP 1 value FROM SGAU_REP_UZO_PACK_OPTIONS WHERE mnemocode = 'RENUMBER_PACK_UPDATER') = '1'
)
BEGIN
	DECLARE @DATE_START DATETIME, @DATE_END DATETIME
	
	SELECT TOP 1 @DATE_START = CAST(value AS DATETIME) FROM SGAU_REP_UZO_PACK_OPTIONS WHERE mnemocode = 'RENUMBER_PACK_DATE_START'
	SELECT TOP 1 @DATE_END = CAST(value AS DATETIME) FROM SGAU_REP_UZO_PACK_OPTIONS WHERE mnemocode = 'RENUMBER_PACK_DATE_END'
	
	SELECT
		ID = UP.ID,
		TL_JOIN_STR = '[' + UP.prefix_pack + '/' + CAST(UP.id_pack as VARCHAR(10))+'] ' + UP.number_pack + ' от '+CONVERT(VARCHAR(10), UP.date_pack, 104),
		NEW_NUMBER_PACK = prefix_pack + '/' + RIGHT('00000' + CAST(NN AS VARCHAR(10)), 5),
		NEW_TL_JOIN_STR = '[' + UP.prefix_pack + '/' + CAST(UP.id_pack as VARCHAR(10))+'] ' + prefix_pack + '/' + RIGHT('00000' + CAST(NN AS VARCHAR(10)), 5) + ' от '+CONVERT(VARCHAR(10), UP.date_pack, 104)
	INTO #UPDATE_PACK
	FROM
	(
		SELECT
			 ID = prefix_pack+'/'+CAST(id_pack as VARCHAR(10)),
			 NN = rank() OVER (ORDER BY prefix_pack, id_contractor_perform, id_pack),
			 prefix_pack,
			 id_pack,
			 number_pack,
			 date_pack
		FROM SGAU_REP_UZO_PACK
		WHERE 
			date_pack BETWEEN @DATE_START AND @DATE_END
	) as UP
	
	UPDATE TRUST_LETTER
	SET REESTR_NUMBER = (SELECT TOP 1 UP.NEW_TL_JOIN_STR FROM #UPDATE_PACK UP WHERE UP.TL_JOIN_STR = REESTR_NUMBER)
	WHERE REESTR_NUMBER IN (SELECT DISTINCT UP2.TL_JOIN_STR FROM #UPDATE_PACK UP2)
	
	UPDATE SGAU_REP_UZO_PACK
	SET number_pack = (SELECT TOP 1 UP.NEW_NUMBER_PACK FROM #UPDATE_PACK UP WHERE UP.ID = prefix_pack + '/' + CAST(id_pack as VARCHAR(10)))
	WHERE prefix_pack + '/' + CAST(id_pack as VARCHAR(10)) IN (SELECT DISTINCT UP2.ID FROM #UPDATE_PACK UP2)
	
	DROP TABLE #UPDATE_PACK
	
	UPDATE SGAU_REP_UZO_PACK_OPTIONS SET value = '0' WHERE mnemocode = 'RENUMBER_PACK_UPDATER'
END