SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REP_UZO_BALANCE_PACK') IS NULL EXEC('CREATE PROCEDURE DBO.REP_UZO_BALANCE_PACK AS RETURN')
GO
ALTER PROCEDURE DBO.REP_UZO_BALANCE_PACK
     @XMLPARAM NVARCHAR(MAX) AS

DECLARE @HDOC INT
DECLARE @ID_PACK VARCHAR(10)

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT TOP 1 
	@ID_PACK = ID_PACK 
FROM OPENXML(@HDOC, '/XML')	WITH
(
	ID_PACK VARCHAR(10) 'ID_PACK'
)

DECLARE @SELF uniqueidentifier
DECLARE @OFFICE_GLOBAL_CODE VARCHAR(10)
DECLARE @SERVICE_PERCENT money
DECLARE @SERVICE_NDS money
DECLARE @BASE_SIGN VARCHAR(100)

SET @OFFICE_GLOBAL_CODE = (select top 1 VALUE from SGAU_REP_UZO_PACK_OPTIONS where MNEMOCODE = 'OFFICE_GLOBAL_CODE')
SET @SERVICE_PERCENT = (select top 1 cast(VALUE as money) from SGAU_REP_UZO_PACK_OPTIONS where MNEMOCODE = 'SERVICE_PERCENT')
SET @SERVICE_NDS = (select top 1 cast(VALUE as money) from SGAU_REP_UZO_PACK_OPTIONS where MNEMOCODE = 'SERVICE_NDS')
SET @BASE_SIGN =   (select top 1 VALUE from SGAU_REP_UZO_PACK_OPTIONS where MNEMOCODE = 'BASE_SIGN_BALANCE')

SELECT TOP 1 @SELF = C.ID_CONTRACTOR_GLOBAL
    FROM ENTERPRISE_BRANCH EB(NOLOCK)
        INNER JOIN CONTRACTOR C(NOLOCK) ON C.ID_CONTRACTOR = EB.ID_CONTRACTOR
    WHERE EB.IS_SELF = 1

-------1_ActCompliteWork (Balance)
SELECT 
	ID_REESTR = UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)),
	REESTR_NUM = UP.NUMBER_PACK,
	REESTR_DATE = CONVERT(VARCHAR(10), UP.DATE_PACK, 104),
	PERFORMER_NAME = PERF.NAME,
	CUSTOMER_NAME = CUST.NAME,
	SUM_SUP = SUM(ROUND(L.PRICE_SUP, 2) * TLI.QUANTITY),
	SUM_SAL = SUM(ROUND(L.PRICE_SAL, 2) * TLI.QUANTITY),
	PVAT_SAL = SUM(ROUND(L.PVAT_SAL, 2) * TLI.QUANTITY)
FROM
SGAU_REP_UZO_PACK UP
INNER JOIN TRUST_LETTER TL ON (TL.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))
INNER JOIN TRUST_LETTER_ITEM TLI ON TL.ID_TRUST_LETTER_GLOBAL = TLI.ID_TRUST_LETTER_GLOBAL
INNER JOIN LOT L ON TLI.ID_SOURCE_GLOBAL = L.ID_LOT_GLOBAL
INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
LEFT JOIN DISCOUNT2_MEDICAL_ORGANIZATION DMO on TL.ID_DISCOUNT2_MEDICAL_ORGANIZATION = DMO.ID_DISCOUNT2_MEDICAL_ORGANIZATION
INNER JOIN CONTRACTOR PERF ON PERF.id_contractor = UP.id_contractor_perform
LEFT JOIN CONTRACTOR CUST ON CUST.id_contractor = UP.id_contractor_custom
WHERE 
	1=1
	AND UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)) = @ID_PACK
	AND TL.DOCUMENT_STATE='PROC'
GROUP BY UP.PREFIX_PACK, UP.ID_PACK, UP.NUMBER_PACK, UP.DATE_PACK, PERF.NAME, CUST.NAME

-------2_Factura (Balance)
SELECT 
	ID_REESTR = UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)),
	REESTR_NUM = UP.NUMBER_PACK,
	REESTR_DATE = CONVERT(VARCHAR(10), UP.DATE_PACK, 104),
	
	PERFORMER_LEGAL_PERS = 
		CASE WHEN ISNULL(PERF.LEGAL_PERS, '') <> '' THEN PERF.LEGAL_PERS ELSE
			CASE WHEN ISNULL(PERF.LEGAL_PERS_SHORT, '') <> '' THEN PERF.LEGAL_PERS_SHORT ELSE 
				CASE WHEN ISNULL(PERF.FULL_NAME, '') ='' THEN PERF.NAME ELSE PERF.FULL_NAME END
	
			END
		END,
	
	PERFORMER_FULL_NAME = CASE WHEN ISNULL(PERF.FULL_NAME, '') ='' THEN PERF.NAME ELSE PERF.FULL_NAME END,
	PERFORMER_NAME = PERF.NAME,
	PERFORMER_UR_ADDRESS = CASE WHEN ISNULL(PERF.UR_ADDRESS, '') ='' THEN PERF.ADDRESS ELSE PERF.UR_ADDRESS END,
	PERFORMER_ADDRESS = PERF.ADDRESS,
	PERFORMER_INN = PERF.INN,
	PERFORMER_KPP = PERF.KPP,
	PERFORMER_BANK = '/Ò '+ISNULL(PERF.ACCOUNT, ' Õ≈ ” ¿«¿Õ –/—!')+ ' ‚ '+ISNULL(PERF.BANK, ' Õ≈ ” ¿«¿Õ ¡¿Õ !') + ' '+ISNULL(PERF.BANK_ADDRESS, ''),
	PERFORMER_BIK = PERF.BIK,
	PERFORMER_OKPO = PERF.OKPO,

	CUSTOMER_FULL_NAME = CASE WHEN ISNULL(CUST.FULL_NAME, '') ='' THEN CUST.NAME ELSE CUST.FULL_NAME END,
	CUSTOMER_NAME = CUST.NAME,
	CUSTOMER_UR_ADDRESS = CASE WHEN ISNULL(CUST.UR_ADDRESS, '') ='' THEN CUST.ADDRESS ELSE CUST.UR_ADDRESS END,
	CUSTOMER_ADDRESS = CUST.ADDRESS,
	CUSTOMER_INN = CUST.INN,
	CUSTOMER_KPP = CUST.KPP,
	CUSTOMER_BANK = '/Ò '+ISNULL(CUST.ACCOUNT, ' Õ≈ ” ¿«¿Õ –/—!')+ ' ‚ '+ISNULL(CUST.BANK, ' Õ≈ ” ¿«¿Õ ¡¿Õ !') + ' '+ISNULL(CUST.BANK_ADDRESS, ''),
	CUSTOMER_BIK = ISNULL(CUST.BIK, '') + ' Í/Ò '+ISNULL(CUST.CORR_ACCOUNT,''),
	CUSTOMER_OKPO = CUST.OKPO,

	HOSPITAL_NAME = DMO.NAME,

	STORE_LIST = 
	(
		SELECT 
			REPLACE(REPLACE(SUBSTRING(ItemListWithTags, 4, LEN(ItemListWithTags)-7), '</S>', ', '),'<S>','')
		FROM 
		(
			SELECT 
				CAST(XmlItemList AS NVARCHAR(MAX)) ItemListWithTags
			FROM 
			(
				SELECT 
					(
						SELECT DISTINCT
							ST_TMP.NAME AS S
						FROM STORE ST_TMP
						WHERE ST_TMP.ID_STORE in (select TL_TMP.id_store from TRUST_LETTER TL_TMP WHERE (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104)))
						FOR XML PATH('')
					) AS XmlItemList
			) AS subq1
		) AS subq2
	),
	CATL_LIST = 
	(
		SELECT 
			REPLACE(REPLACE(SUBSTRING(ItemListWithTags, 4, LEN(ItemListWithTags)-7), '</S>', ', '),'<S>','')
		FROM 
		(
			SELECT 
				CAST(XmlItemList AS NVARCHAR(MAX)) ItemListWithTags
			FROM 
			(
				SELECT 
					(
						SELECT DISTINCT
							CATL_TMP.NAME AS S
						FROM DISCOUNT2_CAT_LGOT CATL_TMP
						WHERE CATL_TMP.ID_DISCOUNT2_CAT_LGOT_GLOBAL in (select TL_TMP.ID_DISCOUNT2_CAT_LGOT_GLOBAL from TRUST_LETTER TL_TMP WHERE (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104)))
						FOR XML PATH('')
					) AS XmlItemList
			) AS subq1
		) AS subq2
	),

	ID_GOODS = G.ID_GOODS,
	GOOD_NAME = G.NAME,
	UNIT_CODE = ISNULL(U.OKEI_CODE, ''),
	UNIT_NAME = U.SHORT_NAME,
	QUANTITY = ROUND(SUM(TLI.QUANTITY * CONVERT(MONEY, SR.NUMERATOR) / SR.DENOMINATOR), 2),
	PRICE_WITHOUT_NDS = ROUND((ROUND(L.PRICE_SAL, 2) - ROUND(L.PVAT_SAL, 2)) * SR.DENOMINATOR / CONVERT(MONEY, SR.NUMERATOR), 2),
	SUM_WITHOUT_NDS = SUM((ROUND(L.PRICE_SAL, 2) - ROUND(L.PVAT_SAL, 2)) * TLI.QUANTITY),
	NDS = L.VAT_SAL,
	NDS_SUM = SUM(ROUND(L.PVAT_SAL, 2) * TLI.QUANTITY),
	SUM_WITH_NDS = SUM(ROUND(L.PRICE_SAL, 2) * TLI.QUANTITY),
	
	COUNTRY_CODE = CASE WHEN CNTR.COD_CODE = 643 THEN '' ELSE ISNULL(CNTR.COD_CODE, '') END,		--–ÓÒÒËˇ
	COUNTRY = CNTR.NAME,
	GTD = L.GTD_NUMBER,
	SIGN_DIR_FIO = OFFICE.DIRECTOR_FIO,
	SIGN_BUH_FIO = OFFICE.BUH_FIO,
	ADD_SIGN_BASE = @BASE_SIGN,
	ADD_SIGN_FIO = PERF.DIRECTOR_FIO
FROM
SGAU_REP_UZO_PACK UP
INNER JOIN TRUST_LETTER TL ON (TL.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))
INNER JOIN TRUST_LETTER_ITEM TLI ON TL.ID_TRUST_LETTER_GLOBAL = TLI.ID_TRUST_LETTER_GLOBAL
INNER JOIN LOT L ON TLI.ID_SOURCE_GLOBAL = L.ID_LOT_GLOBAL
INNER JOIN GOODS G ON L.ID_GOODS = G.ID_GOODS
INNER JOIN PRODUCER PROD ON G.ID_PRODUCER = PROD.ID_PRODUCER
INNER JOIN COUNTRY CNTR ON PROD.ID_COUNTRY = CNTR.ID_COUNTRY
INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
LEFT JOIN DISCOUNT2_MEDICAL_ORGANIZATION DMO on TL.ID_DISCOUNT2_MEDICAL_ORGANIZATION = DMO.ID_DISCOUNT2_MEDICAL_ORGANIZATION
INNER JOIN CONTRACTOR PERF ON PERF.id_contractor = UP.id_contractor_perform
LEFT JOIN CONTRACTOR CUST ON CUST.id_contractor = UP.id_contractor_custom
LEFT JOIN CONTRACTOR OFFICE ON OFFICE.ID_CONTRACTOR_GLOBAL IN (select ID_CONTRACTOR_GLOBAL from REPLICATION_CONFIG where GLOBAL_CODE = @OFFICE_GLOBAL_CODE)
WHERE 
	1=1
	AND UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)) = @ID_PACK
	AND TL.DOCUMENT_STATE='PROC'
GROUP BY 
	UP.PREFIX_PACK, UP.ID_PACK, UP.NUMBER_PACK, UP.DATE_PACK, 
	PERF.FULL_NAME, PERF.NAME, PERF.ADDRESS, PERF.UR_ADDRESS,
	PERF.LEGAL_PERS, PERF.LEGAL_PERS_SHORT,
	PERF.INN, PERF.KPP, PERF.ACCOUNT, PERF.BANK, PERF.BANK_ADDRESS, PERF.BIK, PERF.OKPO,
	CUST.FULL_NAME, CUST.NAME, CUST.ADDRESS, CUST.UR_ADDRESS,
	CUST.INN, CUST.KPP, CUST.ACCOUNT, CUST.BANK, CUST.BANK_ADDRESS, CUST.BIK, CUST.CORR_ACCOUNT, CUST.OKPO,
	DMO.NAME, 
	G.ID_GOODS,	G.NAME,
	L.PRICE_SUP, L.PVAT_SUP, L.VAT_SAL, L.PRICE_SAL, L.PVAT_SAL, SR.DENOMINATOR, SR.NUMERATOR,
	L.GTD_NUMBER, CNTR.NAME,
	OFFICE.DIRECTOR_FIO, OFFICE.BUH_FIO, PERF.DIRECTOR_FIO,
	U.OKEI_CODE, U.SHORT_NAME, CNTR.COD_CODE
ORDER BY GOOD_NAME

-------3_Registry_Short (Balance)
SELECT 
	ID_REESTR = UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)),
	REESTR_NUM = UP.NUMBER_PACK,
	REESTR_DATE = CONVERT(VARCHAR(10), UP.DATE_PACK, 104),
	PERFORMER_FULL_NAME = CASE WHEN ISNULL(PERF.FULL_NAME, '') ='' THEN PERF.NAME ELSE PERF.FULL_NAME END,
	PERFORMER_NAME = PERF.NAME,
	PERFORMER_UR_ADDRESS = CASE WHEN ISNULL(PERF.UR_ADDRESS, '') ='' THEN PERF.ADDRESS ELSE PERF.UR_ADDRESS END,
	PERFORMER_ADDRESS = PERF.ADDRESS,
	PERFORMER_INN = PERF.INN,
	PERFORMER_KPP = PERF.KPP,
	PERFORMER_BANK = '/Ò '+ISNULL(PERF.ACCOUNT, ' Õ≈ ” ¿«¿Õ –/—!')+ ' ‚ '+ISNULL(PERF.BANK, ' Õ≈ ” ¿«¿Õ ¡¿Õ !') + ' '+ISNULL(PERF.BANK_ADDRESS, ''),
	PERFORMER_BIK = PERF.BIK,
	PERFORMER_OKPO = PERF.OKPO,
	PERIOD_DATE = (SELECT 'c '+CONVERT(VARCHAR(10), MIN(TL_TMP.DATE_SHIP), 104)+' ÔÓ '+CONVERT(VARCHAR(10), MAX(TL_TMP.DATE_SHIP), 104) FROM TRUST_LETTER TL_TMP WHERE (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))),
	STORE_LIST = 
	(
		SELECT 
			REPLACE(REPLACE(SUBSTRING(ItemListWithTags, 4, LEN(ItemListWithTags)-7), '</S>', ', '),'<S>','')
		FROM 
		(
			SELECT 
				CAST(XmlItemList AS NVARCHAR(MAX)) ItemListWithTags
			FROM 
			(
				SELECT 
					(
						SELECT DISTINCT
							ST_TMP.NAME AS S
						FROM STORE ST_TMP
						WHERE ST_TMP.ID_STORE in (select TL_TMP.id_store from TRUST_LETTER TL_TMP WHERE (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104)))
						FOR XML PATH('')
					) AS XmlItemList
			) AS subq1
		) AS subq2
	),
	RECIPE_COUNT = (SELECT COUNT(*) FROM TRUST_LETTER TL_TMP WHERE (CATL.ID_DISCOUNT2_CAT_LGOT_GLOBAL = TL_TMP.ID_DISCOUNT2_CAT_LGOT_GLOBAL) AND (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))),
	ID_CATL = CATL.ID_DISCOUNT2_CAT_LGOT_GLOBAL,
	CATL_NAME = CATL.NAME,

	SUM_SUP_WITH_NDS = SUM(ROUND(L.PRICE_SUP, 2) * TLI.QUANTITY),
	SUM_SAL_WITH_NDS = SUM(ROUND(L.PRICE_SAL, 2) * TLI.QUANTITY),

	SIGN_DIR_FIO = OFFICE.DIRECTOR_FIO,
	SIGN_BUH_FIO = OFFICE.BUH_FIO,
	ADD_SIGN_BASE = @BASE_SIGN,
	ADD_SIGN_FIO = PERF.DIRECTOR_FIO
FROM
SGAU_REP_UZO_PACK UP
INNER JOIN TRUST_LETTER TL ON (TL.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))
INNER JOIN TRUST_LETTER_ITEM TLI ON TL.ID_TRUST_LETTER_GLOBAL = TLI.ID_TRUST_LETTER_GLOBAL
INNER JOIN LOT L ON TLI.ID_SOURCE_GLOBAL = L.ID_LOT_GLOBAL
INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
INNER JOIN CONTRACTOR PERF ON PERF.id_contractor = UP.id_contractor_perform
LEFT JOIN CONTRACTOR OFFICE ON OFFICE.ID_CONTRACTOR_GLOBAL IN (select ID_CONTRACTOR_GLOBAL from REPLICATION_CONFIG where GLOBAL_CODE = @OFFICE_GLOBAL_CODE)
LEFT JOIN DISCOUNT2_CAT_LGOT CATL ON CATL.ID_DISCOUNT2_CAT_LGOT_GLOBAL = TL.ID_DISCOUNT2_CAT_LGOT_GLOBAL
WHERE 
	1=1
	AND UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)) = @ID_PACK
	AND TL.DOCUMENT_STATE='PROC'
GROUP BY 
	UP.PREFIX_PACK, UP.ID_PACK, UP.NUMBER_PACK, UP.DATE_PACK, 
	PERF.FULL_NAME, PERF.NAME, PERF.ADDRESS, PERF.UR_ADDRESS,
	PERF.INN, PERF.KPP, PERF.ACCOUNT, PERF.BANK, PERF.BANK_ADDRESS, PERF.BIK, PERF.OKPO,
	CATL.ID_DISCOUNT2_CAT_LGOT_GLOBAL, CATL.NAME,
	OFFICE.DIRECTOR_FIO, OFFICE.BUH_FIO, PERF.DIRECTOR_FIO
ORDER BY CATL_NAME, ID_CATL

-------4_Registry_Full (Balance)
SELECT 
	ID_REESTR = UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)),
	REESTR_NUM = UP.NUMBER_PACK,
	REESTR_DATE = CONVERT(VARCHAR(10), UP.DATE_PACK, 104),
	PERFORMER_FULL_NAME = CASE WHEN ISNULL(PERF.FULL_NAME, '') ='' THEN PERF.NAME ELSE PERF.FULL_NAME END,
	PERFORMER_NAME = PERF.NAME,
	PERFORMER_UR_ADDRESS = CASE WHEN ISNULL(PERF.UR_ADDRESS, '') ='' THEN PERF.ADDRESS ELSE PERF.UR_ADDRESS END,
	PERFORMER_ADDRESS = PERF.ADDRESS,
	PERFORMER_INN = PERF.INN,
	PERFORMER_KPP = PERF.KPP,
	PERFORMER_BANK = '/Ò '+ISNULL(PERF.ACCOUNT, ' Õ≈ ” ¿«¿Õ –/—!')+ ' ‚ '+ISNULL(PERF.BANK, ' Õ≈ ” ¿«¿Õ ¡¿Õ !') + ' '+ISNULL(PERF.BANK_ADDRESS, ''),
	PERFORMER_BIK = PERF.BIK,
	PERFORMER_OKPO = PERF.OKPO,
	PERIOD_DATE = (SELECT 'c '+CONVERT(VARCHAR(10), MIN(TL_TMP.DATE_SHIP), 104)+' ÔÓ '+CONVERT(VARCHAR(10), MAX(TL_TMP.DATE_SHIP), 104) FROM TRUST_LETTER TL_TMP WHERE (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))),
	STORE_LIST = 
	(
		SELECT 
			REPLACE(REPLACE(SUBSTRING(ItemListWithTags, 4, LEN(ItemListWithTags)-7), '</S>', ', '),'<S>','')
		FROM 
		(
			SELECT 
				CAST(XmlItemList AS NVARCHAR(MAX)) ItemListWithTags
			FROM 
			(
				SELECT 
					(
						SELECT DISTINCT
							ST_TMP.NAME AS S
						FROM STORE ST_TMP
						WHERE ST_TMP.ID_STORE in (select TL_TMP.id_store from TRUST_LETTER TL_TMP WHERE (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104)))
						FOR XML PATH('')
					) AS XmlItemList
			) AS subq1
		) AS subq2
	),
	RECIPE_COUNT = (SELECT COUNT(*) FROM TRUST_LETTER TL_TMP WHERE (TL_TMP.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))),
	ID_CATL = CATL.ID_DISCOUNT2_CAT_LGOT_GLOBAL,
	CATL_NAME = CATL.NAME,
	
	MEMBER_NAME = UPPER(MEM.LASTNAME + ' '+MEM.FIRSTNAME + ' ' + MEM.MIDDLENAME),
	MEMBER_ADDRESS = MEM.ADDRESS,
	MEMBER_BIRTHDAY = CONVERT(VARCHAR(10), MEM.BIRTHDAY, 104),
	RECIPE_DATE = CONVERT(VARCHAR(10), TL.DATE_RECIPE, 104),
	RECIPE_NUM = TL.NUMBER_RECIPE,
	
	ID_GOODS = G.ID_GOODS,
	GOOD_NAME = G.NAME,
	QUANTITY = ROUND(SUM(TLI.QUANTITY * CONVERT(MONEY, SR.NUMERATOR) / SR.DENOMINATOR), 2),
	PRICE_PROD = ROUND(ROUND(L.PRICE_PROD, 2) * SR.DENOMINATOR / CONVERT(MONEY, SR.NUMERATOR), 2),
	PRICE_SUP = ROUND(ROUND(L.PRICE_SUP, 2) * SR.DENOMINATOR / CONVERT(MONEY, SR.NUMERATOR), 2),
	PRICE_SAL = ROUND(ROUND(L.PRICE_SAL, 2) * SR.DENOMINATOR / CONVERT(MONEY, SR.NUMERATOR), 2),
	SUM_PRICE_SAL = SUM(ROUND(L.PRICE_SAL, 2) * TLI.QUANTITY),
	DOCTOR_FIO = CASE WHEN ISNULL(TL.DOCTOR,'')='' THEN ISNULL(DOCTOR.LAST_NAME,'')+' '+ISNULL(DOCTOR.FIRST_NAME,'')+' '+ISNULL(DOCTOR.MIDDLE_NAME,'')+'' ELSE TL.DOCTOR END,
	
	SIGN_DIR_FIO = OFFICE.DIRECTOR_FIO,
	SIGN_BUH_FIO = OFFICE.BUH_FIO,
	ADD_SIGN_BASE = @BASE_SIGN,
	ADD_SIGN_FIO = PERF.DIRECTOR_FIO
FROM
SGAU_REP_UZO_PACK UP
INNER JOIN TRUST_LETTER TL ON (TL.reestr_number = '['+UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10))+'] ' + UP.number_pack + ' ÓÚ '+CONVERT(VARCHAR(10), UP.date_pack, 104))
INNER JOIN TRUST_LETTER_ITEM TLI ON TL.ID_TRUST_LETTER_GLOBAL = TLI.ID_TRUST_LETTER_GLOBAL
INNER JOIN LOT L ON TLI.ID_SOURCE_GLOBAL = L.ID_LOT_GLOBAL
INNER JOIN GOODS G ON L.ID_GOODS = G.ID_GOODS
INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
INNER JOIN CONTRACTOR PERF ON PERF.id_contractor = UP.id_contractor_perform
INNER JOIN DISCOUNT2_CAT_LGOT CATL ON CATL.ID_DISCOUNT2_CAT_LGOT_GLOBAL = TL.ID_DISCOUNT2_CAT_LGOT_GLOBAL
INNER JOIN DISCOUNT2_MEMBER MEM ON MEM.ID_DISCOUNT2_MEMBER_GLOBAL = TL.ID_DISCOUNT2_MEMBER_GLOBAL
LEFT JOIN DISCOUNT2_DOCTOR DOCTOR ON DOCTOR.ID_DOCTOR = TL.ID_DISCOUNT2_DOCTOR
LEFT JOIN CONTRACTOR OFFICE ON OFFICE.ID_CONTRACTOR_GLOBAL IN (select ID_CONTRACTOR_GLOBAL from REPLICATION_CONFIG where GLOBAL_CODE = @OFFICE_GLOBAL_CODE)
WHERE 
	1=1
	AND UP.PREFIX_PACK+'/'+CAST(UP.ID_PACK as VARCHAR(10)) = @ID_PACK
	AND TL.DOCUMENT_STATE='PROC'
GROUP BY 
	UP.PREFIX_PACK, UP.ID_PACK, UP.NUMBER_PACK, UP.DATE_PACK, 
	PERF.FULL_NAME, PERF.NAME, PERF.ADDRESS, PERF.UR_ADDRESS,
	PERF.INN, PERF.KPP, PERF.ACCOUNT, PERF.BANK, PERF.BANK_ADDRESS, PERF.BIK, PERF.OKPO,
	CATL.ID_DISCOUNT2_CAT_LGOT_GLOBAL, CATL.NAME,
	MEM.LASTNAME, MEM.FIRSTNAME, MEM.MIDDLENAME, MEM.ADDRESS, MEM.BIRTHDAY,
	TL.NUMBER_RECIPE, TL.DATE_RECIPE,
	TL.DOCTOR, DOCTOR.LAST_NAME, DOCTOR.FIRST_NAME, DOCTOR.MIDDLE_NAME,
	G.ID_GOODS,	G.NAME,
	L.PRICE_PROD, L.PRICE_SUP, L.PRICE_SAL, SR.DENOMINATOR, SR.NUMERATOR,
	OFFICE.DIRECTOR_FIO, OFFICE.BUH_FIO, PERF.DIRECTOR_FIO
ORDER BY CATL_NAME, ID_CATL, MEMBER_NAME, RECIPE_NUM, GOOD_NAME

RETURN 0
GO

/*
exec REP_UZO_BALANCE_PACK N'<XML>
  <ID_PACK>002/5</ID_PACK>
</XML>'
*/