--------------------------------------------------------------------
IF (OBJECT_ID('[REPEX_DLO_SECTION_PAYER]') IS NULL) EXEC ('CREATE PROCEDURE [REPEX_DLO_SECTION_PAYER] AS RETURN')
GO
ALTER PROCEDURE [dbo].[REPEX_DLO_SECTION_PAYER]
    @XMLPARAM NTEXT
AS
DECLARE @HDOC INT
DECLARE @DATE DATETIME, @ALL_CONTRACTOR BIT, @ALL_STORE BIT, @ALL_PROGRAM BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUT, @XMLPARAM

    SELECT TOP 1 @DATE = [DATE]
    FROM OPENXML(@HDOC, '/XML') WITH([DATE] DATETIME 'DATE')

    SELECT * INTO #CONTRACTOR FROM OPENXML(@HDOC, '//ID_CONTRACTOR') 
    WITH(ID_CONTRACTOR BIGINT '.') WHERE ID_CONTRACTOR <> 0
    IF @@ROWCOUNT = 0 SET @ALL_CONTRACTOR = 1 ELSE SET @ALL_CONTRACTOR = 0

    SELECT * INTO #STORE FROM OPENXML(@HDOC, '//ID_STORE') 
    WITH(ID_STORE BIGINT '.') WHERE ID_STORE <> 0
    IF @@ROWCOUNT = 0 SET @ALL_STORE = 1 ELSE SET @ALL_STORE = 0

    SELECT * INTO #PROGRAM FROM OPENXML(@HDOC, '//ID_TASK_PROGRAM_GLOBAL') 
    WITH(ID_TASK_PROGRAM_GLOBAL UNIQUEIDENTIFIER '.') WHERE ID_TASK_PROGRAM_GLOBAL IS NOT NULL
    IF @@ROWCOUNT = 0 SET @ALL_PROGRAM = 1 ELSE SET @ALL_PROGRAM = 0

EXEC SP_XML_REMOVEDOCUMENT @HDOC

DECLARE @DATE_BEGIN DATETIME
SET @DATE_BEGIN = CAST(CAST(YEAR(@DATE) AS VARCHAR) + '-01-01T00:00:00.000' AS DATETIME)

SELECT ID_CONTRACTOR = I.ID_PAYER,
    JANUARY = SUM(CASE WHEN MONTH(I.[DATE]) = 1 THEN I.SUM_SUP ELSE 0 END),
    FEBRUARY  = SUM(CASE WHEN MONTH(I.[DATE]) = 21 THEN I.SUM_SUP ELSE 0 END),
    MARCH = SUM(CASE WHEN MONTH(I.[DATE]) = 3 THEN I.SUM_SUP ELSE 0 END),
    APRIL = SUM(CASE WHEN MONTH(I.[DATE]) = 4 THEN I.SUM_SUP ELSE 0 END),
    MAY = SUM(CASE WHEN MONTH(I.[DATE]) = 5 THEN I.SUM_SUP ELSE 0 END),
    JUNE = SUM(CASE WHEN MONTH(I.[DATE]) = 6 THEN I.SUM_SUP ELSE 0 END),
    JULY = SUM(CASE WHEN MONTH(I.[DATE]) = 7 THEN I.SUM_SUP ELSE 0 END),
    AUGUST = SUM(CASE WHEN MONTH(I.[DATE]) = 8 THEN I.SUM_SUP ELSE 0 END),
    SEPTEMBER = SUM(CASE WHEN MONTH(I.[DATE]) = 9 THEN I.SUM_SUP ELSE 0 END),
    OCTEBER = SUM(CASE WHEN MONTH(I.[DATE]) = 10 THEN I.SUM_SUP ELSE 0 END),
    NOVEMBER = SUM(CASE WHEN MONTH(I.[DATE]) = 11 THEN I.SUM_SUP ELSE 0 END),
    DECEMBER = SUM(CASE WHEN MONTH(I.[DATE]) = 12 THEN I.SUM_SUP ELSE 0 END)
INTO #INVOICE_OUT
FROM INVOICE_OUT I
WHERE (@ALL_PROGRAM = 1 OR EXISTS(SELECT TOP 1 1 FROM #PROGRAM 
        INNER JOIN CONTRACTS C ON C.ID_TASK_PROGRAM_GLOBAL = #PROGRAM.ID_TASK_PROGRAM_GLOBAL
        WHERE C.ID_CONTRACTS_GLOBAL = I.ID_CONTRACTS_GLOBAL))
    AND (@ALL_STORE = 1 OR EXISTS(SELECT TOP 1 1 FROM #STORE WHERE #STORE.ID_STORE = I.ID_STORE))
    AND (@ALL_CONTRACTOR = 1 OR EXISTS(SELECT TOP 1 1 FROM #CONTRACTOR WHERE #CONTRACTOR.ID_CONTRACTOR = I.ID_PAYER))
    AND I.[DATE] BETWEEN @DATE_BEGIN AND @DATE
GROUP BY I.ID_PAYER

SELECT ID_CONTRACTOR = I.ID_CONTRACTOR_FROM,
    JANUARY = SUM(CASE WHEN MONTH(I.[DATE]) = 1 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    FEBRUARY  = SUM(CASE WHEN MONTH(I.[DATE]) = 21 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    MARCH = SUM(CASE WHEN MONTH(I.[DATE]) = 3 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    APRIL = SUM(CASE WHEN MONTH(I.[DATE]) = 4 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    MAY = SUM(CASE WHEN MONTH(I.[DATE]) = 5 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    JUNE = SUM(CASE WHEN MONTH(I.[DATE]) = 6 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    JULY = SUM(CASE WHEN MONTH(I.[DATE]) = 7 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    AUGUST = SUM(CASE WHEN MONTH(I.[DATE]) = 8 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    SEPTEMBER = SUM(CASE WHEN MONTH(I.[DATE]) = 9 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    OCTEBER = SUM(CASE WHEN MONTH(I.[DATE]) = 10 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    NOVEMBER = SUM(CASE WHEN MONTH(I.[DATE]) = 11 THEN I.TOTAL_SUPPLIER ELSE 0 END),
    DECEMBER = SUM(CASE WHEN MONTH(I.[DATE]) = 12 THEN I.TOTAL_SUPPLIER ELSE 0 END)
INTO #RETURN
FROM ACT_RETURN_TO_BUYER I
WHERE (@ALL_PROGRAM = 1 OR EXISTS(SELECT TOP 1 1 FROM #PROGRAM 
        INNER JOIN CONTRACTS C ON C.ID_TASK_PROGRAM_GLOBAL = #PROGRAM.ID_TASK_PROGRAM_GLOBAL
        WHERE C.ID_CONTRACTS_GLOBAL = I.ID_CONTRACTS_GLOBAL))
    AND (@ALL_STORE = 1 OR EXISTS(SELECT TOP 1 1 FROM #STORE WHERE #STORE.ID_STORE = I.ID_STORE_TO))
    AND (@ALL_CONTRACTOR = 1 OR EXISTS(SELECT TOP 1 1 FROM #CONTRACTOR WHERE #CONTRACTOR.ID_CONTRACTOR = I.ID_CONTRACTOR_FROM))
    AND I.[DATE] BETWEEN @DATE_BEGIN AND @DATE
GROUP BY I.ID_CONTRACTOR_FROM

UPDATE I SET
    I.JANUARY = ISNULL(I.JANUARY, 0) - ISNULL(R.JANUARY, 0),
    I.FEBRUARY = ISNULL(I.FEBRUARY, 0) - ISNULL(R.FEBRUARY, 0),
    I.MARCH = ISNULL(I.MARCH, 0) - ISNULL(R.MARCH, 0),
    I.APRIL = ISNULL(I.APRIL, 0) - ISNULL(R.APRIL, 0),
    I.MAY = ISNULL(I.MAY, 0) - ISNULL(R.MAY, 0),
    I.JUNE = ISNULL(I.JUNE, 0) - ISNULL(R.JUNE, 0),
    I.JULY = ISNULL(I.JULY, 0) - ISNULL(R.JULY, 0),
    I.AUGUST = ISNULL(I.AUGUST, 0) - ISNULL(R.AUGUST, 0),
    I.SEPTEMBER = ISNULL(I.SEPTEMBER, 0) - ISNULL(R.SEPTEMBER, 0),
    I.OCTEBER = ISNULL(I.OCTEBER, 0) - ISNULL(R.OCTEBER, 0),
    I.NOVEMBER = ISNULL(I.NOVEMBER, 0) - ISNULL(R.NOVEMBER, 0),
    I.DECEMBER = ISNULL(I.DECEMBER, 0) - ISNULL(R.DECEMBER, 0)
FROM #INVOICE_OUT I
INNER JOIN #RETURN R ON R.ID_CONTRACTOR = I.ID_CONTRACTOR

SELECT 
    C.A_COD,
    CONTRACTOR_NAME = C.[NAME],
    I.JANUARY,
    I.FEBRUARY,
    I.MARCH,
    I.APRIL,
    I.MAY,
    I.JUNE,
    I.JULY,
    I.AUGUST,
    I.SEPTEMBER,
    I.OCTEBER,
    I.NOVEMBER,
    I.DECEMBER
FROM #INVOICE_OUT I
INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = I.ID_CONTRACTOR

SELECT 
    JANUARY = ISNULL(SUM(JANUARY), 0),
    FEBRUARY = ISNULL(SUM(FEBRUARY), 0),
    MARCH = ISNULL(SUM(MARCH), 0),
    APRIL = ISNULL(SUM(APRIL), 0),
    MAY = ISNULL(SUM(MAY), 0),
    JUNE = ISNULL(SUM(JUNE), 0),
    JULY = ISNULL(SUM(JULY), 0),
    AUGUST = ISNULL(SUM(AUGUST), 0),
    SEPTEMBER = ISNULL(SUM(SEPTEMBER), 0),
    OCTEBER = ISNULL(SUM(OCTEBER), 0),
    NOVEMBER = ISNULL(SUM(NOVEMBER), 0),
    DECEMBER = ISNULL(SUM(DECEMBER), 0)
FROM #RETURN

RETURN 0
GO
--exec REPEX_DLO_SECTION_PAYER
--@xmlParam=N'<XML><DATE_BEGIN>2010-01-01T00:00:00.000</DATE_BEGIN><DATE_1P>2010-07-01T00:00:00.000</DATE_1P><DATE_2P>2010-12-31T00:00:00.000</DATE_2P></XML>'
