SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF (OBJECT_ID('DBO.REPEX_BOOK_SALES_RUM') IS NULL) EXEC ('CREATE PROCEDURE DBO.REPEX_BOOK_SALES_RUM AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_BOOK_SALES_RUM
	@XMLPARAM NTEXT AS

DECLARE @HDOC INT
    
DECLARE	@DATE_FROM DATETIME
DECLARE @DATE_TO DATETIME
DECLARE @SEL_STORE BIT
DECLARE @SEL_CONTRACTOR BIT
DECLARE @WITH_DISCOUNT BIT

DECLARE @CONTRACTORS TABLE(CONTRACTOR_NAME VARCHAR(128))

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUT, @XMLPARAM OUT
SELECT
	@DATE_FROM = DATE_FROM,
	@DATE_TO = DATE_TO,
	@WITH_DISCOUNT = WITH_DISCOUNT
FROM OPENXML(@HDOC, '/XML') WITH(
	DATE_FROM DATETIME 'DATE_FROM',
	DATE_TO DATETIME 'DATE_TO',
	WITH_DISCOUNT BIT 'WITH_DISCOUNT'
)

SELECT ID_CONTRACTOR INTO #CONTRACTORS FROM OPENXML(@HDOC, '/XML/ID_CONTRACTOR') WITH(ID_CONTRACTOR BIGINT '.')

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC USP_RANGE_DAYS @DATE_FROM OUT, @DATE_TO OUT
EXEC USP_RANGE_NORM @DATE_FROM OUT, @DATE_TO OUT

SELECT
	DOC_DATE = CASE WHEN MAX(I.DOC_DATE) IS NULL OR MAX(I.DOC_DATE) = '' THEN MAX(I.DATE) ELSE MAX(I.DOC_DATE) END,
	DOC_NUM = CASE WHEN MAX(I.DOC_NUM) IS NULL OR MAX(I.DOC_NUM) = '' THEN MAX(I.MNEMOCODE) ELSE MAX(I.DOC_NUM) END,
	CONTRACTOR_NAME = MAX(C.NAME),
	INN = MAX(C.INN),
	KPP = MAX(C.KPP),
	DATE_PAYMENT = CASE WHEN MAX(I.DOC_DATE) IS NULL THEN MAX(I.DATE) ELSE MAX(I.DOC_DATE) END,
	SUM_SAL = SUM((CASE WHEN @WITH_DISCOUNT = 1 THEN II.PRICE_SAL ELSE L.PRICE_SAL END) * II.QUANTITY),
	VAT_RATE_18 = SUM(CASE WHEN L.VAT_SAL = 18 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN II.PSUM_SAL ELSE L.PVAT_SAL * II.QUANTITY END ELSE 0 END),
	SUM_VAT_RATE_18 = SUM(CASE WHEN L.VAT_SAL = 18 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN II.SUM_SAL - II.PSUM_SAL ELSE (L.PRICE_SAL - L.PVAT_SAL) * II.QUANTITY END ELSE 0 END),
	VAT_RATE_10 = SUM(CASE WHEN L.VAT_SAL = 10 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN II.PSUM_SAL ELSE L.PVAT_SAL * II.QUANTITY END ELSE 0 END),
	SUM_VAT_RATE_10 = SUM(CASE WHEN L.VAT_SAL = 10 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN II.SUM_SAL - II.PSUM_SAL ELSE (L.PRICE_SAL - L.PVAT_SAL) * II.QUANTITY END ELSE 0 END),
	SUM_VAT_RATE_0 = SUM(CASE WHEN L.VAT_SAL = 0 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN II.SUM_SAL - II.PSUM_SAL ELSE (L.PRICE_SAL - L.PVAT_SAL) * II.QUANTITY END ELSE 0 END)
FROM INVOICE_OUT_ITEM II
	INNER JOIN INVOICE_OUT I ON I.ID_INVOICE_OUT_GLOBAL = II.ID_INVOICE_OUT_GLOBAL
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = I.ID_CONTRACTOR_TO
	LEFT JOIN LOT L ON L.ID_LOT_GLOBAL = II.ID_LOT_GLOBAL
	INNER JOIN STORE S ON S.ID_STORE = I.ID_STORE
	INNER JOIN CONTRACTOR CT ON CT.ID_CONTRACTOR = S.ID_CONTRACTOR
WHERE I.STATE = 'PROC' AND
	CT.ID_CONTRACTOR IN (SELECT ID_CONTRACTOR FROM #CONTRACTORS) AND
	I.DATE BETWEEN @DATE_FROM AND @DATE_TO
GROUP BY I.ID_INVOICE_OUT_GLOBAL
UNION ALL
SELECT
	DOC_DATE = MAX(CS.DATE_CLOSE),
	DOC_NUM = MAX(CR.NAME_CASH_REGISTER) + ' / ÏÐÎÄÀÆÀ',
	CONTRACTOR_NAME = NULL,
	INN = NULL,	
	KPP = NULL,
	DATE_PAYMENT = MAX(CS.DATE_CLOSE),
	SUM_SAL = CASE WHEN @WITH_DISCOUNT = 1 THEN MAX(CS.CASH) ELSE MAX(CS.CASH) + MAX(CS.SUM_DISCOUNT) END,
	VAT_RATE_18 = SUM(CASE WHEN L.VAT_SAL = 18 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM_DISCOUNT WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * CHI.SUMM_DISCOUNT ELSE 0 END ELSE CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * L.PVAT_SAL WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * (CHI.QUANTITY * L.PVAT_SAL) ELSE 0 END END ELSE 0 END),
	SUM_VAT_RATE_18 = SUM(CASE WHEN L.VAT_SAL = 18 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM - CHI.SUMM_DISCOUNT WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * (CHI.SUMM - CHI.SUMM_DISCOUNT) ELSE 0 END ELSE CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * (L.PRICE_SAL - L.PVAT_SAL) WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * CHI.QUANTITY * (L.PRICE_SAL - L.PVAT_SAL) ELSE 0 END END ELSE 0 END),
	VAT_RATE_10 = SUM(CASE WHEN L.VAT_SAL = 10 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM_DISCOUNT WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * CHI.SUMM_DISCOUNT ELSE 0 END ELSE CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * L.PVAT_SAL WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * (CHI.QUANTITY * L.PVAT_SAL) ELSE 0 END END ELSE 0 END),
	SUM_VAT_RATE_10 = SUM(CASE WHEN L.VAT_SAL = 10 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM - CHI.SUMM_DISCOUNT WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * (CHI.SUMM - CHI.SUMM_DISCOUNT) ELSE 0 END ELSE CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * (L.PRICE_SAL - L.PVAT_SAL) WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * CHI.QUANTITY * (L.PRICE_SAL - L.PVAT_SAL) ELSE 0 END END ELSE 0 END),
	SUM_VAT_RATE_0 = SUM(CASE WHEN L.VAT_SAL = 0 THEN CASE WHEN @WITH_DISCOUNT = 1 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM - CHI.SUMM_DISCOUNT WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * (CHI.SUMM - CHI.SUMM_DISCOUNT) ELSE 0 END ELSE CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * (L.PRICE_SAL - L.PVAT_SAL) WHEN CH.CHEQUE_TYPE = 'RETURN' THEN -1 * CHI.QUANTITY * (L.PRICE_SAL - L.PVAT_SAL) ELSE 0 END END ELSE 0 END)
FROM CASH_SESSION CS
	INNER JOIN CASH_REGISTER CR ON CR.ID_CASH_REGISTER = CS.ID_CASH_REGISTER
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = CR.ID_CONTRACTOR
	INNER JOIN CHEQUE CH ON CH.ID_CASH_SESSION_GLOBAL = CS.ID_CASH_SESSION_GLOBAL
	LEFT JOIN CHEQUE_ITEM CHI ON CHI.ID_CHEQUE_GLOBAL = CH.ID_CHEQUE_GLOBAL
	LEFT JOIN LOT L ON CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
WHERE CS.DATE_CLOSE BETWEEN @DATE_FROM AND @DATE_TO AND
	C.ID_CONTRACTOR IN (SELECT ID_CONTRACTOR FROM #CONTRACTORS)
GROUP BY CS.ID_CASH_SESSION_GLOBAL

ORDER BY DOC_DATE

INSERT INTO @CONTRACTORS
SELECT
	CONTRACTOR_NAME = [NAME]
FROM CONTRACTOR
WHERE ID_CONTRACTOR IN (SELECT ID_CONTRACTOR FROM #CONTRACTORS)

DECLARE @CONTRACTOR_STRING VARCHAR(4000)

SELECT
	@CONTRACTOR_STRING = ISNULL(@CONTRACTOR_STRING + ' ,' + C.CONTRACTOR_NAME, C.CONTRACTOR_NAME)
FROM @CONTRACTORS C
SELECT CONTRACTOR_NAME = @CONTRACTOR_STRING

RETURN
GO

/*
EXEC REPEX_BOOK_SALES_RUM N'
<XML>
	<DATE_FROM>2009-03-11T11:34:02.348</DATE_FROM>
	<DATE_TO>2009-03-11T11:34:02.348</DATE_TO>
	<ID_CONTRACTOR>5271</ID_CONTRACTOR>
	<WITH_DISCOUNT>1</WITH_DISCOUNT>
</XML>'*/

