SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_PAYMENT_VAT') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_PAYMENT_VAT AS RETURN')
GO
ALTER  PROCEDURE DBO.REPEX_PAYMENT_VAT
	@XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @ID_PAYMENT_ORDER BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT

SELECT @ID_PAYMENT_ORDER = ID_PAYMENT_ORDER	FROM OPENXML(@HDOC, '/XML') WITH(ID_PAYMENT_ORDER BIGINT 'ID_PAYMENT_ORDER')

EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	MNEMOCODE = RIGHT(P.MNEMOCODE, 5),
	P.[DATE],
	TYPE_P = P.PAYMENT_TYPE,
	PVAT_SUM = P.SUM_VAT,
	VAT_SUM = P.PVAT_SUM,
	VAT = CAST(P.PVAT_SUM / P.SUM_VAT * 100 AS INT),
	C.INN,
	C.KPP,
	NAME_ADD = ISNULL(NULLIF(LTRIM(C.FULL_NAME), ''), C.[NAME]),
	C.ACCOUNT,
	NAME_BANK = C.BANK + ' ' + C.BANK_ADDRESS,
	C.BIK,
	C.CORR_ACCOUNT,
	NAME_BANK_P = C_P.BANK + ' ' + C_P.BANK_ADDRESS,
	BIK_P = C_P.BIK,
	CORR_ACCOUNT_P = C_P.CORR_ACCOUNT,
	INN_P = C_P.INN,
	KPP_P = C_P.KPP,
	ACCOUNT_P = C_P.ACCOUNT,
	NAME_ADD_P = ISNULL(NULLIF(LTRIM(C_P.[FULL_NAME]), ''), C_P.[NAME]),
	TYPE_OP = '01',
	P.PAYMENT_PERIOD,
	P.PAYMENT_QUEUE,
	P.PAYMENT_ASSINGMENT
FROM PAYMENT_ORDER P
	LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = P.ID_PAYER
	LEFT JOIN CONTRACTOR C_P ON C_P.ID_CONTRACTOR = P.ID_RECIPIENT
WHERE P.ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER

RETURN 0
GO

--exec REPEX_PAYMENT_VAT N'<XML><ID_PAYMENT_ORDER>50</ID_PAYMENT_ORDER></XML>'