SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('[REPEX_MOVEMENT_SHEET_ACCEPTANCE_GOODS]') IS NULL EXEC('CREATE PROCEDURE [REPEX_MOVEMENT_SHEET_ACCEPTANCE_GOODS] AS RETURN')
GO
ALTER PROCEDURE REPEX_MOVEMENT_SHEET_ACCEPTANCE_GOODS
	(@XMLPARAM NTEXT) AS
	
DECLARE @HDOC INT
DECLARE @ID_MOVEMENT BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_MOVEMENT = ID_MOVEMENT
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_MOVEMENT BIGINT 'ID_MOVEMENT')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

-- ШАПКА И СПИСОК ТОВАРОВ В ПРИХОДНОЙ НАКЛОДНОЙ
SELECT
    ITEM.ID_MOVEMENT_ITEM_GLOBAL,
    
    -- НОМЕР ПРИХОДНОЙ НАКЛОДНОЙ
    M.MNEMOCODE,
    -- ДАТА ПРИХОДНОЙ НАКЛАДНОЙ
    INV0ICE_DATE = CONVERT(VARCHAR, M.[DATE], 104),
    -- ВХОДЯЩИЙ ДОКУМЕНТ
    INCOMING_NUMBER = '' /* COALESCE(M.INCOMING_NUMBER, '')+
        COALESCE(' от '+CONVERT(VARCHAR, M.INCOMING_DATE, 104), '') */,
    -- ПОСТАВЩИК 
    SUPPLIER_NAME = case 
                      when CNR_SUP.[FULL_NAME] is null then CNR_SUP.[NAME]
                      else CNR_SUP.[FULL_NAME]
                      end,
    -- ПОКУПАТЕЛЬ
    CUSTOMER_NAME = (SELECT TOP 1 case 
                                   when C.[FULL_NAME] is null then C.[NAME]
                                   else C.[FULL_NAME]
                                   end FROM DBO.MOVEMENT M
        INNER JOIN DBO.STORE S ON S.ID_STORE = M.ID_STORE_TO 
        INNER JOIN DBO.CONTRACTOR C ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
        WHERE M.ID_MOVEMENT = @ID_MOVEMENT),
    --КОД товара
    CODE = G.CODE,
    --Наименование
    GOODS = G.[NAME] + ' [' + PROD.NAME + ', ' + CNR.NAME + ']',
    --Срок годности
    BEST_BEFORE = ISNULL(CONVERT(VARCHAR,SER.BEST_BEFORE,104),''),
    --Срок годности скорректированный
    BEST_BEFORE_CORRECT = NULL,
    --Серия
    SERIES_NUMBER = ISNULL(SER.SERIES_NUMBER,''),
    --№ короба
    BOX = L_FROM.BOX,
    --внутренний штрих код
    INTERNAL_BARCODE = L.INTERNAL_BARCODE,
    --количество по документу 
    QUANTITY = CAST(ROUND(ITEM.QUANTITY, 0) AS VARCHAR),
	--фактическое количество 
	QUANTITY_FACT = NULL,
	--Место хранения  данные из справочника номенклатуры
	STORE_PLACE = SP.DESCRIPTION
    --select * from GOODS
FROM DBO.MOVEMENT M
  LEFT JOIN STORE S_SUP ON M.ID_STORE_FROM = S_SUP.ID_STORE
  INNER JOIN DBO.CONTRACTOR CNR_SUP ON CNR_SUP.ID_CONTRACTOR = S_SUP.ID_CONTRACTOR
  INNER JOIN DBO.MOVEMENT_ITEM ITEM ON ITEM.ID_MOVEMENT = M.ID_MOVEMENT
  INNER JOIN DBO.GOODS G ON G.ID_GOODS = ITEM.ID_GOODS
  INNER JOIN DBO.PRODUCER PROD ON G.ID_PRODUCER = PROD.ID_PRODUCER
  INNER JOIN DBO.COUNTRY CNR ON PROD.ID_COUNTRY = CNR.ID_COUNTRY
  INNER JOIN LOT L ON L.ID_DOCUMENT_ITEM = ITEM.ID_MOVEMENT_ITEM_GLOBAL
  LEFT JOIN LOT L_FROM ON L_FROM.ID_LOT = ITEM.ID_LOT_FROM
  LEFT JOIN DBO.SERIES SER ON L_FROM.ID_SERIES = SER.ID_SERIES 
  LEFT JOIN STORE_PLACE SP ON G.ID_STORE_PLACE = SP.ID_STORE_PLACE
WHERE (M.ID_MOVEMENT = @ID_MOVEMENT)
ORDER BY GOODS


SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO
FROM CONTRACTOR
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)


RETURN 0
GO


--exec REPEX_MOVEMENT_SHEET_ACCEPTANCE_GOODS N'<XML><ID_MOVEMENT>1958</ID_MOVEMENT></XML>'
--select newid()
--select * from INVOICE_ITEM