SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_CASH') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_CASH AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_CASH
    @XMLPARAM NTEXT
AS

DECLARE @ALL_CASHIER BIT
DECLARE @ALL_KKM BIT
DECLARE @ALL_PRODUCER BIT
DECLARE @ALL_CONTRACTOR BIT
DECLARE @ALL_GOODS BIT

DECLARE @HDOC INT

DECLARE @DATE_FR DATETIME
DECLARE @DATE_TO DATETIME
DECLARE @DETAIL BIT


EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT

SELECT
	@DATE_FR = DATE_FR,
	@DATE_TO = DATE_TO,
	@DETAIL = DETAIL
FROM OPENXML(@HDOC, '/XML') WITH(
	DATE_FR DATETIME 'DATE_FR',
	DATE_TO DATETIME 'DATE_TO',
	DETAIL BIT 'DETAIL'
)

SELECT * INTO #CASHIER FROM OPENXML(@HDOC, '//CASHIER') WITH(ID_CASHIER BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_CASHIER = 1 ELSE SET @ALL_CASHIER = 0

SELECT * INTO #KKM FROM OPENXML(@HDOC, '//KKM') WITH(ID_KKM BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_KKM = 1 ELSE SET @ALL_KKM = 0

SELECT * INTO #PRODUCER FROM OPENXML(@HDOC, '//PRODUCER') WITH(ID_PRODUCER BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_PRODUCER = 1 ELSE SET @ALL_PRODUCER = 0

SELECT * INTO #CONTRACTOR FROM OPENXML(@HDOC, '//CONTRACTOR') WITH(ID_CONTRACTOR BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_CONTRACTOR = 1 ELSE SET @ALL_CONTRACTOR = 0

SELECT * INTO #GOODS FROM OPENXML(@HDOC, '//GOODS') WITH(ID_GOODS BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_GOODS = 1 ELSE SET @ALL_GOODS = 0

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC DBO.USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT
EXEC DBO.REP_RANGEDAY @DATE_FR OUT, @DATE_TO OUT

SELECT
	CASHIER = S.CASHIER,
	CASHIER_NAME = S.CASHIER_NAME,
	CASH_REGISTER = S.CASH_REGISTER,
	CASH_REGISTER_NAME = S.NAME_CASH_REGISTER,

	COUNT_CHEQUE_SAL = S.COUNT_CHEQUE_SAL,
	QUANTITY_SAL = S.QUANTITY_SAL,
	SUM_SUP_SAL = S.SUM_SUP_SAL,
	SUM_RET_SAL = S.SUM_RET_SAL,
	SUM_DIS_SAL = S.SUM_DIS_SAL,
	SUM_RETDIS_SAL = S.SUM_RETDIS_SAL,

	COUNT_CHEQUE_RET = ISNULL(R.COUNT_CHEQUE_RET, 0),
	QUANTITY_RET = ISNULL(R.QUANTITY_RET, 0),
	SUM_SUP_RET = ISNULL(R.SUM_SUP_RET, 0),
	SUM_RET_RET = ISNULL(R.SUM_RET_RET, 0),
	SUM_DIS_RET = ISNULL(R.SUM_DIS_RET, 0),
	SUM_RETDIS_RET = ISNULL(R.SUM_RETDIS_RET, 0),
	DATE_OP = S.DATE_OP
	INTO #TMP_TABLE
FROM
(
SELECT	
	CASHIER = CH.ID_USER_DATA,
	CASHIER_NAME = U.FULL_NAME,
	CASH_REGISTER = CR.ID_CASH_REGISTER,
	NAME_CASH_REGISTER = CR.NAME_CASH_REGISTER,
	COUNT_CHEQUE_SAL = COUNT(DISTINCT(CONVERT(CHAR(36), CH.ID_CHEQUE_GLOBAL))),
	QUANTITY_SAL = SUM(CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END),
	SUM_SUP_SAL = SUM(CHI.QUANTITY * L.PRICE_SUP),
	SUM_RET_SAL = SUM(CHI.QUANTITY * CHI.PRICE),
	SUM_DIS_SAL = SUM(CHI.SUMM_DISCOUNT),
	SUM_RETDIS_SAL = SUM(CHI.SUMM),
	DATE_OP = CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
FROM CASH_SESSION CS
	INNER JOIN CHEQUE CH ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
	LEFT JOIN [META_USER] U ON CH.ID_USER_DATA = U.USER_NUM
	INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	INNER JOIN CHEQUE_ITEM CHI ON CH.ID_CHEQUE_GLOBAL = CHI.ID_CHEQUE_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON CHI.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	INNER JOIN LOT L ON CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = L.ID_SUPPLIER
	LEFT JOIN GOODS G ON CHI.ID_GOODS = G.ID_GOODS
	LEFT JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER	
WHERE CH.CHEQUE_TYPE IN ('SALE') AND CH.DOCUMENT_STATE = 'PROC'
	AND CH.DATE_CHEQUE BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_CASHIER = 1 OR CH.ID_USER_DATA IN (SELECT * FROM #CASHIER))
	AND (@ALL_KKM = 1 OR CS.ID_CASH_REGISTER IN (SELECT * FROM #KKM))
	AND (@ALL_PRODUCER = 1 OR (P.ID_PRODUCER IS NULL OR P.ID_PRODUCER IN (SELECT * FROM #PRODUCER)))
	AND (@ALL_CONTRACTOR = 1 OR (C.ID_CONTRACTOR IS NULL OR C.ID_CONTRACTOR IN (SELECT * FROM #CONTRACTOR)))
	AND (@ALL_GOODS = 1 OR (G.ID_GOODS IS NULL OR G.ID_GOODS IN (SELECT * FROM #GOODS)))
GROUP BY CH.ID_USER_DATA, U.FULL_NAME, CR.ID_CASH_REGISTER, CR.NAME_CASH_REGISTER, CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
) AS S

LEFT JOIN

(
SELECT	
	CASHIER = CH.ID_USER_DATA,
	CASHIER_NAME = U.FULL_NAME,
	CASH_REGISTER = CR.ID_CASH_REGISTER,
	NAME_CASH_REGISTER = CR.NAME_CASH_REGISTER,
	COUNT_CHEQUE_RET = COUNT(DISTINCT(CONVERT(CHAR(36), CH.ID_CHEQUE_GLOBAL))),
	QUANTITY_RET = SUM(CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END),
	SUM_SUP_RET = SUM(CHI.QUANTITY * L.PRICE_SUP),
	SUM_RET_RET = SUM(CHI.QUANTITY * CHI.PRICE),
	SUM_DIS_RET = SUM(CHI.SUMM_DISCOUNT),
	SUM_RETDIS_RET = SUM(CHI.SUMM),
	DATE_OP = CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
	
FROM CASH_SESSION CS
	INNER JOIN CHEQUE CH ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
	LEFT JOIN [META_USER] U ON CH.ID_USER_DATA = U.USER_NUM
	INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	INNER JOIN CHEQUE_ITEM CHI ON CH.ID_CHEQUE_GLOBAL = CHI.ID_CHEQUE_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON CHI.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	INNER JOIN LOT L ON CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = L.ID_SUPPLIER
	LEFT JOIN GOODS G ON CHI.ID_GOODS = G.ID_GOODS
	LEFT JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
WHERE CH.CHEQUE_TYPE IN ('RETURN') AND CH.DOCUMENT_STATE = 'PROC'
	AND CH.DATE_CHEQUE BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_CASHIER = 1 OR CH.ID_USER_DATA IN (SELECT * FROM #CASHIER))
	AND (@ALL_KKM = 1 OR CS.ID_CASH_REGISTER IN (SELECT * FROM #KKM))
	AND (@ALL_PRODUCER = 1 OR (P.ID_PRODUCER IS NULL OR P.ID_PRODUCER IN (SELECT * FROM #PRODUCER)))
	AND (@ALL_CONTRACTOR = 1 OR (C.ID_CONTRACTOR IS NULL OR C.ID_CONTRACTOR IN (SELECT * FROM #CONTRACTOR)))
	AND (@ALL_GOODS = 1 OR (G.ID_GOODS IS NULL OR G.ID_GOODS IN (SELECT * FROM #GOODS)))
GROUP BY CH.ID_USER_DATA, U.FULL_NAME, CR.ID_CASH_REGISTER, CR.NAME_CASH_REGISTER, CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
) AS R ON S.DATE_OP = R.DATE_OP AND S.CASHIER = R.CASHIER AND S.CASH_REGISTER = R.CASH_REGISTER
ORDER BY S.CASHIER_NAME, S.NAME_CASH_REGISTER, S.DATE_OP

CREATE TABLE #TMP_TABLE2(
			ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
			CASHIER BIGINT,
			CASHIER_NAME VARCHAR(150),
			CASH_REGISTER BIGINT,
			CASH_REGISTER_NAME VARCHAR(150),

			COUNT_CHEQUE_SAL MONEY, 
			COUNT_CHEQUE_SAL_TOTAL_BY_CASHIER MONEY,
			QUANTITY_SAL MONEY, 
			SUM_SUP_SAL MONEY,
			SUM_RET_SAL MONEY,  
			SUM_DIS_SAL MONEY, 
			SUM_RETDIS_SAL MONEY,

			COUNT_CHEQUE_RET MONEY,
			COUNT_CHEQUE_RET_TOTAL_BY_CASHIER MONEY,
			QUANTITY_RET MONEY,
			SUM_SUP_RET MONEY,
			SUM_RET_RET MONEY,
			SUM_DIS_RET MONEY,
			SUM_RETDIS_RET MONEY,
			GOODS_NAME VARCHAR(500),
			DATE_OP DATETIME,
			G_CODE VARCHAR(150)
    )
INSERT INTO #TMP_TABLE2
SELECT		
	CASHIER = CH.ID_USER_DATA,
	CASHIER_NAME = U.FULL_NAME,
	CASH_REGISTER = CR.ID_CASH_REGISTER,
	CASH_REGISTER_NAME = CR.NAME_CASH_REGISTER,

	COUNT_CHEQUE_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN 1 ELSE 0 END),
	COUNT_CHEQUE_SAL_TOTAL_BY_CASHIER = 0,
	QUANTITY_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END ELSE 0 END),
	SUM_SUP_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * L.PRICE_SUP ELSE 0 END),
	SUM_RET_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * CHI.PRICE ELSE 0 END),
	SUM_DIS_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM_DISCOUNT ELSE 0 END),
	SUM_RETDIS_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM ELSE 0 END),

	COUNT_CHEQUE_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN 1 ELSE 0 END),
	COUNT_CHEQUE_RET_TOTAL_BY_CASHIER = 0,
	QUANTITY_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END ELSE 0 END),
	SUM_SUP_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CHI.QUANTITY * L.PRICE_SUP ELSE 0 END),
	SUM_RET_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CHI.QUANTITY * CHI.PRICE ELSE 0 END),
	SUM_DIS_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CHI.SUMM_DISCOUNT ELSE 0 END),
	SUM_RETDIS_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CHI.SUMM ELSE 0 END),

	GOODS_NAME = MAX('“Ó‚‡: ' + G.[NAME] + '; »«√Œ“Œ¬»“≈À‹: ' + ISNULL(P.[NAME], '') + '; œŒ—“¿¬Ÿ» : ' + ISNULL(C.[NAME], '')),
	DATE_OP = CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME),
	G_CODE = max(G.CODE)
	
FROM CASH_SESSION CS
	INNER JOIN CHEQUE CH ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
	LEFT JOIN [META_USER] U ON CH.ID_USER_DATA = U.USER_NUM
	INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	INNER JOIN CHEQUE_ITEM CHI ON CH.ID_CHEQUE_GLOBAL = CHI.ID_CHEQUE_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON CHI.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	INNER JOIN LOT L ON CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = L.ID_SUPPLIER
	INNER JOIN GOODS G ON CHI.ID_GOODS = G.ID_GOODS
	INNER JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
WHERE CH.CHEQUE_TYPE IN ('SALE', 'RETURN') AND CH.DOCUMENT_STATE = 'PROC'
	AND CH.DATE_CHEQUE BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_CASHIER = 1 OR CH.ID_USER_DATA IN (SELECT * FROM #CASHIER))
	AND (@ALL_KKM = 1 OR CS.ID_CASH_REGISTER IN (SELECT * FROM #KKM))
	AND (@ALL_PRODUCER = 1 OR (P.ID_PRODUCER IS NULL OR P.ID_PRODUCER IN (SELECT * FROM #PRODUCER)))
	AND (@ALL_CONTRACTOR = 1 OR (C.ID_CONTRACTOR IS NULL OR C.ID_CONTRACTOR IN (SELECT * FROM #CONTRACTOR)))
	AND (@ALL_GOODS = 1 OR (G.ID_GOODS IS NULL OR G.ID_GOODS IN (SELECT * FROM #GOODS)))
GROUP BY CH.ID_USER_DATA, U.FULL_NAME, CR.ID_CASH_REGISTER, CR.NAME_CASH_REGISTER,
 		G.ID_GOODS_GLOBAL, G.NAME,
		CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
ORDER BY G.NAME

select TOP 0 * from #TMP_TABLE

    DECLARE C CURSOR FOR
    SELECT 
        CASHIER, CASH_REGISTER, DATE_OP, COUNT_CHEQUE_SAL, COUNT_CHEQUE_RET
    FROM #TMP_TABLE TT
    DECLARE @CASHIER BIGINT
    DECLARE @CASH_REGISTER BIGINT
    DECLARE @DATE_OP DATETIME
    DECLARE @COUNT_CHEQUE_SAL MONEY
    DECLARE @COUNT_CHEQUE_RET MONEY
    DECLARE @ID BIGINT
    OPEN C 
    WHILE 1=1 BEGIN
        FETCH NEXT FROM C INTO @CASHIER, @CASH_REGISTER, @DATE_OP, @COUNT_CHEQUE_SAL, @COUNT_CHEQUE_RET
        IF (@@FETCH_STATUS<>0) BREAK
        SELECT TOP 1 @ID = ID from #TMP_TABLE2 WHERE CASHIER=@CASHIER AND CASH_REGISTER=@CASH_REGISTER AND DATE_OP=@DATE_OP
       -- SELECT @ID
       
        UPDATE #TMP_TABLE2 SET
            COUNT_CHEQUE_SAL_TOTAL_BY_CASHIER = @COUNT_CHEQUE_SAL,
            COUNT_CHEQUE_RET_TOTAL_BY_CASHIER = @COUNT_CHEQUE_RET
        WHERE #TMP_TABLE2.ID = @ID
       
    END
    CLOSE C
    DEALLOCATE C
    
SELECT 
	I=1
	,TT2.*
	,COUNT_CHEQUE_SAL_TOTAL = TT.COUNT_CHEQUE_SAL	
	,QUANTITY_SAL_TOTAL = TT.QUANTITY_SAL
	,SUM_SUP_SAL_TOTAL = TT.SUM_SUP_SAL
	,SUM_RET_SAL_TOTAL = TT.SUM_RET_SAL
	,SUM_DIS_SAL_TOTAL = TT.SUM_DIS_SAL
	,SUM_RETDIS_SAL_TOTAL = TT.SUM_RETDIS_SAL

	,COUNT_CHEQUE_RET_TOTAL = TT.COUNT_CHEQUE_RET
	,QUANTITY_RET_TOTAL = TT.QUANTITY_RET
	,SUM_SUP_RET_TOTAL = TT.SUM_SUP_RET
	,SUM_RET_RET_TOTAL = TT.SUM_RET_RET
	,SUM_DIS_RET_TOTAL = TT.SUM_DIS_RET
	,SUM_RETDIS_RET_TOTAL = TT.SUM_RETDIS_RET
	,TM.COUNT_SESSION
FROM #TMP_TABLE TT
LEFT JOIN #TMP_TABLE2 TT2 ON TT.CASHIER = TT2.CASHIER AND TT.CASH_REGISTER = TT2.CASH_REGISTER AND TT.DATE_OP = TT2.DATE_OP 
LEFT JOIN (    
				SELECT 
					CASHIER, COUNT_SESSION = COUNT(CASHIER)
				FROM #TMP_TABLE
				GROUP BY CASHIER
		 ) TM ON TM.CASHIER = TT.CASHIER
ORDER BY TT2.CASHIER_NAME, TT2.CASH_REGISTER, TT2.DATE_OP

select PERIOD_DAYS = (
						select count(distinct convert(char(8), date_close, 112)) as PERIOD_DAYS
						from cash_session 
						where date_close between @date_fr and @date_to),
       CASH_SESSION_COUNT = (
							select count(*)
							from #TMP_TABLE 
							)
RETURN 0
GO

/*
EXEC REPEX_CASH N'
<XML>
	<DATE_FR>2009-09-01T00:00:00.000</DATE_FR>
	<DATE_TO>2009-09-09T00:00:00.000</DATE_TO>
	<DETAIL>0</DETAIL>
</XML>'*/

SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_CASH_SERVICE') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_CASH_SERVICE AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_CASH_SERVICE
    @XMLPARAM NTEXT
AS

DECLARE @ALL_CASHIER BIT
DECLARE @ALL_KKM BIT
DECLARE @ALL_PRODUCER BIT
DECLARE @ALL_CONTRACTOR BIT
DECLARE @ALL_GOODS BIT

DECLARE @HDOC INT

DECLARE @DATE_FR DATETIME
DECLARE @DATE_TO DATETIME
DECLARE @DETAIL BIT


EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT

SELECT
	@DATE_FR = DATE_FR,
	@DATE_TO = DATE_TO,
	@DETAIL = DETAIL
FROM OPENXML(@HDOC, '/XML') WITH(
	DATE_FR DATETIME 'DATE_FR',
	DATE_TO DATETIME 'DATE_TO',
	DETAIL BIT 'DETAIL'
)

SELECT * INTO #CASHIER FROM OPENXML(@HDOC, '//CASHIER') WITH(ID_CASHIER BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_CASHIER = 1 ELSE SET @ALL_CASHIER = 0

SELECT * INTO #KKM FROM OPENXML(@HDOC, '//KKM') WITH(ID_KKM BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_KKM = 1 ELSE SET @ALL_KKM = 0

SELECT * INTO #PRODUCER FROM OPENXML(@HDOC, '//PRODUCER') WITH(ID_PRODUCER BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_PRODUCER = 1 ELSE SET @ALL_PRODUCER = 0

SELECT * INTO #CONTRACTOR FROM OPENXML(@HDOC, '//CONTRACTOR') WITH(ID_CONTRACTOR BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_CONTRACTOR = 1 ELSE SET @ALL_CONTRACTOR = 0

SELECT * INTO #GOODS FROM OPENXML(@HDOC, '//GOODS') WITH(ID_GOODS BIGINT '.')
IF @@ROWCOUNT = 0 SET @ALL_GOODS = 1 ELSE SET @ALL_GOODS = 0

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC DBO.USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT
EXEC DBO.REP_RANGEDAY @DATE_FR OUT, @DATE_TO OUT

SELECT
	CASHIER = S.CASHIER,
	CASHIER_NAME = S.CASHIER_NAME,
	CASH_REGISTER = S.CASH_REGISTER,
	CASH_REGISTER_NAME = S.NAME_CASH_REGISTER,

	COUNT_CHEQUE_SAL = S.COUNT_CHEQUE_SAL,
	QUANTITY_SAL = S.QUANTITY_SAL,
	SUM_SUP_SAL = S.SUM_SUP_SAL,
	SUM_RET_SAL = S.SUM_RET_SAL,
	SUM_DIS_SAL = S.SUM_DIS_SAL,
	SUM_RETDIS_SAL = S.SUM_RETDIS_SAL,

	COUNT_CHEQUE_RET = ISNULL(R.COUNT_CHEQUE_RET, 0),
	QUANTITY_RET = ISNULL(R.QUANTITY_RET, 0),
	SUM_SUP_RET = ISNULL(R.SUM_SUP_RET, 0),
	SUM_RET_RET = ISNULL(R.SUM_RET_RET, 0),
	SUM_DIS_RET = ISNULL(R.SUM_DIS_RET, 0),
	SUM_RETDIS_RET = ISNULL(R.SUM_RETDIS_RET, 0),
	DATE_OP = S.DATE_OP
	INTO #TMP_TABLE
	
FROM
(
SELECT	
	CASHIER = CH.ID_USER_DATA,
	CASHIER_NAME = U.FULL_NAME,
	CASH_REGISTER = CR.ID_CASH_REGISTER,
	NAME_CASH_REGISTER = CR.NAME_CASH_REGISTER,
	COUNT_CHEQUE_SAL = COUNT(DISTINCT(CONVERT(CHAR(36), CH.ID_CHEQUE_GLOBAL))),
	QUANTITY_SAL = SUM(CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END),
	SUM_SUP_SAL = SUM(CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.QUANTITY * L.PRICE_SUP END),
	SUM_RET_SAL = SUM(CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN CHI.SUMM ELSE CHI.QUANTITY * CHI.PRICE END),
	SUM_DIS_SAL = SUM(CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.SUMM_DISCOUNT END),
	SUM_RETDIS_SAL = SUM(CHI.SUMM),
	DATE_OP = CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
FROM CASH_SESSION CS
	INNER JOIN CHEQUE CH ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
	LEFT JOIN [META_USER] U ON CH.ID_USER_DATA = U.USER_NUM
	INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	INNER JOIN CHEQUE_ITEM CHI ON CH.ID_CHEQUE_GLOBAL = CHI.ID_CHEQUE_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON CHI.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	LEFT JOIN LOT L ON CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = L.ID_SUPPLIER
	LEFT JOIN GOODS G ON CHI.ID_GOODS = G.ID_GOODS
	LEFT JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER	
WHERE CH.CHEQUE_TYPE IN ('SALE') AND CH.DOCUMENT_STATE = 'PROC'
	AND CH.DATE_CHEQUE BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_CASHIER = 1 OR CH.ID_USER_DATA IN (SELECT * FROM #CASHIER))
	AND (@ALL_KKM = 1 OR CS.ID_CASH_REGISTER IN (SELECT * FROM #KKM))
	AND (@ALL_PRODUCER = 1 OR (P.ID_PRODUCER IS NULL OR P.ID_PRODUCER IN (SELECT * FROM #PRODUCER)))
	AND (@ALL_CONTRACTOR = 1 OR (C.ID_CONTRACTOR IS NULL OR C.ID_CONTRACTOR IN (SELECT * FROM #CONTRACTOR)))
	AND (@ALL_GOODS = 1 OR (G.ID_GOODS IS NULL OR G.ID_GOODS IN (SELECT * FROM #GOODS)))
GROUP BY CH.ID_USER_DATA, U.FULL_NAME, CR.ID_CASH_REGISTER, CR.NAME_CASH_REGISTER, CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
) AS S

LEFT JOIN

(
SELECT	
	CASHIER = CH.ID_USER_DATA,
	CASHIER_NAME = U.FULL_NAME,
	CASH_REGISTER = CR.ID_CASH_REGISTER,
	NAME_CASH_REGISTER = CR.NAME_CASH_REGISTER,
	COUNT_CHEQUE_RET = COUNT(DISTINCT(CONVERT(CHAR(36), CH.ID_CHEQUE_GLOBAL))),
	QUANTITY_RET = SUM(CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END),
	SUM_SUP_RET = SUM(CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.QUANTITY * L.PRICE_SUP END),
	SUM_RET_RET = SUM(CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN CHI.SUMM ELSE CHI.QUANTITY * CHI.PRICE END),
	SUM_DIS_RET = SUM(CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.SUMM_DISCOUNT END),
	SUM_RETDIS_RET = SUM(CHI.SUMM),
	DATE_OP = CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
FROM CASH_SESSION CS
	INNER JOIN CHEQUE CH ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
	LEFT JOIN [META_USER] U ON CH.ID_USER_DATA = U.USER_NUM
	INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	INNER JOIN CHEQUE_ITEM CHI ON CH.ID_CHEQUE_GLOBAL = CHI.ID_CHEQUE_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON CHI.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	LEFT JOIN LOT L ON CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = L.ID_SUPPLIER
	LEFT JOIN GOODS G ON CHI.ID_GOODS = G.ID_GOODS
	LEFT JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
WHERE CH.CHEQUE_TYPE IN ('RETURN') AND CH.DOCUMENT_STATE = 'PROC'
	AND CH.DATE_CHEQUE BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_CASHIER = 1 OR CH.ID_USER_DATA IN (SELECT * FROM #CASHIER))
	AND (@ALL_KKM = 1 OR CS.ID_CASH_REGISTER IN (SELECT * FROM #KKM))
	AND (@ALL_PRODUCER = 1 OR (P.ID_PRODUCER IS NULL OR P.ID_PRODUCER IN (SELECT * FROM #PRODUCER)))
	AND (@ALL_CONTRACTOR = 1 OR (C.ID_CONTRACTOR IS NULL OR C.ID_CONTRACTOR IN (SELECT * FROM #CONTRACTOR)))
	AND (@ALL_GOODS = 1 OR (G.ID_GOODS IS NULL OR G.ID_GOODS IN (SELECT * FROM #GOODS)))
GROUP BY CH.ID_USER_DATA, U.FULL_NAME, CR.ID_CASH_REGISTER, CR.NAME_CASH_REGISTER, CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)
) AS R ON S.DATE_OP = R.DATE_OP AND S.CASHIER = R.CASHIER AND S.CASH_REGISTER = R.CASH_REGISTER
ORDER BY S.CASHIER_NAME, S.NAME_CASH_REGISTER, S.DATE_OP

CREATE TABLE #TMP_TABLE2(
			ID BIGINT NOT NULL IDENTITY PRIMARY KEY,
			CASHIER BIGINT,
			CASHIER_NAME VARCHAR(150),
			CASH_REGISTER BIGINT,
			CASH_REGISTER_NAME VARCHAR(150),

			COUNT_CHEQUE_SAL MONEY, 
			COUNT_CHEQUE_SAL_TOTAL_BY_CASHIER MONEY,
			QUANTITY_SAL MONEY, 
			SUM_SUP_SAL MONEY,
			SUM_RET_SAL MONEY,  
			SUM_DIS_SAL MONEY, 
			SUM_RETDIS_SAL MONEY,

			COUNT_CHEQUE_RET MONEY,
			COUNT_CHEQUE_RET_TOTAL_BY_CASHIER MONEY,
			QUANTITY_RET MONEY,
			SUM_SUP_RET MONEY,
			SUM_RET_RET MONEY,
			SUM_DIS_RET MONEY,
			SUM_RETDIS_RET MONEY,
			GOODS_NAME VARCHAR(500),
			DATE_OP DATETIME,
			G_CODE VARCHAR(150)
    )

insert INTO #TMP_TABLE2
SELECT		
	
	CASHIER = CH.ID_USER_DATA,
	CASHIER_NAME = U.FULL_NAME,
	CASH_REGISTER = CR.ID_CASH_REGISTER,
	CASH_REGISTER_NAME = CR.NAME_CASH_REGISTER,

	COUNT_CHEQUE_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN 1 ELSE 0 END),
	COUNT_CHEQUE_SAL_TOTAL_BY_CASHIER = 0,
	QUANTITY_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END ELSE 0 END),
	SUM_SUP_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.QUANTITY * L.PRICE_SUP END ELSE 0 END),
	SUM_RET_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN CHI.SUMM ELSE CHI.QUANTITY * CHI.PRICE END ELSE 0 END),
	SUM_DIS_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.SUMM_DISCOUNT END ELSE 0 END),
	SUM_RETDIS_SAL = SUM(CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN CHI.SUMM ELSE 0 END),

	COUNT_CHEQUE_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN 1 ELSE 0 END),
	COUNT_CHEQUE_RET_TOTAL_BY_CASHIER = 0,
	QUANTITY_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CHI.QUANTITY * CASE WHEN SR.ID_SCALING_RATIO IS NULL THEN 1 ELSE CONVERT(MONEY, SR.NUMERATOR) / CONVERT(MONEY,SR.DENOMINATOR) END ELSE 0 END),
	SUM_SUP_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.QUANTITY * L.PRICE_SUP END ELSE 0 END),
	SUM_RET_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN CHI.SUMM ELSE CHI.QUANTITY * CHI.PRICE END ELSE 0 END),
	SUM_DIS_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CASE WHEN L.ID_LOT_GLOBAL IS NULL THEN 0 ELSE CHI.SUMM_DISCOUNT END ELSE 0 END),
	SUM_RETDIS_RET = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CHI.SUMM ELSE 0 END),

	GOODS_NAME = MAX(CASE WHEN L.ID_LOT_GLOBAL IS NULL 
					THEN '”ÒÎÛ„‡: ' + S4S.NAME
					ELSE '“Ó‚‡: ' + G.[NAME] + '; »«√Œ“Œ¬»“≈À‹: ' + ISNULL(P.[NAME], '') + '; œŒ—“¿¬Ÿ» : ' + ISNULL(C.[NAME], '')
				END),	
	DATE_OP = CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME),
	G_CODE = max(G.CODE)
	
FROM CASH_SESSION CS
	INNER JOIN CHEQUE CH ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
	LEFT JOIN [META_USER] U ON CH.ID_USER_DATA = U.USER_NUM
	INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	INNER JOIN CHEQUE_ITEM CHI ON CH.ID_CHEQUE_GLOBAL = CHI.ID_CHEQUE_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON CHI.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	LEFT JOIN LOT L ON CHI.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = L.ID_SUPPLIER
	LEFT JOIN GOODS G ON CHI.ID_GOODS = G.ID_GOODS
	LEFT JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
	LEFT JOIN SERVICE_4_SALE S4S ON S4S.ID_SERVICE_4_SALE = CHI.ID_LOT_GLOBAL
	
WHERE CH.CHEQUE_TYPE IN ('SALE', 'RETURN') AND CH.DOCUMENT_STATE = 'PROC'
	AND CH.DATE_CHEQUE BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_CASHIER = 1 OR CH.ID_USER_DATA IN (SELECT * FROM #CASHIER))
	AND (@ALL_KKM = 1 OR CS.ID_CASH_REGISTER IN (SELECT * FROM #KKM))
	AND (@ALL_PRODUCER = 1 OR (P.ID_PRODUCER IS NULL OR P.ID_PRODUCER IN (SELECT * FROM #PRODUCER)))
	AND (@ALL_CONTRACTOR = 1 OR (C.ID_CONTRACTOR IS NULL OR C.ID_CONTRACTOR IN (SELECT * FROM #CONTRACTOR)))
	AND (@ALL_GOODS = 1 OR (G.ID_GOODS IS NULL OR G.ID_GOODS IN (SELECT * FROM #GOODS)))
GROUP BY CH.ID_USER_DATA, U.FULL_NAME, CR.ID_CASH_REGISTER, CR.NAME_CASH_REGISTER,
 		CASE WHEN L.ID_LOT_GLOBAL IS NULL 
			THEN S4S.ID_SERVICE_4_SALE
			ELSE G.ID_GOODS_GLOBAL
		END,
		CAST(CONVERT(VARCHAR(8), CH.DATE_CHEQUE, 112) AS DATETIME)


select TOP 0 * from #TMP_TABLE


    
    DECLARE C CURSOR FOR
    SELECT 
        CASHIER, CASH_REGISTER, DATE_OP, COUNT_CHEQUE_SAL, COUNT_CHEQUE_RET
    FROM #TMP_TABLE TT
    DECLARE @CASHIER BIGINT
    DECLARE @CASH_REGISTER BIGINT
    DECLARE @DATE_OP DATETIME
    DECLARE @COUNT_CHEQUE_SAL MONEY
    DECLARE @COUNT_CHEQUE_RET MONEY
    DECLARE @ID BIGINT
    OPEN C 
    WHILE 1=1 BEGIN
        FETCH NEXT FROM C INTO @CASHIER, @CASH_REGISTER, @DATE_OP, @COUNT_CHEQUE_SAL, @COUNT_CHEQUE_RET
        IF (@@FETCH_STATUS<>0) BREAK
        SELECT TOP 1 @ID = ID from #TMP_TABLE2 WHERE CASHIER=@CASHIER AND CASH_REGISTER=@CASH_REGISTER AND DATE_OP=@DATE_OP
       -- SELECT @ID
       
        UPDATE #TMP_TABLE2 SET
            COUNT_CHEQUE_SAL_TOTAL_BY_CASHIER = @COUNT_CHEQUE_SAL,
            COUNT_CHEQUE_RET_TOTAL_BY_CASHIER = @COUNT_CHEQUE_RET
        WHERE #TMP_TABLE2.ID = @ID
       
    END
    CLOSE C
    DEALLOCATE C


SELECT
	I=1
	,TT2.*
	,COUNT_CHEQUE_SAL_TOTAL = TT.COUNT_CHEQUE_SAL	
	,QUANTITY_SAL_TOTAL = TT.QUANTITY_SAL
	,SUM_SUP_SAL_TOTAL = TT.SUM_SUP_SAL
	,SUM_RET_SAL_TOTAL = TT.SUM_RET_SAL
	,SUM_DIS_SAL_TOTAL = TT.SUM_DIS_SAL
	,SUM_RETDIS_SAL_TOTAL = TT.SUM_RETDIS_SAL

	,COUNT_CHEQUE_RET_TOTAL = TT.COUNT_CHEQUE_RET
	,QUANTITY_RET_TOTAL = TT.QUANTITY_RET
	,SUM_SUP_RET_TOTAL = TT.SUM_SUP_RET
	,SUM_RET_RET_TOTAL = TT.SUM_RET_RET
	,SUM_DIS_RET_TOTAL = TT.SUM_DIS_RET
	,SUM_RETDIS_RET_TOTAL = TT.SUM_RETDIS_RET
,TM.COUNT_SESSION
	
FROM #TMP_TABLE TT
LEFT JOIN #TMP_TABLE2 TT2 ON TT.CASHIER = TT2.CASHIER AND TT.CASH_REGISTER = TT2.CASH_REGISTER AND TT.DATE_OP = TT2.DATE_OP 
LEFT JOIN (    
				SELECT 
					CASHIER, COUNT_SESSION = COUNT(CASHIER)
				FROM #TMP_TABLE
				GROUP BY CASHIER
		 ) TM ON TM.CASHIER = TT.CASHIER
ORDER BY TT2.CASHIER_NAME, TT2.CASH_REGISTER, TT2.DATE_OP

select PERIOD_DAYS = (
						select count(distinct convert(char(8), date_close, 112)) as PERIOD_DAYS
						from cash_session 
						where date_close between @date_fr and @date_to),
       CASH_SESSION_COUNT = (
							select count(*)
							from #TMP_TABLE 
							)

				
RETURN 0
GO
/*
EXEC REPEX_CASH_SERVICE N'
<XML>
	<DATE_FR>2010-11-01T00:00:00.000</DATE_FR>
	<DATE_TO>2010-11-19T00:00:00.000</DATE_TO>
	<DETAIL>0</DETAIL>
</XML>'
*/
/*
EXEC REPEX_CASH N'<XML><DATE_FR>2012-01-11T10:28:44.882</DATE_FR><DATE_TO>2012-01-24T10:28:44.882</DATE_TO><DETAIL>0</DETAIL></XML>'
*/