rem call $(SolutionDir)post_build.bat $(SolutionDir)

call %1\copyPr.bat %1 70_1_CRF
call %1\copyPr.bat %1 71_List
call %1\copyPr.bat %1 AnalizeAction
call %1\copyPr.bat %1 BookSale
call %1\copyPr.bat %1 ContractMov
call %1\copyPr.bat %1 ExpensiveLS
call %1\copyPr.bat %1 FinanceProgram
call %1\copyPr.bat %1 GoodsStock
call %1\copyPr.bat %1 InfoLS
call %1\copyPr.bat %1 InfoSecuringLS
call %1\copyPr.bat %1 InvoiceInformNovgD
call %1\copyPr.bat %1 ReestrCountInvoice
call %1\copyPr.bat %1 101_InvoiceLS
call %1\copyPr.bat %1 102_InvoiceLS
call %1\copyPr.bat %1 103_InvoiceLS
call %1\copyPr.bat %1 73_Stock
call %1\copyPr.bat %1 74_Info
call %1\copyPr.bat %1 75_Measure
call %1\copyPr.bat %1 76_InvoiceLS
call %1\copyPr.bat %1 RCS03InvoiceInformNovgD19
call %1\copyPr.bat %1 Shipping
call %1\copyPr.bat %1 InvoiceOut
call %1\copyPr.bat %1 InvoiceOutGoods
call %1\copyPr.bat %1 InvoiceOutMnn
call %1\copyPr.bat %1 37_InfoMonitoring
call %1\copyPr.bat %1 ReestrPayNoLS
call %1\copyPr.bat %1 PartSupplier
call %1\copyPr.bat %1 InfoContracts