SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_KM3') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_KM3 AS RETURN')
GO
ALTER  PROCEDURE DBO.REPEX_KM3
 @XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT @ID_GLOBAL = ID_GLOBAL FROM OPENXML(@HDOC, '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	C.[NAME] AS contractor_name,
	C.ADDRESS AS ADDRESS,
	C.PHONE AS PHONE,
	C.INN AS INN,
	CR.MODEL AS MODEL,
	CR.TYPE AS TYPE,
	CR.NUMBER_CASH_REGISTER AS NUMBER_CASH_REGISTER,
	CR.PRODUCER_NUMBER AS PRODUCER_NUMBER,
	US.[NAME] AS US_NAME,
	CH.ID_CHEQUE AS NUMBER_DOC,
	CH.DATE_CHEQUE AS DATE_DOC
FROM CHEQUE CH
	INNER JOIN CASH_SESSION CS ON CH.ID_CASH_SESSION_GLOBAL = CS.ID_CASH_SESSION_GLOBAL
	INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	INNER JOIN CONTRACTOR C ON CR.ID_CONTRACTOR = C.ID_CONTRACTOR
	LEFT JOIN [USER] US ON CH.ID_USER_DATA = US.ID_USER
WHERE CH.ID_CHEQUE_GLOBAL = @ID_GLOBAL AND CH.CHEQUE_TYPE = 'RETURN'


SELECT 
 S.[NAME],
 CH.ID_CHEQUE AS NUMBER_CHEQUE,
 SUM(CI.SUMM) AS SUMM,
 US.FULL_NAME AS US_NAMEFULL
FROM CHEQUE CH
	INNER JOIN CHEQUE_ITEM CI ON CI.ID_CHEQUE_GLOBAL = CH.ID_CHEQUE_GLOBAL
	LEFT JOIN LOT L ON L.ID_LOT_GLOBAL = CI.ID_LOT_GLOBAL
	LEFT JOIN STORE S ON S.ID_STORE = L.ID_STORE
	LEFT JOIN [USER] US ON CH.ID_USER_DATA = US.ID_USER
WHERE CH.ID_CHEQUE_GLOBAL = @ID_GLOBAL AND CH.CHEQUE_TYPE = 'RETURN'
GROUP BY S.[NAME], CH.ID_CHEQUE, US.FULL_NAME

RETURN 0
GO

--EXEC REPEX_KM3 N'<XML><ID_GLOBAL>E466662D-59E6-4DF1-8954-ECA9FD14EB8C</ID_GLOBAL></XML>'