SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF (OBJECT_ID('DBO.REPEX_INVOICE_GOODS_DEFECT') IS NULL) EXEC ('CREATE PROCEDURE DBO.REPEX_INVOICE_GOODS_DEFECT AS RETURN')
GO
ALTER  PROCEDURE DBO.REPEX_INVOICE_GOODS_DEFECT
    @XMLPARAM NTEXT AS
    
DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

DECLARE @MNAME INT
DECLARE @MSER INT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUT, @XMLPARAM OUT

SELECT @ID_GLOBAL = ID_INVOICE_GLOBAL FROM OPENXML(@HDOC, '/XML/INVOICE') WITH(
	ID_INVOICE_GLOBAL UNIQUEIDENTIFIER 'ID_INVOICE_GLOBAL')

--select @ID_GLOBAL

SELECT
	@MNAME = MNAME, 
	@MSER = MSER
FROM OPENXML(@HDOC, '/XML/DEFECT_SETTINGS/SETTINGS') WITH(
	MNAME INT 'LENGTH_DRUGTXT',
	MSER INT 'LENGTH_SERIES'
)

--SELECT @MNAME, @MSER

EXEC SP_XML_REMOVEDOCUMENT @HDOC

declare @join_filter nvarchar(255)
set @join_filter = CASE WHEN @MNAME = 0 THEN '' ELSE 'LEFT(g.NAME, ' + CAST(@MNAME AS VARCHAR) + ') = LEFT(GD.DRUG_TXT, ' + CAST(@MNAME AS VARCHAR) +') AND ' END + CASE WHEN @MSER = 0 THEN 'ser.SERIES_NUMBER = GD.SERIES_NR' ELSE 'LEFT(ser.SERIES_NUMBER, ' + CAST(@MSER AS VARCHAR) + ') = LEFT(GD.SERIES_NR, ' + CAST(@MSER AS VARCHAR) + ')' END
--select @join_filter

DECLARE @QUERY NVARCHAR(4000)

set @QUERY = '
SELECT
	ID_INVOICE_GLOBAL = II.ID_INVOICE_GLOBAL,
	MNEMOCODE = I.MNEMOCODE,
	INCOMING_NUMBER = I.INCOMING_NUMBER,
	SUPPLIER = SUP.NAME,
	DOCUMENT_DATE = I.DOCUMENT_DATE,
	GOODS_NAME = G.NAME,
	SERIES_NUMBER = SER.SERIES_NUMBER,
	BEST_BEFORE = SER.BEST_BEFORE,
	DRUG_TXT = GD.DRUG_TXT,
	SERIES_NR = GD.SERIES_NR,
	LAB_NM = LAB_NM, 
	LETTER_DATE = LETTER_DATE,
	SPEC_NM = SPEC_NM
FROM INVOICE_ITEM II
	INNER JOIN INVOICE I ON I.ID_INVOICE_GLOBAL = II.ID_INVOICE_GLOBAL	
	INNER JOIN CONTRACTOR SUP ON SUP.ID_CONTRACTOR = I.ID_CONTRACTOR_SUPPLIER
	INNER JOIN GOODS G ON G.ID_GOODS = II.ID_GOODS
	INNER JOIN SERIES SER ON SER.ID_SERIES = II.ID_SERIES
	INNER JOIN GOODS_DEFECT GD ON ' + @join_filter + ' WHERE II.ID_INVOICE_GLOBAL = ''' + CAST(@ID_GLOBAL AS VARCHAR(36)) + ''''

--select @QUERY

exec sp_executesql @query

RETURN 0
GO

/*
exec DBO.REPEX_INVOICE_GOODS_DEFECT '
<XML>
	<INVOICE>
		<ID_INVOICE_GLOBAL>7437F7B3-A10B-4A44-AFE9-4E240A09D7EF</ID_INVOICE_GLOBAL>
	</INVOICE>
<DEFECT_SETTINGS>
	<IS_ACTIVE>1</IS_ACTIVE>
	<SETTINGS>
		<ID_STORE>152</ID_STORE>
		<LENGTH_DRUGTXT>0</LENGTH_DRUGTXT>
		<LENGTH_SERIES>4</LENGTH_SERIES>
		<DATA_SERVICEABLE>Нет</DATA_SERVICEABLE>
		<CHECKREMAINS>Нет</CHECKREMAINS>
	</SETTINGS>
</DEFECT_SETTINGS>
</XML>'*/