SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INVOICE_OUT_TORG_13') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INVOICE_OUT_TORG_13 AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INVOICE_OUT_TORG_13
	(@XMLPARAM NTEXT) AS 
		
DECLARE	@HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
		
SELECT TOP 1 @ID_GLOBAL = ID_GLOBAL
FROM OPENXML(@HDOC , '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC 

SELECT
	DOC_NUM = IT.MNEMOCODE,
	DOC_DATE = IT.DATE,
	NAME_FR = C_FR.NAME,
	NAME_TO = C_TO.NAME	
FROM INVOICE_OUT IT
	INNER JOIN STORE S_FR ON S_FR.ID_STORE = IT.ID_STORE
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S_FR.ID_CONTRACTOR
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = IT.ID_CONTRACTOR_TO
	--INNER JOIN STORE S_TO ON S_TO.ID_STORE = IT.ID_STORE_TO_MAIN
WHERE ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

DECLARE @USE_VAT BIT
SELECT @USE_VAT = C_FR.USE_VAT
FROM INVOICE_OUT IT
	INNER JOIN STORE S_FR ON S_FR.ID_STORE = IT.ID_STORE
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S_FR.ID_CONTRACTOR
WHERE ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

SELECT
	GOODS_NAME = G.NAME,
	GOODS_CODE = G.CODE,
	UNIT_NAME = CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	OKEI_CODE = U.OKEI_CODE,
	QUANTITY = II.QUANTITY,
	PRICE_SUP = CASE WHEN @USE_VAT <> 1 THEN L.PRICE_SUP ELSE L.PRICE_SUP - L.PVAT_SUP END,
	SUM_SUP = CAST(CASE WHEN @USE_VAT <> 1 THEN L.PRICE_SUP * II.QUANTITY ELSE L.PRICE_SUP * II.QUANTITY / (100. + L.VAT_SUP) * 100. END AS MONEY),
	PRICE_PROD = L.PRICE_PROD,
	SUM_PROD = II.QUANTITY * L.PRICE_PROD
	--select *
FROM INVOICE_OUT_ITEM II
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = II.ID_LOT_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON L.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	INNER JOIN UNIT AS U ON U.ID_UNIT = SR.ID_UNIT
WHERE II.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL
ORDER BY G.NAME

RETURN 0
GO
/*
exec REPEX_INVOICE_OUT_TORG_13 N'<XML><ID_GLOBAL>F9345D0A-BA92-4036-AA09-E0BE44C84E83</ID_GLOBAL></XML>'
*/
