SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_AP_20') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_AP_20 AS RETURN')
GO

ALTER PROCEDURE DBO.REPEX_AP_20
    @XMLPARAM NTEXT AS
    
DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUT, @XMLPARAM    

SELECT @ID_GLOBAL = ID_GLOBAL FROM OPENXML(@HDOC , '/XML')
WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	AD_COMPANY = ct.name,
	AD_STORE = s.NAME,
	AD_NUMBER = AD.MNEMOCODE,
	AD_DATE = AD.[DATE]	
FROM ACT_DEDUCTION AD
	inner join store s on s.id_store = ad.id_store
	inner join contractor ct on ct.id_contractor = s.id_contractor
WHERE AD.ID_ACT_DEDUCTION_GLOBAL = @ID_GLOBAL

SELECT 
	GOODS_NAME = G.NAME, 
	SER = CASE WHEN ISNULL(S.SERIES_NUMBER, '') = '' THEN '' ELSE 'סונ. ' + S.SERIES_NUMBER  + ', ' END +
			CASE WHEN ISNULL(RC.NAME, '') = '' THEN '' ELSE 'סונע. ' + RC.NAME END +
			CASE WHEN RC.[DATE] IS NULL THEN '' ELSE ' מע ' + CONVERT(VARCHAR, RC.[DATE], 104) END +
			CASE WHEN ISNULL(RC.ORGAN, '') = '' THEN '' ELSE ', גûהאם ' + RC.ORGAN END +
			CASE WHEN S.BEST_BEFORE IS NULL THEN '' ELSE ', דמהום המ ' + CONVERT(VARCHAR, S.BEST_BEFORE, 104) END,
	UNIT_NAME = cast(sr.numerator as varchar) + '/' + cast(sr.denominator as varchar) + ' ' + u.short_name,
	QUANTITY = ADI.QUANTITY,
	PRICE_SAL = ADI.PRICE_ACC,
	SUM_SAL = ADI.SUM_ACC,
	PRICE_SUP = ADI.PRICE_SUP,
	SUM_SUP = ADI.PRICE_SUP * ADI.QUANTITY,
	INCOMING_NUM = L.INCOMING_NUM,
	INCOMING_DATE = L.INCOMING_DATE,
	SUPPLIER = cnt.NAME,
	SERIES = S.SERIES_NUMBER,
	BEST_BEFORE = S.BEST_BEFORE
FROM ACT_DEDUCTION_ITEM ADI
	INNER JOIN GOODS G ON G.ID_GOODS = ADI.ID_GOODS
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = ADI.ID_LOT_GLOBAL
	LEFT JOIN SERIES S ON S.ID_SERIES = L.ID_SERIES
	LEFT JOIN REG_CERT RC ON RC.ID_REG_CERT_GLOBAL = L.ID_REG_CERT_GLOBAL 
	inner join scaling_ratio sr on sr.id_scaling_ratio = l.id_scaling_ratio
	inner join unit u on u.id_unit = sr.id_unit
	inner join contractor cnt on cnt.id_contractor = l.id_supplier
WHERE ADI.ID_ACT_DEDUCTION_GLOBAL = @ID_GLOBAL
ORDER BY GOODS_NAME

RETURN 0
GO

--exec repex_ap_20 N'<XML><ID_GLOBAL>C9506858-AA00-47E5-BE9A-A64C8DD42CF5</ID_GLOBAL></XML>'