SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INVOICE_OUT_PROTOCOL_ZNVLS') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INVOICE_OUT_PROTOCOL_ZNVLS AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INVOICE_OUT_PROTOCOL_ZNVLS
    @XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER
DECLARE @ZNVLS BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT @ID_GLOBAL = ID_GLOBAL FROM OPENXML(@HDOC, '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')
SELECT @ZNVLS = ZNVLS FROM OPENXML(@HDOC, '/XML') WITH(ZNVLS BIT 'ZNVLS')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	FR_NAME = CASE WHEN ISNULL(C_FR.FULL_NAME, '') = '' THEN C_FR.NAME ELSE C_FR.FULL_NAME END,
	TO_NAME = CASE WHEN ISNULL(C_TO.FULL_NAME, '') = '' THEN C_TO.NAME ELSE C_TO.FULL_NAME END,
	DOC_NUM = I.DOC_NUM,
	DOC_DATE = CONVERT(VARCHAR, I.DOC_DATE, 104)
FROM INVOICE_OUT I
	INNER JOIN STORE S ON I.ID_STORE = S.ID_STORE
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = I.ID_CONTRACTOR_TO
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S.ID_CONTRACTOR
WHERE I.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

SELECT
	GOODS_NAME = G.NAME, 
	SERIES_NAME = S.SERIES_NUMBER,
	PRODUCER_NAME = P.NAME,
	REGISTER_PRICE = L.REGISTER_PRICE,
	--6
	--7
	PRICE_PROD = L.PRICE_PROD,
	SUP_ADPRICE = L.ADPRICE_SUP,
	SUM_ADPRICE = L.PRICE_PROD * L.ADPRICE_SUP / (100 + L.PRICE_PROD),
	PRICE_SUP = L.PRICE_SAL - L.PVAT_SAL
FROM INVOICE_OUT_ITEM II
	LEFT JOIN LOT L ON L.ID_LOT_GLOBAL = II.ID_LOT_GLOBAL
	LEFT JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
	LEFT JOIN SERIES S ON S.ID_SERIES = L.ID_SERIES	
WHERE II.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL AND 
	((@ZNVLS = 0) OR (G.IMPORTANT = @ZNVLS AND @ZNVLS = 1))
ORDER BY G.NAME

RETURN 0
GO

--exec DBO.REPEX_INVOICE_OUT_PROTOCOL_ZNVLS N'<XML><ID_GLOBAL>59367F51-CCB4-4F01-87CE-566DFD4A3BD5</ID_GLOBAL><ZNVLS>0</ZNVLS></XML>'