SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF (OBJECT_ID('DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE') IS NULL) EXEC ('CREATE PROCEDURE DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE
	@XMLPARAM NTEXT AS
		
DECLARE	@HDOC INT
DECLARE	@ID_GLOBAL UNIQUEIDENTIFIER
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT , @XMLPARAM OUTPUT
SELECT @ID_GLOBAL = ID_GLOBAL FROM OPENXML(@HDOC , '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
    [INVOICE_OUT_NAME] = A.MNEMOCODE,
    [INVOICE_OUT_DATE] = A.DATE,
    [CONTRACTOR_FROM_NAME] = C_FR.LEGAL_PERS + ' (' + C_FR.LEGAL_PERS_SHORT + ')',
    [CONTRACTOR_FROM_ADDRESS] = C_FR.UR_ADDRESS,
    [CONTRACTOR_FROM_INN] = C_FR.INN + ' / ' + C_FR.KPP,
    GCONTRACTOR = C_FR.NAME + ', ' + C_FR.ADDRESS,
    GCONTRACTOR_TO_NAME = CASE WHEN ISNULL(C_TO.FULL_NAME, '') = '' THEN C_TO.NAME ELSE C_TO.FULL_NAME END + ', ' + C_TO.ADDRESS,
    [CONTRACTOR_TO_NAME] = CASE WHEN ISNULL(C_TO.FULL_NAME, '') = '' THEN C_TO.NAME ELSE C_TO.FULL_NAME END,
    [CONTRACTOR_TO_ADDRESS] = C_TO.UR_ADDRESS,
    [CONTRACTOR_TO_INN] = C_TO.INN +' / '+ C_TO.KPP
FROM ACT_RETURN_TO_CONTRACTOR A
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = A.ID_CONTRACTOR_FROM
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = A.ID_CONTRACTOR_TO
WHERE A.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = @ID_GLOBAL

SELECT
    [GOODS_NAME] = G.NAME,
    [UNIT_NAME] = U.SHORT_NAME,
    [QUANTITY] = AI.QUANTITY,
    [PRICE_SAL] = L.PRICE_SUP - L.PVAT_SUP,
    [SUM_SAL_WITHOUT_VAT] = (L.PRICE_SUP - L.PVAT_SUP) * AI.QUANTITY,
    [VAT_SAL] = case when L.VAT_SUP = 0 then 'Без НДС' else CAST(l.vat_sup as varchar) + ' %' end, --ISNULL(CONVERT(VARCHAR, NULLIF(L.VAT_SUP, 0))+'%', 'Без НДС'),
    [PSUM_SAL] = L.PVAT_SUP * AI.QUANTITY,
    [SUM_SAL] = L.PRICE_SUP * AI.QUANTITY,
    [COUNTRY] = C.NAME,
	GTD_NUMBER = CASE WHEN CT.NAME <> 'россия' THEN L.GTD_NUMBER ELSE '' END
FROM ACT_RETURN_TO_CONTRACTOR_ITEM AI
	LEFT JOIN LOT L ON L.ID_LOT_GLOBAL = AI.ID_LOT_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
	INNER JOIN COUNTRY C ON C.ID_COUNTRY = P.ID_COUNTRY
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
	INNER JOIN PRODUCER PR ON PR.ID_PRODUCER = G.ID_PRODUCER
	INNER JOIN COUNTRY CT ON CT.ID_COUNTRY = PR.ID_COUNTRY
WHERE AI.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = @ID_GLOBAL

SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO
FROM CONTRACTOR
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)

RETURN
GO

--EXEC DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE N'<XML><ID_GLOBAL>AC1B8D5E-CBB0-4AFC-8E9C-D123BCAC2F85</ID_GLOBAL></XML>'