SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_UNSATISFIED_DEMAND') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_UNSATISFIED_DEMAND AS RETURN')
GO
ALTER  PROCEDURE DBO.REPEX_UNSATISFIED_DEMAND
    @XMLPARAM NTEXT AS
    
DECLARE @HDOC INT
DECLARE @DATE_FR DATETIME
DECLARE @DATE_TO DATETIME

DECLARE @ALL_USER BIT
DECLARE @ALL_CONTRACTOR BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUT, @XMLPARAM

SELECT
	@DATE_FR = DATE_FR,
	@DATE_TO = DATE_TO	
FROM OPENXML(@HDOC, '/XML') WITH(
	DATE_FR DATETIME 'DATE_FR',
	DATE_TO DATETIME 'DATE_TO'
)

SELECT * INTO #ID_STORES FROM OPENXML(@HDOC, '/XML/ID_USERS') WITH(ID_USER UNIQUEIDENTIFIER '.')
IF (@@ROWCOUNT = 0)	SET @ALL_USER = 1

SELECT * INTO #ID_CONTRACTORS FROM OPENXML(@HDOC, '/XML/ID_CONTRACTORS') WITH(ID_CONTRACTOR UNIQUEIDENTIFIER '.')
IF (@@ROWCOUNT = 0)	SET @ALL_CONTRACTOR = 1

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC USP_RANGE_DAYS @DATE_FR OUT, @DATE_TO OUT
EXEC USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT

SELECT 
	AU = CASE WHEN C.FULL_NAME IS NULL OR C.FULL_NAME = '' THEN C.NAME
		ELSE C.FULL_NAME
		END,  
	ID, 
	CANCEL_DATE = [DATE], 
	GOODS_NAME, 
	GOODS_CODE,
	PRODUCER_NAME, 
	QUANTITY, 
	PRICE, 
	BUY_FREQUENCY = CASE ISNULL(UD.BUY_FREQUENCY, 0)
		WHEN 0 THEN 'Не задано'
		WHEN 1 THEN 'Еженедельно'
		WHEN 2 THEN 'Раз в месяц'
		WHEN 3 THEN 'Раз в квартал'
		WHEN 4 THEN 'Раз в полгода'
		WHEN 5 THEN 'Раз в год'
		ELSE 'Не задано'
		END, 
	EMPLOYEE = MU.FULL_NAME
FROM UNSATISFIED_DEMAND UD
INNER JOIN META_USER MU WITH(NOLOCK) ON MU.ID_USER = UD.ID_USER_GLOBAL
INNER JOIN CONTRACTOR C WITH(NOLOCK) ON UD.ID_CONTRACTOR_GLOBAL = C.ID_CONTRACTOR_GLOBAL
WHERE 
	UD.[DATE] BETWEEN @DATE_FR AND @DATE_TO
	AND (@ALL_CONTRACTOR = 1 OR UD.ID_CONTRACTOR_GLOBAL IN (SELECT ID_CONTRACTOR FROM #ID_CONTRACTORS))
	AND (@ALL_USER = 1 OR UD.ID_USER_GLOBAL IN (SELECT ID_USER FROM #ID_STORES))
ORDER BY AU

RETURN 
GO