SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF (OBJECT_ID('DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE') IS NULL) EXEC ('CREATE PROCEDURE DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE
	@XMLPARAM NTEXT AS
		
DECLARE	@HDOC INT
DECLARE	@ID_GLOBAL UNIQUEIDENTIFIER
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT , @XMLPARAM OUTPUT
SELECT @ID_GLOBAL = ID_GLOBAL FROM OPENXML(@HDOC , '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
    [INVOICE_OUT_NAME] = A.MNEMOCODE,
    [INVOICE_OUT_DATE] = A.DATE,
    [CONTRACTOR_FROM_NAME] =ISNULL(C_FR.FULL_NAME,'') + ISNULL(' (' + C_FR.NAME + ')',''),-- C_FR.LEGAL_PERS + ' (' + C_FR.LEGAL_PERS_SHORT + ')',--??select * from contractor
    [CONTRACTOR_FROM_ADDRESS] = C_FR.[ADDRESS],--C_FR.UR_ADDRESS,
    [CONTRACTOR_FROM_INN] = ISNULL(C_FR.INN,'') + ' / ' + ISNULL(C_FR.KPP,''),
    GCONTRACTOR = C_FR.NAME + ', ' + C_FR.ADDRESS,
    GCONTRACTOR_TO_NAME = CASE WHEN ISNULL(C_TO.FULL_NAME, '') = '' THEN C_TO.NAME ELSE C_TO.FULL_NAME END + ISNULL(', ' + C_TO.ADDRESS,''),
    [CONTRACTOR_TO_NAME] = CASE WHEN ISNULL(C_TO.FULL_NAME, '') = '' THEN C_TO.NAME ELSE C_TO.FULL_NAME END,
    [CONTRACTOR_TO_ADDRESS] = ISNULL(C_TO.[ADDRESS],''),--C_TO.UR_ADDRESS,
    [CONTRACTOR_TO_INN] = ISNULL(C_TO.INN,'') +' / '+ ISNULL(C_TO.KPP,'')
FROM ACT_RETURN_TO_CONTRACTOR A
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = A.ID_CONTRACTOR_FROM
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = A.ID_CONTRACTOR_TO
WHERE A.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = @ID_GLOBAL

SELECT
    [GOODS_NAME] = G.NAME,
    [UNIT_NAME] = U.SHORT_NAME,
    [UNIT_OKEI_CODE] = U.OKEI_CODE,
    [QUANTITY] = AI.QUANTITY,
    [PRICE_SAL] = L.PRICE_SUP - L.PVAT_SUP,
    [SUM_SAL_WITHOUT_VAT] = (L.PRICE_SUP - L.PVAT_SUP) * AI.QUANTITY,
    [VAT_SAL] = case when L.VAT_SUP = 0 then 'Без НДС' else CAST(l.vat_sup as varchar) + ' %' end, --ISNULL(CONVERT(VARCHAR, NULLIF(L.VAT_SUP, 0))+'%', 'Без НДС'),
    [PSUM_SAL] = L.PVAT_SUP * AI.QUANTITY,
    [SUM_SAL] = L.PRICE_SUP * AI.QUANTITY,
    [COUNTRY] = C.NAME,
	[COUNTRY_SHORT] = CASE WHEN C.NAME = 'Россия' THEN NULL ELSE C.MNEMOCODE END ,
	[COUNTRY_CODE] = CASE WHEN C.NAME = 'Россия' THEN NULL ELSE C.COD_CODE END,
	GTD_NUMBER = CASE WHEN CT.NAME <> 'россия' THEN L.GTD_NUMBER ELSE '' END
	--select * 
FROM ACT_RETURN_TO_CONTRACTOR_ITEM AI
	LEFT JOIN LOT L ON L.ID_LOT_GLOBAL = AI.ID_LOT_GLOBAL
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
	INNER JOIN COUNTRY C ON C.ID_COUNTRY = P.ID_COUNTRY
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
	INNER JOIN PRODUCER PR ON PR.ID_PRODUCER = G.ID_PRODUCER
	INNER JOIN COUNTRY CT ON CT.ID_COUNTRY = PR.ID_COUNTRY
WHERE AI.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = @ID_GLOBAL

SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO
FROM CONTRACTOR
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)

RETURN
GO

--EXEC DBO.REPEX_ACT_RETURN_TO_CONTRACTOR_INVOICE N'<XML><ID_GLOBAL>810E2B00-F682-4FF6-89D8-EA3245C096AB</ID_GLOBAL></XML>'




SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO 

IF OBJECT_ID('DBO.REMOVE_REPORT_BY_TYPE_NAME') IS NULL EXEC('CREATE PROCEDURE DBO.REMOVE_REPORT_BY_TYPE_NAME AS RETURN')
GO
ALTER PROCEDURE DBO.REMOVE_REPORT_BY_TYPE_NAME 
	@REPORT_TYPE_NAME VARCHAR(200) AS
	
DECLARE @id_meta_report BIGINT

	select 
		@id_meta_report = id_meta_report
	from meta_report
	where type_name = @REPORT_TYPE_NAME
	--select @id_meta_report
		
	DECLARE @SQL NVARCHAR(200)
	SET @SQL = N'delete from META_REPORT_2_REPORT_GROUPS
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('META_REPORT_2_REPORT_GROUPS') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_csv_export
		where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_csv_export') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_visible
		where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_visible') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report
		

	SET @SQL = N'delete from meta_report_settings_managed
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_managed') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report


	SET @SQL = N'delete from meta_report_settings_archive
				where id_meta_report = @id_meta_report'
	IF (OBJECT_ID('meta_report_settings_archive') IS NOT NULL)
		EXEC SP_EXECUTESQL @SQL, N'@id_meta_report BIGINT', @id_meta_report=@id_meta_report


	delete from meta_report
	where id_meta_report = @id_meta_report

RETURN 0
GO

EXEC DBO.REMOVE_REPORT_BY_TYPE_NAME 'ActReturnToContractorInvoice.ActReturnToContractorInvoice'