SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_ADRESSLIST_BY_CONTRACTOR') IS NULL EXEC('CREATE PROCEDURE REPEX_ADRESSLIST_BY_CONTRACTOR AS RETURN')
GO
ALTER PROCEDURE REPEX_ADRESSLIST_BY_CONTRACTOR(
    @XMLPARAM NTEXT
) AS

DECLARE @HDOC INT, @ID_CONTRACTOR BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
    SELECT TOP 1 @ID_CONTRACTOR = ID_CONTRACTOR
    FROM OPENXML(@HDOC, '/XML') WITH(
        ID_CONTRACTOR BIGINT 'ID_CONTRACTOR'
    )
EXEC SP_XML_REMOVEDOCUMENT @HDOC


SELECT TOP 1
    SUPPLIER_NAME = CASE WHEN ISNULL(SUP.LEGAL_PERS, '') != '' THEN SUP.LEGAL_PERS ELSE SUP.LEGAL_PERS_SHORT END,
    SUPPLIER_ADDRESS = CASE WHEN ISNULL(SUP.ADDRESS, '') != '' THEN 'Адрес: '+ SUP.ADDRESS ELSE '' END,
    CUSTOMER_NAME = CASE WHEN ISNULL(CUST.FULL_NAME, '') != '' THEN CUST.FULL_NAME ELSE CUST.[NAME] END,
    CUSTOMER_ADDRESS = CASE WHEN ISNULL(CUST.ADDRESS, '') != '' THEN 'Адрес: '+ CUST.ADDRESS ELSE '' END +
		CASE WHEN ISNULL(CUST.PHONE, '') != '' THEN ' Тел.: '+ CUST.PHONE ELSE '' END
FROM DBO.CONTRACTOR CUST(NOLOCK)
    LEFT JOIN DBO.ENTERPRISE_BRANCH EB(NOLOCK) ON EB.IS_SELF = 1
    LEFT JOIN DBO.CONTRACTOR SUP(NOLOCK) ON SUP.ID_CONTRACTOR = EB.ID_CONTRACTOR
WHERE CUST.ID_CONTRACTOR = @ID_CONTRACTOR

RETURN 0
GO

