SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO


IF OBJECT_ID(N'dbo.FN_CHEQUE_CERTIFICATE_FORMAT_STRING', N'FN') IS NOT NULL 
DROP FUNCTION dbo.FN_CHEQUE_CERTIFICATE_FORMAT_STRING
GO

CREATE FUNCTION dbo.FN_CHEQUE_CERTIFICATE_FORMAT_STRING
    (@STR VARCHAR(4000))
RETURNS VARCHAR(4000)
AS
BEGIN

DECLARE @RESULT VARCHAR(4000)
SET @RESULT = ''
IF (LEN(@STR)>50)
	BEGIN
		WHILE (LEN(@STR)>50)
			BEGIN
				SET @RESULT = @RESULT + LEFT(@STR,50)+''+CHAR(10)+CHAR(13)
				SET @STR = RIGHT(@STR,LEN(@STR)-50)
			END
		SET @RESULT = @RESULT + @STR
		IF (LEN(@RESULT)>199)
			SET @RESULT = LEFT(@RESULT,199) 
	END
		ELSE
			SET @RESULT = @STR
			
RETURN @RESULT

END
GO

IF OBJECT_ID('REPEX_CHEQUE_CERTIFICATE') IS NULL EXEC('CREATE PROCEDURE REPEX_CHEQUE_CERTIFICATE AS RETURN')
GO

ALTER PROCEDURE REPEX_CHEQUE_CERTIFICATE
	(@XMLPARAM NTEXT) AS

/* PARAMETERS */
DECLARE @HDOC INT
DECLARE @STORE VARCHAR(500)
DECLARE @LEN INT
DECLARE @ID_CHEQUE_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_CHEQUE_GLOBAL = ID_CHEQUE_GLOBAL
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_CHEQUE_GLOBAL UNIQUEIDENTIFIER 'ID_CHEQUE_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC


SELECT
	CAST(CH.ID_CHEQUE AS VARCHAR) AS N_CHEQUE,
	CH.DATE_CHEQUE,
 	CONTRACTOR_NAME = case 
 	                      when C.FULL_NAME is null then C.NAME
 	                      when C.FULL_NAME = '' then C.NAME
 	                      else C.FULL_NAME
 	                  end,    
 	C.ADDRESS, 
 	C.INN
FROM CHEQUE CH
	INNER JOIN CASH_SESSION CS ON CH.ID_CASH_SESSION_GLOBAL = CS.ID_CASH_SESSION_GLOBAL
	LEFT JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
	LEFT JOIN CONTRACTOR C ON CR.ID_CONTRACTOR = C.ID_CONTRACTOR
WHERE CH.ID_CHEQUE_GLOBAL = @ID_CHEQUE_GLOBAL 

SELECT 
	G.[NAME] AS GOODS_NAME,
	P.[NAME] AS PRODUCER_NAME,
	S.SERIES_NUMBER,
	C.CERT_NUMBER,
	C.CERT_DATE,
	C.ISSUED_BY,
	C.CERT_END_DATE,
	SUPPLIER = DBO.FN_CHEQUE_CERTIFICATE_FORMAT_STRING(ISNULL(SUP.FULL_NAME,''))+ 
				CHAR(10)+CHAR(13)+ DBO.FN_CHEQUE_CERTIFICATE_FORMAT_STRING(ISNULL(SUP.ADDRESS,''))
FROM CHEQUE CH
	INNER JOIN CHEQUE_ITEM CH_I ON CH.ID_CHEQUE_GLOBAL = CH_I.ID_CHEQUE_GLOBAL
	INNER JOIN GOODS G ON CH_I.ID_GOODS = G.ID_GOODS
	LEFT JOIN PRODUCER P ON G.ID_PRODUCER = P.ID_PRODUCER
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = CH_I.ID_LOT_GLOBAL
	LEFT JOIN CONTRACTOR SUP ON SUP.ID_CONTRACTOR = L.ID_SUPPLIER
	LEFT JOIN SERIES S ON S.ID_SERIES = L.ID_SERIES
	LEFT JOIN CERTIFICATE C ON C.ID_SERIES = L.ID_SERIES
WHERE CH.ID_CHEQUE_GLOBAL = @ID_CHEQUE_GLOBAL
	  AND 
	  C.DATE_DELETED IS NULL 
ORDER BY GOODS_NAME

RETURN 0
GO

/*
exec REPEX_CHEQUE_CERTIFICATE @xmlParam=N'<XML>
          <ID_CHEQUE_GLOBAL>DE0E8F9A-0483-45E1-B8B8-7979EE0E0FD2</ID_CHEQUE_GLOBAL>
          </XML>'
          */