SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_PACKING_JOURNAL') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_PACKING_JOURNAL AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_PACKING_JOURNAL
	@XMLPARAM NTEXT AS

DECLARE @HDOC INT, @SORT INT
DECLARE @TEXT NVARCHAR(4000)
DECLARE @DATE_FR DATETIME, @DATE_TO DATETIME
DECLARE @ALL_CONTRACTOR BIT, @ALL_STORE BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @DATE_FR = DATE_FR, @DATE_TO = DATE_TO 
		FROM OPENXML(@HDOC, '/XML') 
	WITH(DATE_FR DATETIME 'DATE_FR', DATE_TO DATETIME 'DATE_TO')

	/* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬  ŒÕ“–¿√≈Õ“Œ¬ */
	SELECT * INTO #CONTRACTOR FROM OPENXML(@HDOC, '//ID_CONTRACTOR') 
	WITH(ID_CONTRACTOR BIGINT '.') WHERE ID_CONTRACTOR <> 0
	IF @@ROWCOUNT = 0 SET @ALL_CONTRACTOR = 1

        /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬ — À¿ƒŒ¬ */
	SELECT * INTO #STORE FROM OPENXML(@HDOC, '//ID_STORE') 
	WITH(ID_STORE BIGINT '.') WHERE ID_STORE <> 0
	IF @@ROWCOUNT = 0 SET @ALL_STORE = 1;
	
EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC DBO.USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT
EXEC DBO.REP_RANGEDAY @DATE_FR OUT, @DATE_TO OUT

SELECT  AD.MNEMOCODE , 
	AD.DATE ,
	GOODS_NAME = (SELECT G.NAME FROM GOODS G WHERE G.ID_GOODS = ADI.ID_GOODS) ,
	PRODUCER_NAME = (SELECT P.NAME FROM GOODS G LEFT JOIN PRODUCER P ON G.ID_PRODUCER = P.ID_PRODUCER WHERE G.ID_GOODS = ADI.ID_GOODS) ,
	SERIES_NUMBER = (SELECT S.SERIES_NUMBER FROM LOT L INNER JOIN SERIES S ON L.ID_SERIES = S.ID_SERIES WHERE L.ID_LOT = ADI.ID_LOT_FROM) ,
	BEST_BEFORE = (SELECT S.BEST_BEFORE FROM LOT L INNER JOIN SERIES S ON L.ID_SERIES = S.ID_SERIES WHERE L.ID_LOT = ADI.ID_LOT_FROM) ,
	ADI.QUANTITY_FROM ,
	UNIT_NAME_FROM = (SELECT U.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR) + '/'  + CAST(SR.DENOMINATOR AS VARCHAR) FROM SCALING_RATIO SR INNER JOIN UNIT U ON SR.ID_UNIT = U.ID_UNIT WHERE SR.ID_SCALING_RATIO = ADI.ID_SCALING_RATIO_FROM) ,
	PRICE_FROM = L.PRICE_SAL,--ROUND(ADI.PRICE_FROM , 2) ,
	SUM_FROM = L.PRICE_SAL* ADI.QUANTITY_FROM, --ROUND(ADI.PRICE_FROM , 2) * ADI.QUANTITY_FROM ,
	QUANTITY_TO = ADI.QUANTITY ,
	UNIT_NAME_TO = (SELECT U.NAME + ' ' + CAST(SR.NUMERATOR AS VARCHAR) + '/'  +CAST(SR.DENOMINATOR AS VARCHAR) FROM SCALING_RATIO SR INNER JOIN UNIT U ON SR.ID_UNIT = U.ID_UNIT WHERE SR.ID_SCALING_RATIO = ADI.ID_SCALING_RATIO_TO) ,
	PRICE_TO = ADI.PRICE_VAT,--ROUND(ADI.PRICE , 2) ,
	SUM_TO = ADI.QUANTITY * ADI.PRICE_VAT,--ROUND(ADI.PRICE , 2) ,
	SUB_SUM = L.PRICE_SAL * ADI.QUANTITY_FROM - ADI.QUANTITY * ADI.PRICE_VAT,--ROUND(ADI.PRICE_FROM , 2) * ADI.QUANTITY_FROM - ADI.QUANTITY * ROUND(ADI.PRICE , 2) ,
	USER_CREATOR_NAME = (SELECT U.NAME FROM [USER] U WHERE U.ID_USER = AD.ID_USER_DATA)
FROM ACT_DISASSEMBLING AD 
INNER JOIN STORE S ON S.ID_STORE = AD.ID_STORE
INNER JOIN ACT_DISASSEMBLING_ITEM ADI ON AD.DATE BETWEEN @DATE_FR AND @DATE_TO AND
			AD.ID_ACT_DISASSEMBLING_GLOBAL = ADI.ID_ACT_DISASSEMBLING_GLOBAL 	
INNER JOIN LOT L ON L.ID_LOT = ADI.ID_LOT_FROM
	AND (@ALL_CONTRACTOR = 1 OR S.ID_CONTRACTOR IN (SELECT ID_CONTRACTOR FROM #CONTRACTOR))
    AND (@ALL_STORE = 1 OR S.ID_STORE IN (SELECT ID_STORE FROM #STORE))
WHERE DOCUMENT_STATE = 'PROC'
ORDER BY AD.DATE, AD.MNEMOCODE
        	
RETURN 0
GO

--exec REPEX_PACKING_JOURNAL N'<XML><DATE_FR>2009-01-01T00:00:00.000</DATE_FR><DATE_TO>2009-02-17T00:00:00.000</DATE_TO></XML>'