SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.GOODS_MOVEMENT_DOCS') IS NULL EXEC('CREATE PROCEDURE DBO.GOODS_MOVEMENT_DOCS AS RETURN')
GO
ALTER PROCEDURE DBO.GOODS_MOVEMENT_DOCS
     @XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @DATE_FROM DATETIME, @DATE_TO DATETIME
DECLARE @IS_SHORT BIT
DECLARE @ALL_CONTRACTORS BIT, @ALL_STORES BIT, @ALL_GOODS BIT, @ALL_SUPPLIERS BIT, @ALL_PRODUCERS BIT
DECLARE @SORT BIT
DECLARE @NOAU BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT TOP 1 
	@DATE_FROM = DATE_FROM, 
	@DATE_TO = DATE_TO,
	@IS_SHORT = IS_SHORT,
	@SORT = SORT,
	@NOAU = NOAU
FROM OPENXML(@HDOC, '/XML')	WITH(
	DATE_FROM DATETIME 'DATE_FROM',  
	DATE_TO DATETIME 'DATE_TO',
	IS_SHORT BIT 'IS_SHORT',
	SORT BIT 'SORT',
	NOAU BIT 'NOAU')

--select @date_from as 'from'
--select @date_to as 'to'
--select @is_short as 'short'
--select @sort
--select @noau

/*
SELECT * INTO #STORES
FROM OPENXML(@HDOC, '//ID_STORE', 2) WITH (ID_STORE BIGINT '.')
IF (@@ROWCOUNT = 0)
	SET @ALL_STORES = 1*/

SELECT DISTINCT S.ID_STORE, S.ID_CONTRACTOR INTO #STORES
FROM
	(SELECT * FROM OPENXML(@HDOC, '//ID_STORE', 2) 
    WITH(ID_STORE BIGINT '.')) TAB
INNER JOIN STORE S ON S.ID_STORE = TAB.ID_STORE
IF @@ROWCOUNT = 0
	SET @ALL_STORES = 1

--select * from #stores
--select @all_stores

SELECT ID_STORE, ID_CONTRACTOR INTO #STORES_EX FROM #STORES
INSERT INTO #STORES_EX
SELECT ID_STORE, ID_CONTRACTOR FROM STORE WHERE ID_CONTRACTOR NOT IN (SELECT ID_CONTRACTOR FROM #STORES)

--SELECT * FROM #STORES_EX

DECLARE @STORES TABLE
(
	ID_STORE BIGINT,
	ID_CONTRACTOR BIGINT
)

INSERT INTO @STORES
SELECT S.ID_STORE, S.ID_CONTRACTOR FROM STORE AS S INNER JOIN #STORES AS ST ON S.ID_STORE = ST.ID_STORE

--select * from @stores

SELECT * INTO #CONTRACTORS 
FROM OPENXML(@HDOC, '//ID_CONTRACTOR')WITH(ID_CONTRACTOR BIGINT '.') WHERE ID_CONTRACTOR <> 0
IF (@@ROWCOUNT = 0)
	SET @ALL_CONTRACTORS = 1

--select * from #contractors
--select @ALL_CONTRACTORS

SELECT * INTO #GOODS 
FROM OPENXML(@HDOC, '//ID_GOODS') WITH(ID_GOODS BIGINT '.') WHERE ID_GOODS <> 0
IF (@@ROWCOUNT = 0)
	SET @ALL_GOODS = 1

SELECT * INTO #SUPPLIERS
FROM OPENXML(@HDOC, '//ID_SUPPLIER') WITH(ID_SUPPLIER BIGINT '.') WHERE ID_SUPPLIER <> 0
IF (@@ROWCOUNT = 0)
	SET @ALL_SUPPLIERS = 1

SELECT * INTO #PRODUCERS
FROM OPENXML(@HDOC, '//ID_PRODUCER') WITH(ID_PRODUCER BIGINT '.') WHERE ID_PRODUCER <> 0
IF (@@ROWCOUNT = 0)
	SET @ALL_PRODUCERS = 1

--select * from #goods
--select * from #suppliers
--select * from #producers

EXEC USP_RANGE_NORM @DATE_FROM OUT, @DATE_TO OUT
EXEC USP_RANGE_DAYS @DATE_FROM OUT, @DATE_TO OUT

SELECT
	ID_GOODS = G.ID_GOODS,
	GOODS_NAME = G.NAME,
	QUANTITY_ADD = SUM(LM.QUANTITY_ADD * SR.NUMERATOR / CONVERT(MONEY, SR.DENOMINATOR)),
	QUANTITY_SUB = SUM(LM.QUANTITY_SUB * SR.NUMERATOR / CONVERT(MONEY, SR.DENOMINATOR)),
	QF_PRICE_SUP = SUM((LM.QUANTITY_ADD - LM.QUANTITY_SUB) * L.PRICE_SUP),
	QF_PRICE_SAL = SUM((LM.QUANTITY_ADD - LM.QUANTITY_SUB) * L.PRICE_SAL),
	num = MAX(SR.NUMERATOR),
	den = MAX(SR.DENOMINATOR),
	price_sal = max(l.price_sal)
INTO #QUANTITY_FROM
FROM LOT_MOVEMENT LM
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = LM.ID_LOT_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	LEFT JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = LM.ID_TABLE
	INNER JOIN STORE S ON L.ID_STORE = S.ID_STORE
	INNER JOIN CONTRACTOR C ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
	LEFT JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = LM.ID_DOCUMENT
WHERE (LM.DATE_OP <= @DATE_FROM)
	AND (LM.QUANTITY_ADD! = 0 OR LM.QUANTITY_SUB! = 0)
	AND (@ALL_CONTRACTORS = 1 OR C.ID_CONTRACTOR IN (SELECT ID_CONTRACTOR FROM #CONTRACTORS))
    AND (@ALL_STORES = 1 OR L.ID_STORE IN (SELECT ID_STORE FROM @STORES AS ST INNER JOIN CONTRACTOR AS CT ON ST.ID_CONTRACTOR = CT.ID_CONTRACTOR WHERE ST.ID_CONTRACTOR = C.ID_CONTRACTOR))
	AND (@ALL_GOODS = 1 OR G.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS))	
	AND (@ALL_SUPPLIERS = 1 OR L.ID_SUPPLIER IN (SELECT ID_SUPPLIER FROM #SUPPLIERS))
	AND (@ALL_PRODUCERS = 1 OR G.ID_PRODUCER IN (SELECT ID_PRODUCER FROM #PRODUCERS))
	AND (@NOAU = 1 OR (LM.ID_TABLE NOT IN (8, 37, 39)) OR AD.ID_STORE_TO NOT IN (SELECT ID_STORE FROM #STORES_EX))
GROUP BY G.ID_GOODS, G.NAME

--select * from #quantity_from

SELECT 
	ID_GOODS = G.ID_GOODS,
	GOODS_NAME = G.NAME,
	QUANTITY_ADD = SUM(LM.QUANTITY_ADD * SR.NUMERATOR / CONVERT(MONEY, SR.DENOMINATOR)),
	QUANTITY_SUB = SUM(LM.QUANTITY_SUB * SR.NUMERATOR / CONVERT(MONEY, SR.DENOMINATOR)),
	QT_PRICE_SUP = SUM((LM.QUANTITY_ADD - LM.QUANTITY_SUB) * L.PRICE_SUP),
	QT_PRICE_SAL = SUM((LM.QUANTITY_ADD - LM.QUANTITY_SUB) * L.PRICE_SAL),
	num = MAX(SR.NUMERATOR),
	den = MAX(SR.DENOMINATOR)
INTO #QUANTITY_TO
FROM LOT_MOVEMENT LM
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = LM.ID_LOT_GLOBAL
	LEFT JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	LEFT JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	LEFT JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = LM.ID_TABLE
	INNER JOIN STORE S ON L.ID_STORE = S.ID_STORE
	INNER JOIN CONTRACTOR C ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
	LEFT JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = LM.ID_DOCUMENT
WHERE (LM.DATE_OP <= @DATE_TO) 
	AND (LM.QUANTITY_ADD! = 0 OR LM.QUANTITY_SUB! = 0)
	AND (@ALL_CONTRACTORS = 1 OR C.ID_CONTRACTOR IN (SELECT ID_CONTRACTOR FROM #CONTRACTORS))
    AND (@ALL_STORES = 1 OR L.ID_STORE IN (SELECT ID_STORE FROM @STORES AS ST INNER JOIN CONTRACTOR AS CT ON ST.ID_CONTRACTOR = CT.ID_CONTRACTOR WHERE ST.ID_CONTRACTOR = C.ID_CONTRACTOR))
	AND (@ALL_GOODS = 1 OR G.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS))
	AND (@ALL_SUPPLIERS = 1 OR L.ID_SUPPLIER IN (SELECT ID_SUPPLIER FROM #SUPPLIERS))
	AND (@ALL_PRODUCERS = 1 OR G.ID_PRODUCER IN (SELECT ID_PRODUCER FROM #PRODUCERS))
	AND (@NOAU = 1 OR (LM.ID_TABLE NOT IN (8, 37, 39)) OR AD.ID_STORE_TO NOT IN (SELECT ID_STORE FROM #STORES_EX))
GROUP BY G.ID_GOODS, G.NAME

--select * from #quantity_to

SELECT 
	ID_GOODS = G.ID_GOODS,
	GOODS_NAME = G.NAME,
	QUANTITY_FROM = (QF.QUANTITY_ADD - QF.QUANTITY_SUB),
	QF_PRICE_SUP = QF.QF_PRICE_SUP,
	QF_PRICE_SAL = QF.QF_PRICE_SAL,
	DATE_OP = LM.DATE_OP,
	DOC_NAME = TD.DESCRIPTION + ' ' + CASE WHEN AD.DOC_NUM IS NULL THEN '' ELSE AD.DOC_NUM + ' от ' END + CONVERT(VARCHAR, AD.DOC_DATE, 104),

	SORT_ORDER = CASE
					WHEN TD.ID_TABLE_DATA = 2  THEN 1
					WHEN TD.ID_TABLE_DATA = 19 THEN 2
					WHEN TD.ID_TABLE_DATA = 3  THEN 3
					WHEN TD.ID_TABLE_DATA = 12 THEN 4
					WHEN TD.ID_TABLE_DATA = 6  THEN 5
					WHEN TD.ID_TABLE_DATA = 8  THEN 6
					ELSE TD.ID_TABLE_DATA END,
	QUANTITY_ADD = LM.QUANTITY_ADD * SR.NUMERATOR / CONVERT(MONEY, SR.DENOMINATOR),
	QA_PRICE_SUP = LM.QUANTITY_ADD * L.PRICE_SUP,
	QA_PRICE_SAL = LM.QUANTITY_ADD * L.PRICE_SAL,
	QUANTITY_SUB = LM.QUANTITY_SUB * SR.NUMERATOR / CONVERT(MONEY, SR.DENOMINATOR),
	QS_PRICE_SUP = LM.QUANTITY_SUB * L.PRICE_SUP,
	QS_PRICE_SAL = LM.QUANTITY_SUB * L.PRICE_SAL,
	QUANTITY_TO = (QT.QUANTITY_ADD - QT.QUANTITY_SUB),
	QT_PRICE_SUP = QT.QT_PRICE_SUP,
	QT_PRICE_SAL = QT.QT_PRICE_SAL
INTO #temp_t
FROM LOT_MOVEMENT LM
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = LM.ID_LOT_GLOBAL
	INNER JOIN STORE S ON L.ID_STORE = S.ID_STORE
	INNER JOIN CONTRACTOR C ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
	INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = LM.ID_TABLE
	LEFT JOIN #QUANTITY_FROM QF ON QF.ID_GOODS = G.ID_GOODS
	LEFT JOIN #QUANTITY_TO QT ON QT.ID_GOODS = G.ID_GOODS
	LEFT JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = LM.ID_DOCUMENT
WHERE (DATE_OP BETWEEN @DATE_FROM AND @DATE_TO)
	AND (LM.QUANTITY_ADD != 0 OR LM.QUANTITY_SUB != 0)
	AND (@ALL_CONTRACTORS = 1 OR C.ID_CONTRACTOR IN (SELECT ID_CONTRACTOR FROM #CONTRACTORS))
    AND (@ALL_STORES = 1 OR L.ID_STORE IN (SELECT ID_STORE FROM @STORES AS ST INNER JOIN CONTRACTOR AS CT ON ST.ID_CONTRACTOR = CT.ID_CONTRACTOR WHERE ST.ID_CONTRACTOR = C.ID_CONTRACTOR))
	AND (@ALL_GOODS = 1 OR G.ID_GOODS IN (SELECT ID_GOODS FROM #GOODS))
	AND (@ALL_SUPPLIERS = 1 OR L.ID_SUPPLIER IN (SELECT ID_SUPPLIER FROM #SUPPLIERS))
	AND (@ALL_PRODUCERS = 1 OR G.ID_PRODUCER IN (SELECT ID_PRODUCER FROM #PRODUCERS))
	AND (@NOAU = 1 OR (LM.ID_TABLE NOT IN (8, 37, 39)) OR AD.ID_STORE_TO NOT IN (SELECT ID_STORE FROM #STORES_EX))

select * from #temp_t
ORDER BY GOODS_NAME, 
	CASE WHEN @SORT = 1 THEN NULL ELSE SORT_ORDER END, DATE_OP

SELECT
	TOTAL_SUM_FROM = SUM(QUANTITY_ADD - QUANTITY_SUB),
	TOTAL_QF_PRICE_SUP = SUM(QF_PRICE_SUP),
	TOTAL_QF_PRICE_SAL = SUM(QF_PRICE_SAL)
FROM #QUANTITY_FROM

SELECT
	TOTAL_SUM_TO = SUM(QUANTITY_ADD - QUANTITY_SUB),
	TOTAL_QT_PRICE_SUP = SUM(QT_PRICE_SUP),
	TOTAL_QT_PRICE_SAL = SUM(QT_PRICE_SAL)
FROM #QUANTITY_TO

RETURN 0
GO

/*
exec GOODS_MOVEMENT_DOCS N'
<XML>
	<DATE_FROM>2009-12-08T00:00:00.000</DATE_FROM>
	<DATE_TO>2009-12-10T00:00:00.000</DATE_TO>
	<SORT>0</SORT>
	<NOAU>0</NOAU>
</XML>'*/
