SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INVOICE_OUT_KIROV') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INVOICE_OUT_KIROV AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INVOICE_OUT_KIROV
	@XMLPARAM NTEXT AS

DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT

SELECT @ID_GLOBAL = ID_GLOBAL
FROM OPENXML(@HDOC, '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	DOC_NUM = I.MNEMOCODE,
	DOC_DATE = I.DATE,
    SUPPLIER =
		CASE WHEN ISNULL(SUP.FULL_NAME, '') != '' THEN SUP.FULL_NAME ELSE SUP.NAME END +
		CASE WHEN ISNULL(SUP.INN, '') != '' THEN ' »ÕÕ:' + SUP.INN ELSE '' END,
    BASE_DOC = I.BASE_DOCUMENT_NAME,
	CUSTOMER =
		CASE WHEN ISNULL(PAY.FULL_NAME, '') != '' THEN PAY.FULL_NAME ELSE PAY.NAME END +
		CASE WHEN ISNULL(PAY.INN, '') != '' THEN ' »ÕÕ:' + PAY.INN ELSE '' END,
	STORE = S.NAME	
FROM INVOICE_OUT I
    INNER JOIN STORE S ON S.ID_STORE = I.ID_STORE 
    INNER JOIN CONTRACTOR SUP ON SUP.ID_CONTRACTOR = S.ID_CONTRACTOR
    INNER JOIN CONTRACTOR PAY ON PAY.ID_CONTRACTOR = I.ID_CONTRACTOR_TO
WHERE ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

SELECT
    GOODS_NAME = G.NAME + ' [' + P.NAME + ', ' + COALESCE(C.NAME, '') + ']',
    QUANTITY = II.QUANTITY,
	SCALING_RATIO = CAST(SR.NUMERATOR AS VARCHAR) + '/' + CAST(SR.DENOMINATOR AS VARCHAR) + ' ' + U.NAME,
	INTERNAL_BARCODE = L.INTERNAL_BARCODE,
	RETAIL_PRICE = II.PRICE_SAL,
	PRICE_SUM = II.SUM_SAL,
	SERIES_NUMBER = SER.SERIES_NUMBER,
	BEST_BEFORE = SER.BEST_BEFORE,
	CERT = RC.NAME + ' ' + ISNULL(RC.ORGAN, '')
FROM INVOICE_OUT I
    INNER JOIN INVOICE_OUT_ITEM II ON II.ID_INVOICE_OUT_GLOBAL = I.ID_INVOICE_OUT_GLOBAL
    INNER JOIN LOT L ON L.ID_LOT_GLOBAL = II.ID_LOT_GLOBAL
    INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
    INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
    INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
    INNER JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
    LEFT JOIN COUNTRY C ON C.ID_COUNTRY = P.ID_COUNTRY
    LEFT JOIN SERIES SER ON SER.ID_SERIES = L.ID_SERIES
	LEFT JOIN REG_CERT RC ON RC.ID_REG_CERT_GLOBAL = L.ID_REG_CERT_GLOBAL
WHERE I.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL
ORDER BY GOODS_NAME

RETURN 0
GO

--exec REPEX_INVOICE_OUT_KIROV '<XML><ID_GLOBAL>65AB0BE9-4D2A-4931-965A-097EFD825553</ID_GLOBAL></XML>'

