IF (OBJECT_ID('INVOICE_OUT_PROTOCOL_KONS') IS NULL) EXEC ('CREATE PROCEDURE INVOICE_OUT_PROTOCOL_KONS AS RETURN')
GO
ALTER PROCEDURE INVOICE_OUT_PROTOCOL_KONS(
    @XMLPARAM NTEXT
)
AS
    DECLARE @HDOC INT
    DECLARE @ID_GLOBAL UNIQUEIDENTIFIER
    EXEC SP_XML_PREPAREDOCUMENT @HDOC OUT, @XMLPARAM
    SElECT
        @ID_GLOBAL = ID_GLOBAL
    FROM OPENXML(@HDOC, '//XML') WITH(
        ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL'
    )
    EXEC SP_XML_REMOVEDOCUMENT @HDOC


	DECLARE @ERRMES NVARCHAR(256)

	--ШАПКА
    SELECT 
        MNEMOCODE = I_O.MNEMOCODE,
	    DATE_FR = I_O.DATE,
        CONTRACTOR_FR = C_FROM.NAME,
        CONTRACTOR_TO = C_TO.NAME,
        SUM_SAL = I_O.SUM_SAL,
		CONTRACT_NAME = C.NAME
    FROM INVOICE_OUT I_O
    INNER JOIN STORE S ON S.ID_STORE = I_O.ID_STORE
    INNER JOIN CONTRACTOR C_FROM ON C_FROM.ID_CONTRACTOR = S.ID_CONTRACTOR
    INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = I_O.ID_CONTRACTOR_TO
	LEFT JOIN CONTRACTS C ON C.ID_CONTRACTS_GLOBAL = I_O.ID_CONTRACTS_GLOBAL	
    WHERE ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

	--ТАБЛИЧНАЯ ЧАСТЬ
    SELECT 
        GOODS_NAME = G.NAME,-- +' - '+c.NAME+CHAR(10)+CHAR(13)+P.NAME, --наименование
        S.ID_SERIES,												--серия
        SERIES = S.SERIES_NUMBER,									--серия
		PRODUCER_NAME = P.[NAME],									--производитель
        BEST_BEFORE = S.BEST_BEFORE,								--срок годности
		REG_CERT = RC.[NAME],
        CERT_NUMBER = CONVERT(VARCHAR(4000), NULL),					--номер сертификата
        CERT_END_DATE = CONVERT(VARCHAR(4000), NULL),

		UNIT_MEASURE = CAST(SR.NUMERATOR AS VARCHAR) + '/' + CAST(SR.DENOMINATOR AS VARCHAR) + ' ' + U.SHORT_NAME,									--единица измерения
        QUANTITY = IOI.QUANTITY,	--количество
		REG_PRICE = G.REGISTER_PRICE,								--реестровая цена
		PRICE_PROD = L.PRICE_PROD, 									--цена производителя
 		TORG_N_TR = L.ADPRICE_SUP, --CASE WHEN II.SUPPLIER_ADPRICE IS NULL THEN 
--  				  		 CASE WHEN ISNULL(L.PRICE_PROD,0)!=0 THEN ((L.PRICE_SUP - L.PVAT_SUP)/L.PRICE_PROD - 1)* 100 
--  						      ELSE 0 
--  						 END 
--  					     ELSE II.SUPPLIER_ADPRICE 
--                     END,  --торговая надбавка (ТР)
        PRICE_SUP = (L.PRICE_SUP - L.PVAT_SUP), --цена поставщика без НДС
		PRICE_SUP_VAT = L.PRICE_SUP, --цена поставщика с НДС
		TORG_N = CASE WHEN L.PRICE_PROD !=0 AND (IOI.PRICE_SAL - IOI.PVAT_SAL)!=0 THEN ((IOI.PRICE_SAL - IOI.PVAT_SAL) - L.PRICE_SUP * L.ADPRICE_SUP / 100 - (L.PRICE_SUP - L.PVAT_SUP)) * 100 / L.PRICE_PROD ELSE 0 END,
-- 				CASE WHEN II.SUPPLIER_ADPRICE IS NULL THEN 
-- 					  CASE WHEN ISNULL(L.PRICE_PROD,0) != 0 AND (IOI.PRICE_SAL - IOI.PVAT_SAL)!=0 THEN ((IOI.PRICE_SAL - IOI.PVAT_SAL) - L.PRICE_SUP * (((L.PRICE_SUP - L.PVAT_SUP)/L.PRICE_PROD - 1)* 100) / 100 - (L.PRICE_SUP - L.PVAT_SUP)) * 100 / L.PRICE_PROD 
--                            ELSE 0 
--                       END 
-- 				      ELSE
-- 					      CASE WHEN L.PRICE_PROD !=0 AND (IOI.PRICE_SAL - IOI.PVAT_SAL)!=0 THEN ((IOI.PRICE_SAL - IOI.PVAT_SAL) - L.PRICE_SUP * L.ADPRICE_SUP / 100 - (L.PRICE_SUP - L.PVAT_SUP)) * 100 / L.PRICE_PROD
--                                ELSE 0 
--                                END 
--                  END, --ТОРГОВАЯ НАДБАВКА
        PRICE_SAL = (IOI.SUM_SAL - IOI.PSUM_SAL)/ IOI.QUANTITY,--(L.PRICE_SAL - L.PVAT_SAL)* CONVERT(MONEY, SR.DENOMINATOR) / SR.NUMERATOR,   --ЦЕНА РОЗН БЕЗ НДС
        PRICE_SAL_VAT = IOI.SUM_SAL / IOI.QUANTITY,--L.PRICE_SAL* CONVERT(MONEY, SR.DENOMINATOR) / SR.NUMERATOR,   --ЦЕНА РОЗН C НДС
        SUM_SAL = IOI.SUM_SAL --L.PRICE_SAL * QUANTITY
    INTO #ITEMS
    FROM INVOICE_OUT_ITEM IOI
    INNER JOIN LOT L ON L.ID_LOT_GLOBAL = IOI.ID_LOT_GLOBAL
--	LEFT JOIN INVOICE_ITEM II ON II.ID_INVOICE_ITEM_GLOBAL = L.ID_DOCUMENT_ITEM
    INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
    INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
    INNER JOIN PRODUCER P ON P.ID_PRODUCER = G.ID_PRODUCER
    INNER JOIN COUNTRY C ON C.ID_COUNTRY = P.ID_COUNTRY
	LEFT JOIN REG_CERT RC ON RC.ID_REG_CERT_GLOBAL = L.ID_REG_CERT_GLOBAL--II.ID_REG_CERT_GLOBAL
	LEFT JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
    LEFT JOIN SERIES S ON S.ID_SERIES = L.ID_SERIES
    WHERE ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

    DECLARE C CURSOR FOR
    SELECT 
        ID_SERIES,    
        CERT_NUMBER,
        CERT_END_DATE
    FROM CERTIFICATE C
    WHERE EXISTS (SELECT NULL FROM #ITEMS I WHERE I.ID_SERIES = C.ID_SERIES)    

    DECLARE @ID_SERIES BIGINT
    DECLARE @CERT_NUMBER VARCHAR(40)
    DECLARE @CERT_END_DATE DATETIME
    OPEN C 
    WHILE 1=1 BEGIN
        FETCH NEXT FROM C INTO @ID_SERIES, @CERT_NUMBER, @CERT_END_DATE
        IF (@@FETCH_STATUS<>0) BREAK
        UPDATE #ITEMS SET
            CERT_NUMBER = ISNULL(CERT_NUMBER+ISNULL(', '+@CERT_NUMBER,''), @CERT_NUMBER),
            CERT_END_DATE = ISNULL(CERT_END_DATE+ISNULL(', '+dbo.FN_DATE_2_VARCHAR(@CERT_END_DATE),''), dbo.FN_DATE_2_VARCHAR(@CERT_END_DATE))
        WHERE #ITEMS.ID_SERIES = @ID_SERIES
    END
    CLOSE C
    DEALLOCATE C

    SELECT 
        GOODS_NAME, --наименование
        SERIES,									--серия
		PRODUCER_NAME,									--производитель
        BEST_BEFORE,								--срок годности
		REG_CERT,						--рег.сертификат
        CERT_NUMBER,					--номер сертификата
		UNIT_MEASURE,									--единица измерения
        QUANTITY,	--количество
		REG_PRICE,								--реестровая цена
		PRICE_PROD, --цена производителя
		TORG_N_TR,
        PRICE_SUP, --цена поставщика без НДС
		PRICE_SUP_VAT, --цена поставщика с НДС
		TORG_N, --ТОРГОВАЯ НАДБАВКА
        PRICE_SAL,   --ЦЕНА РОЗН БЕЗ НДС
        PRICE_SAL_VAT,   --ЦЕНА РОЗН C НДС
        SUM_SAL
    FROM #ITEMS
    ORDER BY GOODS_NAME ASC
RETURN
GO

--exec INVOICE_OUT_PROTOCOL_KONS @xmlParam = N'<XML><ID_GLOBAL>4f08ea01-4e44-426a-aa43-9abed82f2319</ID_GLOBAL></XML>'
--exec INVOICE_OUT_PROTOCOL_KONS @xmlParam = N'<XML><ID_GLOBAL>8fa34d78-e8b3-470d-a13d-48a5364666ff</ID_GLOBAL></XML>'