SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_LIST_RETURN_TO_CONTRACTOR_APT76') IS NULL EXEC('CREATE PROCEDURE REPEX_LIST_RETURN_TO_CONTRACTOR_APT76 AS RETURN')
GO
ALTER  PROCEDURE REPEX_LIST_RETURN_TO_CONTRACTOR_APT76
	@XMLPARAM NTEXT AS
		
DECLARE	@HDOC INT, @ID_ACT_RETURN_TO_CONTRACTOR BIGINT
DECLARE	@ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL UNIQUEIDENTIFIER
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT , @XMLPARAM OUTPUT
		
SELECT TOP 1 @ID_ACT_RETURN_TO_CONTRACTOR = ID_ACT_RETURN_TO_CONTRACTOR, @ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL
FROM OPENXML(@HDOC , '/XML')
WITH(ID_ACT_RETURN_TO_CONTRACTOR BIGINT 'ID_ACT_RETURN_TO_CONTRACTOR', ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL UNIQUEIDENTIFIER 'ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL')
		
EXEC SP_XML_REMOVEDOCUMENT @HDOC
		
SELECT	TOP 1 FROM_ID = CO.ID_CONTRACTOR,
	FROM_NAME = CASE WHEN CO.FULL_NAME IS NULL OR CO.FULL_NAME = '' THEN CO.NAME ELSE CO.FULL_NAME END,
	FROM_FULLNAME = CO.FULL_NAME,
	FROM_INN = CO.INN,
	FROM_ADDRESS = CO.ADDRESS,
	FROM_PHONE = CO.PHONE,
	FROM_BANK = CO.BANK,
	FROM_BANKADDRESS = CO.BANK_ADDRESS,
	FROM_ACCOUNT = CO.ACCOUNT,
	FROM_CORRACCOUNT = CO.CORR_ACCOUNT,
	FROM_BIK = CO.BIK
FROM CONTRACTOR CO
WHERE CO.ID_CONTRACTOR = (SELECT TOP 1 AC.ID_CONTRACTOR_FROM FROM ACT_RETURN_TO_CONTRACTOR AC WHERE ID_ACT_RETURN_TO_CONTRACTOR = @ID_ACT_RETURN_TO_CONTRACTOR OR ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = @ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL)
		
SELECT	TOP 1 AC_ID = AC.ID_ACT_RETURN_TO_CONTRACTOR,
	AC_NUMBER = AC.MNEMOCODE,
	AC_DATE = CONVERT(VARCHAR, AC.DATE, 104),
	AC_STORE = (SELECT TOP 1 S.NAME FROM STORE S WHERE S.ID_STORE = AC.ID_STORE),
	TO_ID = CO.ID_CONTRACTOR,
	TO_NAME = CASE WHEN CO.FULL_NAME IS NULL OR CO.FULL_NAME = '' THEN CO.NAME ELSE CO.FULL_NAME END,
	TO_FULLNAME = CO.FULL_NAME,
	TO_INN = CO.INN,
	TO_ADDRESS = CO.ADDRESS,
	TO_PHONE = CO.PHONE,
	TO_BANK = CO.BANK,
	TO_BANKADDRESS = CO.BANK_ADDRESS,
	TO_ACCOUNT = CO.ACCOUNT,
	TO_CORRACCOUNT = CO.CORR_ACCOUNT,
	TO_BIK = CO.BIK,
	I_NUMBER = (SELECT TOP 1 COALESCE(I.INCOMING_NUMBER, I.MNEMOCODE, '') FROM INVOICE I WHERE I.ID_INVOICE = AC.ID_DOCUMENT_BASE),
	I_DATE = (SELECT TOP 1 COALESCE(CONVERT(VARCHAR, I.INCOMING_DATE, 104) , CONVERT(VARCHAR, I.DOCUMENT_DATE, 104), '') FROM INVOICE I WHERE I.ID_INVOICE = AC.ID_DOCUMENT_BASE)
FROM ACT_RETURN_TO_CONTRACTOR AC INNER JOIN CONTRACTOR CO ON CO.ID_CONTRACTOR = AC.ID_CONTRACTOR_TO
WHERE ID_ACT_RETURN_TO_CONTRACTOR = @ID_ACT_RETURN_TO_CONTRACTOR OR ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = @ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL
		
SELECT
	G_ID = G.ID_GOODS,
	G_MODELCODE = G.MNEMOCODE,
	G_RUSNAME = G.NAME,
	G_SERIALNUMBER = CASE WHEN (SELECT TOP 1 SN.SERIES_NUMBER 
		FROM SERIES SN WHERE SN.ID_SERIES = ISNULL(L.ID_SERIES , 0)) IS NULL THEN 'Õ≈“ ƒ¿ÕÕ€’' 
		ELSE (SELECT TOP 1 SN.SERIES_NUMBER FROM SERIES SN 
		WHERE SN.ID_SERIES = ISNULL(L.ID_SERIES , 0)) END,
	G_BESTBEFORE = CASE WHEN (SELECT TOP 1 CONVERT(VARCHAR, SN.BEST_BEFORE , 104) 
		FROM SERIES SN WHERE SN.ID_SERIES = ISNULL(L.ID_SERIES, 0)) IS NULL THEN 'Õ≈“ ƒ¿ÕÕ€’' 
		ELSE (SELECT TOP 1 CONVERT(VARCHAR , SN.BEST_BEFORE, 104) FROM SERIES SN WHERE SN.ID_SERIES = ISNULL(L.ID_SERIES, 0)) END,
	G_NAMESCALING = DBO.FN_SCALE_NAME_SHORT(ACI.ID_SCALING_RATIO),
	ACI_QUANTITY = CAST(ACI.QUANTITY AS DECIMAL(18, 2)),
	ACI_PRICESUPP = CAST(ACI.PRICE_VAT AS DECIMAL(18, 2)),
	ACI_PVATSUPP = CAST(ACI.PRICE_VAT - ACI.PRICE AS DECIMAL(18, 2)),
	ACI_TAXVAT = CAST(ROUND(100 * ((ACI.PRICE_VAT - ACI.PRICE) / ACI.PRICE), 0) AS DECIMAL(18, 2)),
	ACI_SUMSUPP = CAST(0 AS DECIMAL(18, 2)),
	ACI_PRICESAL = CAST(L.PRICE_SAL AS DECIMAL(18, 2)),
	ACI_PVATSAL = CAST(L.PVAT_SAL AS DECIMAL(18, 2)),
	ACI_SUMSAL = CAST(0 AS DECIMAL(18, 2)),
	ACI_SUMDISCOUNT = CAST(0 AS DECIMAL(18, 2)),
	ACI_TAXSALE = CAST(0 AS DECIMAL(18, 2))
FROM GOODS G, LOT L, ACT_RETURN_TO_CONTRACTOR_ITEM ACI
WHERE G.ID_GOODS = ACI.ID_GOODS AND L.ID_LOT_GLOBAL = ACI.ID_LOT_GLOBAL AND (ACI.ID_ACT_RETURN_TO_CONTRACTOR = @ID_ACT_RETURN_TO_CONTRACTOR OR ACI.ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL = @ID_ACT_RETURN_TO_CONTRACTOR_GLOBAL)
ORDER BY G_RUSNAME
		
RETURN 0
GO