SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO
--InternetOrder
IF OBJECT_ID('REPEX_SUPPLY_PRODUCTS_RYAZAN') IS NULL EXEC('CREATE PROCEDURE REPEX_SUPPLY_PRODUCTS_RYAZAN AS RETURN')
GO

ALTER PROCEDURE REPEX_SUPPLY_PRODUCTS_RYAZAN
	(@XMLPARAM NTEXT) AS

/* PARAMETERS */
DECLARE @HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_GLOBAL = ID_GLOBAL
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
		[GOOD_NAME] = G.NAME,
		[UOM] = U.SHORT_NAME,
		[QTY] = II.QUANTITY,
		[PRICE] = L.PRICE_SAL,
		[SUMM] = II.QUANTITY * (L.PRICE_SAL),
		--[VAT_SAL] = CASE WHEN L.PVAT_SUP = 0 THEN CAST('Без НДС' AS VARCHAR(10)) ELSE CAST(L.VAT_SUP AS VARCHAR(9)) + '%' END,
		[PSUM_SAL] = II.QUANTITY * L.PVAT_SAL
		--[SUM_SAL] = II.QUANTITY * L.PRICE_SUP
	FROM INVOICE_OUT_ITEM II
		INNER JOIN LOT L ON L.ID_LOT_GLOBAL = II.ID_LOT_GLOBAL
		INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
		INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO 
		INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
	WHERE II.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL
	ORDER BY G.NAME

SELECT
	[INVOICE_OUT_NAME] = I.MNEMOCODE,
	[INVOICE_OUT_DATE] = I.DATE,
	[CONTRACTOR_FROM_NAME] = /*ISNULL(C_FR.FULL_NAME,''),--ISNULL(C_FR.LEGAL_PERS_SHORT,''),*/ISNULL(C_FR.LEGAL_PERS,'') + ' (' + ISNULL(C_FR.LEGAL_PERS_SHORT,'') + ')',
	[CONTRACTOR_FROM_ADDRESS] = ISNULL(C_FR.[UR_ADDRESS], ''),
	[CONTRACTOR_FROM_INN] = 'ИНН :' + ISNULL(C_FR.INN, ''),
	[CONTRACTOR_FROM_KPP] = 'КПП :' + ISNULL(C_FR.KPP, ''),
	[CONTRACTOR_FROM_BIK] = 'БИК :' + ISNULL(C_FR.BIK, ''),
	[CONTRACTOR_FROM_ACCOUNT] = 'Р/с :' + ISNULL(C_FR.ACCOUNT, ''),
	[CONTRACTOR_FROM_BANK] = ISNULL(C_FR.BANK, ''),
	[CONTRACTOR_FROM_DIRECTOR_FIO] = ISNULL(C_FR.DIRECTOR_FIO, ''),
--	[GCONTRACTOR] = ISNULL(ISNULL(C_FR.LEGAL_PERS + ' ', C_FR.LEGAL_PERS_SHORT + ' '), '') + ISNULL(C_FR.NAME, 'Не указано') + ', ' + ISNULL(C_FR.ADDRESS, 'Адрес не указан'), 
	[GCONTRACTOR] = ISNULL(C_FR.FULL_NAME+', ', '') + ISNULL(C_FR.[ADDRESS], ''),
	[GCONTRACTOR_TO_NAME] = ISNULL(C_TO.FULL_NAME+', ', '') + ISNULL(C_TO.[ADDRESS], ''),
	[CONTRACTOR_TO_NAME] = ISNULL(C_P.FULL_NAME, ''),
	[CONTRACTOR_TO_ADDRESS] = ISNULL(C_P.[UR_ADDRESS], ''),
	[CONTRACTOR_TO_INN] = 'ИНН :' + ISNULL(C_P.INN, ''),
	[CONTRACTOR_TO_KPP] = 'КПП :' + ISNULL(C_P.KPP, ''),
	[CONTRACTOR_TO_DIRECTOR_FIO] = ISNULL(C_P.DIRECTOR_FIO, '')
	--,C_FR.ID_CONTRACTOR
	--select * 
FROM INVOICE_OUT I
	INNER JOIN STORE S ON S.ID_STORE = I.ID_STORE
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S.ID_CONTRACTOR
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = I.ID_CONTRACTOR_TO
	INNER JOIN CONTRACTOR C_P ON C_P.ID_CONTRACTOR = I.ID_PAYER
WHERE I.ID_INVOICE_OUT_GLOBAL = @ID_GLOBAL

RETURN 0
GO

/*
exec REPEX_CHEQUE_INTERNET_ORDER @xmlParam=N'<XML>
          <ID_INTERNET_ORDER_GLOBAL>65CB92A7-9340-4E53-8343-C1DBE9E488FE</ID_INTERNET_ORDER_GLOBAL>
          </XML>'

*/



    -- select * from CHEQUE_ITEM     
    
      