--use eplus_dev10
SET NOCOUNT ON
SET ANSI_NULLS ON 
SET QUOTED_IDENTIFIER OFF
-------------------------------------------------------------------------------
IF OBJECT_ID('REP_PRICELIST_ES_EX') IS NULL EXEC('CREATE PROCEDURE REP_PRICELIST_ES_EX AS RETURN')
GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

ALTER  PROCEDURE DBO.REP_PRICELIST_ES_EX
	(@XMLPARAM NTEXT) 
AS

DECLARE @HDOC INT, @SORT INT
DECLARE @TEXT NVARCHAR(4000)
DECLARE @DATE_OST DATETIME
DECLARE @ALL_GOODS BIT, @ALL_STORE BIT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @DATE_OST = DATE_OST, @SORT = SORT
		FROM OPENXML(@HDOC, '/XML') 
	WITH(DATE_OST DATETIME 'DATE_OST', SORT INT 'SORT')

	/* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬ “Œ¬¿–€ */
	SELECT * INTO #GOODS2 FROM OPENXML(@HDOC, '//KOD_ES') 
	WITH(KOD_ES BIGINT '.') WHERE KOD_ES <> 0
	IF @@ROWCOUNT = 0 SET @ALL_GOODS = 1

    /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬ — À¿ƒŒ¬ */
	SELECT * INTO #STORE
	FROM OPENXML(@HDOC, '//ID_STORE') 
	WITH(ID_STORE BIGINT '.') WHERE ID_STORE <> 0
	IF @@ROWCOUNT = 0 SET @ALL_STORE = 1

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC DBO.USP_RANGE_DAYS NULL, @DATE_OST OUT
EXEC DBO.USP_RANGE_NORM NULL, @DATE_OST OUT
SET @SORT = ISNULL(@SORT, 0)

SELECT L.ID_GOODS, L.ID_STORE,
	L.ID_LOT_GLOBAL,
	AMOUNT_OST = SUM(LM.QUANTITY_ADD - LM.QUANTITY_SUB - LM.QUANTITY_RES),
	L.PRICE_SUP,
	L.PRICE_SAL	
INTO #OST
FROM LOT L
INNER JOIN LOT_MOVEMENT LM ON L.ID_LOT_GLOBAL = LM.ID_LOT_GLOBAL
WHERE (@ALL_GOODS = 1 OR L.ID_GOODS IN (
        SELECT G.ID_GOODS FROM GOODS G
        INNER JOIN (SELECT G.ID_GOODS_GLOBAL
            FROM #GOODS2 G2
            INNER JOIN ES_EF2 F2 ON F2.KOD_ES = G2.KOD_ES
            INNER JOIN ES_ES_2_GOODS G ON G.C_ES = F2.GUID_ES) TAB ON TAB.ID_GOODS_GLOBAL = G.ID_GOODS_GLOBAL))
AND  (@ALL_STORE = 1 OR L.ID_STORE IN (SELECT ID_STORE FROM #STORE))
AND LM.DATE_OP <= @DATE_OST
GROUP BY L.ID_GOODS, L.ID_STORE, L.PRICE_SUP, L.PRICE_SAL, L.ID_LOT_GLOBAL

SELECT F2.GUID_ES,
	  GOODS_NAME = F2.[NAME],
      MV.DOC_DATE,
      GOODS_NAME_FULL = F2.[NAME] + ' (' + PROD.PRODUCER_NAME + ')',
	  AMOUNT = OST.AMOUNT_OST,
   	  SCALE_NAME = DBO.FN_SCALE_NAME_SHORT(L.ID_SCALING_RATIO),
	  DOC_NAME = DBO.REP_DATE(MV.DOC_DATE) + ' ' + MV.DOC_NUM,
	  CONTRACTOR_NAME = C.[NAME],--œŒ—“¿¬Ÿ» 
	  PRICE_OPT = OST.PRICE_SUP, --Œœ“. ÷≈Õ¿
	  PRICE_SAL = OST.PRICE_SAL, --–Œ«Õ. ÷≈Õ¿
	  RETAIL_PRICE_SUM = OST.AMOUNT_OST*OST.PRICE_SAL, 
	  BEST_BEFORE = DBO.REP_DATE(S.BEST_BEFORE), --√Œƒ≈Õ ƒŒ
	  S.SERIES_NUMBER, --—≈–»ﬂ
	  L.INTERNAL_BARCODE, --ÿ“–»’ Œƒ
	  -- CERT_NUMBER = (SELECT CR.CERT_NUMBER FROM #result_cert cr where CR.ID_SERIES = LOT.ID_SERIES),
      CERT_NUMBER = DBO.FN_SERIES_CERTIFICATE(L.ID_SERIES),
	  COUNTRY = COALESCE(CNR.COUNTRY_NAME, ''), --—“–¿Õ¿
	  IMPORTANT = 
	  CASE F2.PR_JNVLS
	      WHEN 0 THEN '-'
	      WHEN 1 THEN 'ƒ¿'
	  END, --∆Õ¬À—
	  IN_DRUG = 
	  CASE F2.PR_BAD
	      WHEN 0 THEN '-'
	      WHEN 1 THEN 'ƒ¿'
	  END, --œ ”
	  ITOG = OST.AMOUNT_OST*CONVERT(MONEY, SR.NUMERATOR) / SR.DENOMINATOR
INTO #TEMP
FROM #OST OST
INNER JOIN LOT L ON L.ID_LOT_GLOBAL = OST.ID_LOT_GLOBAL
INNER JOIN DBO.GOODS G ON G.ID_GOODS = OST.ID_GOODS
INNER JOIN ES_ES_2_GOODS G2(NOLOCK) ON G2.ID_GOODS_GLOBAL = G.ID_GOODS_GLOBAL
INNER JOIN ES_EF2 F2(NOLOCK) ON F2.GUID_ES = G2.C_ES
INNER JOIN DBO.CONTRACTOR C ON C.ID_CONTRACTOR= L.ID_SUPPLIER
INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = L.ID_SCALING_RATIO
LEFT JOIN SERIES S ON S.ID_SERIES = L.ID_SERIES
LEFT JOIN MV_DOCUMENTS MV ON MV.ID_DOCUMENT_GLOBAL = L.ID_DOCUMENT
LEFT JOIN ES_PRODUCER PROD(NOLOCK) ON PROD.KOD_PRODUCER = F2.PRODUCER_COD
LEFT JOIN ES_COUNTRY CNR(NOLOCK) ON CNR.KOD_COUNTRY = PROD.COUNTRY_COD
WHERE AMOUNT_OST > 0

SELECT *,
	SUM_OPT = PRICE_OPT * AMOUNT,
	SUM_SAL = PRICE_SAL * AMOUNT 
INTO #SORT FROM #TEMP

DECLARE @QUERY NVARCHAR(4000)
SET @QUERY = 'SELECT * FROM #SORT'
IF @SORT = 0 SET @QUERY = @QUERY + ' ORDER BY GOODS_NAME'
IF @SORT = 1 SET @QUERY = @QUERY + ' ORDER BY CONTRACTOR_NAME, GOODS_NAME'
IF @SORT = 2 SET @QUERY = @QUERY + ' ORDER BY DOC_DATE, GOODS_NAME'

SELECT 
    ISNULL(CNT.NAME, '') AS COMPANY,
    CNT.PHONE
FROM DBO.CONTRACTOR CNT
WHERE CNT.ID_CONTRACTOR = DBO.FN_CONST_CONTRACTOR_SELF()

EXEC SP_EXECUTESQL @query

RETURN 0


GO
SET QUOTED_IDENTIFIER OFF 
GO
SET ANSI_NULLS ON 
GO

--exec REP_PRICELIST_ES_EX @xmlParam = N'<XML><DATE_OST>2008-10-20T17:19:46.203</DATE_OST><SORT>0</SORT></XML>'
