SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INV26') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_INV26 AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_INV26
	@XMLPARAM NTEXT AS

DECLARE	@HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT

SELECT @ID_GLOBAL = ID_GLOBAL
FROM OPENXML(@HDOC , '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT
	CONTRACTOR = CASE WHEN ISNULL(C.FULL_NAME, '') = '' THEN C.NAME ELSE C.FULL_NAME END,
	STORE = S.NAME,
	DOC_NUM = I.DOC_NUM,
	DOC_DATE = CONVERT(VARCHAR(10), I.DOC_DATE, 104)
FROM INVENTORY_SVED I
	INNER JOIN STORE S ON S.ID_STORE = I.ID_STORE
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
WHERE I.ID_INVENTORY_GLOBAL = @ID_GLOBAL

SELECT
	IVI.ID_GOODS,
	QUANTITY_REM = ISNULL(IVI.QUANTITY_REM, 0),
	QUANTITY = IVI.QUANTITY,
	PRICE_SAL = IVI.PRICE_SAL
FROM MV_INVENTORY_VED_ITEM IVI
	INNER JOIN INVENTORY_VED IV ON IV.ID_INVENTORY_VED_GLOBAL = IVI.ID_INVENTORY_VED_GLOBAL
	INNER JOIN INVENTORY_SVED I ON I.ID_INVENTORY_GLOBAL = IV.ID_INVENTORY_SVED_GLOBAL
WHERE I.ID_INVENTORY_GLOBAL = @ID_GLOBAL AND ISNULL(IVI.QUANTITY_REM, 0) <> IVI.QUANTITY

SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO
FROM CONTRACTOR
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)


RETURN 0
GO

--exec REPEX_INV26 N'<XML><ID_GLOBAL>D3F842BE-6856-4920-B7DA-D3F9B28E3AA2</ID_GLOBAL></XML>'
