SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_ACT_DISASSEMBLING') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_ACT_DISASSEMBLING AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_ACT_DISASSEMBLING
	@XMLPARAM NTEXT AS
	
DECLARE	@HDOC INT, @ID_ACT_DISASSEMBLING BIGINT
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT		
	SELECT TOP 1 @ID_ACT_DISASSEMBLING = ID_ACT_DISASSEMBLING
	FROM OPENXML(@HDOC , '/XML') WITH (ID_ACT_DISASSEMBLING BIGINT 'ID_ACT_DISASSEMBLING')		
EXEC SP_XML_REMOVEDOCUMENT @HDOC	
	
SELECT
	CONTRACTOR_NAME = case 
	                    when C.FULL_NAME is null then C.NAME
	                    when C.FULL_NAME = '' then C.NAME
	                    else C.FULL_NAME
	                  end,  
	C.ADDRESS AS CONTRACTOR_ADDRESS,
	AD.MNEMOCODE AS MNEMOCODE,
	AD.DATE AS DOC_DATE,
	S.NAME AS STORE_NAME
FROM ACT_DISASSEMBLING AD
	LEFT JOIN STORE S ON AD.ID_STORE = S.ID_STORE
	LEFT JOIN CONTRACTOR C ON S.ID_CONTRACTOR = C.ID_CONTRACTOR
WHERE AD.ID_ACT_DISASSEMBLING = @ID_ACT_DISASSEMBLING
 
SELECT
	G.NAME AS GOODS_NAME_FROM, 
	(SELECT U.NAME+ ' (' + CAST(SR.NUMERATOR AS VARCHAR) + '/' + CAST(SR.DENOMINATOR AS VARCHAR) + ')' FROM SCALING_RATIO SR
		LEFT JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
	WHERE SR.ID_SCALING_RATIO = ADI.ID_SCALING_RATIO_FROM AND SR.ID_GOODS = ADI.ID_GOODS) AS UNIT_NAME_FROM,
	ADI.QUANTITY_FROM AS QUANTITY_FROM,
	ADI.PRICE_VAT_FROM AS PRICE_FROM,
	G.NAME AS GOODS_NAME_TO, 
	(SELECT U.NAME+ ' (' + CAST(SR.NUMERATOR AS VARCHAR) + '/' + CAST(SR.DENOMINATOR AS VARCHAR) + ')' FROM SCALING_RATIO SR
		LEFT JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
	WHERE SR.ID_SCALING_RATIO = ADI.ID_SCALING_RATIO_TO AND SR.ID_GOODS = ADI.ID_GOODS) AS UNIT_NAME_TO,
	ADI.QUANTITY AS QUANTITY_TO,
	ADI.PRICE_VAT AS PRICE_TO
FROM ACT_DISASSEMBLING_ITEM ADI
	LEFT JOIN GOODS G ON G.ID_GOODS = ADI.ID_GOODS
WHERE ADI.ID_ACT_DISASSEMBLING = @ID_ACT_DISASSEMBLING
ORDER BY GOODS_NAME_FROM

SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO
FROM CONTRACTOR
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)

	
RETURN 0
GO

--EXEC REPEX_ACT_DISASSEMBLING '<XML><ID_ACT_DISASSEMBLING>762</ID_ACT_DISASSEMBLING></XML>'
