SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_PAYMENT') IS NULL EXEC('CREATE PROCEDURE REPEX_PAYMENT AS RETURN')
GO
ALTER  PROCEDURE REPEX_PAYMENT
	(@XMLPARAM NTEXT) AS

DECLARE @HDOC INT
DECLARE @ID_PAYMENT_ORDER BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT @ID_PAYMENT_ORDER = ID_PAYMENT_ORDER
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_PAYMENT_ORDER BIGINT 'ID_PAYMENT_ORDER')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

DECLARE @NUM BIGINT
SET @NUM = (SELECT COUNT_BIG(*) FROM PAYMENT_ORDER_ITEM WHERE ID_PAYMENT_ORDER_GLOBAL = (SELECT ID_PAYMENT_ORDER_GLOBAL FROM PAYMENT_ORDER WHERE ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER))

SELECT 
	MNEMOCODE = P.MNEMOCODE,
	P_DATE = P.[DATE],
	TYPE_P = P.PAYMENT_TYPE,
	PVAT_SUM = CASE WHEN P.INCLUDE_VAT = 0 AND @NUM = 0 THEN P.SUM_VAT + P.PVAT_SUM ELSE P.SUM_VAT END,
	INN = C.INN,
	KPP = C.KPP,
	NAME_ADD = ISNULL(NULLIF(LTRIM(C.FULL_NAME), ''), C.[NAME]),
	ACCOUNT = C.ACCOUNT,
	NAME_BANK = C.BANK+' '+C.BANK_ADDRESS,
	BIK = C.BIK,
	CORR_ACCOUNT = C.CORR_ACCOUNT,
	NAME_BANK_P = C_P.BANK+' '+C_P.BANK_ADDRESS,
	BIK_P = C_P.BIK,
	CORR_ACCOUNT_P = C_P.CORR_ACCOUNT,
	INN_P = C_P.INN,
	KPP_P = C_P.KPP,
	ACCOUNT_P = C_P.ACCOUNT,
	NAME_ADD_P = ISNULL(NULLIF(LTRIM(C_P.[FULL_NAME]), ''), C_P.[NAME]),
	TYPE_OP = '01',
	PAYMENT_PERIOD = P.PAYMENT_PERIOD,
	PAYMENT_QUEUE = P.PAYMENT_QUEUE,
	PAYMENT_ASSINGMENT = P.PAYMENT_ASSINGMENT,
    SUM_DOC = CASE WHEN P.INCLUDE_VAT = 0 AND @NUM = 0 THEN P.SUM_VAT + P.PVAT_SUM ELSE P.SUM_VAT END
FROM PAYMENT_ORDER P
	LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = P.ID_PAYER
	LEFT JOIN CONTRACTOR C_P ON C_P.ID_CONTRACTOR = P.ID_RECIPIENT
WHERE P.ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER


DECLARE @NDS VARCHAR(100)
DECLARE @ID_TAX_TYPE BIGINT
DECLARE @TAX_RATE MONEY

IF (@NUM <> 0)
BEGIN

SELECT
	SUM_VAT_10 = ISNULL(SUM(CASE WHEN II.SUPPLIER_VAT = 10 THEN II.SUPPLIER_VAT_SUM ELSE 0 END), 0),
	SUM_VAT_18 = ISNULL(SUM(CASE WHEN II.SUPPLIER_VAT = 18 THEN II.SUPPLIER_VAT_SUM ELSE 0 END), 0),
	SUM_NO = 0
FROM PAYMENT_ORDER PO
	INNER JOIN PAYMENT_ORDER_ITEM POI ON POI.ID_PAYMENT_ORDER_GLOBAL = PO.ID_PAYMENT_ORDER_GLOBAL
	INNER JOIN INVOICE I ON I.ID_INVOICE = POI.ID_DOCUMENT
	INNER JOIN INVOICE_ITEM II ON II.ID_INVOICE_GLOBAL = I.ID_INVOICE_GLOBAL
WHERE PO.ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER

END
ELSE
BEGIN
	SET @ID_TAX_TYPE = (SELECT ID_TAX_TYPE FROM PAYMENT_ORDER WHERE ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER)
	SET @TAX_RATE = (SELECT TAX_RATE FROM TAX_TYPE WHERE ID_TAX_TYPE = @ID_TAX_TYPE)
	IF (@TAX_RATE IS NULL)
	BEGIN
		SELECT SUM_VAT_10 = 0, SUM_VAT_18 = 0, SUM_NO = PVAT_SUM FROM PAYMENT_ORDER WHERE ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER
	END
	ELSE
	BEGIN
		IF (@TAX_RATE = 0)
			SELECT SUM_VAT_10 = 0, SUM_VAT_18 = 0, SUM_NO = 0
		ELSE IF (@TAX_RATE = 10)
			SELECT SUM_VAT_10 = PVAT_SUM, SUM_VAT_18 = 0, SUM_NO = 0 FROM PAYMENT_ORDER WHERE ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER
		ELSE IF (@TAX_RATE = 18)
			SELECT SUM_VAT_10 = 0, SUM_VAT_18 = PVAT_SUM, SUM_NO = 0 FROM PAYMENT_ORDER WHERE ID_PAYMENT_ORDER = @ID_PAYMENT_ORDER
	END
END

SELECT
	DIR = DIRECTOR_FIO,
	BUH = BUH_FIO
FROM CONTRACTOR
WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)


RETURN 0
GO

--exec REPEX_PAYMENT '<XML><ID_PAYMENT_ORDER>96</ID_PAYMENT_ORDER></XML>'