SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
-------------------------------------------------------------------------------------------
IF OBJECT_ID('DBO.REP_KKMZREPORT_PLANET') IS NULL BEGIN
    EXEC('CREATE PROCEDURE DBO.REP_KKMZREPORT_PLANET AS RETURN')
    GRANT EXEC ON [DBO].[REP_KKMZREPORT_PLANET] TO [PUBLIC]
END
GO

ALTER PROCEDURE DBO.REP_KKMZREPORT_PLANET 
	@XMLPARAM NTEXT 
AS

/* PARAMETERS */
DECLARE @HDOC INT
DECLARE @DATE_FR DATETIME, @DATE_TO DATETIME

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 
		@DATE_FR = DATE_FR, 
		@DATE_TO = DATE_TO
	FROM OPENXML(@HDOC, '/XML') WITH(
		DATE_FR DATETIME 'DATE_FR', 
		DATE_TO DATETIME 'DATE_TO'
	)

	/* таблица идентификаторов контрагентов*/
	SELECT * INTO #CONTRACTOR
	FROM OPENXML(@HDOC, '//ID_CONTRACTOR') 
	WITH(ID_CONTRACTOR BIGINT '.')

        /* таблица идентификаторов   ћ*/
	SELECT * INTO #CASH_REGISTER
	FROM OPENXML(@HDOC, '//ID_CASH_REGISTER') 
	WITH(ID_CASH_REGISTER BIGINT '.')

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC DBO.USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT
EXEC DBO.REP_RANGEDAY @DATE_FR OUT, @DATE_TO OUT

SELECT 
	CONTRACTOR_NAME = C.NAME, 
	NAME_CASH_REGISTER = CR.NAME_CASH_REGISTER, 
	NUMBER_CASH_REGISTER = CR.NUMBER_CASH_REGISTER,
 	DATE_OPEN = CS.DATE_OPEN, 		--начало смены
	DATE_CLOSE = CS.DATE_CLOSE, 		--окончание смены
-- 	CS.SUM_PAYMENT, 		--сумма внесений
-- 	CS.SUM_REQUISITIONING,	--сумма изъ€тий
-- 	CS.SUM_SALES, 
-- 	CS.SUM_SALES_RETURNS, 
-- 	CS.CASH, 
	SUMM_IN = SUM(CASE WHEN CP.SUMM_IN IS NULL THEN 0 ELSE CP.SUMM_IN END),
	SUMM_OUT = SUM(CASE WHEN CP.SUMM_OUT IS NULL THEN 0 ELSE CP.SUMM_OUT END),
	SUMM_NAL = SUM(CASE WHEN CP.SUMM_NAL IS NULL THEN 0 ELSE CP.SUMM_NAL END),		--сумма наличных продаж
	SUMM_DISC = SUM(CASE WHEN CP.SUMM_DISCOUNT IS NULL THEN 0 ELSE CP.SUMM_DISCOUNT END),	--сумма по кредитной карте
    SUMM_SALE = SUM(CASE WHEN CP.SUMM_NAL IS NULL THEN 0 ELSE CP.SUMM_NAL END) - SUM(CASE WHEN CP.SUM_RETURN IS NULL THEN 0 ELSE CP.SUM_RETURN END) + SUM(CASE WHEN CP.SUMM_DISCOUNT IS NULL THEN 0 ELSE CP.SUMM_DISCOUNT END), --сумма продаж всего
	SUM_RETURN = SUM(CASE WHEN CP.SUM_RETURN IS NULL THEN 0 ELSE CP.SUM_RETURN END),	--возврат
--	SUM_DISCOUNT = MAX(CS.SUM_DISCOUNT),					--скидка
	SUM_DISC_NAL = SUM(CASE WHEN CP.SUM_DISC_NAL IS NULL THEN 0 ELSE CP.SUM_DISC_NAL END), --скидка по наличн.продажам
	SUM_DISC_DISCOUNT = SUM(CASE WHEN CP.SUM_DISC_DISCOUNT IS NULL THEN 0 ELSE CP.SUM_DISC_DISCOUNT END), --скидка по продажам по карте
	SUM_CASH = SUM(CASE WHEN CP.SUMM_NAL IS NULL THEN 0 ELSE CP.SUMM_NAL END) - SUM(CASE WHEN CP.SUM_RETURN IS NULL THEN 0 ELSE CP.SUM_RETURN END), --итогова€ сумма
	CS.ID_CASH_SESSION
FROM CASH_SESSION CS
INNER JOIN CASH_REGISTER CR ON CS.ID_CASH_REGISTER = CR.ID_CASH_REGISTER
INNER JOIN CONTRACTOR C ON CR.ID_CONTRACTOR = C.ID_CONTRACTOR
INNER JOIN CHEQUE CH ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
INNER JOIN (SELECT
               CP.ID_CHEQUE_GLOBAL,
			   SUMM_IN = SUM(CASE WHEN CH.CHEQUE_TYPE = 'CASH_IN' THEN CP.SUMM ELSE 0 END),
			   SUMM_OUT = SUM(CASE WHEN CH.CHEQUE_TYPE = 'CASH_OUT' THEN CP.SUMM ELSE 0 END),
               SUMM_NAL = SUM(CASE WHEN ((CP.TYPE_PAYMENT = 'TYPE1')OR(CP.TYPE_PAYMENT = 'TYPE3' AND (LEN(CP.CARD_NUMBER)=0)))AND CH.CHEQUE_TYPE='SALE' THEN CP.SUMM ELSE 0 END), --продажа наличка
               SUMM_DISCOUNT = SUM(CASE WHEN ((CP.TYPE_PAYMENT = 'TYPE2')OR(CP.TYPE_PAYMENT = 'TYPE3' AND (LEN(CP.CARD_NUMBER)>0)))AND CH.CHEQUE_TYPE='SALE' THEN CP.SUMM ELSE 0 END),--продажа по кредитке
-- 			   SUM_DISC_NAL = SUM(CASE WHEN ((CP.TYPE_PAYMENT = 'TYPE1')AND CH.CHEQUE_TYPE = 'SALE') THEN CH.SUM_DISCOUNT ELSE 0 END),	--сумма скидки при наличн.продажам
 			   SUM_DISC_NAL = SUM(CASE WHEN (CP.TYPE_PAYMENT = 'TYPE1' AND CH.CHEQUE_TYPE = 'SALE') THEN CH.SUM_DISCOUNT ELSE CASE WHEN (CP.TYPE_PAYMENT = 'TYPE1' AND CH.CHEQUE_TYPE = 'RETURN') THEN CH.SUM_DISCOUNT*-1 ELSE 0 END END),	--сумма скидки при наличн.продажам
 			   SUM_DISC_DISCOUNT = SUM(CASE WHEN (CP.TYPE_PAYMENT = 'TYPE2' AND CH.CHEQUE_TYPE = 'SALE') THEN CH.SUM_DISCOUNT ELSE CASE WHEN (CP.TYPE_PAYMENT = 'TYPE2' AND CH.CHEQUE_TYPE = 'RETURN') THEN -1* CH.SUM_DISCOUNT ELSE 0 END END), --сумма скидки при продаже по карте
-- 			   SUM_DISC_DISCOUNT = SUM(CASE WHEN (CP.TYPE_PAYMENT = 'TYPE2' AND CH.CHEQUE_TYPE = 'SALE') THEN CH.SUM_DISCOUNT ELSE 0 END), --сумма скидки при продаже по карте
			   SUM_RETURN = SUM(CASE WHEN CH.CHEQUE_TYPE = 'RETURN' THEN CP.SUMM ELSE 0 END) --возврат  -CP.SUM_DISCOUNT
           FROM CHEQUE_PAYMENT CP
           INNER JOIN CHEQUE CH ON CH.ID_CHEQUE_GLOBAL = CP.ID_CHEQUE_GLOBAL
           GROUP BY CP.ID_CHEQUE_GLOBAL) CP ON CP.ID_CHEQUE_GLOBAL = CH.ID_CHEQUE_GLOBAL
WHERE
  	CS.DATE_OPEN >= @DATE_FR AND CS.DATE_CLOSE <= @DATE_TO AND
	(CS.ID_CASH_REGISTER IN (SELECT * FROM #CASH_REGISTER) OR (SELECT COUNT(*) FROM #CASH_REGISTER)=0 ) AND
	(C.ID_CONTRACTOR IN (SELECT * FROM #CONTRACTOR) OR (SELECT COUNT(*) FROM #CONTRACTOR)=0)
	AND CH.DOCUMENT_STATE = 'PROC'
GROUP BY CS.ID_CASH_SESSION,CS.ID_CASH_SESSION, CS.DATE_OPEN, CS.DATE_CLOSE,C.NAME, CR.NAME_CASH_REGISTER, CR.NUMBER_CASH_REGISTER

RETURN 0
GO

--exec REP_KKMZREPORT_PLANET @xmlParam = N'<XML><DATE_FR>2008-12-22T13:18:27.750</DATE_FR><DATE_TO>2008-12-22T13:18:27.750</DATE_TO></XML>'
--exec REP_KKMZREPORT_PLANET @xmlParam = N'<XML><DATE_FR>2008-01-01T13:18:27.750</DATE_FR><DATE_TO>2008-12-31T13:18:27.750</DATE_TO></XML>'
