SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
---------------------------------------------------------------------------
IF (OBJECT_ID('DBO.REP_GOODS_REPORTS_GROUPS_TG_EX') IS NULL ) EXEC ('CREATE PROCEDURE DBO.REP_GOODS_REPORTS_GROUPS_TG_EX AS SELECT NULL')
GO
ALTER PROCEDURE DBO.REP_GOODS_REPORTS_GROUPS_TG_EX
         @XMLPARAM NTEXT
AS
SET NOCOUNT ON
DECLARE @NO_DETAIL BIT
DECLARE @DATE_FR DATETIME, @DATE_TO DATETIME
DECLARE @SORT_DOC BIT, @SHOW_ADD BIT, @SHOW_SUB BIT, @REFRESH_DOC_MOV BIT

DECLARE @HDOC INT, @SQL NVARCHAR(4000), @SQL_FIELDS NVARCHAR(4000)

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
    SELECT TOP 1 
        @DATE_FR = DATE_FR, @DATE_TO = DATE_TO,
        @NO_DETAIL = NO_DETAIL, @SORT_DOC = SORT_DOC,
        @SHOW_ADD = SHOW_ADD, @SHOW_SUB = SHOW_SUB,
        @REFRESH_DOC_MOV = REFRESH_DOC_MOV
    FROM OPENXML(@HDOC, '/XML') WITH(
        DATE_FR DATETIME 'DATE_FR', 
        DATE_TO DATETIME 'DATE_TO', 
        NO_DETAIL BIT 'NO_DETAIL',
        SORT_DOC BIT 'SORT_DOC', 
        SHOW_ADD BIT 'SHOW_ADD', 
        SHOW_SUB BIT 'SHOW_SUB',
        REFRESH_DOC_MOV BIT 'REFRESH_DOC_MOV')

    /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬  ŒÕ“–¿√≈Õ“Œ¬ */
--     SELECT DISTINCT C.ID_CONTRACTOR, C.NAME INTO #CONTRACTOR
--     FROM 
--         (SELECT * FROM OPENXML(@HDOC, '//ID_CONTRACTOR') 
--         WITH(ID_CONTRACTOR BIGINT '.')) TAB
--     INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = TAB.ID_CONTRACTOR
    
    /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬ — À¿ƒŒ¬ */
    SELECT DISTINCT S.ID_STORE, S.ID_CONTRACTOR, S.NAME INTO #STORE
    FROM
    	(SELECT * FROM OPENXML(@HDOC, '//ID_STORE') 
        WITH(ID_STORE BIGINT '.')) TAB
    INNER JOIN STORE S ON S.ID_STORE = TAB.ID_STORE
EXEC SP_XML_REMOVEDOCUMENT @HDOC

create table #CONTRACTOR(id_contractor bigint,name varchar(100))
insert into #contractor
select
    c.id_contractor,
    c.name
from contractor c
where exists(select null from #STORE s where s.id_contractor = c.id_contractor)

IF @REFRESH_DOC_MOV = 1 BEGIN
    -- ÔÂÂÒ˜ËÚ‡Ú¸ DOC_MOVEMENT ÔÓ ‚ÒÂÏ ‰ÓÍÛÏÂÌÚ‡Ï
    EXEC UTL_REFRESH_DOC_MOVEMENT 'REPAIR', 0
END

-- ÓÚÌÓÏËÓ‚‡Ú¸ ‰‡Ú˚
EXEC USP_RANGE_DAYS @DATE_FR OUT, @DATE_TO OUT
EXEC USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT

-- ≈—À» Õ≈ ” ¿«¿Õ — À¿ƒ, “Œ »“Œ√» ¬€¡»–¿ﬁ“—ﬂ œŒ ¬—≈Ã — À¿ƒ¿Ã
-- IF NOT EXISTS(SELECT TOP 1 1 FROM #STORE) BEGIN
--     INSERT INTO #STORE (ID_STORE, ID_CONTRACTOR, NAME)
--     SELECT S.ID_STORE, S.ID_CONTRACTOR, S.NAME
--     FROM STORE S(NOLOCK) INNER JOIN #CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
-- END
-- DELETE FROM #STORE WHERE ID_CONTRACTOR NOT IN (SELECT ID_CONTRACTOR FROM #CONTRACTOR)

-- Œ—“¿“Œ  Õ¿ Õ¿◊¿ÀŒ
SELECT
    SUM_SUP = SUM(DM.SUM_SUP * DM.SIGN_OP),
    SUM_ACC = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP),
	NAL = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP - DM.SUM_SUP * DM.SIGN_OP),
    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,

    SUM_SVAT_SUP = SUM(DM.SVAT_SUP * DM.SIGN_OP),
    SUM_SVAT_ACC = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP),

    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP),
    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP),
    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP),

    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP),
    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP)
FROM DOC_MOVEMENT DM
WHERE DATE_OP < @DATE_FR
AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)

IF(@SHOW_ADD = 1) BEGIN
	-- Œ¡Ÿ»… œ–»’Œƒ œŒ ƒŒ ”Ã≈Õ“¿Ã
    SELECT
        ID_DOCUMENT = DM.ID_DOCUMENT,
        DOC_NAME = ISNULL(TD.DESCRIPTION+': ','')+CASE WHEN DM.ID_TABLE=19 THEN '' ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END,--(SELECT TOP 1 [DESCRIPTION_EXT] FROM FN_DOC_MOVEMENT_DESCRIPTION() DMD
        DATE_OP = DM.DATE_OP, 
        DOC_NUM = AD.DOC_NUM,
		INCOMING_NUMBER = CASE WHEN DM.ID_TABLE = 2 THEN ISNULL('π Õœ:'+ I.INCOMING_NUMBER,'') ELSE '' END,

	    SUM_SUP = SUM(DM.SUM_SUP),
	    SUM_ACC = SUM(DM.SUM_ACC),--SUM(CASE WHEN CODE_OP<>'DIS' THEN DM.SUM_ACC ELSE 0 END),
		NAL = SUM(DM.SUM_ACC - DM.SUM_SUP),
	    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,
	
	    SUM_SVAT_SUP = SUM(DM.SVAT_SUP),
	    SUM_SVAT_ACC = SUM(DM.SVAT_ACC),--SUM(CASE WHEN CODE_OP<>'DIS' THEN DM.SVAT_ACC ELSE 0 END),
	
	    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN SUM_ACC ELSE 0 END),
	    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE =10 THEN SUM_ACC ELSE 0 END),
	    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SUM_ACC ELSE 0 END),
	
	    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN SVAT_ACC ELSE 0 END),
	    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN SVAT_ACC ELSE 0 END)
    FROM DOC_MOVEMENT DM
    INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = DM.ID_TABLE
    INNER JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = DM.ID_DOCUMENT
	LEFT JOIN INVOICE I ON DM.ID_DOCUMENT = I.ID_INVOICE_GLOBAL
    LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
    LEFT JOIN STORE S ON S.ID_STORE = DM.ID_STORE_FROM
    WHERE --(CODE_OP='ADD' OR (CODE_OP='DIS' AND DM.ID_TABLE=19 AND SIGN_OP=-1))
    DM.CODE_OP='ADD' AND DM.ID_TABLE<>19
	AND DATE_OP BETWEEN @DATE_FR AND @DATE_TO
	AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)	 
    GROUP BY DM.ID_DOCUMENT, 
			 DM.ID_TABLE, 
			 TD.DESCRIPTION, 
			 DM.DATE_OP, 
			 AD.DOC_NUM,
  			 CASE WHEN DM.ID_TABLE = 2 THEN ISNULL('π Õœ:'+ I.INCOMING_NUMBER,'') ELSE '' END,
			 ISNULL(TD.DESCRIPTION+': ','')+CASE WHEN DM.ID_TABLE=19 THEN '' ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END,
			 CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(DM.ID_CONTRACTOR_FROM, 0) END,
             CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END
    ORDER BY CASE WHEN NULLIF(@SORT_DOC,0) IS NULL THEN DM.DATE_OP ELSE DM.ID_TABLE END, DM.DATE_OP
END
ELSE BEGIN
    SELECT
        ID_DOCUMENT = CAST(NULL AS UNIQUEIDENTIFIER),
        DOC_NAME = CAST(NULL AS NVARCHAR(128)),
		DATE_OP = CAST(NULL AS DATETIME),
		DOC_NUM = CAST(NULL AS NVARCHAR(128)),
		INCOMING_NUMBER = CAST(NULL AS NVARCHAR(128)),
        SUM_SUP = CAST(NULL AS MONEY),
        SUM_ACC = CAST(NULL AS MONEY),
		KOF = CAST(NULL AS BIT),
		SUM_SVAT_SUP = CAST(NULL AS MONEY),
		SUM_SVAT_ACC = CAST(NULL AS MONEY),
		SUM_SUP0 = CAST(NULL AS MONEY),
		SUM_SUP10 = CAST(NULL AS MONEY),
		SUM_SUP18 = CAST(NULL AS MONEY),
		SUM_ACC0 = CAST(NULL AS MONEY),
		SUM_ACC10 = CAST(NULL AS MONEY),
		SUM_ACC18 = CAST(NULL AS MONEY),
	    SVAT_SUP10 = CAST(NULL AS MONEY),
	    SVAT_SUP18 = CAST(NULL AS MONEY),
	    SVAT_ACC10 = CAST(NULL AS MONEY),
	    SVAT_ACC18 = CAST(NULL AS MONEY)
END

IF(@SHOW_SUB = 1) BEGIN
	-- Œ¡Ÿ»… –¿—’Œƒ œŒ ƒŒ ”Ã≈Õ“¿Ã
	SELECT 
        ID_DOCUMENT = DM.ID_DOCUMENT,
        DOC_NAME = ISNULL(TD.DESCRIPTION+': ','')+CASE WHEN DM.ID_TABLE=19 THEN '' ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END,--(SELECT TOP 1 [DESCRIPTION_EXT] FROM FN_DOC_MOVEMENT_DESCRIPTION() DMD
        DATE_OP = DM.DATE_OP, 
        DOC_NUM = AD.DOC_NUM,
		
		SUM_DIS = SUM(CASE WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE=19 THEN DM.SUM_ACC * DM.SIGN_OP
						   WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE<>19 THEN DM.SUM_ACC
						   ELSE 0 END),
        SUM_DIS_0 = SUM(CASE WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE=19 AND DM.VAT_RATE = 0 THEN DM.SUM_ACC * DM.SIGN_OP
						   WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE<>19 AND DM.VAT_RATE = 0 THEN DM.SUM_ACC
						   ELSE 0 END),
        SUM_DIS_10 = SUM(CASE WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE=19 AND DM.VAT_RATE = 10 THEN DM.SUM_ACC * DM.SIGN_OP
						   WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE<>19 AND DM.VAT_RATE = 10 THEN DM.SUM_ACC
						   ELSE 0 END),
        SUM_DIS_18 = SUM(CASE WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE=19 AND DM.VAT_RATE = 18 THEN DM.SUM_ACC * DM.SIGN_OP
						   WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE<>19 AND DM.VAT_RATE = 18 THEN DM.SUM_ACC
						   ELSE 0 END),
 	    SUM_SUP =  SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
 						   ELSE DM.SUM_SUP * DM.SIGN_OP * -1
 						   END),

	    SUM_ACC = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
						   ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   END),
		NAL = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_ACC * DM.SIGN_OP * -1 END - 
				  CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_SUP * DM.SIGN_OP * -1 END),
	    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,
	
	    SUM_SVAT_SUP = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
						   ELSE DM.SVAT_SUP * DM.SIGN_OP * -1
						   END),--SUM(DM.SVAT_SUP),
	    SUM_SVAT_ACC = SUM(CASE WHEN DM.CODE_OP='DIS' THEN 0
						   ELSE DM.SVAT_ACC * DM.SIGN_OP * -1
						   END),--SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP),
	
	    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN DM.SUM_SUP*SIGN_OP*-1 ELSE 0 END),
	    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SUM_SUP*SIGN_OP*-1 ELSE 0 END),
	    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SUM_SUP*SIGN_OP*-1 ELSE 0 END),
	    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SUM_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	
	    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN DM.SVAT_SUP*SIGN_OP*-1 ELSE 0 END),
	    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN DM.SVAT_SUP*SIGN_OP*-1 ELSE 0 END),
	    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SVAT_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END),
	    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN 
									CASE WHEN DM.CODE_OP='DIS' THEN 0
		 						    ELSE DM.SVAT_ACC * DM.SIGN_OP * -1
						   			END 
												ELSE 0 END)	
	INTO #T
    FROM DOC_MOVEMENT DM
    INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = DM.ID_TABLE
    LEFT JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = DM.ID_DOCUMENT
    LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_TO
    LEFT JOIN STORE S ON S.ID_STORE = DM.ID_STORE_TO
    WHERE (CODE_OP IN ('SUB', 'DIS') OR DM.ID_TABLE=19)
		AND DATE_OP BETWEEN @DATE_FR AND @DATE_TO
		AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)	 
    GROUP BY DM.ID_DOCUMENT, 
		     DM.ID_TABLE, 
             TD.DESCRIPTION, 
             DM.DATE_OP, 
             AD.DOC_NUM,
			 ISNULL(TD.DESCRIPTION+': ','')+CASE WHEN DM.ID_TABLE=19 THEN '' ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END,
			 CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(DM.ID_CONTRACTOR_TO, 0) END,
			 CASE WHEN DM.ID_TABLE=19 THEN NULL ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END			
    ORDER BY CASE WHEN NULLIF(@SORT_DOC,0) IS NULL THEN DM.DATE_OP ELSE DM.ID_TABLE END, DM.DATE_OP

	SELECT * FROM #T

	SELECT SUM_DIS = SUM(SUM_DIS) FROM #T
END
ELSE BEGIN
    SELECT
        ID_DOCUMENT = CAST(NULL AS UNIQUEIDENTIFIER),
        DOC_NAME = CAST(NULL AS NVARCHAR(128)),
		DATE_OP = CAST(NULL AS DATETIME),
		DOC_NUM = CAST(NULL AS NVARCHAR(128)),
		SUM_DIS = CAST(NULL AS MONEY),
		SUM_DIS_0 = CAST(NULL AS MONEY),
		SUM_DIS_10 = CAST(NULL AS MONEY),
		SUM_DIS_18 = CAST(NULL AS MONEY),
        SUM_SUP = CAST(NULL AS MONEY),
        SUM_ACC = CAST(NULL AS MONEY),
		KOF = CAST(NULL AS BIT),
		SUM_SVAT_SUP = CAST(NULL AS MONEY),
		SUM_SVAT_ACC = CAST(NULL AS MONEY),
		SUM_SUP0 = CAST(NULL AS MONEY),
		SUM_SUP10 = CAST(NULL AS MONEY),
		SUM_SUP18 = CAST(NULL AS MONEY),
		SUM_ACC0 = CAST(NULL AS MONEY),
		SUM_ACC10 = CAST(NULL AS MONEY),
		SUM_ACC18 = CAST(NULL AS MONEY),
	    SVAT_SUP10 = CAST(NULL AS MONEY),
	    SVAT_SUP18 = CAST(NULL AS MONEY),
	    SVAT_ACC10 = CAST(NULL AS MONEY),
	    SVAT_ACC18 = CAST(NULL AS MONEY)
	    
	SELECT SUM_DIS = NULL
END

DECLARE @STORES VARCHAR(1024)
DECLARE @CONTRACTORS VARCHAR(1024)

EXEC DBO.USP_TABLE_NAMES '#STORE', @STORES OUT
EXEC DBO.USP_TABLE_NAMES '#CONTRACTOR', @CONTRACTORS OUT
SELECT CONTRACTOR = @CONTRACTORS, STORE = @STORES

-- Œ—“¿“Œ  Õ¿  ŒÕ≈÷
    SELECT
        SUM_SUP = SUM(DM.SUM_SUP * DM.SIGN_OP),
        SUM_ACC = SUM(CASE WHEN ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP),
		NAL = SUM(CASE WHEN ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP - DM.SUM_SUP * DM.SIGN_OP),
	    KOF = CASE WHEN MAX(CODE_OP) = 'DIS' THEN 0 ELSE 1 END,
	
	    SUM_SVAT_SUP = SUM(DM.SVAT_SUP * DM.SIGN_OP),
	    SUM_SVAT_ACC = SUM(CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP),
	
	    SUM_SUP0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END),
	    SUM_ACC0 = SUM(CASE WHEN DM.VAT_RATE = 0 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP),
	    SUM_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP),
	    SUM_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP),
	    SVAT_SUP10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_SUP18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END),
	    SVAT_ACC10 = SUM(CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP),
	    SVAT_ACC18 = SUM(CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP)
    FROM DOC_MOVEMENT DM
    WHERE DATE_OP <= @DATE_TO
    AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)

RETURN 0
GO

SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO
--------------------------------------------------------------------
IF (OBJECT_ID('DBO.REP_GOODS_REPORTS_TO_EX_SERVICE') IS NULL ) EXEC ('CREATE PROCEDURE DBO.REP_GOODS_REPORTS_TO_EX_SERVICE AS SELECT NULL')
GO
ALTER PROCEDURE DBO.REP_GOODS_REPORTS_TO_EX_SERVICE
         @XMLPARAM NTEXT
AS
SET NOCOUNT ON
DECLARE @NO_DETAIL BIT
DECLARE @DATE_FR DATETIME, @DATE_TO DATETIME
DECLARE @SORT_DOC BIT, @SHOW_ADD BIT, @SHOW_SUB BIT, @REFRESH_DOC_MOV BIT

DECLARE @HDOC INT, @SQL NVARCHAR(4000), @SQL_FIELDS NVARCHAR(4000)

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
    SELECT TOP 1 
        @DATE_FR = DATE_FR, @DATE_TO = DATE_TO,
        @NO_DETAIL = NO_DETAIL, @SORT_DOC = SORT_DOC,
        @SHOW_ADD = SHOW_ADD, @SHOW_SUB = SHOW_SUB,
        @REFRESH_DOC_MOV = REFRESH_DOC_MOV
    FROM OPENXML(@HDOC, '/XML') WITH(
        DATE_FR DATETIME 'DATE_FR', 
        DATE_TO DATETIME 'DATE_TO', 
        NO_DETAIL BIT 'NO_DETAIL',
        SORT_DOC BIT 'SORT_DOC', 
        SHOW_ADD BIT 'SHOW_ADD', 
        SHOW_SUB BIT 'SHOW_SUB',
        REFRESH_DOC_MOV BIT 'REFRESH_DOC_MOV')

    /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬  ŒÕ“–¿√≈Õ“Œ¬ */
--     SELECT DISTINCT C.ID_CONTRACTOR, C.NAME INTO #CONTRACTOR
--     FROM 
--         (SELECT * FROM OPENXML(@HDOC, '//ID_CONTRACTOR') 
--         WITH(ID_CONTRACTOR BIGINT '.')) TAB
--     INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = TAB.ID_CONTRACTOR
    /* “¿¡À»÷¿ »ƒ≈Õ“»‘» ¿“Œ–Œ¬ — À¿ƒŒ¬ */
    SELECT DISTINCT S.ID_STORE, S.ID_CONTRACTOR, S.NAME INTO #STORE
    FROM
    	(SELECT * FROM OPENXML(@HDOC, '//ID_STORE') 
        WITH(ID_STORE BIGINT '.')) TAB
    INNER JOIN STORE S ON S.ID_STORE = TAB.ID_STORE
    EXEC SP_XML_REMOVEDOCUMENT @HDOC

    create table #CONTRACTOR(id_contractor bigint,name varchar(100))
    insert into #contractor
    select
        c.id_contractor,
        c.name
    from contractor c
    where exists(select null from #STORE s where s.id_contractor = c.id_contractor)
          
    IF @REFRESH_DOC_MOV = 1 BEGIN
        -- ÔÂÂÒ˜ËÚ‡Ú¸ DOC_MOVEMENT ÔÓ ‚ÒÂÏ ‰ÓÍÛÏÂÌÚ‡Ï
        EXEC UTL_REFRESH_DOC_MOVEMENT 'REPAIR', 0
    END

-- ÓÚÌÓÏËÓ‚‡Ú¸ ‰‡Ú˚
EXEC USP_RANGE_DAYS @DATE_FR OUT, @DATE_TO OUT
EXEC USP_RANGE_NORM @DATE_FR OUT, @DATE_TO OUT

-- ≈—À» Õ≈ ” ¿«¿Õ — À¿ƒ, “Œ »“Œ√» ¬€¡»–¿ﬁ“—ﬂ œŒ ¬—≈Ã — À¿ƒ¿Ã
IF NOT EXISTS(SELECT TOP 1 1 FROM #STORE) BEGIN
    INSERT INTO #STORE (ID_STORE, ID_CONTRACTOR, NAME)
    SELECT S.ID_STORE, S.ID_CONTRACTOR, S.NAME
    FROM STORE S(NOLOCK) INNER JOIN #CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
END
DELETE FROM #STORE WHERE ID_CONTRACTOR NOT IN (SELECT ID_CONTRACTOR FROM #CONTRACTOR)

-- Œ—“¿“Œ  Õ¿ Õ¿◊¿ÀŒ
SELECT
	SUM_SUP = SUM(S1.SUM_SUP),
    SUM_ACC = SUM(S1.SUM_ACC),
	NAL = SUM(S1.NAL),
    --KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,

    SUM_SVAT_SUP = SUM(S1.SUM_SVAT_SUP),
    SUM_SVAT_ACC = SUM(S1.SUM_SVAT_ACC),

    SUM_SUP0 = SUM(S1.SUM_SUP0),
    SUM_SUP10 = SUM(S1.SUM_SUP10),
    SUM_SUP18 = SUM(S1.SUM_SUP18),
    SUM_ACC0 = SUM(S1.SUM_ACC0),
    SUM_ACC10 = SUM(S1.SUM_ACC10),
    SUM_ACC18 = SUM(S1.SUM_ACC18),

    SVAT_SUP10 = SUM(S1.SVAT_SUP10),
    SVAT_SUP18 = SUM(S1.SVAT_SUP18),
    SVAT_ACC10 = SUM(S1.SVAT_ACC10),
    SVAT_ACC18 = SUM(S1.SVAT_ACC18)
FROM
(
SELECT
    SUM_SUP = DM.SUM_SUP * DM.SIGN_OP,
    SUM_ACC = CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP,
	NAL = CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * (DM.SUM_ACC - DM.SUM_SUP) * DM.SIGN_OP,
    --KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,

    SUM_SVAT_SUP = DM.SVAT_SUP * DM.SIGN_OP,
    SUM_SVAT_ACC = CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP,

    SUM_SUP0 = CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
    SUM_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
    SUM_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
    SUM_ACC0 = CASE WHEN DM.VAT_RATE = 0 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP,
    SUM_ACC10 = CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP,
    SUM_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP,

    SVAT_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END,
    SVAT_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END,
    SVAT_ACC10 = CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP,
    SVAT_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP
FROM DOC_MOVEMENT DM
WHERE DATE_OP < @DATE_FR
    AND (DM.ID_STORE IS NOT NULL AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE))

UNION ALL

SELECT	
	SUM_SUP = 0,
	SUM_ACC = CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
	NAL = CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
	--KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,

	SUM_SVAT_SUP = 0,
	SUM_SVAT_ACC = CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY,

	SUM_SUP0 = 0,
	SUM_SUP10 = 0,
	SUM_SUP18 = 0,
	SUM_ACC0 = CASE WHEN TT.TAX_RATE = 0 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
	SUM_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
	SUM_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,

    SVAT_SUP10 = 0,
    SVAT_SUP18 = 0,
    SVAT_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
    SVAT_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END
FROM CHEQUE_ITEM CH_I
     INNER JOIN CHEQUE CH ON CH.ID_CHEQUE_GLOBAL = CH_I.ID_CHEQUE_GLOBAL
     INNER JOIN CASH_SESSION CS ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
     INNER JOIN SERVICE_4_SALE_ITEM S4S ON S4S.ID_SERVICE_4_SALE = CH_I.ID_LOT_GLOBAL
     INNER JOIN SERVICE S ON S.ID_SERVICE = S4S.ID_SERVICE
     INNER JOIN TAX_TYPE TT ON TT.ID_TAX_TYPE = S.ID_TAX_TYPE
WHERE CS.DATE_CLOSE < @DATE_FR
and exists(select null from lot l where l.id_lot_global = ch_i.id_lot_global
           and exists (select null from #store s where s.id_store = l.id_store))

) AS S1

---œ–»’Œƒ
IF(@SHOW_ADD = 1) BEGIN
SELECT
	ID_DOCUMENT = R1.ID_DOCUMENT,	
	DOC_NAME = R1.DOC_NAME,
	DATE_OP = R1.DATE_OP,
	DOC_NUM = R1.DOC_NUM,
	INCOMING_NUMBER = MAX(R1.INCOMING_NUMBER),

	SUM_SUP = SUM(R1.SUM_SUP),
    SUM_ACC = SUM(R1.SUM_ACC),
	NAL = SUM(R1.NAL),
    --KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,

    SUM_SVAT_SUP = SUM(R1.SUM_SVAT_SUP),
    SUM_SVAT_ACC = SUM(R1.SUM_SVAT_ACC),

    SUM_SUP0 = SUM(R1.SUM_SUP0),
    SUM_SUP10 = SUM(R1.SUM_SUP10),
    SUM_SUP18 = SUM(R1.SUM_SUP18),
    SUM_ACC0 = SUM(R1.SUM_ACC0),
    SUM_ACC10 = SUM(R1.SUM_ACC10),
    SUM_ACC18 = SUM(R1.SUM_ACC18),

    SVAT_SUP10 = SUM(R1.SVAT_SUP10),
    SVAT_SUP18 = SUM(R1.SVAT_SUP18),
    SVAT_ACC10 = SUM(R1.SVAT_ACC10),
    SVAT_ACC18 = SUM(R1.SVAT_ACC18)
FROM
(
SELECT
	ID_DOCUMENT = DM.ID_DOCUMENT,
	DOC_NAME = ISNULL(TD.DESCRIPTION+': ','')+CASE WHEN DM.ID_TABLE=19 THEN '' ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END,
	DATE_OP = DM.DATE_OP,
	DOC_NUM = AD.DOC_NUM,
	INCOMING_NUMBER = CASE WHEN DM.ID_TABLE = 2 THEN ISNULL('π Õœ:'+ I.INCOMING_NUMBER,'') ELSE '' END,

	SUM_SUP = DM.SUM_SUP,
	SUM_ACC = DM.SUM_ACC,
	NAL = DM.SUM_ACC - DM.SUM_SUP,
	--KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,
	
	SUM_SVAT_SUP = DM.SVAT_SUP,
	SUM_SVAT_ACC = DM.SVAT_ACC,
	
	SUM_SUP0 = CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
	SUM_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
	SUM_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
	SUM_ACC0 = CASE WHEN DM.VAT_RATE = 0 THEN SUM_ACC ELSE 0 END,
	SUM_ACC10 = CASE WHEN DM.VAT_RATE =10 THEN SUM_ACC ELSE 0 END,
	SUM_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN SUM_ACC ELSE 0 END,
	
	SVAT_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END,
	SVAT_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END,
	SVAT_ACC10 = CASE WHEN DM.VAT_RATE = 10 THEN SVAT_ACC ELSE 0 END,
	SVAT_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN SVAT_ACC ELSE 0 END

FROM DOC_MOVEMENT DM
    INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = DM.ID_TABLE
    INNER JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = DM.ID_DOCUMENT
	LEFT JOIN INVOICE I ON DM.ID_DOCUMENT = I.ID_INVOICE_GLOBAL
    LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_FROM
    LEFT JOIN STORE S ON S.ID_STORE = DM.ID_STORE_FROM
WHERE DM.CODE_OP='ADD' AND DM.ID_TABLE<>19--(CODE_OP='ADD' OR (CODE_OP='DIS' AND DM.ID_TABLE=19 AND SIGN_OP=-1))
	AND (DATE_OP BETWEEN @DATE_FR AND @DATE_TO)
	AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE)	 

-- UNION ALL
-- 
-- SELECT
-- 	ID_DOCUMENT = CS.ID_CASH_SESSION_GLOBAL,
-- 	DOC_NAME = ' ‡ÒÒÓ‚‡ˇ ÒÏÂÌ‡:',
-- 	DATE_OP = CS.DATE_CLOSE,
-- 	DOC_NUM = CS.MNEMOCODE,
-- 	INCOMING_NUMBER = '',
-- 
-- 	SUM_SUP = 0,
-- 	SUM_ACC =  S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
-- 	NAL = S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
-- 
-- 	SUM_SVAT_SUP = 0,
-- 	SUM_SVAT_ACC = (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY,
-- 
-- 	SUM_SUP0 = 0,
-- 	SUM_SUP10 = 0,
-- 	SUM_SUP18 = 0,
-- 	SUM_ACC0 = CASE WHEN TT.TAX_RATE = 0 THEN S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
-- 	SUM_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
-- 	SUM_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
-- 
--     SVAT_SUP10 = 0,
--     SVAT_SUP18 = 0,
--     SVAT_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
--     SVAT_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END
-- FROM CHEQUE_ITEM CH_I
-- 	INNER JOIN CHEQUE CH ON CH.ID_CHEQUE_GLOBAL = CH_I.ID_CHEQUE_GLOBAL
-- 	INNER JOIN CASH_SESSION CS ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
-- 	INNER JOIN SERVICE_4_SALE_ITEM S4S ON S4S.ID_SERVICE_4_SALE = CH_I.ID_LOT_GLOBAL
-- 	INNER JOIN SERVICE S ON S.ID_SERVICE = S4S.ID_SERVICE
-- 	INNER JOIN TAX_TYPE TT ON TT.ID_TAX_TYPE = S.ID_TAX_TYPE
-- WHERE CH.CHEQUE_TYPE = 'RETURN' AND CS.DATE_CLOSE BETWEEN @DATE_FR AND @DATE_TO
-- and exists(select null from lot l where l.id_lot_global = ch_i.id_lot_global
--            and exists (select null from #store s where s.id_store = l.id_store))
) AS R1
GROUP BY R1.ID_DOCUMENT, R1.DATE_OP, R1.DOC_NAME, R1.DOC_NUM
ORDER BY CASE WHEN @SORT_DOC = 0 THEN NULL ELSE R1.DOC_NAME END, R1.DATE_OP

END
ELSE BEGIN
    SELECT
        ID_DOCUMENT = CAST(NULL AS UNIQUEIDENTIFIER),
        DOC_NAME = CAST(NULL AS NVARCHAR(128)),
		DATE_OP = CAST(NULL AS DATETIME),
		DOC_NUM = CAST(NULL AS NVARCHAR(128)),
		INCOMING_NUMBER = CAST(NULL AS NVARCHAR(128)),
        SUM_SUP = CAST(NULL AS MONEY),
        SUM_ACC = CAST(NULL AS MONEY),
		KOF = CAST(NULL AS BIT),
		SUM_SVAT_SUP = CAST(NULL AS MONEY),
		SUM_SVAT_ACC = CAST(NULL AS MONEY),
		SUM_SUP0 = CAST(NULL AS MONEY),
		SUM_SUP10 = CAST(NULL AS MONEY),
		SUM_SUP18 = CAST(NULL AS MONEY),
		SUM_ACC0 = CAST(NULL AS MONEY),
		SUM_ACC10 = CAST(NULL AS MONEY),
		SUM_ACC18 = CAST(NULL AS MONEY),
	    SVAT_SUP10 = CAST(NULL AS MONEY),
	    SVAT_SUP18 = CAST(NULL AS MONEY),
	    SVAT_ACC10 = CAST(NULL AS MONEY),
	    SVAT_ACC18 = CAST(NULL AS MONEY)
END

-- Œ¡Ÿ»… –¿—’Œƒ œŒ ƒŒ ”Ã≈Õ“¿Ã
IF(@SHOW_SUB = 1)
BEGIN

SELECT
	ID_DOCUMENT = R1.ID_DOCUMENT,
	DOC_NAME = R1.DOC_NAME,
	DATE_OP = R1.DATE_OP,
	DOC_NUM = R1.DOC_NUM,

	SUM_DIS = SUM(R1.SUM_DIS),
	SUM_SUP = SUM(R1.SUM_SUP),
    SUM_ACC = SUM(R1.SUM_ACC),
	NAL = SUM(R1.NAL),
    KOF = MAX(R1.KOF),

    SUM_SVAT_SUP = SUM(R1.SUM_SVAT_SUP),
    SUM_SVAT_ACC = SUM(R1.SUM_SVAT_ACC),

    SUM_SUP0 = SUM(R1.SUM_SUP0),
    SUM_SUP10 = SUM(R1.SUM_SUP10),
    SUM_SUP18 = SUM(R1.SUM_SUP18),
    SUM_ACC0 = SUM(R1.SUM_ACC0),
    SUM_ACC10 = SUM(R1.SUM_ACC10),
    SUM_ACC18 = SUM(R1.SUM_ACC18),

    SVAT_SUP10 = SUM(R1.SVAT_SUP10),
    SVAT_SUP18 = SUM(R1.SVAT_SUP18),
    SVAT_ACC10 = SUM(R1.SVAT_ACC10),
    SVAT_ACC18 = SUM(R1.SVAT_ACC18)
INTO #temp_t
FROM
(
SELECT 
	ID_DOCUMENT = DM.ID_DOCUMENT,
	DOC_NAME = ISNULL(TD.DESCRIPTION+': ','')+CASE WHEN DM.ID_TABLE=19 THEN '' ELSE ISNULL(C.NAME,'')+ISNULL('('+S.NAME+')','') END,
	DATE_OP = DM.DATE_OP,
	DOC_NUM = AD.DOC_NUM,
		
	SUM_DIS = CASE WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE=19 THEN DM.SUM_ACC * DM.SIGN_OP WHEN DM.CODE_OP='DIS' AND DM.ID_TABLE<>19 THEN DM.SUM_ACC ELSE 0 END,
	SUM_SUP = CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_SUP * DM.SIGN_OP * -1 END,
	SUM_ACC = CASE WHEN DM.CODE_OP='DIS' THEN 0	ELSE DM.SUM_ACC * DM.SIGN_OP * -1 END,
	NAL = CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_ACC * DM.SIGN_OP * -1 END -	CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_SUP * DM.SIGN_OP * -1 END,
	KOF = CASE WHEN DM.CODE_OP = 'DIS' THEN 0 ELSE 1 END,
	
	SUM_SVAT_SUP = CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SVAT_SUP * DM.SIGN_OP * -1	END,
	SUM_SVAT_ACC = CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SVAT_ACC * DM.SIGN_OP * -1 END,
	
	SUM_SUP0 = CASE WHEN DM.VAT_RATE = 0 THEN DM.SUM_SUP* DM.SIGN_OP * -1 ELSE 0 END,
	SUM_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN DM.SUM_SUP* DM.SIGN_OP * -1 ELSE 0 END,
	SUM_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN DM.SUM_SUP* DM.SIGN_OP * -1 ELSE 0 END,
	SUM_ACC0 = CASE WHEN DM.VAT_RATE = 0 THEN CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_ACC * DM.SIGN_OP * -1 END ELSE 0 END,
	SUM_ACC10 = CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_ACC * DM.SIGN_OP * -1 END	ELSE 0 END,
	SUM_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SUM_ACC * DM.SIGN_OP * -1	END ELSE 0 END,
	
	SVAT_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN DM.SVAT_SUP* DM.SIGN_OP * -1 ELSE 0 END,
	SVAT_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN DM.SVAT_SUP* DM.SIGN_OP * -1 ELSE 0 END,
	SVAT_ACC10 = CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SVAT_ACC * DM.SIGN_OP * -1 END ELSE 0 END,
	SVAT_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.CODE_OP='DIS' THEN 0 ELSE DM.SVAT_ACC * DM.SIGN_OP * -1 END ELSE 0 END
FROM DOC_MOVEMENT DM
    INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = DM.ID_TABLE
    INNER JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = DM.ID_DOCUMENT
    LEFT JOIN CONTRACTOR C ON C.ID_CONTRACTOR = DM.ID_CONTRACTOR_TO
    LEFT JOIN STORE S ON S.ID_STORE = DM.ID_STORE_TO
WHERE (CODE_OP IN ('SUB', 'DIS') OR DM.ID_TABLE=19)
		AND DATE_OP BETWEEN @DATE_FR AND @DATE_TO
		AND (DM.ID_STORE IS NOT NULL AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE))

UNION ALL

SELECT
	ID_DOCUMENT = CS.ID_CASH_SESSION_GLOBAL,
	DOC_NAME = ' ‡ÒÒÓ‚‡ˇ ÒÏÂÌ‡:',
	DATE_OP = CS.DATE_CLOSE,
	DOC_NUM = CS.MNEMOCODE,
	
	SUM_DIS = 0,
	SUM_SUP = 0,
	SUM_ACC = S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
	NAL = S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
	KOF = 1,

	SUM_SVAT_SUP = 0,
	SUM_SVAT_ACC = (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY,

	SUM_SUP0 = 0,
	SUM_SUP10 = 0,
	SUM_SUP18 = 0,
	SUM_ACC0 = CASE WHEN TT.TAX_RATE = 0 THEN S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
	SUM_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
	SUM_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,

    SVAT_SUP10 = 0,
    SVAT_SUP18 = 0,
    SVAT_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
    SVAT_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END
FROM CHEQUE_ITEM CH_I
	INNER JOIN CHEQUE CH ON CH.ID_CHEQUE_GLOBAL = CH_I.ID_CHEQUE_GLOBAL
	INNER JOIN CASH_SESSION CS ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
	INNER JOIN SERVICE_4_SALE_ITEM S4S ON S4S.ID_SERVICE_4_SALE = CH_I.ID_LOT_GLOBAL
	INNER JOIN SERVICE S ON S.ID_SERVICE = S4S.ID_SERVICE
	INNER JOIN TAX_TYPE TT ON TT.ID_TAX_TYPE = S.ID_TAX_TYPE
WHERE CH.CHEQUE_TYPE = 'SALE' AND CS.DATE_CLOSE BETWEEN @DATE_FR AND @DATE_TO
) AS R1
GROUP BY R1.ID_DOCUMENT, R1.DATE_OP, R1.DOC_NAME, R1.DOC_NUM
ORDER BY CASE WHEN @SORT_DOC = 0 THEN NULL ELSE R1.DOC_NAME END, R1.DATE_OP

SELECT * FROM #temp_t

SELECT SUM_DIS = SUM(SUM_DIS) FROM #temp_t

END
ELSE BEGIN
    SELECT
        ID_DOCUMENT = CAST(NULL AS UNIQUEIDENTIFIER),
        DOC_NAME = CAST(NULL AS NVARCHAR(128)),
		DATE_OP = CAST(NULL AS DATETIME),
		DOC_NUM = CAST(NULL AS NVARCHAR(128)),
		SUM_DIS = CAST(NULL AS MONEY),
        SUM_SUP = CAST(NULL AS MONEY),
        SUM_ACC = CAST(NULL AS MONEY),
		KOF = CAST(NULL AS BIT),
		SUM_SVAT_SUP = CAST(NULL AS MONEY),
		SUM_SVAT_ACC = CAST(NULL AS MONEY),
		SUM_SUP0 = CAST(NULL AS MONEY),
		SUM_SUP10 = CAST(NULL AS MONEY),
		SUM_SUP18 = CAST(NULL AS MONEY),
		SUM_ACC0 = CAST(NULL AS MONEY),
		SUM_ACC10 = CAST(NULL AS MONEY),
		SUM_ACC18 = CAST(NULL AS MONEY),
	    SVAT_SUP10 = CAST(NULL AS MONEY),
	    SVAT_SUP18 = CAST(NULL AS MONEY),
	    SVAT_ACC10 = CAST(NULL AS MONEY),
	    SVAT_ACC18 = CAST(NULL AS MONEY)
	    
	SELECT SUM_DIS = NULL
END

DECLARE @STORES VARCHAR(1024)
DECLARE @CONTRACTORS VARCHAR(1024)

EXEC DBO.USP_TABLE_NAMES '#STORE', @STORES OUT
EXEC DBO.USP_TABLE_NAMES '#CONTRACTOR', @CONTRACTORS OUT
SELECT CONTRACTOR = @CONTRACTORS, STORE = @STORES

-- Œ—“¿“Œ  Õ¿  ŒÕ≈÷
SELECT
	SUM_SUP = SUM(S1.SUM_SUP),
    SUM_ACC = SUM(S1.SUM_ACC),
	NAL = SUM(S1.NAL),
    --KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,

    SUM_SVAT_SUP = SUM(S1.SUM_SVAT_SUP),
    SUM_SVAT_ACC = SUM(S1.SUM_SVAT_ACC),

    SUM_SUP0 = SUM(S1.SUM_SUP0),
    SUM_SUP10 = SUM(S1.SUM_SUP10),
    SUM_SUP18 = SUM(S1.SUM_SUP18),
    SUM_ACC0 = SUM(S1.SUM_ACC0),
    SUM_ACC10 = SUM(S1.SUM_ACC10),
    SUM_ACC18 = SUM(S1.SUM_ACC18),

    SVAT_SUP10 = SUM(S1.SVAT_SUP10),
    SVAT_SUP18 = SUM(S1.SVAT_SUP18),
    SVAT_ACC10 = SUM(S1.SVAT_ACC10),
    SVAT_ACC18 = SUM(S1.SVAT_ACC18)
FROM
(
SELECT
    SUM_SUP = DM.SUM_SUP * DM.SIGN_OP,
    SUM_ACC = CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SUM_ACC * DM.SIGN_OP,
	NAL = CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * (DM.SUM_ACC - DM.SUM_SUP) * DM.SIGN_OP,
    --KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,

    SUM_SVAT_SUP = DM.SVAT_SUP * DM.SIGN_OP,
    SUM_SVAT_ACC = CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END * DM.SVAT_ACC * DM.SIGN_OP,

    SUM_SUP0 = CASE WHEN DM.VAT_RATE = 0 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
    SUM_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
    SUM_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN (DM.SUM_SUP * DM.SIGN_OP) ELSE 0 END,
    SUM_ACC0 = CASE WHEN DM.VAT_RATE = 0 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP,
    SUM_ACC10 = CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP,
    SUM_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SUM_ACC * DM.SIGN_OP,

    SVAT_SUP10 = CASE WHEN DM.VAT_RATE = 10 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END,
    SVAT_SUP18 = CASE WHEN DM.VAT_RATE = 18 THEN (DM.SVAT_SUP * DM.SIGN_OP) ELSE 0 END,

    SVAT_ACC10 = CASE WHEN DM.VAT_RATE = 10 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP,
    SVAT_ACC18 = CASE WHEN DM.VAT_RATE = 18 THEN CASE WHEN DM.ID_TABLE=19 AND CODE_OP='DIS' THEN -1 ELSE 1 END ELSE 0 END * SVAT_ACC * DM.SIGN_OP
FROM DOC_MOVEMENT DM
WHERE DATE_OP < @DATE_TO
    AND (DM.ID_STORE IS NOT NULL AND DM.ID_STORE IN (SELECT ID_STORE FROM #STORE))

UNION ALL

SELECT	
	SUM_SUP = 0,
	SUM_ACC = CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
	NAL = CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY,
	--KOF = CASE WHEN CODE_OP = 'DIS' THEN 0 ELSE 1 END,

	SUM_SVAT_SUP = 0,
	SUM_SVAT_ACC = CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY,

	SUM_SUP0 = 0,
	SUM_SUP10 = 0,
	SUM_SUP18 = 0,
	SUM_ACC0 = CASE WHEN TT.TAX_RATE = 0 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
	SUM_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
	SUM_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * S4S.PRICE_SAL * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,

    SVAT_SUP10 = 0,
    SVAT_SUP18 = 0,
    SVAT_ACC10 = CASE WHEN TT.TAX_RATE = 10 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END,
    SVAT_ACC18 = CASE WHEN TT.TAX_RATE = 18 THEN CASE WHEN CH.CHEQUE_TYPE = 'SALE' THEN -1 ELSE 1 END * (S4S.PRICE_SAL * TT.TAX_RATE / 100) * S4S.QUANTITY * CH_I.QUANTITY ELSE 0 END
FROM CHEQUE_ITEM CH_I
     INNER JOIN CHEQUE CH ON CH.ID_CHEQUE_GLOBAL = CH_I.ID_CHEQUE_GLOBAL
     INNER JOIN CASH_SESSION CS ON CS.ID_CASH_SESSION_GLOBAL = CH.ID_CASH_SESSION_GLOBAL
     INNER JOIN SERVICE_4_SALE_ITEM S4S ON S4S.ID_SERVICE_4_SALE = CH_I.ID_LOT_GLOBAL
     INNER JOIN SERVICE S ON S.ID_SERVICE = S4S.ID_SERVICE
     INNER JOIN TAX_TYPE TT ON TT.ID_TAX_TYPE = S.ID_TAX_TYPE
WHERE CS.DATE_CLOSE < @DATE_TO
) AS S1

RETURN 0
GO

/*
exec REP_GOODS_REPORTS_TO_EX_SERVICE N'
<XML>
	<DATE_FR>2009-05-05T00:00:00.000</DATE_FR>
	<DATE_TO>2009-06-18T00:00:00.000</DATE_TO>
	<NO_DETAIL>0</NO_DETAIL>
	<SHOW_ADD>1</SHOW_ADD>
	<SHOW_SUB>1</SHOW_SUB>
	<SORT_DOC>1</SORT_DOC>
	<ID_CONTRACTOR>5271</ID_CONTRACTOR>	
</XML>'*/
--exec REP_GOODS_REPORTS_GROUPS_TG_EX @xmlParam = N'<XML><DATE_FR>2009-06-20T00:00:00.000</DATE_FR><DATE_TO>2009-07-03T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_STORE>152</ID_STORE><ID_STORE>158</ID_STORE><ID_STORE>173</ID_STORE></XML>'
--exec REP_GOODS_REPORTS_TO_EX_SERVICE @xmlParam = N'<XML><DATE_FR>2009-06-20T00:00:00.000</DATE_FR><DATE_TO>2009-07-03T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_STORE>152</ID_STORE><ID_STORE>157</ID_STORE></XML>'


--exec REP_GOODS_REPORTS_GROUPS_TG_EX @xmlParam = N'<XML><DATE_FR>2009-05-28T00:00:00.000</DATE_FR><DATE_TO>2009-07-03T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_STORE>152</ID_STORE><ID_STORE>157</ID_STORE><ID_STORE>160</ID_STORE></XML>'
--exec REP_GOODS_REPORTS_TO_EX_SERVICE @xmlParam = N'<XML><DATE_FR>2009-07-06T00:00:00.000</DATE_FR><DATE_TO>2009-07-07T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC></XML>'
--exec REP_GOODS_REPORTS_GROUPS_TG_EX @xmlParam = N'<XML><DATE_FR>2009-07-06T00:00:00.000</DATE_FR><DATE_TO>2009-07-06T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_STORE>153</ID_STORE><ID_STORE>154</ID_STORE></XML>'

--exec REP_GOODS_REPORTS_TO_EX_SERVICE @xmlParam = N'<XML><DATE_FR>2009-07-06T00:00:00.000</DATE_FR><DATE_TO>2009-07-06T00:00:00.000</DATE_TO><NO_DETAIL>0</NO_DETAIL><SHOW_ADD>1</SHOW_ADD><SHOW_SUB>1</SHOW_SUB><SORT_DOC>1</SORT_DOC><ID_STORE>153</ID_STORE><ID_STORE>154</ID_STORE></XML>'