SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_TORG13') IS NULL EXEC('CREATE PROCEDURE REPEX_TORG13 AS RETURN')
GO
ALTER PROCEDURE REPEX_TORG13
	(@XMLPARAM NTEXT) AS 

/* PARAMETERS */
DECLARE @HDOC INT
DECLARE @ID_MOVEMENT BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_MOVEMENT = ID_MOVEMENT
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_MOVEMENT BIGINT 'ID_MOVEMENT')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SELECT 
	G.NAME AS GOODSNAME, 
	U.NAME AS UNITNAME,
	OKEI_CODE = U.OKEI_CODE,
	M.QUANTITY AS MOVEQUANTITY,
	(M.QUANTITY*CONVERT(MONEY, SR.NUMERATOR) / SR.DENOMINATOR) AS MOVEQTY,
--	M.PRICE_SUPPLIER,
    M.PRICE_SALE PRICE_SUPPLIER, 
	PRICESUMMA = M.PRICE_SUPPLIER * M.QUANTITY
FROM MOVEMENT_ITEM AS M
	LEFT JOIN GOODS AS G ON G.ID_GOODS = M.ID_GOODS
	LEFT JOIN SCALING_RATIO SR ON M.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	LEFT JOIN UNIT AS U ON U.ID_UNIT = SR.ID_UNIT
WHERE M.ID_MOVEMENT = @ID_MOVEMENT
ORDER BY 1 ASC

SELECT M.MNEMOCODE,
	M.DATE,
	C.NAME,
	C.OKPO,
	S.NAME AS STORENAMEFROM,
	STORENAMETO = (SELECT TOP 1 ST.NAME FROM STORE AS ST WHERE M.ID_STORE_TO = ST.ID_STORE)
FROM MOVEMENT AS M 
	LEFT JOIN STORE AS S ON M.ID_STORE_FROM = S.ID_STORE
	LEFT JOIN CONTRACTOR AS C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
WHERE M.ID_MOVEMENT = @ID_MOVEMENT

RETURN 0
GO


