SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_ACT_RETURN_TORG2_EX2') IS NULL EXEC('CREATE PROCEDURE REPEX_ACT_RETURN_TORG2_EX2 AS RETURN')
GO
ALTER PROCEDURE REPEX_ACT_RETURN_TORG2_EX2
	(@XMLPARAM NTEXT)
AS
    DECLARE @HDOC INT
    DECLARE @ID_DOCUMENT BIGINT, @ID_CONTRACTOR BIGINT
    DECLARE @ID_DOCUMENT_BASE BIGINT
    SET LANGUAGE 'russian'
    EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	    SELECT TOP 1
		    @ID_DOCUMENT = ID_DOCUMENT
		    ,@ID_CONTRACTOR = ID_CONTRACTOR
	    FROM OPENXML(@HDOC, '/XML') 
	    WITH (ID_DOCUMENT BIGINT 'ID_DOCUMENT'
	        ,ID_CONTRACTOR BIGINT 'ID_CONTRACTOR'
	        )
    EXEC SP_XML_REMOVEDOCUMENT @HDOC

    SELECT	@ID_DOCUMENT_BASE = AR.ID_DOCUMENT_BASE
    FROM DBO.ACT_RETURN_TO_CONTRACTOR AR
    WHERE AR.ID_ACT_RETURN_TO_CONTRACTOR = @ID_DOCUMENT

    DECLARE @CONTRACTOR_TO_FULL_NAME varchar(4000)
    SELECT @CONTRACTOR_TO_FULL_NAME = CASE LEN(ISNULL(FUll_NAME, ''))
                WHEN 0 THEN NAME
	            ELSE FUll_NAME
	        END
	        +CASE LEN(ISNULL(ADDRESS, '')) WHEN 0 THEN '' ELSE ', '+ADDRESS END
	        +CASE LEN(ISNULL(PHONE, '')) WHEN 0 THEN '' ELSE ', '+PHONE END
    FROM CONTRACTOR
    WHERE ID_CONTRACTOR = @ID_CONTRACTOR
    
    SELECT TOP 1 
        AR.MNEMOCODE,
	    AR.DATE,
        CONTRACTOR_FROM_NAME = CASE LEN(ISNULL(CR_FROM.FUll_NAME, ''))
                WHEN 0 THEN CR_FROM.NAME
	            ELSE CR_FROM.FUll_NAME
	        END,
        CONTRACTOR_FROM_FULL_NAME = 
	        CASE LEN(ISNULL(CR_FROM.ADDRESS, '')) WHEN 0 THEN '' ELSE ', '+CR_FROM.ADDRESS END
	        +CASE LEN(ISNULL(CR_FROM.PHONE, '')) WHEN 0 THEN '' ELSE ', '+CR_FROM.PHONE END
	        
	    --CONTRACTOR_FROM_ADDRESS = ISNULL(CR_FROM.ADDRESS, ''),
	    --CONTRACTOR_FROM_PHONE = ISNULL(CR_FROM.PHONE, ''),
	    
	    ,CONTRACTOR_TO_FULL_NAME = 
	        CASE WHEN @CONTRACTOR_TO_FULL_NAME IS NOT NULL THEN
	            @CONTRACTOR_TO_FULL_NAME
	        ELSE
	            CASE LEN(ISNULL(CR_TO.FUll_NAME, ''))
                    WHEN 0 THEN CR_TO.NAME
	                ELSE CR_TO.FUll_NAME
	            END
	            +CASE LEN(ISNULL(CR_TO.ADDRESS, '')) WHEN 0 THEN '' ELSE ', '+CR_TO.ADDRESS END
	            +CASE LEN(ISNULL(CR_TO.PHONE, '')) WHEN 0 THEN '' ELSE ', '+CR_TO.PHONE END
	        END
	    --CONTRACTOR_TO_ADDRESS = ISNULL(CR_TO.ADDRESS, ''),
	    --CONTRACTOR_TO_PHONE = ISNULL(CR_TO.PHONE, ''),
	    ,STORE_FROM = ISNULL(ST.NAME, '')
    FROM DBO.ACT_RETURN_TO_CONTRACTOR AR
    INNER JOIN DBO.CONTRACTOR CR_FROM ON AR.ID_CONTRACTOR_FROM = CR_FROM.ID_CONTRACTOR
    INNER JOIN DBO.CONTRACTOR CR_TO ON AR.ID_CONTRACTOR_TO = CR_TO.ID_CONTRACTOR
    INNER JOIN DBO.STORE ST ON ST.ID_STORE = AR.ID_STORE
    WHERE AR.ID_ACT_RETURN_TO_CONTRACTOR = @ID_DOCUMENT

    SELECT TOP 1
        DOC = INCOMING_NUMBER + CASE LEN(ISNULL(INCOMING_DATE, '')) 
            WHEN 0 THEN ''
            ELSE ' от '+ CONVERT(VARCHAR(10), INCOMING_DATE, 104) END,
        BILL = INCOMING_BILL_NUMBER + CASE LEN(ISNULL(INCOMING_BILL_DATE, '')) 
            WHEN 0 THEN ''
            ELSE ' от '+ 
                STR(DAY(INCOMING_BILL_DATE), 2)
                +' ' + DATENAME(MONTH, MONTH(INCOMING_BILL_DATE)) +' '
                +STR(YEAR(INCOMING_BILL_DATE), 4)
            --CONVERT(VARCHAR(10), INCOMING_BILL_DATE, 104) 
            END
    FROM DBO.INVOICE
    WHERE ID_INVOICE = @ID_DOCUMENT_BASE

    SELECT
	    GOODS_NAME = G.NAME,
	    UNIT_NAME = U.NAME,
	    A.QUANTITY,
	    CONTRACTOR_PRICE_PER_UNIT = A.PRICE_VAT
    FROM ACT_RETURN_TO_CONTRACTOR_ITEM A
    INNER JOIN GOODS G ON G.ID_GOODS = A.ID_GOODS
    INNER JOIN SCALING_RATIO SR ON SR.ID_SCALING_RATIO = A.ID_SCALING_RATIO
    INNER JOIN UNIT U ON U.ID_UNIT = SR.ID_UNIT
    WHERE A.ID_ACT_RETURN_TO_CONTRACTOR = @ID_DOCUMENT
    ORDER BY GOODS_NAME, UNIT_NAME, CONTRACTOR_PRICE_PER_UNIT

    SELECT TOP 1
	    DIR = DIRECTOR_FIO,
	    BUH = BUH_FIO
	    ,COMPANY = COALESCE(NAME, '')
    FROM CONTRACTOR
    WHERE ID_CONTRACTOR = (SELECT TOP 1 ID_CONTRACTOR FROM ENTERPRISE_BRANCH WHERE IS_SELF = 1)

RETURN 0
GO
/*
exec REPEX_ACT_RETURN_TORG2_EX2 @XMLPARAM = '<XML>
<ID_DOCUMENT>496</ID_DOCUMENT>
<ID_CONTRACTOR>5456</ID_CONTRACTOR>
</XML>'
*/

