SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_TURNOVER_PERCENT') IS NULL EXEC ('CREATE PROCEDURE DBO.REPEX_TURNOVER_PERCENT AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_TURNOVER_PERCENT
    @XMLPARAM NTEXT
AS

DECLARE @DATE_FR DATETIME
DECLARE @DATE_TO DATETIME
DECLARE @ID_CONTRACTOR BIGINT
DECLARE @ORDER INT
DECLARE @IS_SAL INT
DECLARE @HDOC INT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT
	@DATE_FR = DATE_FR,
	@DATE_TO = DATE_TO,
	@ID_CONTRACTOR = ID_CONTRACTOR,
	@ORDER = [ORDER],
	@IS_SAL = IS_SAL
FROM OPENXML(@HDOC, '/XML') WITH(
	DATE_FR DATETIME 'DATE_FR',
	DATE_TO DATETIME 'DATE_TO',
	ID_CONTRACTOR BIGINT 'ID_CONTRACTOR',
	[ORDER] INT 'ORDER',
	IS_SAL INT 'IS_SAL'
)

EXEC SP_XML_REMOVEDOCUMENT @HDOC

EXEC DBO.USP_RANGE_NORM	@DATE_FR OUTPUT, @DATE_TO OUTPUT
EXEC DBO.USP_RANGE_DAYS	@DATE_FR OUTPUT, @DATE_TO OUTPUT

--SELECT @DATE_FR, @DATE_TO, @id_contractor
--SELECT @ORDER
--SELECT @IS_SAL

DECLARE @TEMP_T1 TABLE
(
	GOODS_NAME VARCHAR(255),
	QUANTITY MONEY,
	VAT INT,
	SUMM MONEY
)

IF (@IS_SAL = 0)
BEGIN

INSERT INTO @TEMP_T1 (
	GOODS_NAME,
	QUANTITY,
	VAT,
	SUMM
) 
SELECT
	GOODS_NAME = G.NAME,
	QUANTITY = SUM(LM.QUANTITY_SUB - LM.QUANTITY_ADD),
	VAT = L.VAT_SUP,
	SUMM = SUM(CASE WHEN LM.QUANTITY_SUB > 0 THEN 1 ELSE CASE WHEN LM.CODE_OP = 'MOVE' THEN 0 ELSE -1 END END * LM.SUM_SUP)
--INTO #TEMP_T1
FROM DBO.LOT_MOVEMENT LM
	INNER JOIN DBO.LOT L ON LM.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	INNER JOIN DBO.GOODS G ON L.ID_GOODS = G.ID_GOODS
	INNER JOIN dbo.STORE S ON S.ID_STORE = L.ID_STORE
	--INNER JOIN dbo.CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR	
WHERE LM.DATE_OP BETWEEN @DATE_FR AND @DATE_TO
	AND LM.CODE_OP IN ('ACT_R2B', 'INVOICE_OUT', 'CHEQUE', 'MOVE')
	AND S.ID_CONTRACTOR = @ID_CONTRACTOR
GROUP BY G.ID_GOODS, G.[NAME], L.VAT_SUP
END
ELSE
BEGIN
INSERT INTO @TEMP_T1 (
	GOODS_NAME,
	QUANTITY,
	VAT,
	SUMM
) 
SELECT
	GOODS_NAME = G.NAME,
	QUANTITY = SUM(LM.QUANTITY_SUB - LM.QUANTITY_ADD),
	VAT = L.VAT_SAL,
	SUMM = SUM(CASE WHEN LM.QUANTITY_SUB > 0 THEN 1 ELSE CASE WHEN LM.CODE_OP = 'MOVE' THEN 0 ELSE -1 END END * LM.SUM_ACC)
--INTO #TEMP_T1
FROM DBO.LOT_MOVEMENT LM
	INNER JOIN DBO.LOT L ON LM.ID_LOT_GLOBAL = L.ID_LOT_GLOBAL
	INNER JOIN DBO.GOODS G ON L.ID_GOODS = G.ID_GOODS
	INNER JOIN dbo.STORE S ON S.ID_STORE = L.ID_STORE
	--INNER JOIN dbo.CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR	
WHERE LM.DATE_OP BETWEEN @DATE_FR AND @DATE_TO
	AND LM.CODE_OP IN ('ACT_R2B', 'INVOICE_OUT', 'CHEQUE', 'MOVE')
	AND S.ID_CONTRACTOR = @ID_CONTRACTOR
GROUP BY G.ID_GOODS, G.[NAME], L.VAT_SAL
END

--SELECT * FROM #TEMP_T1

SELECT
	SUMM = SUM(SUMM),
	SUMM_0 = SUM(CASE WHEN VAT = 0 THEN SUMM ELSE 0 END),
	SUMM_10 = SUM(CASE WHEN VAT = 10 THEN SUMM ELSE 0 END),
	SUMM_18 = SUM(CASE WHEN VAT = 18 THEN SUMM ELSE 0 END)
INTO #TEMP_T2
FROM @TEMP_T1

DECLARE @SUMM MONEY
SET @SUMM = (SELECT SUMM FROM #TEMP_T2)

--SELECT @SUMM 

IF (@ORDER = 0)
BEGIN
SELECT
	GOODS_NAME,
	QUANTITY,
	VAT = CASE WHEN VAT = 0 THEN 'Áåç ÍÄÑ' ELSE CAST(VAT AS VARCHAR(10)) END,
	SUMM,
	[PERCENT] = CASE WHEN @SUMM = 0 THEN NULL ELSE SUMM / @SUMM * 100 END
FROM @TEMP_T1
ORDER BY GOODS_NAME
END
ELSE
BEGIN
SELECT
	GOODS_NAME,
	QUANTITY,
	VAT = CASE WHEN VAT = 0 THEN 'Áåç ÍÄÑ' ELSE CAST(VAT AS VARCHAR(10)) END,
	SUMM,
	[PERCENT] = CASE WHEN @SUMM = 0 THEN NULL ELSE SUMM / @SUMM * 100 END
FROM @TEMP_T1
ORDER BY CASE WHEN @ORDER = 1 THEN VAT ELSE CASE WHEN @SUMM = 0 THEN NULL ELSE SUMM / @SUMM * 100 END END
END

SELECT
	SUMM_0 = SUMM_0,
	PSUMM_0 = CASE WHEN SUMM = 0 THEN NULL ELSE SUMM_0 / SUMM * 100 END,
	SUMM_10 = SUMM_10,
	PSUMM_10 = CASE WHEN SUMM = 0 THEN NULL ELSE SUMM_10 / SUMM * 100 END,
	SUMM_18 = SUMM_18,
	PSUMM_18 = CASE WHEN SUMM = 0 THEN NULL ELSE SUMM_18 / SUMM * 100 END
FROM #TEMP_T2

RETURN
GO

/*
EXEC DBO.REPEX_TURNOVER_PERCENT N'
<XML>
	<DATE_FR>2009-09-01T16:13:14.453</DATE_FR>
	<DATE_TO>2009-09-30T16:13:14.453</DATE_TO>
	<ID_CONTRACTOR>5271</ID_CONTRACTOR>
	<ORDER>1</ORDER>
	<IS_SAL>0</IS_SAL>
</XML>'*/