SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
-----------------------------------------------------------------------------------------
IF OBJECT_ID('SUM_SUP_AND_DISCOUNT_EX') IS NULL BEGIN
    EXEC('CREATE PROCEDURE SUM_SUP_AND_DISCOUNT_EX AS RETURN')
    GRANT EXEC ON [SUM_SUP_AND_DISCOUNT_EX] TO [PUBLIC]
END
GO
ALTER PROCEDURE SUM_SUP_AND_DISCOUNT_EX
    @XMLPARAM NTEXT
AS

DECLARE	@HDOC INT
DECLARE @DATE_FROM DATETIME   --ÄÀÒÀ ÍÀ×ÀËÀ ÏÅÐÈÎÄÀ
DECLARE @DATE_TO DATETIME	--ÄÀÒÀ ÎÊÎÍ×ÀÍÈß ÏÅÐÈÎÄÀ

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT , @XMLPARAM OUTPUT
    SELECT TOP 1
        @DATE_FROM = DATE_FROM,
        @DATE_TO = DATE_TO
	FROM OPENXML(@HDOC , '/XML') WITH(
		DATE_FROM DATETIME 'DATE_FROM',
        DATE_TO DATETIME 'DATE_TO'
	)

-- --Ñåáåñòîèìîñòü
	Select 
		NAME_C = C.NAME,	--êîíòðàãåíò
		DATE_CH = CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,LM.DATE_OP))),104),  --äàòà
		SUMM_SUPPLIER = SUM(CONVERT(DECIMAL(18,2), LM.SUM_SUP))  --ñóììà ïîñòàâùèêà
	FROM LOT_MOVEMENT LM
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = LM.ID_LOT_GLOBAL
	INNER JOIN STORE S ON S.ID_STORE = L.ID_STORE
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
	WHERE LM.CODE_OP = 'CHEQUE'
	AND LM.DATE_OP BETWEEN CONVERT(DATETIME, FLOOR(CONVERT(MONEY,@DATE_FROM))) AND CONVERT(DATETIME, FLOOR(CONVERT(MONEY,@DATE_TO)+1))
	AND LM.QUANTITY_SUB>0
	group by C.NAME, CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,LM.DATE_OP))),104)
	order by 2
	
	--Ñêèäêè
	Select 
		NAME_C = C.NAME,		--êîíòðàãåíò
		DATE_CH = CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,LM.DATE_OP))),104),	--äàòà	
		SUM_DISCOUNT = SUM(CONVERT(DECIMAL(18,2), LM.DISCOUNT_ACC))	--ñóììà ñêèäêè
	FROM LOT_MOVEMENT LM
	INNER JOIN LOT L ON L.ID_LOT_GLOBAL = LM.ID_LOT_GLOBAL
	INNER JOIN STORE S ON S.ID_STORE = L.ID_STORE
	INNER JOIN CONTRACTOR C ON C.ID_CONTRACTOR = S.ID_CONTRACTOR
	WHERE LM.CODE_OP = 'CHEQUE'
	AND LM.DATE_OP BETWEEN CONVERT(DATETIME, FLOOR(CONVERT(MONEY,@DATE_FROM))) AND CONVERT(DATETIME, FLOOR(CONVERT(MONEY,@DATE_TO)+1))
	AND LM.QUANTITY_SUB>0
	group by C.NAME, CONVERT(VARCHAR,CONVERT(DATETIME, FLOOR(CONVERT(MONEY,LM.DATE_OP))),104)
	order by 2

RETURN 0
GO

--exec SUM_SUP_AND_DISCOUNT_EX @xmlParam = N'<XML><DATE_FROM>2008-01-29T00:00:00.000</DATE_FROM><DATE_TO>2009-02-28T00:00:00.000</DATE_TO></XML>'
--exec SUM_SUP_AND_DISCOUNT_EX @xmlParam = N'<XML><DATE_FROM>2008-01-01T00:00:00.000</DATE_FROM><DATE_TO>2009-02-12T00:00:00.000</DATE_TO></XML>'