SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF (OBJECT_ID('DBO.REPEX_STOCK_GOODS_EXT') IS NULL) EXEC ('CREATE PROCEDURE DBO.REPEX_STOCK_GOODS_EXT AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_STOCK_GOODS_EXT
    @XMLPARAM NTEXT
AS

DECLARE	@HDOC INT
DECLARE @ID_GOODS BIGINT
DECLARE @ID_LOT_GLOBAL UNIQUEIDENTIFIER

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
SELECT @ID_GOODS= ID_GLOBAL, @ID_LOT_GLOBAL = ID_LOT_GLOBAL  FROM OPENXML(@HDOC, '/XML') WITH(ID_GLOBAL BIGINT 'ID_GOODS', ID_LOT_GLOBAL UNIQUEIDENTIFIER 'ID_LOT_GLOBAL')
EXEC SP_XML_REMOVEDOCUMENT @HDOC
--select @ID_LOT_GLOBAL
SELECT
	--L.*
	DOC_TYPE = TD.DESCRIPTION
	,AD.DOC_NUM
	,AD.DOC_DATE
	,GOODS_NAME = G.NAME
	,L.LOT_NAME
	,Q_BEGIN = DR.QUANTITY_INIT
	,Q_RESERV = DR.QUANTITY
	,DR.DATE_MODIFIED
	,DR.RESERVE_STATE
	,USER_NAME = MU.NAME
	--,g.id_goods
	--,L.ID_LOT_global
--select *
FROM DOC_RESERVE DR
INNER JOIN LOT L ON L.ID_LOT = DR.ID_LOT
INNER JOIN ALL_DOCUMENT AD ON AD.ID_DOCUMENT_GLOBAL = DR.ID_DOC_GLOBAL
INNER JOIN META_USER MU ON MU.ID_USER = DR.ID_USER_GLOBAL
INNER JOIN TABLE_DATA TD ON TD.ID_TABLE_DATA = AD.ID_TABLE
INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
WHERE (@ID_LOT_GLOBAL IS NULL AND G.ID_GOODS = @ID_GOODS) 
		OR (@ID_LOT_GLOBAL IS NOT NULL AND L.ID_LOT_GLOBAL = @ID_LOT_GLOBAL) --DR.ID_LOT = @ID_LOT
--select @ID_LOT_GLOBAL
RETURN
GO


/*
exec DBO.REPEX_STOCK_GOODS_EXT '<XML>
<ID_GOODS>188865</ID_GOODS>
<ID_LOT_GLOBAL>59F91124-744A-40E2-ABEB-CF43F7A3EF1B</ID_LOT_GLOBAL>
</XML>'
*/