SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_IM_TORG_13_RIGLA') IS NULL EXEC('CREATE PROCEDURE DBO.REPEX_IM_TORG_13_RIGLA AS RETURN')
GO
ALTER PROCEDURE DBO.REPEX_IM_TORG_13_RIGLA
	(@XMLPARAM NTEXT) AS 
		
DECLARE	@HDOC INT
DECLARE @ID_GLOBAL UNIQUEIDENTIFIER
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
		
SELECT TOP 1 @ID_GLOBAL = ID_GLOBAL
FROM OPENXML(@HDOC , '/XML') WITH(ID_GLOBAL UNIQUEIDENTIFIER 'ID_GLOBAL')

EXEC SP_XML_REMOVEDOCUMENT @HDOC 

SELECT
	DOC_NUM = IM.MNEMOCODE,
	DOC_DATE = IM.DATE,
	NAME_FR = C_FR.NAME,
	NAME_TO = C_TO.NAME	
FROM INTERFIRM_MOVING IM
	INNER JOIN STORE S_FR ON S_FR.ID_STORE = IM.ID_STORE_FROM_MAIN
	INNER JOIN CONTRACTOR C_FR ON C_FR.ID_CONTRACTOR = S_FR.ID_CONTRACTOR
	INNER JOIN STORE S_TO ON S_TO.ID_STORE = IM.ID_STORE_TO_MAIN
	INNER JOIN CONTRACTOR C_TO ON C_TO.ID_CONTRACTOR = S_TO.ID_CONTRACTOR
WHERE ID_INTERFIRM_MOVING_GLOBAL = @ID_GLOBAL

SELECT
	GOODS_NAME = G.NAME,
	GOODS_CODE = G.CODE,
	UNIT_NAME = CAST(SR.NUMERATOR AS VARCHAR(5)) + '/' + CAST(SR.DENOMINATOR AS VARCHAR(5)) + ' ' + U.NAME,
	OKEI_CODE = U.OKEI_CODE,
	QUANTITY = II.QUANTITY,
	PRICE_SUP = II.PVAT_RETAIL/* * 100 / (100 + L.VAT_SAL)*/,
	SUM_SUP = II.PVAT_RETAIL * II.QUANTITY/* * 100 / (100 + L.VAT_SAL)*/,
	PRICE_PROD = L.PRICE_SUP - L.PVAT_SUP,
	SUM_PROD = II.SUM_SUPPLIER * 100 / (100 + L.VAT_SUP)
FROM INTERFIRM_MOVING_ITEM II
	INNER JOIN LOT L ON L.ID_LOT = II.ID_LOT_FROM
	INNER JOIN GOODS G ON G.ID_GOODS = L.ID_GOODS
	INNER JOIN SCALING_RATIO SR ON L.ID_SCALING_RATIO = SR.ID_SCALING_RATIO
	INNER JOIN UNIT AS U ON U.ID_UNIT = SR.ID_UNIT
WHERE II.ID_INTERFIRM_MOVING_GLOBAL = @ID_GLOBAL
ORDER BY G.NAME
	
RETURN 0
GO

--exec REPEX_IM_TORG_13_RIGLA N'<XML><ID_GLOBAL>96B7810B-9E05-452E-8561-5914625CE011</ID_GLOBAL></XML>'
