SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('REPEX_INVOICE') IS NULL EXEC('CREATE PROCEDURE REPEX_INVOICE AS RETURN')
GO

ALTER PROCEDURE REPEX_INVOICE
    @XMLPARAM NTEXT
AS

/* PARAMETERS */
DECLARE @HDOC INT
DECLARE @ID_INVOICE BIGINT

EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
	SELECT TOP 1 @ID_INVOICE = ID_INVOICE
	FROM OPENXML(@HDOC, '/XML') 
	WITH(ID_INVOICE BIGINT 'ID_INVOICE')
EXEC SP_XML_REMOVEDOCUMENT @HDOC

-- яохянй рнбюпнб б опхундмни
SELECT DISTINCT
  --мюхлемнбюмхе рнбюпю
  G.[NAME] + ' [' + PROD.NAME + ', ' + COALESCE(CNR.NAME, '') + ']' AS GOODS_NAME,
  --мюхлемнбюмхе союйнбйх
  --U.[SHORT_NAME] + '(' + CAST(SR.NUMERATOR AS VARCHAR) + '/' + CAST(SR.DENOMINATOR AS VARCHAR) + ')' AS UNIT_NAME,
  --йнкхвеярбн
  ITEM.QUANTITY	AS QUANTITY,
  --жемю опнхгбндхрекъ гю едхмхжс
  --ROUND(ITEM.PRODUCER_PRICE_PER_UNIT, 2) AS PRODUCER_PRICE_PER_UNIT,
  --жемю онярюбыхйю гю едхмхжс (аег мдя)
  ITEM.SUPPLIER_PRICE AS CONTRACTOR_PRICE_PER_UNIT,
  --жемю онярюбыхйю гю едхмхжс (я мдя)
  ITEM.SUPPLIER_PRICE_VAT AS CONTRACTOR_PRICE_PER_UNIT_VAT,
  --ясллю онярюбыхйю (я мдя)
  ITEM.SUPPLIER_SUM_VAT AS CONTRACTOR_SUM_VAT,
  -- ярюбйю мдя
  ITEM.SUPPLIER_VAT AS VAT_RATE,
  --пнгмхвмюъ мюдаюбйю
  ITEM.RETAIL_ADPRICE AS RETAIL_ADPRICE,  
  --ROUND((ITEM.RETAIL_PRICE-ITEM.CONTRACTOR_PRICE_PER_UNIT_VAT)/ITEM.CONTRACTOR_PRICE_PER_UNIT_VAT*100,2) AS RETAIL_ADPRICE,
  --пнгмхвмюъ жемю (я мдя) 
  ITEM.RETAIL_PRICE_VAT AS RETAIL_PRICE,
  --пнгмхвмюъ ясллю (я мдя) 
  ITEM.RETAIL_SUM_VAT AS RETAIL_SUM,
  ITEM.ID_INVOICE_ITEM
FROM DBO.INVOICE INV
  INNER JOIN DBO.INVOICE_ITEM ITEM ON ITEM.ID_INVOICE = INV.ID_INVOICE
  INNER JOIN DBO.GOODS G ON G.ID_GOODS = ITEM.ID_GOODS
  INNER JOIN DBO.PRODUCER PROD ON G.ID_PRODUCER = PROD.ID_PRODUCER
  LEFT OUTER JOIN DBO.COUNTRY CNR ON PROD.ID_COUNTRY = CNR.ID_COUNTRY
--  INNER JOIN DBO.SCALING_RATIO SR ON SR.ID_SCALING_RATIO = ITEM.ID_SCALING_RATIO
--  INNER JOIN DBO.UNIT U ON SR.ID_UNIT = U.ID_UNIT
WHERE (INV.ID_INVOICE = @ID_INVOICE)
ORDER BY GOODS_NAME
  
SELECT 
  -- мнлеп опхундмни мюйкюдмни
  INV.MNEMOCODE AS INVOICE_NUMBER,
  -- дюрю опхундмни мюйкюдмни
  INV.DOCUMENT_DATE AS INVICE_DATE,
  -- бундъыхи днйслемр
  COALESCE(INV.INCOMING_NUMBER, '')+
    COALESCE(' НР '+CONVERT(VARCHAR, INV.INCOMING_DATE, 104), '') 
    AS INCOMING_NUMBER,
  -- онйсоюрекэ
  CASE WHEN ISNULL(CNR_CUST.FULL_NAME,'') <> '' THEN CNR_CUST.FULL_NAME ELSE CNR_CUST.[NAME] END AS CUSTOMER_NAME,
  CASE WHEN ISNULL(CNR_CUST.ADDRESS,'') <> '' THEN ' юДПЕЯ:'+CNR_CUST.ADDRESS ELSE '' END AS CUSTOMER_ADDRESS,
  -- онярюбыхй 
  CASE WHEN ISNULL(CNR_SUP.FULL_NAME,'') <> '' THEN CNR_SUP.FULL_NAME ELSE CNR_SUP.[NAME] END
  +CASE WHEN ISNULL(CNR_SUP.INN,'') <> '' THEN ' хмм:'+CNR_SUP.INN ELSE '' END AS SUPPLIER_NAME,
  -- яйкюд 
  ST.[NAME] AS STORE_NAME,
-- рейсыюъ юорейю (ме днкфмн ашрэ NULL хмюве б нрвере опнакелш)
  (SELECT COALESCE(CNT.[NAME], '') 
  FROM DBO.CONTRACTOR CNT
  WHERE CNT.ID_CONTRACTOR = ST.ID_CONTRACTOR) AS COMPANY

FROM DBO.INVOICE INV
  INNER JOIN DBO.CONTRACTOR CNR_SUP ON CNR_SUP.ID_CONTRACTOR = INV.ID_CONTRACTOR_SUPPLIER
  INNER JOIN DBO.STORE ST ON ST.ID_STORE = INV.ID_STORE 
  INNER JOIN DBO.CONTRACTOR CNR_CUST ON ST.ID_CONTRACTOR = CNR_CUST.ID_CONTRACTOR
WHERE (INV.ID_INVOICE = @ID_INVOICE)

--хрнцнбше ясллш
SELECT 
  --ясллю нор. аег мдя
  INV.SUM_SUPPLIER-INV.SVAT_SUPPLIER AS CONTRACTOR_SUM,
  --ясллю нор. я мдя  
  INV.SUM_SUPPLIER AS CONTRACTOR_SUM_VAT,
  --ясллю мдя нор.
  INV.SVAT_SUPPLIER AS SUM_CONTRACTOR_VAT,
  --ясллю нор. мдя он яр. 10%
  SUM(CASE WHEN ITEM.SUPPLIER_VAT = 10.0 THEN ITEM.SUPPLIER_VAT_SUM ELSE 0.0 END) AS SUM_CONTRACTOR_VAT_10,  --ясллю нор. мдя он яр. 18%
  SUM(CASE WHEN ITEM.SUPPLIER_VAT = 18.0 THEN ITEM.SUPPLIER_VAT_SUM ELSE 0.0 END) AS SUM_CONTRACTOR_VAT_18,
  --хрнцнбюъ пнгмхвмюъ ясллю
  INV.SUM_RETAIL AS SUM_RETAIL_SUM,
  --хрнцнбюъ опндюфмюъ ясллю
  0.00 AS SUM_PROD_SUM,
  --ясллю пнгм. мдя он яр. 10%
  SUM(CASE WHEN ITEM.RETAIL_VAT = 10.0 THEN ITEM.RETAIL_VAT_SUM ELSE 0.0 END) AS SUM_RETAIL_VAT_10,
  --ясллю пнгм. мдя он яр. 18%
  SUM(CASE WHEN ITEM.RETAIL_VAT = 18.0 THEN ITEM.RETAIL_VAT_SUM ELSE 0.0 END) AS SUM_RETAIL_VAT_18,
  --ясллю мюкнцю я опндюф
  0.00 AS SUM_PROD_TAX
FROM DBO.INVOICE INV
  INNER JOIN DBO.INVOICE_ITEM ITEM ON ITEM.ID_INVOICE = INV.ID_INVOICE
WHERE INV.ID_INVOICE = @ID_INVOICE
GROUP BY INV.SUM_SUPPLIER-INV.SVAT_SUPPLIER, INV.SUM_SUPPLIER,INV.SVAT_SUPPLIER,INV.SUM_RETAIL
RETURN 0
GO