-- USE EDPLUS_DEV10
IF (OBJECT_ID('USP_INVOICE_LIST_BY_PERIOD') IS NULL) EXEC ('CREATE PROCEDURE USP_INVOICE_LIST_BY_PERIOD AS RETURN')
GO
ALTER PROCEDURE USP_INVOICE_LIST_BY_PERIOD(
    @DATE_FROM DATETIME,    
    @DATE_TO DATETIME
)
AS
EXEC USP_RANGE_DAYS @DATE_FROM OUT, @DATE_TO OUT
EXEC USP_RANGE_NORM @DATE_FROM OUT, @DATE_TO OUT

SELECT 
    ID_INVOICE_GLOBAL
FROM INVOICE WHERE DOCUMENT_DATE BETWEEN @DATE_FROM AND @DATE_TO
AND DOCUMENT_STATE <>'DEL'
RETURN
GO