SET NOCOUNT ON
SET QUOTED_IDENTIFIER OFF
GO

IF OBJECT_ID('DBO.REPEX_INVENTORY_EMPTY') IS NULL BEGIN EXEC('CREATE PROCEDURE DBO.REPEX_INVENTORY_EMPTY AS RETURN')    
END
GO
ALTER PROCEDURE DBO.REPEX_INVENTORY_EMPTY
    @XMLPARAM NTEXT AS

DECLARE	@HDOC INT
DECLARE @NUM INT
		
EXEC SP_XML_PREPAREDOCUMENT @HDOC OUTPUT, @XMLPARAM OUTPUT
		
SELECT @NUM = NUM
FROM OPENXML(@HDOC , '/XML') WITH(NUM INT 'NUM')
		
EXEC SP_XML_REMOVEDOCUMENT @HDOC

SET @NUM = CASE WHEN @num = 1 THEN 22 ELSE 24 * (@num - 1) + 22 END

SELECT TOP 0 NUM = IDENTITY(INT, 1, 1) INTO #EMPTY
WHILE (SELECT COUNT(*) FROM #EMPTY) < @num INSERT #EMPTY DEFAULT VALUES

SELECT
    DOC_DATE = GETDATE(),    
    DOC_NAME = 'Инвентаризационный лист № _________________ от ' + CONVERT(VARCHAR, GETDATE(), 104) + ' г.'

SELECT * FROM #EMPTY

RETURN 0
GO

--exec REPEX_INVENTORY_EMPTY '<XML><NUM>5</NUM></XML>'